README.md

I saw your post on reddit a few days ago, and thought I'd check it out, good work. Haven't been able to dive deep into the code, but noticed something minor I could help with at least. Cheers!

Added link to data policy to README

---

assets/css/tooltip.css
lib/plausible/billing/billing.ex
lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/controllers/stats_controller.ex
lib/plausible_web/plugs/auth_plug.ex
lib/plausible_web/templates/auth/user_settings.html.eex
lib/plausible_web/templates/layout/app.html.eex
lib/plausible_web/views/auth_view.ex
test/plausible/billing/billing_test.exs
test/plausible_web/plugs/auth_plug_test.exs
test/test_helper.exs

Fix billing bugs

---

lib/plausible/clickhouse.ex
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/router.ex
lib/plausible_web/templates/site/settings.html.eex
test/plausible_web/controllers/site_controller_test.exs

Add ability to reset stats

---

assets/js/dashboard/number-formatter.js
assets/js/dashboard/stats/modals/referrers.js
assets/js/dashboard/stats/visitor-graph.js
lib/plausible/stats/clickhouse.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
test/plausible_web/controllers/api/stats_controller/referrers_test.exs
test/support/clickhouse_setup.ex

Visit duration

---

lib/plausible/clickhouse.ex

Escape single quote in CH query

---

assets/js/dashboard/stats/countries.js
assets/js/dashboard/stats/visitor-graph.js

Use singular 'visitor' when appropriate

---

lib/plausible/stats/clickhouse.ex
test/support/clickhouse_setup.ex

Fixes timezone handling for realtime reports.
Closes #242

Fix realtime conversion report

---

assets/js/dashboard/stats/modals/referrer-drilldown.js
assets/js/dashboard/stats/referrers.js
lib/plausible/stats/clickhouse.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/stats_controller/referrers_test.exs

Direct traffic improvements

---

assets/js/dashboard/stats/conversions.js
lib/plausible/stats/clickhouse.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/stats_controller/conversions_test.exs
test/plausible_web/controllers/api/stats_controller/main_graph_test.exs

Show total conversions in addition to uniques

---

Dockerfile

Fixed a typo that breaks the build using docker.

Fix typo in dockerfile

---

CHANGELOG.md
assets/js/dashboard/stats/modals/referrer-drilldown.js
assets/js/dashboard/stats/pages.js
assets/js/dashboard/stats/sources/referrer-list.js
docker_push

Linkify top pages

---

CHANGELOG.md
assets/js/dashboard/datepicker.js

Ignore arrow keys when modifier keys are pressed

---

CHANGELOG.md
assets/js/dashboard/stats/conversions.js
assets/js/dashboard/stats/modals/referrer-drilldown.js
lib/plausible/stats/clickhouse.ex
lib/plausible_web/controllers/api/stats_controller.ex

Improve stats when drilling into goal completions.

Show correct stats when filtered for goal

---

CONTRIBUTING.md
Makefile

Added a CONTRIBUTING.md with instructions to setup your development environment as requested in https://github.com/plausible/analytics/issues/176

task: Add CONTRIBUTING.md with development setup instructions

---

CONTRIBUTING.md
Makefile

Updated the contribution guidelines to better illustrate a first time setup. The list of system dependencies is mostly useful to avoid an error (with an unhelpful error message) when compiling the `:gettext` dependency if Erlang isn't installed. Users may still encounter some errors (e.g. requiring Elixir 1.10+), but there are friendly error messages for those.
The make file is updated to start Clickhouse and PostgreSQL in detached mode. This is just a quick usability improvement so both containers are ran in the background while you continue with the other steps.
(on a sidenote, big thanks to @Eptis for adding contribution guidelines; the lack of them have been a roadblock for me in the past)

Update contribution guidelines

---

CHANGELOG.md
lib/plausible_web/controllers/api/external_controller.ex
test/plausible_web/controllers/api/external_controller_test.exs
test/plausible_web/controllers/api/stats_controller/browsers_test.exs
test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
test/plausible_web/controllers/api/stats_controller/operating_systems_test.exs
test/plausible_web/controllers/api/stats_controller/sources_test.exs
test/support/clickhouse_setup.ex

Url decode

---

CHANGELOG.md
lib/plausible/stats/clickhouse.ex
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/templates/site/index.html.eex

Redesigns the site listing page.

Add nicer grid list for sites

---

lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/plugs/require_logged_out.ex

Title. See [reference](https://github.com/plausible/website/pull/162#issuecomment-747306972)

Extends "logged_in" cookie to 5000 years

---

lib/plausible/session/store.ex
lib/plausible/session/write_buffer.ex
lib/plausible_web/controllers/api/external_controller.ex
lib/plausible_web/templates/auth/register_form.html.eex

Fixes issue with some session data going missing.

Fix sessions bug

---

lib/plausible_web/templates/site/settings_danger_zone.html.eex

Fixes typo in danger zone

---

assets/js/dashboard/filters.js

Adds fallback for countries missing in DataMap

---

assets/js/app.js
lib/plausible_web/controllers/api/external_controller.ex
lib/plausible_web/templates/layout/app.html.eex

In app release notes

---

assets/js/dashboard/site-switcher.js

Add "Add Site" button to site switcher

---

lib/plausible_web/plugs/tracker.ex

Fix: Re-add hash and outbound-links only options

---

assets/js/dashboard/stats/sources/source-list.js

Fixes MoreLink for UTM tags

---

CHANGELOG.md
assets/js/dashboard/api.js
lib/plausible_web/plugs/authorize_stats_plug.ex
test/plausible_web/controllers/stats_controller_test.exs

Fix shared link download link

---

config/runtime.exs
lib/plausible/billing/plans.ex
lib/plausible_web/email.ex
lib/plausible_web/templates/email/yearly_expiration_notification.html.eex
lib/plausible_web/templates/email/yearly_renewal_notification.html.eex
lib/workers/notify_annual_renewal.ex
priv/repo/migrations/20210420075623_add_sent_renewal_notifications.exs
test/workers/notify_annual_renewal_test.exs

Send renewal notification for annual subscriptions

---

config/runtime.exs

This makes the change talked about in PR #1096 

add tzdata storage dir

---

assets/js/dashboard/stats/visitor-graph.js
assets/package-lock.json
assets/package.json

Updates Chart.js v3 to benefit from performance updates and tree-shaking.

Chartjs v3

---

config/runtime.exs

Cherry picked the commit on master to fix https://github.com/plausible/analytics/discussions/1136.

Fix issue with config loading

---

lib/plausible/stats/aggregate.ex
lib/plausible/stats/base.ex
lib/plausible/stats/breakdown.ex
lib/plausible/stats/query.ex
lib/plausible/stats/timeseries.ex
lib/plausible_web/controllers/api/external_stats_controller.ex
lib/plausible_web/controllers/api/stats_controller.ex
mix.lock

Finishes up the stats module refactoring. Everything should work the same with the new module.

Finish stats module

---

CONTRIBUTING.md

This updates the contributing to correct the sublists and clarify a couple of steps.

Fix sublists in CONTRIBUTING.md + minor changes for clarity

---

lib/plausible/auth/auth.ex
lib/plausible/site/schema.ex
lib/plausible/sites.ex
lib/plausible/stats/clickhouse.ex
lib/plausible_web/controllers/stats_controller.ex
lib/plausible_web/templates/stats/waiting_first_pageview.html.eex
lib/workers/send_site_setup_emails.ex
priv/repo/migrations/20210906102736_memoize_setup_complete.exs
test/plausible/sites_test.exs

Optimization to reduce data scanning in Clickhouse.

Memoize has_stats?

---

lib/plausible/auth/user.ex
lib/plausible/billing/billing.ex
lib/plausible/sites.ex
lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/controllers/invitation_controller.ex
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/templates/site/index.html.eex
lib/plausible_web/templates/site/new.html.eex
priv/repo/migrations/20210908081119_allow_trial_expiry_to_be_null.exs
test/plausible_web/controllers/auth_controller_test.exs
test/plausible_web/controllers/invitation_controller_test.exs
test/plausible_web/controllers/site_controller_test.exs

Makes `trial_expiry_date` nullable

Remove trial banner for admins & viewers

---

.tool-versions
Dockerfile
config/.env.dev
config/runtime.exs
lib/plausible/google/api.ex
lib/plausible_web/controllers/api/external_stats_controller.ex
lib/plausible_web/controllers/site/membership_controller.ex
lib/plausible_web/controllers/stats_controller.ex
lib/plausible_web/email.ex
test/plausible_web/controllers/api/stats_controller/suggestions_test.exs

Upgrade otp

---

Makefile
assets/package-lock.json
lib/plausible_web/controllers/api/external_controller.ex
test/plausible_web/controllers/api/external_controller_test.exs

Allow URLs without hostname setting it to (none)

---

lib/plausible/site/admin.ex
test/plausible_web/controllers/api/external_controller_test.exs

Admin - CRM shows site owner

---

CHANGELOG.md
assets/js/dashboard/stats/conversions/index.js
assets/js/dashboard/stats/current-visitors.js
assets/js/dashboard/stats/devices/browsers.js
assets/js/dashboard/stats/devices/index.js
assets/js/dashboard/stats/devices/operating-systems.js
assets/js/dashboard/stats/pages/entry-pages.js
assets/js/dashboard/stats/pages/exit-pages.js
assets/js/dashboard/stats/pages/pages.js
assets/js/dashboard/stats/sources/source-list.js
assets/js/dashboard/url.js

Fixes #1198 except for the countries tab (the whole datamaps library works outside normal browser link behaviour)

Fix links in new tab

---

lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/CSVs/30d-filter-goal/browsers.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/countries.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/devices.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/entry_pages.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/exit_pages.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/operating_systems.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/pages.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/sources.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/utm_campaigns.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/utm_mediums.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/utm_sources.csv
test/plausible_web/controllers/api/stats_controller/browsers_test.exs
test/plausible_web/controllers/api/stats_controller/countries_test.exs
test/plausible_web/controllers/api/stats_controller/operating_systems_test.exs
test/plausible_web/controllers/api/stats_controller/screen_sizes_test.exs

This makes the CSV export output conversions and conversion rate values for all metrics when filtering by goal, as seen on the dashboard.

CSV export output conversions and conversion rate when filtering for goal

---

CHANGELOG.md
assets/css/app.css
assets/js/dashboard/datepicker.js
assets/js/embed.content.js
assets/js/embed.host.js

Allow custom styles to be passed to embedded iframe

---

lib/plausible_web/controllers/api/external_controller.ex

- list of city overrides now alphabetical
- added new overrides for switzerland and canada

Couple of changes to the cities

---

assets/js/dashboard/filters.js
assets/js/dashboard/query.js
assets/js/dashboard/stats/modals/filter.js

Replace plus icon with search icon for filter

---

lib/plausible_web/templates/email/welcome_email.html.eex

Add a note to invite team members to the welcome email

Add a note to invite team members

---

assets/js/dashboard/stats/modals/filter.js

Note about double asterisks in front and back for contains

---

lib/plausible_web/templates/site/settings_general.html.eex

changed url to ga import docs

---

lib/plausible_web/templates/email/site_setup_success_email.html.eex

add GA importer to one of the welcome emails

add GA importer

---

assets/js/dashboard/stats/graph/graph-util.js

New version as per discussions in #1364

Improves tooltip UI hierarchy

---

lib/plausible_web/controllers/api/external_controller.ex

Innenstadt I to Frankfurt to fix #1875

Fix Innenstadt I

---

lib/mix/tasks/create_sandbox_subscription.ex
lib/mix/tasks/pull_sandbox_subscription.ex
lib/plausible/auth/user_admin.ex
lib/plausible/billing/site_locker.ex
lib/plausible/site/admin.ex

CRM improvements

---

lib/plausible_web/templates/email/ownership_transfer_request.html.eex

Fixing a typo

---

assets/js/dashboard/stats/graph/visitor-graph.js

Fixes edge case on conversion metric automatic change

---

.github/workflows/elixir.yml

Use erlef/setup-beam for GitHub Actions

---

lib/plausible_web/templates/layout/_notice.html.eex

just to make sure that it's the stats rather than actual sites that get locked

Changing sites into stats in this message as well

---

lib/plausible_web/templates/layout/_footer.html.eex

adding the note in the footer in-app

We are looking for a Technical Customer Success Manager

---

config/runtime.exs

fix: Oban pruner max_age config

---

lib/sentry_filter.ex

Filter out noisy exception from Sentry

---

CONTRIBUTING.md

Add 'Finding a task' section to CONTRIBUTING.md

Add 'Finding a task' section to CONTRIBUTING.md

---

test/load/README.md

Simple path change after folder move.

Fix script path for k6 load test

---

fixture/vcr_cassettes/google_analytics_stats#with_page.json
fixture/vcr_cassettes/google_analytics_stats#without_page.json
fixture/vcr_cassettes/google_analytics_stats.json
lib/plausible/google/api.ex
lib/plausible/google/http.ex
test/plausible/google/api_test.exs

This commit fixes a bug where fetching Google Search Console keywords raised a FunctionClauseError. This was introduced in #2046. This commit also adds test coverage.
I don't have a Google Search Console account to reproduce this, but I added tests using Google API documentation data.

Fix Google Search Console API call

---

lib/plausible/google/http.ex

This commit handles unexpected Google Analytics responses while
importing, and logs to Sentry and Logger. This will improve
observability when things go wrong with GA imports.

Handle unexpected Google Analytics responses

---

lib/plausible/ingestion/city_overrides.ex

Fixing Innenstadt II/III to Frankfurt

Fixing Innenstadt II/III to Frankfurt

---

CHANGELOG.md
assets/js/dashboard/stats/sources/source-list.js

In favour of https://github.com/plausible/analytics/pull/2126
**Before:**
**After:**

Add link to UTM builder

---

lib/plausible/google/api.ex

This makes Google Analytics HTTP requests synchronous. Parallel requests were added in the recent refactor (#2046) as a strategy to make importing faster, but turns out the change that made it faster was fetching GA records paginated instead of monthly batches, not parallelism. We decided to make it synchronous because:
- Makes request mocking easier
- Removes unnecessary complexity
- Mitigates HTTP connectivity issues (e.g. timeouts)
Me and @aerosol tested this against a 1M pageviews GA import, and importing was finished in 45 seconds without parallel requests, which is good. Parallel requests are in fact faster in most cases, but given the reasons above, not worth the complexity in this instance.

Remove parallel requests to Google Analytics

---

lib/plausible/billing/paddle_api.ex

Inspect extra sentry payload for get_invoices/1 failure

---

lib/plausible/site/admin.ex
mix.lock

Increases site transfer query timeout from 15s to 30s.

Increase DB query timeout for site transfers

---

Dockerfile

This reverts commit 76806a89246311ef700694c353c1d67a730e8848.

Revert "Bump hexpm/elixir (#2239)"

---

lib/plausible/google/http.ex

This commit parses failed GA responses to JSON before reporting to Sentry. This makes Sentry's PII filtering smarter, redacting only specific keys from the response, instead of the whole string.

Parse Google Analytics failed response before reporting to Sentry

---

test/plausible/purge_test.exs

This makes sure a) the DB is provisioned initially, b) the events queries are querying the events table

Fix up Purge tests

---

.github/workflows/elixir.yml
CONTRIBUTING.md
Makefile

This PR updates Makefile with tracker generation and also makes the CI use it.

Update Makefile with tracker generation

---

lib/plausible/google/api.ex

This commit adds exponential backoff to GA request retries, increasing the waiting time between requests.

Implement exponential backoff for GA requests

---

lib/mix/tasks/send_pageview.ex
lib/plausible_web/controllers/stats_controller.ex
test/plausible_web/controllers/site_controller_test.exs

Fix random typos

---

lib/plausible/goals.ex
lib/plausible_web/controllers/api/external_sites_controller.ex
lib/plausible_web/controllers/invitation_controller.ex
lib/plausible_web/controllers/site/membership_controller.ex
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/router.ex
lib/plausible_web/templates/site/settings_people.html.eex
test/plausible_web/controllers/invitation_controller_test.exs
test/plausible_web/controllers/site/membership_controller_test.exs
test/plausible_web/controllers/site_controller_test.exs

Co-authored-by: ruslandoga <doga.ruslan@gmail.com>
General sweep through controller tests

Improve test coverage

---

lib/plausible_web/views/site_view.ex

As per https://plausible.io/docs/plausible-script

Update the snippet from js/plausible.js to js/script.js

---

assets/js/dashboard/stats/graph/top-stats.js

Show 0% difference instead of N/A

---

lib/plausible/open_telemetry.ex

This commit removes the current 1% sampling on ingestion to completely ignore ingestion traces. We are not getting enough value from those, and we'll keep dashboard, API and background jobs traces only.

Remove ingestion from OTEL tracing

---

lib/plausible_web/templates/layout/_footer.html.eex

Update to keep the in-app footer consistent with the main site footer

Update to keep the in-app footer consistent with the main site footer

---

lib/plausible_web/templates/site/settings_people.html.eex

I just fixed a quick typo that seemed to be inconsistent. The word "friend" was singular while "coworkers" was plural, and it seemed awkwardly worded.
This fix is so minor, I'm not sure it qualifies as a user-facing change.

Fixed a minor typo for consistency

---

.github/workflows/elixir.yml
lib/plausible/billing/billing.ex
lib/plausible/billing/subscription.ex
lib/plausible/stats/base.ex
lib/plausible_web/controllers/stats_controller.ex
test/support/test_utils.ex

Fixed dialyzer errors and enabled it in CI.
I had to mark one function as `:nowarn` because we use an ecto feature that does not have a proper typespec.

Fix and enable dialyzer

---

lib/plausible/http_client.ex

This commit adds OTEL tracing to external HTTP requests made with the `Plausible.HTTPClient` module. It records the elapsed time, host, path, and response status code.

Trace external HTTP requests

---

assets/js/dashboard/datepicker.js
assets/js/dashboard/query.js
assets/js/dashboard/stats/graph/graph-util.js
assets/js/dashboard/stats/graph/top-stats.js
assets/js/dashboard/stats/graph/visitor-graph.js

This commit lints JavaScript files, removes commented-out code, and moves 3 constants to `graph-util.js`. This is part of the Intervals work, in order to make the original pull request smaller and release this feature incrementally.
Related: #1574
Co-authored-by: Vignesh Joglekar <hey@vigneshjoglekar.com>

Clean up JavaScript graph code

---

lib/plausible/site/cache.ex
test/plausible/site/cache_test.exs

This PR is on top of #2452 and addresses the following aspect: https://github.com/plausible/analytics/pull/2444/files#r1023751222

Fix empty cache race condition on refresh

---

lib/plausible/ingestion/event.ex
lib/plausible/ingestion/request.ex
lib/plausible_web/controllers/api/external_controller.ex
test/plausible/ingestion/event_test.exs

This PR contains changes against (on top of) #2351 to address concerns expressed in the originating [thread](https://github.com/plausible/analytics/pull/2351#discussion_r1021580109). With this change applied it should be fairly straight-forward to integrate and test Rate Limiting (ref #2452)

Rework ingestion pipeline processing

---

config/runtime.exs

This PR adds a fallback to empty build metadata when BUILD_METADATA contains invalid JSON.
Example `warning` log for `BUILD_METADATA={...}`:
```
20:57:57.872 [warning] failed to parse $BUILD_METADATA, reason: ** (Jason.DecodeError) unexpected byte at position 1: 0x2E (".")
```
Fixes https://github.com/plausible/analytics/issues/2491

add BUILD_METADATA fallback when parsing

---

lib/plausible/open_telemetry.ex

This pull requests removes ingestion requests (`/api/event`) and Oban queries from OpenTelemetry to reduce noise. Ingestion should already be ignored, but a bug fixed by this PR was still counting some of the traces. I left some comments inline.

Remove ingestion requests and Oban queries from OTEL

---

lib/plausible/clickhouse_repo.ex
lib/plausible/stats/aggregate.ex
lib/plausible/stats/timeseries.ex
lib/plausible_web/controllers/api/external_stats_controller.ex
lib/plausible_web/controllers/stats_controller.ex

Refine parallel application-side joins

---

lib/plausible_web/templates/email/over_limit.html.eex

Some changes to the 'over limit' email copy

---

lib/plausible_web/templates/email/dashboard_locked.html.eex

Some changes to the 'dashboard locked' email copy

---

lib/plausible_web/controllers/api/stats_controller.ex
lib/plausible_web/endpoint.ex
lib/sentry_filter.ex

This PR prevents most common and non-critical errors from polluting Sentry.

Sentry cleanup

---

lib/plausible_web/templates/layout/_notice.html.eex

This pull request fixes the warning notice for mobile. Closes #2528
| Mobile                                                                                                                       | Desktop                                                                                                                       |
|------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------|
| <img width="558" src="https://user-images.githubusercontent.com/5093045/212389047-ab453379-f252-41d3-a5ae-dd964f4ab9f1.png"> | <img width="1121" src="https://user-images.githubusercontent.com/5093045/212389043-f7cdd9 …

Make warning notices responsive

---

assets/js/dashboard/stats/graph/date-formatter.js

This reverts commit 7a7076ed209afa0549cbd976c7d13bca481b703c.

Revert "parse date labels by local timezone instead of UTC (#2601)"

---

priv/clickhouse_repo/migrations/20230124140348_add_city_name_to_imported_locations.exs

Add city name to imported_locations table

---

lib/plausible/stats/breakdown.ex
test/plausible_web/controllers/api/stats_controller/conversions_test.exs

Fixes DB query error when a certain combination of filters is used. I didn't add a changelog entry because the issue was introduced very recently.

Fix 'field key does not exist' error

---

assets/js/dashboard/datepicker.js

Updates the `DatePicker` react component to use new hooks API instead of deprecated React Classes.
The idea is to slowly move over to hooks in general. This will allow us to upgrade react-router-dom from v5 -> v6 which should help us more easily solve https://github.com/plausible/analytics/issues/2258. It's also nice to keep dependencies up to date in general.

Refactor: Use hooks instead of classes for DatePicker

---

assets/js/dashboard/stats/graph/interval-picker.js
assets/js/dashboard/stats/graph/visitor-graph.js

- Revert "Fix graph element z-index (#2698)"
- Revert "Fix interval selector z-index (#2696)"
- Set graph z-index to zero

Fix graph z-index property

---

lib/plausible/ingestion/counters.ex
lib/plausible/prom_ex.ex

Better Sentry grouping + PromEx metrics for AsyncInsertRepo.

Add extra error info + telemetry for AsyncInsertRepo

---

.github/workflows/elixir.yml
test/workers/import_google_analytics_test.exs

This reverts commit ef894b0546270df2a9aeeb172cdc5039ad5aa676.

Revert "Fail the CI if tests emit log errors/warnings (#2694)"

---

test/plausible/imported/imported_test.exs

Fix a test that was failing in the Elixir CI

fix test to make build green

---

lib/plausible/stats/imported.ex
lib/plausible/stats/timeseries.ex
test/plausible_web/controllers/api/stats_controller/main_graph_test.exs

This PR re-applies changes in https://github.com/ruslandoga/analytics/pull/75

fix events main-graph error

---

.github/bin/log-watch.sh
.github/workflows/elixir.yml

A re-iteration of a miserable attempt from https://github.com/plausible/analytics/pull/2694
prints the output properly now and fails when it should

Fail CI when tests are logging

---

lib/plausible/site.ex
lib/plausible_web/templates/site/settings_danger_zone.html.eex

Removing the notes about the 48 hour deletion delay

Removing the notes about the 48 hour deletion delay

---

lib/plausible_web/templates/site/membership/transfer_ownership_form.html.eex

Some people think that the subscription gets transferred too.

Add a note that a subscription is not transferred alongside a site

---

mix.exs

Closes https://github.com/plausible/analytics/issues/2740

update elixir version in mix.exs

---

assets/js/dashboard/api.js
assets/js/dashboard/comparison-input.js
assets/js/dashboard/datepicker.js
assets/js/dashboard/query.js
assets/js/dashboard/stats/graph/graph-tooltip.js
assets/js/dashboard/stats/graph/graph-util.js
assets/js/dashboard/stats/graph/visitor-graph.js
assets/js/dashboard/util/date.js
lib/plausible/stats/comparisons.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible/stats/comparisons_test.exs
test/plausible_web/controllers/api/stats_controller/main_graph_test.exs

This pull request implements the custom comparison mode using a date range.

Custom comparison mode

---

assets/js/dashboard/comparison-input.js

This commit improves the datepicker state management. Due to a bug, we needed to use setTimeout to open Flatpickr. This change replaces the setTimeout workaround by using a proper React state.
I'd appreciate if reviewers could actually test this in their local environments, as this behavior depends on the browser performance - don't ask me why 😅.

Control comparison datepicker using React state

---

lib/plausible_web/plugs/tracker.ex
lib/plausible_web/templates/layout/_tracking.html.eex
mix.lock
tracker/compile.js
tracker/src/plausible.js

* Rename the extension `script.dimensions.js` to `script.pageview-props.js`

Rename dimensions script to pageview-props

---

assets/.eslintrc.json
assets/js/dashboard/components/combobox.js
assets/js/dashboard/stats/modals/filter.js
assets/js/dashboard/util/filters.js

Fixes a small issue with combobox not opening when:
1. User has selected an option
2. Starts typing again

Fix open state in combobox

---

lib/plausible_web/controllers/api/external_sites_controller.ex
lib/plausible_web/templates/site/new.html.eex
test/plausible_web/controllers/api/external_sites_controller_test.exs

This reverts commit b626329ec570899df7d1cfcacf3f1073f010dcdf.

Revert "Temporarily disable site creation (#2813)"

---

priv/repo/migrations/20230328062644_allow_domain_change.exs

Ref #1080 
First pass to migrate `sites` table.

Migration: enable domain changes (upcoming feature)

---

lib/plausible_release.ex

Start :ssl for migrations

---

lib/plausible_web/templates/email/dashboard_locked.html.eex
lib/plausible_web/templates/email/over_limit.html.eex

Tweaks to the email copy

---

lib/plausible_web/templates/email/site_setup_help_email.html.eex

link to the WP plugin and the integration guides in one of the welcome emails

link to the WP plugin and the integration guides

---

priv/repo/migrations/20230417092745_add_monetary_value_to_goals.exs

Related: https://github.com/plausible/analytics/pull/2948

Revenue tracking: Migrate goals table

---

lib/plausible/money_without_currency.ex
lib/plausible/stats/base.ex

An attempt to make the query work with Money type.

use money type in type/2 macro

---

lib/plausible_web/templates/page/index.html.eex

Fixes twitter link on landing page introduced in https://github.com/plausible/analytics/pull/2989

fix twitter link

---

priv/repo/migrations/20230530161856_add_enable_feature_fields_for_site.exs

Migration Only: add `conversions_enabled`, `funnels_enabled`, `props_enabled` to `site`

---

priv/ingest_repo/migrations/20230417104025_add_revenue_to_events.exs

Revenue tracking: ClickHouse migrations

---

lib/plausible_web/templates/layout/focus.html.eex

Add missed space

---

CHANGELOG.md

This PR just updates the changelog.

update changelog with v2.0.0

---

lib/plausible_web/controllers/stats_controller.ex
test/plausible_web/controllers/stats_controller_test.exs

Respond with early 400 on malformed export request

---

CHANGELOG.md
assets/js/dashboard/stats/behaviours/prop-breakdown.js
assets/js/dashboard/util/url.js
priv/repo/seeds.exs

Fixes: https://github.com/plausible/analytics/issues/3158
Before:
After:

Fix long URLs in outbound breakdown

---

assets/js/dashboard/stats/behaviours/goal-conversions.js
lib/plausible_web/templates/site/settings_props.html.heex
lib/plausible_web/views/layout_view.ex

* rename Properties > Custom Properties in Site Settings
* add back the external links to 404s, File Downloads, Outbound Links
* fix docs link in site settings
* add note about grandfathering customers

Some fixes to the Custom Props feature

---

assets/js/dashboard/stats/graph/interval-picker.js
assets/js/dashboard/stats/graph/visitor-graph.js
assets/js/dashboard/util/date.js
lib/plausible/stats/interval.ex
lib/plausible_web/controllers/api/stats_controller.ex
lib/plausible_web/templates/stats/stats.html.eex
test/plausible/stats/interval_test.exs

This PR disables "date" (=daily 😩) intervals for "all" and "custom" periods if the date range queried exceeds 12 months.

Disallow small intervals on large ranges

---

lib/mix/tasks/analyze_plans.ex
lib/plausible/billing/plans.ex
lib/plausible/billing/site_locker.ex
lib/plausible_web/email.ex
lib/plausible_web/templates/billing/_plan_option.html.eex
lib/plausible_web/templates/billing/change_plan.html.eex
lib/plausible_web/templates/billing/upgrade.html.eex
lib/plausible_web/templates/email/dashboard_locked.html.eex
lib/plausible_web/templates/email/over_limit.html.eex
lib/plausible_web/templates/email/trial_upgrade_email.html.eex
lib/workers/check_usage.ex
lib/workers/notify_annual_renewal.ex
priv/sandbox_plans.json
priv/unlisted_plans_v1.json
priv/unlisted_plans_v2.json
test/plausible/billing/plans_test.exs

This commit introduces a series of improvements on the Plans module including function renaming, documentation and readability. This is the groundwork for billing plans.
There should be no _actual_ changes with this commit, therefore no changes in tests either.

Refactor Plausible.Billing.Plans module

---

lib/plausible/stats/filter_suggestions.ex
lib/plausible_web/controllers/api/external_stats_controller.ex

Fix filter suggestions

---

lib/plausible_web/email.ex
lib/plausible_web/templates/layout/priority_email.html.eex
test/plausible_web/email_test.exs

Separates emails that can be unsubscribed from and those that cannot.

Add new priority email template

---

config/runtime.exs
lib/plausible_web/endpoint.ex
lib/plausible_web/live_socket.ex
lib/plausible_web/plugs/runtime_session_adapter.ex

This reverts commit 65f7b4c5ccf628f8aadc81a80ea773f8aee39173.
Re-submit of #3274

Revert "Revert "Reconfigure session cookie (#3274)" (#3284)"

---

config/runtime.exs

I tested the changes on staging.

verify tls connection to clickhouse and postgres

---

lib/plausible/auth/auth.ex
lib/plausible/auth/user.ex
lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/live/register_form.ex
lib/plausible_web/live/reset_password_form.ex
test/plausible/auth/user_test.exs
test/plausible_web/controllers/auth_controller_test.exs

Improve forms

---

priv/repo/migrations/20231003081927_add_user_previous_email.exs

Migration must be executed before deploying the rest of https://github.com/plausible/analytics/pull/3388

Add `previous_email` column to `users`

---

priv/repo/migrations/20231011101825_add_email_activation_codes.exs

Add `email_activation_codes` table

---

lib/plausible/auth/user.ex
lib/plausible_web/components/generic.ex

Fix master build

---

lib/plausible_web/live/components/visitors.ex
lib/plausible_web/live/sites.ex

Show 0% change on the small plot

---

lib/plausible/sites.ex

Fix sites query invitation left join lookup

---

lib/plausible/sites.ex
test/plausible/site/sites_test.exs

Fixups sites

---

test/plausible_web/controllers/api/stats_controller/pages_test.exs
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs

This PR adds tests for which https://github.com/plausible/analytics/pull/3446 fails unless https://github.com/ruslandoga/analytics/pull/183 is merged.

add tests for time_on_page edge cases

---

lib/plausible_web/controllers/site/membership_controller.ex
test/plausible_web/controllers/site/membership_controller_test.exs

ref https://github.com/plausible/analytics/pull/3493
Fixes a bug where the invitation form submit renders disabled

Fix disabled invitation form on business tier

---

lib/plausible_web/components/billing.ex
lib/plausible_web/templates/site/new.html.heex
test/plausible_web/components/billing_test.exs
test/plausible_web/controllers/site_controller_test.exs

Keeping this open here until there are either more changes or something more critical to deploy.

Fixing Business Tier related bugs

---

priv/repo/migrations/20231115140646_add_totp_user_fields_and_recovery_codes.exs

Extracted from https://github.com/plausible/analytics/pull/3525

Create migration adding TOTP fields to `users` and recovery codes table

---

lib/plausible/auth/user.ex
lib/plausible/auth/user_admin.ex
lib/plausible/billing/billing.ex
lib/plausible/billing/quota.ex
lib/plausible/billing/site_locker.ex
lib/plausible/stats/clickhouse.ex
lib/plausible/users.ex
lib/plausible_web/components/billing.ex
lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/controllers/billing_controller.ex
lib/plausible_web/email.ex
lib/plausible_web/live/choose_plan.ex
lib/plausible_web/templates/auth/user_settings.html.heex
lib/plausible_web/views/text_helpers.ex
lib/workers/check_usage.ex
lib/workers/send_trial_notifications.ex
test/plausible/billing/billing_test.exs
test/plausible/billing/quota_test.exs
test/plausible_web/controllers/auth_controller_test.exs
test/plausible_web/controllers/billing_controller_test.exs
test/plausible_web/live/choose_plan_test.exs
test/support/test_utils.ex
test/workers/check_usage_test.exs
test/workers/send_trial_notifications_test.exs

This reverts commit c739b8878d25710473fb4b18875dbbd9ebe94701.

Reapply "Define a better monthly pageview usage (#3564)"

---

.github/workflows/build-private-images.yml

Ref: https://github.com/docker/metadata-action/pull/352#issuecomment-1833733738

Pin https://github.com/docker/metadata-action/

---

lib/plausible/auth/user_admin.ex
lib/plausible_web/templates/auth/user_settings.html.heex
priv/repo/seeds.exs
test/test_helper.exs

Follow-up to #3541 which is fully released by now.
BTW fixes one small build compilation issue that popped up recently.

Remove `two_factor` feature flag

---

test/plausible/rate_limit_test.exs

This PR fixes the tests that failed in a recent action: https://github.com/plausible/analytics/actions/runs/7169184626/job/19519017227

fix flaky rate_limit test

---

lib/plausible/billing/plan.ex
lib/plausible_web/live/choose_plan.ex
priv/plans_v4.json
priv/repo/migrations/20231208125624_add_data_retention_in_years_to_plans.exs
priv/sandbox_plans.json
test/plausible_web/live/choose_plan_test.exs

This PR adds data retention as a benefit of the new V4 plans.

Add data retention to the choose plan page

---

assets/js/liveview/dropdown.js
lib/plausible_web/components/generic.ex
lib/plausible_web/live/sites.ex
test/plausible_web/live/sites_test.exs

Refactoring to consolidate some UI code

Use dropdown component in /sites page

---

lib/plausible/site.ex
lib/plausible/site/cache.ex
lib/plausible/site/gate_keeper.ex
priv/repo/migrations/20231211092344_add_accept_traffic_until_to_sites.exs
test/plausible/ingestion/event_test.exs
test/plausible/site/cache_test.exs
test/plausible/site/gate_keeper_test.exs

Contains migration that needs to be merged first (#3627).

Add `:payment_required` policy to `GateKeeper`

---

CHANGELOG.md
config/runtime.exs
lib/plausible/application.ex
lib/plausible/event/write_buffer.ex
lib/plausible/ingestion/write_buffer.ex
lib/plausible/session/cache_store.ex
lib/plausible/session/write_buffer.ex
test/plausible/session/cache_store_test.exs

This PR retries https://github.com/plausible/analytics/pull/3511, but with the session insert order fixed.
I'm keeping it in draft until https://github.com/plausible/analytics/pull/3622 is merged

Flush Clickhouse buffers faster by encoding early

---

assets/js/dashboard/comparison-input.js

Fix dropdown highlighting for comparisons

---

priv/repo/migrations/20231219083050_track_accept_traffic_until_notifcations.exs
priv/repo/migrations/20231220072829_add_accept_traffic_until_to_user.exs

Only new table structures for now, backfill will be separate

Migrations for #3641

---

lib/plausible_web/email.ex
lib/plausible_web/templates/email/approaching_accept_traffic_until.html.heex
test/plausible_web/email_test.exs

Greet the user and add line breaks between paragraphs

Improve approaching accept_traffic_until e-mail

---

assets/js/dashboard/stats/modals/modal.js

This reverts commit 75a7ef52410b7ffa8bc373eeb74f335d7a296918.
Addresses a problem of non-functional filters due to regression in FE code.

Revert "Prevent scrollbar click to close modal (#3651)"

---

priv/repo/migrations/20231220101920_backfill_accept_traffic_until.exs

Data backfill necessary once #3641 is live
@RobertJoonas 70224db is per your suggestion

Lock traffic data backfill

---

lib/plausible_web/controllers/auth_controller.ex
test/plausible_web/controllers/auth_controller_test.exs

Rate limit e-mail change to 2 per hour. We see you :)

Rate limit e-mail changes

---

assets/js/app.js
assets/js/liveview/combo-box.js
extra/lib/plausible_web/live/funnel_settings/form.ex
lib/plausible_web/components/generic.ex
lib/plausible_web/live/components/combo_box.ex
lib/plausible_web/live/components/modal.ex
lib/plausible_web/live/goal_settings.ex
lib/plausible_web/live/goal_settings/form.ex
lib/plausible_web/live/goal_settings/list.ex
lib/plausible_web/live/props_settings/form.ex
test/plausible_web/live/goal_settings/form_test.exs
test/plausible_web/live/goal_settings_test.exs

This PR:
- implements universal LV modal component ([documentation](https://github.com/plausible/analytics/pull/3649/files#diff-2da12bc470c3b45efacd72241d0c957fb5bad2c49aa0d87d3822bf19487070a1R2-R84))
- refactor ComboBox compoenent to provide better feedback on high latency connections
- refactors Goal Settings form to use the new modal and makes the form contents provide better feedback on high latency connections

Latency-friendly LV modal implementation and Goals form refactor

---

lib/plausible_web/live/plugins/api/token_form.ex

fyi @aerosol. i guess this change doesn't break anything

capital P in WordPress

---

priv/ref_inspector/referers.yml
test/plausible_web/controllers/api/external_controller_test.exs

Update ref_inspector database

---

lib/plausible_web/live/plugins/api/settings.ex
test/plausible_web/controllers/api/external_sites_controller_test.exs
test/plausible_web/live/plugins_api_tokens_test.exs

WordPress spelling fixup

---

lib/plausible_web/components/generic.ex
lib/plausible_web/templates/layout/_settings_tab.html.eex
lib/plausible_web/templates/layout/_settings_tab.html.heex
lib/plausible_web/templates/layout/site_settings.html.eex
lib/plausible_web/templates/site/settings_danger_zone.html.eex
lib/plausible_web/views/layout_view.ex

Decorate site settings sidebar with heroicons

---

config/runtime.exs
lib/plausible/site/gate_keeper.ex
test/plausible/ingestion/event_test.exs
test/plausible/site/gate_keeper_test.exs

Temporarily disable accept_traffic_until actions

---

lib/plausible_web/components/billing/notice.ex
lib/plausible_web/templates/billing/change_enterprise_plan_contact_us.html.eex
test/plausible_web/components/billing/notice_test.exs
test/plausible_web/controllers/billing_controller_test.exs

Make `hello@plausible.io` clickable

---

lib/plausible_web/templates/layout/_tracking.html.heex

We just released support for multiple custom property filters, but our demo/live setup does not have many useful custom properties. This PR adds a few more to allow better slicing-and-dicing.

Add more custom properties to be tracked

---

priv/repo/migrations/20240123085318_add_ip_block_list_table.exs

Shields IP blocklist: migration

---

assets/js/dashboard/api.js
assets/js/dashboard/query.js
lib/plausible/site.ex
lib/plausible/stats/base.ex
lib/plausible/stats/query.ex
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs

Experimental session count

---

priv/repo/migrations/20240220144655_cascade_delete_ip_rules.exs

Forgotten `on_delete` in #3761

Allow site deletion with IP Rules stored

---

lib/plausible/billing/feature.ex

Use `String.to_atom/1` at compile time

---

.github/workflows/build-public-images-ghcr.yml

Publish community edition under plausible/community-edition on GHCR and dockerhub

---

lib/plausible_web/live/shields/country_rules.ex
test/plausible_web/live/shields/countries_test.exs

Fix `added_by` not saving on adding country rules

---

priv/repo/migrations/20240214114158_add_legacy_flag_to_site_imports.exs

Migration extracted from #3727 in order to deploy and run it before releasing the code depending on it.

Add `legacy` flag column to `site_imports` schema

---

test/plausible_web/controllers/api/stats_controller/screen_sizes_test.exs

I broke tests in https://github.com/plausible/analytics/pull/3854 and https://github.com/plausible/analytics/pull/3863 combined. This PR gets the tests green again

Fix broken tests

---

lib/plausible_web/templates/layout/_footer.html.heex

ref https://github.com/plausible/analytics/pull/3879

changes to the in-app footer (clean)

---

Makefile
config/.env.dev
config/.env.test
config/runtime.exs
lib/plausible/s3.ex
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/router.ex
lib/plausible_web/templates/site/settings_imports_exports.html.heex
test/plausible/config_test.exs

This PR makes the "Export to CSV" button in `/:website/settings/imports-exports` schedule a `Plausible.Workers.ExportCSV` job.

CSV exports (UI)

---

extra/lib/plausible/stats/goal/revenue.ex
lib/plausible/stats/aggregate.ex
lib/plausible/stats/base.ex
lib/plausible/stats/breakdown.ex
lib/plausible/stats/timeseries.ex
lib/plausible/stats/util.ex
test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
test/plausible_web/controllers/api/stats_controller/conversions_test.exs

Reverts plausible/analytics#3887
Getting a new sentry error with conversions: https://sentry.plausible.io/organizations/sentry/issues/5608/?query=is%3Aunresolved

Revert "Move conversion_rate logic from elixir to clickhouse"

---

priv/repo/migrations/20240319094940_add_label_to_site_imports.exs

Migration that has to be run before releasing https://github.com/plausible/analytics/pull/3914

Add `label` column to `site_imports` schema

---

lib/plausible/imported/csv_importer.ex

For https://github.com/plausible/analytics/pull/3949

Insert columns in s3 import

---

lib/plausible/data_migration/site_imports.ex
test/plausible/data_migration/site_imports_test.exs

This PR alters the behavior of the data migration so that all existing imports without any CH data are simply deleted.

Delete imports which have no stats in `DataMigration.SiteImports`

---

lib/plausible/application.ex
lib/plausible/request_logger.ex
lib/plausible_web/endpoint.ex

This reverts commit acbd2f8e308d89f1cda0097073f524cc6fabe8be.

Reapply "Include query string when logging the request (#3971)" (#3984)

---

test/plausible/google/api_test.exs

Should address frequent test run failures on CI like https://github.com/plausible/analytics/actions/runs/8615634478/job/23623815751?pr=3989

Fix flaky tests caused by hardcoded import ID

---

priv/repo/migrations/20240407104659_shield_hostname_rules.exs

Migration extracted from #3990

Add shield hostname rules migration

---

lib/plausible/stats/breakdown.ex
lib/plausible/stats/imported.ex
test/plausible/imported/google_analytics4_test.exs
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
test/plausible_web/controllers/api/stats_controller/browsers_test.exs
test/plausible_web/controllers/api/stats_controller/operating_systems_test.exs
test/plausible_web/controllers/api/stats_controller/screen_sizes_test.exs

* Refactor the `Plausible.Stats.Imported` module (mainly the `merge_imported` function)
* Add support for new properties in `merge_imported`
* `os_version`
* `browser_version`
* `utm_source`
* `referrer`

Improve merge imported

---

assets/js/dashboard/stats/graph/interval-picker.js
assets/js/dashboard/util/date.js

This PR fixes a regression caused by https://github.com/plausible/analytics/pull/3936 where invalid intervals were returned for the custom period. It also makes the default intervals more sensible.

Fix main graph intervals

---

priv/ingest_repo/migrations/20240419133926_add_active_visitors_to_imported_pages.exs

Migration extracted from https://github.com/plausible/analytics/pull/4027

Add `active_visitors` column to `imported_pages` CH table

---

config/runtime.exs
lib/plausible/auth/totp.ex
lib/plausible/auth/user_admin.ex
lib/plausible/purge.ex
lib/plausible/site.ex
lib/plausible/site/admin.ex
test/plausible/auth/totp_test.exs
test/plausible_web/controllers/admin_controller_test.exs

Add new actions to CRM

---

test/plausible_web/controllers/api/stats_controller/suggestions_test.exs

Fix a test failing due to inconsistent ordering of results.

Fix a test

---

lib/plausible/exports.ex

This PR makes all export queries use events_v2 for pageviews.
I'll perform manual tests with plausible.io data to check if this is enough or if other queries that have pageviews need to be updated as well.
Top stats pageviews seem to be "correct" now:
Since imported data filtering is not implemented yet, I'm not sure how to check `pageviews` exported in other queries.

use events_v2 for pageviews export

---

priv/ingest_repo/migrations/20240502115822_alias_api_prop_names.exs

This allows for simplifications in the API code.
Companion (App code) PR: https://github.com/plausible/analytics/pull/4059

Add migration to add ALIAS columns to common session/visit properties

---

lib/plausible/stats/base.ex
lib/plausible/stats/breakdown.ex

Uses https://github.com/plausible/analytics/pull/4058 to simplify some API code

Use ALIAS columns to simplify querying API

---

lib/plausible_web/live/imports_exports_settings.ex

This PR makes minor adjustments to distances/margins within import labels so that they are more consistent. The import entry got extracted to a separate sub-component in the process.

Improve styling of imports list

---

lib/plausible_web/templates/site/settings_imports_exports.html.heex

Adds a feature flag override on CSV export UI.

Add override on CSV exports for super admins

---

lib/plausible/exports.ex

This PR just fixes a type typo.

fix type in date_range/2

---

lib/plausible/exports.ex

This PR refactors export queries a bit.

Refactor filtering in export queries

---

config/runtime.exs

This PR updates self-hosted config links to https://github.com/plausible/community-edition/tree/v2.1.0

update links to configs

---

lib/plausible/stats/comparisons.ex
lib/plausible/stats/query.ex
test/plausible/stats/query_test.exs

Just some groundwork that is relevant for me and @zoldar to work with. No behavioural changes, just introducing a new field.

Introduce :skip_imported_reason field into Query struct

---

lib/plausible_web/controllers/api/external_stats_controller.ex
test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs

This PR adds a hint in a form of warning to Stats API responses when imported data are requested but can't be processed because query parameters are not supported for it.
Goes together with changes in docs at https://github.com/plausible/docs/pull/499/files

Return warning when imported stats are skipped in Stats API due to unsupported query

---

lib/plausible/verification/diagnostics.ex
lib/plausible/verification/errors.ex
test/plausible/site/verification/checks_test.exs

We like to make them easier to maintain.
An update fixing documentation URLs will follow.

First pass: extract verification errors

---

lib/plausible/stats/filters/dashboard_filter_parser.ex

Closes https://github.com/plausible/analytics/issues/4135

remove duplicate clause in filter parser

---

lib/plausible/verification/errors.ex

Ref https://github.com/plausible/docs/pull/498

Include docs anchors in diagnostic message links

---

assets/js/dashboard/stats/modals/sources.js

This was broken by a recent refactor and the links did not filter properly.

Fix linking in dashboard sources/utm details modal

---

lib/plausible/verification/check.ex
lib/plausible/verification/checks/csp.ex
lib/plausible/verification/checks/fetch_body.ex
lib/plausible/verification/checks/installation.ex
lib/plausible/verification/checks/scan_body.ex
lib/plausible/verification/checks/snippet.ex
lib/plausible/verification/checks/snippet_cache_bust.ex
lib/plausible/verification/diagnostics.ex
lib/plausible_web/live/components/verification.ex
lib/plausible_web/live/verification.ex
test/plausible/site/verification/checks_test.exs
test/plausible_web/live/components/verification_test.exs

Minor reorganization of annoying bits

Tidy up verification code a little

---

CHANGELOG.md
lib/plausible/imported/csv_importer.ex
test/plausible/imported/csv_importer_test.exs

add newline to csv importer insert sql

---

lib/plausible/verification/errors.ex

Periods are added later on when necessary.

Remove redundant dot

---

CHANGELOG.md

This PR updates changelog for the v2.1.1 patch release.

release v2.1.1

---

CHANGELOG.md
lib/plausible/auth/api_key.ex
test/plausible/auth/auth_test.exs

increase api_keys.hourly_request_limit in CE

---

lib/plausible/stats/base.ex

Follow up to https://github.com/plausible/analytics/pull/4204 - make the CI green again.

Make CI green (remove broken typespec)

---

assets/js/dashboard/filters.js

Caused issues with the filter dropdown menu. Will have a closer look later.

Revert filters.js changes from 14cf650

---

CHANGELOG.md
lib/plausible/auth/auth.ex
lib/plausible/billing/feature.ex
test/plausible/auth/auth_test.exs
test/plausible/billing/feature_test.exs
test/plausible_web/controllers/api/external_stats_controller/auth_test.exs
test/plausible_web/plugins/api/controllers/capabilities_test.exs

Fixes #4243 by always allowing StatsAPI feature in CE.

fix ce stats api access

---

assets/js/dashboard/stats/behaviours/goal-conversions.js

cc @ukutaht - re: https://3.basecamp.com/5308029/buckets/32037438/card_tables/cards/7484474363#__recording_7524191145

Add WordPress Search Queries "special goal"

---

assets/js/dashboard/stats/behaviours/index.js

This adds max height + overflow to the funnel picker

Add max height/overflow to funnel picker

---

assets/js/dashboard.js
assets/js/dashboard/router.js

I have no idea what I'm doing wrt react router, but this seems to work?

Make new tab dashboard links work

---

assets/js/dashboard/util/url.js
priv/repo/seeds.exs

Fixes regression made via https://github.com/plausible/analytics/pull/4278

Bugfix: opening details UTM sources modal

---

lib/plausible/stats/goal_suggestions.ex

This is a fix for situations where large number of existing goals caused the suggestions query run over the limit of parameters in the CH query. As, worst case, this will cause suggesting goal which is already added (which is later validated anyway), it's safe to trim the list of exclusions.
The fix is not ideal but will address the immediate problem of goal settings failing to load for sites with large number of goals defined.

Limit excluded goals to 1000 in goal suggestions

---

lib/plausible/site/spike_notification.ex
priv/repo/migrations/20240702055817_traffic_drop_notifications.exs

Extracted from #4300 
This PR cannot pass CI without code changes. Thus, the "validate migrations" step will fail.

Migration: add traffic change type

---

priv/repo/migrations/20240708120453_create_help_scout_credentials.exs

Migration extracted from https://github.com/plausible/analytics/pull/4327.

Add migration for table storing HelpScout credentials

---

lib/plausible/application.ex

Closes #4269 
This PR allows to configure Finch pools which are used by the Plausible HTTP client.
Example [configuration](https://github.com/plausible/analytics/pull/3906) to enable proxying:
```elixir
import Config
if http_proxy = System.get_env("HTTP_PROXY") do
%URI{scheme: "http", host: host, port: port} = URI.parse(http_proxy)
config :plausible, Plausible.Finch, conn_opts: [proxy: {:http, host, port, _opts = []}]
end
```

allow to configure Finch pools

---

lib/plausible_web/templates/layout/_header.html.heex

Add margin to CRM link

---

assets/js/dashboard/stats/modals/locations-modal.js

Fix country, region, and city labels when applying a filter from any of the location modals.

Fix location labels

---

lib/plausible_web/controllers/unsubscribe_controller.ex
lib/workers/send_email_report.ex
test/plausible_web/controllers/unsubscribe_controller_test.exs
test/workers/send_email_report_test.exs

Fixes the following sentry crashes
https://sentry.plausible.io/organizations/plausible/issues/53/?project=2&query=is%3Aunresolved&referrer=issue-stream&stream_index=7
https://sentry.plausible.io/organizations/plausible/issues/52/?query=is%3Aunresolved&referrer=issue-stream&stream_index=23

Fix email report sentry errors

---

CHANGELOG.md

Follow up to https://github.com/plausible/analytics/pull/4378

Update changelog about search in Google Keywords modal

---

lib/plausible/stats/sql/where_builder.ex

This PR addresses a pretty sneaky issue leading to inconsistent and incomplete view of stats for sites with large number of events. More details put in code comment.

Make time range filter for sessions not break sample size estimation

---

priv/repo/migrations/20240722143005_create_helpscout_mappings.exs

Migration which is prerequisite to https://github.com/plausible/analytics/pull/4377/commits/a405052443b272c80c026b41b628d4a185dcba83

Helpscout email mapping migration

---

assets/js/dashboard/filters.js

Removed extraneous path from link

Fix extraneous link fragment

---

assets/js/dashboard/stats/modals/conversions.js
lib/plausible/goals/filters.ex
lib/plausible/stats/filters/query_parser.ex
test/plausible_web/controllers/api/external_stats_controller/query_test.exs
test/plausible_web/controllers/api/stats_controller/conversions_test.exs

Adds support for goal contains filter and adds search functionality into the goal details view in the dashboard.
Should be documented in APIv2 docs which are in the works

Implement goal contains filter + search in Conversions > Details

---

assets/js/dashboard/stats/behaviours/conversions.js
assets/js/dashboard/stats/modals/breakdown-modal.js

* [Always show details modal for goal conversions](https://github.com/plausible/analytics/commit/66cb6ebe1f7615b1823f8c39fa7fc528c7bd1eb0)
* [Make metrics smaller in breakdown table](https://github.com/plausible/analytics/commit/34b4b5807e9f0f13990c7ee732f1a06a954f2e1b)

Goal detail tweaks

---

CHANGELOG.md
assets/js/dashboard/components/filter-operator-selector.js
assets/js/dashboard/util/filters.js

Expose goal contains filter in dashboard

---

assets/js/dashboard/util/url.js

Stop JSONUrl parse failures from crashing the app

---

priv/repo/migrations/20240801052902_add_goal_display_name.exs

Display names: 1st stage migration

---

lib/plausible_web/templates/debug/clickhouse.html.heex

Fix dark mode in clickhouse debug view

---

priv/repo/migrations/20240821033217_add_site_installation_config.exs

Migration extracted from #4459

Migration: add installation meta

---

lib/plausible_web/live/installation.ex

https://github.com/user-attachments/assets/e5877069-84d1-47c5-9ab3-a95fd5750caa

Onboarding improvements improvements

---

priv/repo/migrations/20240822095245_create_user_sessions.exs

Migration extracted from https://github.com/plausible/analytics/pull/4463, for deployment and run before deploying the new logic.

Create `user_sessions` table

---

lib/plausible_web/live/choose_plan.ex
test/plausible_web/user_auth_test.exs

Remove custom background from "Choose Plan" page

---

lib/plausible_web/live/installation.ex
test/plausible_web/live/installation_test.exs

Fixes https://sentry.plausible.io/organizations/plausible/issues/486/?environment=prod&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h&stream_index=6

Installation: don't crash when socket reconnects and finds no changes

---

priv/ingest_repo/migrations/20240829092858_add_acquisition_channel.exs

Migration extracted from https://github.com/plausible/analytics/pull/4489

Migration for acquisition channel

---

lib/plausible_web/live/components/verification.ex
lib/plausible_web/live/verification.ex
test/plausible_web/live/components/verification_test.exs
test/plausible_web/live/verification_test.exs

https://github.com/user-attachments/assets/e57ac18a-d92f-4331-b50a-e922ed0e8608
Yet another debug/troubleshooting option for super-admins

Verification: Add super-admin report displaying diagnostics

---

lib/plausible_web/live/installation.ex

Update to the copy to include a note about billable pageviews. hopefully it doesn't make the copy too long...

Update to the copy

---

test/test_helper.exs

ref: https://github.com/sasa1977/con_cache/pull/79

Warm up ConCache before tests

---

lib/plausible_web/controllers/google_analytics_controller.ex
lib/plausible_web/controllers/invitation_controller.ex
lib/plausible_web/controllers/site/membership_controller.ex
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/controllers/stats_controller.ex
lib/plausible_web/plugs/authorize_site_access.ex
lib/plausible_web/router.ex
test/plausible_web/controllers/site_controller_test.exs
test/plausible_web/plugs/authorise_site_access_test.exs
test/plausible_web/plugs/authorize_site_access_test.exs

This PR is refactoring `AuthorizeSiteAccess`, adding some extra compile- and runtime checks along the way. The range of accepted inputs was revised as well.

Refactor `AuthorizeSiteAccess`

---

assets/js/dashboard/router.tsx
assets/js/dashboard/stats/modals/filter-modal.js
assets/js/dashboard/stats/modals/sources.js
assets/js/dashboard/stats/sources/source-list.js
assets/js/dashboard/util/filters.js
lib/plausible/stats/filter_suggestions.ex
lib/plausible/stats/filters/filters.ex
lib/plausible/stats/legacy/legacy_dimensions.ex
lib/plausible/stats/sql/expression.ex
lib/plausible_web/controllers/api/stats_controller.ex
lib/plausible_web/controllers/stats_controller.ex
lib/plausible_web/router.ex
priv/json-schemas/query-api-schema.json
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
test/plausible_web/controllers/api/external_stats_controller/query_test.exs
test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
test/plausible_web/controllers/api/stats_controller/sources_test.exs
test/plausible_web/controllers/api/stats_controller/suggestions_test.exs

This PR adds dashboard reports for the new `channel` dimension.
Remaining work on channels before go-live:
* Add channels to dashboard CSV export
* Add channels to full CSV export/import
* Import channels from GA4
Feature is not ready yet
Feature is not ready yet

Add feature-flagged channels UI

---

lib/plausible_web/live/verification.ex
test/plausible_web/live/verification_test.exs

Another attempt at https://github.com/plausible/analytics/pull/4459#discussion_r1758491643

Skip verification in CE

---

priv/repo/migrations/20240924085157_add_notes_to_users.exs

Required for https://github.com/plausible/analytics/pull/4611

Add `notes` column to `users` table

---

assets/js/dashboard/filters.js
assets/js/liveview/live_socket.js

Fixes https://github.com/plausible/analytics/issues/4625

Don't track custom events in CE

---

lib/workers/check_usage.ex

Addresses performance regression in `CheckUsage` worker.

Improve `CheckUsage` query performance

---

config/runtime.exs

This PR changes the CE default from "no registration" to "registration by invites".
As recommended in https://github.com/plausible/analytics/issues/1706#issuecomment-2373558928

Default to invite_only in CE

---

test/plausible_web/controllers/auth_controller_test.exs

Test for https://github.com/plausible/analytics/pull/4684

Allow me deletions with enterprise plans test

---

priv/repo/migrations/20240924115329_add_teams_tables_fields.exs

Migration extracted from https://github.com/plausible/analytics/pull/4658

Add fields and tables for teams

---

lib/plausible.ex

Fix `with_teams`

---

lib/plausible_web/live/sites.ex

Remove eex artifact

---

lib/plausible/auth/grace_period.ex
lib/plausible/billing/billing.ex
lib/plausible/data_migration/backfill_teams.ex
lib/plausible/site.ex
lib/plausible/site/memberships/accept_invitation.ex
lib/plausible/sites.ex
lib/plausible/teams.ex
lib/plausible/teams/invitations.ex
test/plausible/billing/billing_test.exs
test/plausible/billing/site_locker_test.exs
test/plausible/site/memberships/accept_invitation_test.exs
test/plausible/site/memberships/create_invitation_test.exs
test/plausible/site/sites_test.exs
test/plausible_web/controllers/site/membership_controller_test.exs
test/support/factory.ex
test/support/teams/test.ex
test/workers/check_usage_test.exs

This PR fixes a number of issues in team sync logic.

Ensure team is present before use in sync logic

---

lib/plausible/data_migration/backfill_teams.ex

Fixes issue in backfill procedure.

Fix backfilling teams for users without sites but with subscriptions

---

lib/plausible/site/memberships/reject_invitation.ex
lib/plausible/site/memberships/remove_invitation.ex
lib/plausible/teams/invitations.ex
test/plausible_web/controllers/invitation_controller_test.exs

Fix further team sync discrepancies

---

CHANGELOG.md
assets/js/dashboard/site-context.tsx
assets/js/dashboard/stats/modals/breakdown-modal.tsx
assets/js/dashboard/stats/reports/metric-value.test.tsx
assets/js/dashboard/stats/reports/metric-value.tsx
lib/plausible_web/controllers/stats_controller.ex

The flag has been enabled in production for a while now, we can clean up the code.

Release breakdown_comparisons_ui flag

---

lib/plausible/teams/invitations.ex

Addresses a (hopefully last) problem with syncing teams schema where yet-unaccepted guest invitations are removed along with the team invitation when syncing accepting the invitation.

Clean up guest invitations selectively after accepting

---

CHANGELOG.md
lib/plausible_web/templates/auth/login_form.html.heex

This adds a missing question mark, so it is equal for both questions (register & forgot password)

Add missing question mark on login page

---

lib/plausible/teams/invitations.ex
lib/plausible/teams/memberships.ex
lib/plausible/teams/team.ex

Yet another round of fixes to team sync procedure.

Fix team struct sync and pruning team memberships/invitations on site transfer

---

lib/plausible/sites.ex
lib/plausible/teams/adapter/read/billing.ex
lib/plausible/teams/adapter/read/ownership.ex
lib/plausible/teams/adapter/read/sites.ex
lib/plausible_web/live/sites.ex

See if a separate namespace helps with reasoning about transitioning new schema reads

Extract schema transitions under delegated namespace

---

lib/plausible_web/controllers/api/stats_controller.ex
lib/plausible_web/controllers/stats_controller.ex
test/plausible_web/controllers/CSVs/30d-filter-goal/channels.csv
test/plausible_web/controllers/CSVs/30d-filter-path/channels.csv
test/plausible_web/controllers/CSVs/30d/channels.csv
test/plausible_web/controllers/CSVs/6m/channels.csv
test/plausible_web/controllers/stats_controller_test.exs
test/test_helper.exs

Adds channels report to the dashboard CSV export.
Will add changelog for the whole channels feature once it's ready for launch
Will add docs for the whole channels feature once it's ready for launch

Channels in dashboard CSV export

---

priv/repo/migrations/20241112092718_set_not_null_on_teams_allow_next_upgrade_override.exs

Follow-up to https://github.com/plausible/analytics/pull/4799

Set NOT NULL on `teams.allow_next_upgrade_override`

---

priv/repo/migrations/20241111121802_add_invitation_id_to_guest_invitations.exs

Extracted from https://github.com/plausible/analytics/pull/4802

Guest invitations update migration

---

priv/repo/migrations/20241112142236_invitation_id_not_null_at_guest_invitations.exs

Once https://github.com/plausible/analytics/pull/4811/files is migrated.

Set `guest_invitations.invitation_id` not null

---

assets/js/dashboard/stats/modals/breakdown-modal.tsx

Make BreakdownModal dimension column use up all remaining width

---

priv/data_migrations/AcquisitionChannel/sql/acquisition_channel_functions.sql.eex
priv/ingest_repo/migrations/20241113194422_update_acquisition_channel_udf.exs
test/plausible/ingestion/acquisition_test.exs
test/plausible_web/controllers/api/external_controller_test.exs

Ref: https://3.basecamp.com/5308029/buckets/39036182/card_tables/cards/8022487952

Update acquisition channel UDF to prioritize display over paid search

---

priv/ingest_repo/migrations/20241112222848_add_channel_to_imported_source.exs

Migration extracted from https://github.com/plausible/analytics/pull/4814

Imported channel migration

---

priv/ingest_repo/migrations/20241028142653_add_scroll_depth_to_events.exs

Migration only, extracted from #4791.

Average Scroll Depth Metric: extracted migration

---

lib/plausible/billing/billing.ex
lib/plausible/teams/adapter/read/billing.ex
lib/plausible/teams/billing.ex
lib/plausible_web/controllers/billing_controller.ex
test/plausible_web/controllers/billing_controller_test.exs

Switch billing controller action to teams schema behind FF

---

lib/plausible/teams/invitations.ex
test/plausible/site/memberships/accept_invitation_test.exs

Fixes an issue with case of site transfers with pending invitations which was failing due to an error in team sync logic.

Fix a regression in accepting site transfers with pending invitations

---

.github/workflows/elixir.yml

We're not expecting a lot of incompatibilities with pg 15 so it makes sense to combine these with reading team schemas

CI: Reduce separate jobs being executed for elixir

---

lib/plausible/stats/sql/query_builder.ex

There was a branch in code where sampling was never triggered. This fixes that issue.

Fix: Add missing SAMPLE BY to query

---

lib/plausible_web/controllers/admin_controller.ex

Improvement to User CRM for users with very large number of sites. As search works again, we don't need it anymore anyway.

Only show sites count in user CRM instead of full list of sites

---

lib/plausible/site/memberships/accept_invitation.ex
lib/plausible/sites.ex

Please see https://github.com/plausible/analytics/pull/4920 for context.

Remove old `Plausible.Site.Membership` references

---

lib/plausible/mailer.ex

Context: https://github.com/plausible/analytics/pull/4885#discussion_r1888126629

Use `inspect` Sentry workaround in mailer

---

lib/plausible/site/admin.ex

Currently all "other members" roles are displayed as "guest", which is not helpful.

Show guest roles for other members in Site CRM

---

lib/mix/tasks/create_free_subscription.ex
lib/plausible/billing/billing.ex
lib/plausible/billing/subscription.ex
lib/plausible/teams.ex
lib/plausible_web/components/billing/billing.ex
test/plausible/billing/billing_test.exs
test/plausible_web/controllers/api/paddle_controller_test.exs
test/plausible_web/controllers/billing_controller_test.exs
test/plausible_web/controllers/settings_controller_test.exs
test/plausible_web/live/choose_plan_test.exs

A slight cleanup of Paddle webhook.

Refactor Paddle webhook

---

lib/plausible/teams/invitations/candidates.ex
test/plausible/teams/invitations/candidates_test.exs

A small building block for team setup process:

Implement basic service for searching through site guests 

---

lib/plausible_web/live/sites.ex

someone sent a screenshot of this message and it looked too long and unclear to me so here's an attempt at shortening it

Shortened copy

---

lib/plausible/cache.ex

This wraps cache refreshes with a pokemon catch, so that whatever happens with postgres, the cache supervision tree remains stable.

Keep caches alive in case of postgres unavailability

---

priv/repo/migrations/20250120095114_add_teams_identifier.exs

Migration needed for https://github.com/plausible/analytics/pull/4977 and multiple-teams switcher going-forward

Implement migration adding UUID identifier to team

---

assets/js/dashboard/components/search-input.tsx
assets/js/dashboard/datepicker.tsx
assets/js/dashboard/keybinding.tsx
assets/js/dashboard/stats/modals/modal.js
lib/plausible/segments/segment.ex

This small refactor is so we could have
* segments dropdown with search in it (event.stopPropagation() doesn't work when both listeners are on document)
* segments modals that don't function like a separate page

Keybind and modal refactor

---

lib/plausible_web/live/components/combo_box.ex
test/plausible_web/live/components/combo_box_test.exs

Remnants from https://github.com/plausible/analytics/pull/4960

ComboBox: revert unused changes

---

lib/plausible/application.ex

Follow-up to https://github.com/plausible/analytics/pull/5069

Adjust sessions cache TTL check interval down to 10s

---

lib/plausible/stats/sql/expression.ex

Remove a dead todo

---

config/runtime.exs
lib/plausible/application.ex
lib/plausible/cache/adapter.ex
lib/plausible/cache/stats.ex
test/plausible/cache/adapter_test.exs
test/plausible/cache_test.exs

This PR introduces cache partitioning mechanism in `Plausible.Cache.Adapter` and uses it for `sessions`.

Implement support for cache partitioning for sessions

---

priv/ingest_repo/migrations/20250218094453_create_custom_event_array_function.exs

See #5084  for full information.

Extracted migration from PR #5084 (createCustomEventArray udf)

---

assets/js/dashboard/stats/graph/stats-export.js
lib/plausible_web/controllers/stats_controller.ex
lib/plausible_web/plugs/authorize_site_access.ex
test/plausible_web/controllers/stats_controller_test.exs

Allow access to CSV export only to authenticated users having access to the website.

Restrict public CSV export access

---

assets/js/dashboard/stats/graph/stats-export.js
assets/js/dashboard/user-context.tsx

Ref https://github.com/plausible/analytics/issues/5090

Ensure no export button is rendered for public roles

---

priv/ingest_repo/migrations/20250219093806_events_engagement_time.exs

Migration extracted from https://github.com/plausible/analytics/pull/5093

Migration to add new engagement_time column

---

lib/plausible/clickhouse_event_v2.ex
lib/plausible/ingestion/event.ex
lib/plausible/ingestion/request.ex
test/plausible/ingestion/request_test.exs
test/plausible_web/controllers/api/external_controller_test.exs

The previous PR was merged into a dependant branch not master :facepalm: https://github.com/plausible/analytics/pull/5093

time-on-page: Ingestion logic for engagement_time

---

test/plausible_web/plugs/tracker_test.exs
tracker/report-sizes.js
tracker/src/plausible.js
tracker/test/fixtures/engagement-hash-exclusions.html
tracker/test/fixtures/engagement-hash-pageview-props.html
tracker/test/fixtures/engagement-hash.html
tracker/test/fixtures/engagement-manual.html
tracker/test/fixtures/engagement-pageview-props.html
tracker/test/fixtures/engagement.html
tracker/test/fixtures/scroll-depth-content-onscroll.html
tracker/test/fixtures/scroll-depth-dynamic-content-load.html
tracker/test/fixtures/scroll-depth-hash.html
tracker/test/fixtures/scroll-depth-slow-window-load.html
tracker/test/fixtures/scroll-depth.html

This reverts commit 079b40068c17ee623f8a9fcb2e84a4c9106b12ed. The extra load frequent app restarts to occur again.

Revert "Scroll Depth Release: make pageleave script the new default

---

tracker/package-lock.json
tracker/package.json

Update tracker deps

---

assets/js/dashboard/segments/routeless-segment-modals.tsx

Fixes issue with mutation error state persisting through close modal -> reopen modal cycle.

Stop error state from persisting

---

test/plausible_web/plugs/tracker_test.exs
tracker/report-sizes.js
tracker/src/plausible.js
tracker/test/fixtures/engagement-hash-exclusions.html
tracker/test/fixtures/engagement-hash-pageview-props.html
tracker/test/fixtures/engagement-hash.html
tracker/test/fixtures/engagement-manual.html
tracker/test/fixtures/engagement-pageview-props.html
tracker/test/fixtures/engagement.html
tracker/test/fixtures/scroll-depth-content-onscroll.html
tracker/test/fixtures/scroll-depth-dynamic-content-load.html
tracker/test/fixtures/scroll-depth-hash.html
tracker/test/fixtures/scroll-depth-slow-window-load.html
tracker/test/fixtures/scroll-depth.html

Trying this again cc @RobertJoonas @macobo @ruslandoga @aerosol

Scroll Depth Release: make pageleave script the new default (#5105)

---

tracker/src/plausible.js
tracker/test/fixtures/no-defer.html
tracker/test/scroll-depth.spec.js

Follow-up fix for yesterday's engagements release

Access document more defensively

---

CHANGELOG.md

Shows Saved Segments related changes in changelog. To be merged as per the release plan in Basecamp.

Show Saved Segments in changelog

---

assets/js/dashboard/stats/graph/stats-export.js
assets/js/dashboard/user-context.tsx
lib/plausible_web/controllers/stats_controller.ex
lib/plausible_web/plugs/authorize_site_access.ex
test/plausible_web/controllers/stats_controller_test.exs

https://secure.helpscout.net/conversation/2868770513/23550?viewId=6977434

Exports revert

---

lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/live/team_management.ex
test/plausible_web/live/team_setup_test.exs
test/support/html.ex

Removes excessive flash messages and ensures team member limit is reported early on.

Team provisioning tweaks

---

assets/js/dashboard/segments/segment-modals.tsx

Reorders buttons on Segment modals.

Update button positions

---

priv/repo/migrations/20250224074807_rename_my_team.exs

Follow-up to https://github.com/plausible/analytics/pull/5144 to keep things consistent, even if not strictly necessary.

Migration: rename "My Team" to "My Personal Sites"

---

assets/js/dashboard.tsx
assets/js/dashboard/user-context.tsx
lib/plausible_web/templates/stats/stats.html.heex
test/plausible_web/controllers/stats_controller_test.exs

Fix shared link site role

---

priv/ingest_repo/migrations/20250316182725_ingest_counters_tracker_script_version.exs

Migration for https://github.com/plausible/analytics/pull/5198

Migration to add `tracker_script_version` to ingest_counters table

---

lib/plausible_web/components/generic.ex
lib/plausible_web/live/team_setup.ex
lib/plausible_web/templates/settings/team_general.html.heex

Ref https://github.com/plausible/docs/pull/589

Docs links for teams

---

test/plausible_web/controllers/api/stats_controller/sources_test.exs

Stop logging noise during tests

---

lib/plausible_web/live/components/form.ex
lib/plausible_web/templates/layout/settings.html.heex
lib/plausible_web/templates/layout/site_settings.html.heex

This PR makes site/account settings sidebars sticky
https://github.com/user-attachments/assets/4467eba4-d8b9-47eb-80c2-851277b3ffa9
https://github.com/user-attachments/assets/58a022ab-cfde-4e1b-8f28-ee06ffa8a633

Make settings sidebars sticky

---

lib/plausible/application.ex
lib/plausible/ingestion/event.ex

Ref https://hexdocs.pm/elixir/Task.Supervisor.html#module-scalability-and-partitioning

Use `PartitionSupervisor` for UA parse dispatch

---

priv/repo/migrations/20250318131615_site_legacy_time_on_page_cutoff.exs

Extracted migration from https://github.com/plausible/analytics/pull/5215

time-on-page: site.legacy_time_on_page migration

---

lib/plausible_web/live/team_management.ex
lib/plausible_web/live/team_setup.ex
lib/plausible_web/templates/email/team_member_removed.html.heex
test/plausible_web/live/team_setup_test.exs

Ensure guest promotion e-mail is sent w/ updated team name

---

lib/plausible/teams/team_admin.ex

Show number of setup teams in CRM dashboard

---

lib/plausible_web/templates/site/new.html.heex

Remove trial notice on 1st site creation

---

lib/plausible_web/components/team/notice.ex

Add styling to CTA link

---

lib/plausible/teams.ex
lib/plausible_web/live/sites.ex
lib/plausible_web/live/team_setup.ex
lib/plausible_web/plugs/authorize_team_access.ex
lib/plausible_web/templates/layout/_header.html.heex
lib/plausible_web/templates/layout/settings.html.heex
lib/plausible_web/views/layout_view.ex
priv/repo/seeds.exs
test/plausible/billing/billing_test.exs
test/plausible/site/site_removal_test.exs
test/test_helper.exs

Remove `teams` feature flag as teams are released by now and fix broken seeds.

Remove `teams` feature flag and fix seeds

---

.github/workflows/migrations-validation.yml
lib/plausible/migration_utils.ex
priv/repo/migrations/20240528115149_migrate_site_imports.exs
priv/repo/migrations/20250403093826_backfill_teams_hourly_api_request_limit.exs

Fix determining CE/EE in migrations

---

lib/plausible/billing/site_locker.ex
lib/plausible/data_migration/backfill_teams.ex
lib/plausible/teams.ex
lib/plausible/teams/team.ex

Refs https://github.com/plausible/analytics/pull/5304

Update `team.locked` in parallel with `sites.locked` in SiteLocker

---

lib/plausible/data_migration/backfill_teams.ex

As team backfill is now run in (CE-only) migration, its use of Ecto schemas causes issues every time the used schemas change. This PR converts the backfill procedure to use schemaless queries exclusively. The underlying columns and tables must remain for the migration to work but it's not dependent on Ecto-level schemas anymore.

Make BackfillTeams completely schemaless

---

lib/plausible/session/transfer.ex
lib/plausible/telemetry/plausible_metrics.ex

I think we should follow the others, right? @ruslandoga 
Not sure if this warrants a new metric name just in case?

Change session transfer duration unit

---

CHANGELOG.md
tracker/package.json
tracker/src/plausible.js

Fixes #5343
I couldn't find tests for existing older prerendered check, which this just extends. So not sure if
Can add/update docs if this change is accepted

Only log a pageview for visible pages

---

extra/lib/plausible_web/live/customer_support/live/team.ex
lib/plausible_web/live/components/form.ex

This PR carries over a small convenience in plan form CRM, where co-dependent features are selected and deselected for consistency.

Automatically select and deselect dependent API features in CS

---

extra/lib/plausible_web/live/customer_support/live/site.ex
extra/lib/plausible_web/live/customer_support/live/team.ex
lib/plausible/teams.ex

CS: display only team's sites + rejecting traffic info if applicable

---

extra/lib/plausible_web/live/customer_support.ex
test/plausible_web/live/customer_support/sites_test.exs
test/plausible_web/live/customer_support/teams_test.exs
test/plausible_web/live/customer_support/users_test.exs
test/plausible_web/live/customer_support_test.exs

Just a very basic stab at #5390 tests

Minimal stub for CS tests

---

priv/repo/migrations/20250520084130_add_sso_tables_columns.exs

Migration extracted from https://github.com/plausible/analytics/pull/5411

Add migration adding SSO-related schemas, columns and indexes

---

lib/plausible/session/salts.ex

Context: https://github.com/plausible/analytics/pull/5401 and https://github.com/plausible/analytics/pull/5421#issuecomment-2915828007

log salt hashes with warnings

---

lib/plausible_web/components/team/notice.ex
lib/plausible_web/templates/layout/_header.html.heex

Removing "new" and "now" as teams have been available for some time now
cc @zoldar

Small changes to the teams copy

---

lib/plausible_web/components/generic.ex

This fixes a dummy "refresh" when hitting enter on filter bars, e.g. in CRM.

Add phx-submit to filter bars

---

priv/repo/migrations/20250603104648_remove_teams_from_plan_features.exs

Ref https://github.com/plausible/analytics/commit/38f1de6ecdccd636facf74fcc9e48a1f37f8fdd5

Remove `teams` feature from custom plans

---

extra/lib/plausible_web/live/customer_support/live/user.ex
test/plausible_web/live/customer_support/users_test.exs

Extracted from #5442 since the OG PR will have to sit there for a while.

CRM: List API keys per user

---

extra/lib/plausible_web/live/customer_support/live/site.ex
extra/lib/plausible_web/live/customer_support/live/team.ex
test/plausible_web/live/customer_support/sites_test.exs

CRM: Add quick links section to site view

---

extra/lib/plausible_web/live/customer_support/live/team.ex

CRM: fix lock icon

---

.github/workflows/build-private-images-ghcr.yml

@cnkk unclear how to test it, halp :)

Make BC notifications more compact and meaningful?

---

config/runtime.exs
extra/lib/plausible/auth/sso.ex
extra/lib/plausible/auth/sso/integration.ex
extra/lib/plausible/auth/sso/saml_config.ex
extra/lib/plausible_web/controllers/sso_controller.ex
extra/lib/plausible_web/live/sso_management.ex
extra/lib/plausible_web/sso/fake_saml_adapter.ex
extra/lib/plausible_web/templates/sso/sso_settings.html.heex
lib/plausible/teams/policy.ex
lib/plausible_web/components/generic.ex
lib/plausible_web/controllers/settings_controller.ex
lib/plausible_web/live/components/form.ex
lib/plausible_web/router.ex
lib/plausible_web/views/layout_view.ex
test/plausible/auth/sso_test.exs
test/plausible_web/controllers/sso_controller_sync_test.exs
test/plausible_web/controllers/sso_controller_test.exs
test/plausible_web/live/sso_management_test.exs

This PR implements fundamentals of SSO setup UI.

Implement SSO setup UI

---

lib/plausible/billing/plan_benefits.ex
lib/plausible/billing/plans.ex
lib/plausible/billing/qouta/quota.ex
lib/plausible/teams/billing.ex
lib/plausible_web/components/billing/legacy_plan_box.ex
lib/plausible_web/components/billing/notice.ex
lib/plausible_web/components/billing/plan_benefits.ex
lib/plausible_web/components/billing/plan_box.ex
lib/plausible_web/controllers/billing_controller.ex
lib/plausible_web/live/choose_plan.ex
test/plausible/billing/billing_test.exs
test/plausible/billing/plan_benefits_test.exs
test/plausible/billing/quota_test.exs
test/plausible_web/live/choose_plan_test.exs
test/plausible_web/live/legacy_choose_plan_test.exs

This PR should leave the Starter Tier project ready for release (which will be flipping the feature flag).
Highly recommended to review this PR commit by commit as there are quite a few independent changes described by the commit message. More info and screenshots in https://3.basecamp.com/5308029/buckets/41857003/card_tables/cards/8710825189

Starter Tier: Getting ready for release

---

test/e2e/main.tf

Increase check frequency for /api/event and /api/health

---

priv/repo/migrations/20250616121812_sso_domains_validation_to_verification_rename.exs

~~Not sure how to get this merged though, since obviously tests will fail...~~

Migration: SSO domains: s/validated/verified

---

extra/lib/plausible_web/live/customer_support/live/team.ex
lib/plausible/users.ex
lib/plausible_web/components/generic.ex
test/plausible_web/live/customer_support/teams_test.exs

CRM: add ability to deprovision individual users

---

lib/plausible_web/live/installation.ex

Ref: https://3.basecamp.com/5308029/buckets/42034199/card_tables/cards/8830625067

Fix installationv2 redirect url encoding

---

.github/workflows/elixir.yml

See https://hexdocs.pm/mix/1.12/Mix.Tasks.Test.html#module-operating-system-process-partitioning

Add configuration for partitioned testing

---

priv/repo/migrations/20250708102205_audit_entries.exs

Migration: audit entries

---

extra/lib/plausible_web/controllers/sso_controller.ex
extra/lib/plausible_web/templates/sso/cta.html.heex
lib/plausible_web/components/layout.ex
lib/plausible_web/router.ex
lib/plausible_web/views/layout_view.ex
test/plausible_web/controllers/sso_controller_test.exs

Exposes SSO availability in team settings.

Implement CTA for SSO

---

extra/lib/plausible_web/templates/sso/cta.html.heex

Adjustment of the copy in SSO CTA.

Adjust copy in SSO CTA

---

lib/plausible/billing/plan_benefits.ex
lib/plausible_web/components/billing/legacy_plan_benefits.ex
test/plausible/billing/plan_benefits_test.exs
test/plausible_web/live/choose_plan_test.exs
test/plausible_web/live/legacy_choose_plan_test.exs

Updates plan features list, adding "SSO" for custom/enterpriese tier

Put SSO among enterprise plan features

---

lib/plausible_web/components/generic.ex

Fixes https://github.com/plausible/analytics/issues/5518 - @apata @zoldar @RobertJoonas do you know if there's a better way to do it?

Fix shifting focus to filter bar when typing / in a legit input

---

extra/lib/plausible_web/dogfood.ex
lib/plausible/installation_support/checks/installation.ex
lib/plausible/installation_support/detection.ex
tracker/installation_support/detector.js
tracker/installation_support/plausible-function-check.js
tracker/test/installation_support/detector.spec.js

This PR introduces `detector.js` as well as its Elixir wrapper - `Plausible.InstallationSupport.Detection`.
This is meant to be integrated into the `InstallationV2` LiveView module (cc @ukutaht)

Detector.js - detect v1 and technologies used on the website

---

lib/plausible_web/templates/email/dashboard_locked.html.heex
lib/plausible_web/templates/email/over_limit.html.heex
lib/plausible_web/templates/email/trial_upgrade_email.html.heex
test/plausible_web/email_test.exs
test/workers/check_usage_test.exs
test/workers/send_trial_notifications_test.exs

we've had a couple of people think that when we say 10k/mo plan we mean $10k/mo while it is 10k pageviews/mo so I've now updated the email copy to clarify that 
cc @RobertJoonas

clarifying the suggested plan

---

tracker/npm_package/CHANGELOG.md
tracker/package.json
tracker/src/config.js
tracker/src/plausible.js
tracker/test/plausible-web-init.spec.ts

Script v2: Fix unexpected config switch from calling init twice with plausible web

---

lib/plausible/installation_support/checks/detection.ex

Heads up @apata @RobertJoonas - hope I'm not missing anything, but looks like this work is already done?

Remove redundant options merge

---

lib/plausible_web/live/installationv2.ex

To better align with https://github.com/plausible/docs/pull/614

ScriptV2: Update links in instructions

---

extra/lib/plausible_web/live/funnel_settings/form.ex
lib/plausible/stats/goal_suggestions.ex
lib/plausible/stats/query.ex
lib/plausible_web/live/goal_settings/form.ex
lib/plausible_web/live/shields/hostname_rules.ex
lib/plausible_web/live/shields/page_rules.ex
lib/workers/send_email_report.ex
lib/workers/traffic_change_notifier.ex
test/plausible/stats/comparisons_test.exs
test/plausible/stats/query_result_test.exs

Minor query interface UX extension

---

rel/vm.args.eex

Add kernel settings for non-selfhosted envs

---

lib/plausible/data_migration/backfill_tracker_script_configuration.ex
lib/plausible/site.ex

Also fixes the data migration referencing the Site.Schema, which it shouldn't do.

Change Site schema: Add consolidated (boolean) field
