assets/js/plausible.js
lib/plausible/event/schema.ex
lib/plausible/stats/stats.ex
lib/plausible_web/controllers/api/external_controller.ex
priv/repo/migrations/20200211133829_add_initial_source_and_referrer_to_events.exs
test/plausible_web/controllers/api/external_controller_test.exs
test/plausible_web/controllers/api/stats_controller/referrers_test.exs

Separates referrer data from 'initial referrer'. The former represents the referrer for the pageview/event in question, the latter represents the first-touch referrer for the lifecycle of the visitor.
This removes a bug in production to do with referrer handling. It also prepares the ground for making cookies optional. The `initial_referrer` data point requires a cookie whereas `referrer` doesn't.

Introduce initial referrer and initial referrer source

---

assets/js/p.js
assets/js/plausible.js

I happened to notice that Plausible was still sending analytics events while I was running my website locally. While `localhost` is already excluded, other loopback addresses like `127.0.0.1` (which is the address I was using, in this case) are not.
This PR prevents analytics from being collected for loopback addresses in addition to localhost.
The regex used to match loopback addresses was taken from [this Stack Overflow](https://stackoverflow.com/a/8426365) post.
<details>
This RegEx matches
The string "localhost"
localhost
LOCALHOST
These permutations of the IPv4 loopback address
127.0.0.1
127.0.0.001
127.0.00.1
127.00.0.1
127.000.000.001
127.0000.0000.1
127.0.01
127.1
127.001
127.0.0.254
127.63.31.15
127.255.255.254
These permutations of the IPv6 loopback address
0:0:0:0:0:0:0:1 …

Exclude loopback addresses from analytics

---

lib/plausible_web/templates/site/index.html.eex

On mobile, the website list at /sites does not have any X padding. The elements touch the screen left and right. This corrects it by wrapping the list in a div with "px-4" on it.
This could also be achieved by setting "px-4" and "md:px-0" on every element but it is unecessarily complex and if some more elements appeared on this screen, it would be easy to forget this. A container should be in charge of this, which is what is proposed here.
Only two lines are added. Two spaces are added at the beginning of all the other lines changed for better formatting of the code.

Correctly position websites list on mobile

---

assets/js/dashboard/stats/countries.js
assets/js/dashboard/stats/pages.js
assets/js/dashboard/stats/referrers.js

The "more" links are absolutely positioned. It works fine on desktop when there is two columns. On mobile, the absolute sends the "more" links on top of each other. Adding a simple "relative" class on each cards that contains a "more" link ensures that they stay when they belong.

Correctly position more links on mobile

---

HOSTING.md

Not being documented caused some confusion for me. The tracker link had references to http links so events weren't being sent because https sites aren't allowed to use http links.

Added SCHEME to HOSTING.md

---

docker-compose.yml

As stated in #71, the docker-compose example does not work with postgres `9.4` but with `12` this pr updates the default version to `12`.

Use a working postgres version for docker-compose

---

docker-compose.yml

Without the volume, all analytics data is lost on container restart.

Add extra volume for clickhouse server events

---

assets/js/dashboard/datepicker.js
assets/js/dashboard/stats/more-link.js
assets/js/dashboard/stats/visitor-graph.js
lib/plausible/stats/clickhouse.ex
lib/plausible_web/controllers/api/stats_controller.ex
lib/plausible_web/controllers/stats_controller.ex

Remove comparison line

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

When rendered on GitHub, this isn't formatted as `h2` correctly.

Fix issue template formatting

---

HOSTING.md
docker-compose.yml
lib/plausible_release.ex
rel/overlays/init-admin.sh

This means the migrations can always be run on startup, meaning the database won't get out of sync with the running application. It also means users who don't set the credential variables in their compose files don't keep creating admin users every time the application starts.
I'm hoping at some point we can get to a point where the `setup` container isn't necessary, which is how i've setup plausible myself, but that'll come as a later PR.
Looks like the diff is a bit noisy due to trailing space cleanup, sorry!

Create the admin user as a separate command

---

lib/plausible/stats/clickhouse.ex

Sorting by a fixed list does make quick referencing slightly easier, but having them ordered looks much nicer, as the other tabs are also ordered.
This may also come with a performance boost, as the ordering is being handed by Clickhouse.

Sort screen sizes by count

---

assets/js/dashboard/filters.js
assets/js/dashboard/query.js
assets/js/dashboard/stats/modals/pages.js
assets/js/dashboard/stats/more-link.js
assets/js/dashboard/stats/pages.js
lib/plausible/google/api.ex
lib/plausible/stats/clickhouse.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
test/plausible_web/controllers/api/stats_controller/referrers_test.exs

Page drilldown

---

assets/css/loader.css
assets/js/dashboard/historical.js
assets/js/dashboard/index.js
assets/js/dashboard/mount.js
assets/js/dashboard/realtime.js
assets/js/dashboard/router.js
assets/js/dashboard/site-switcher.js
assets/js/dashboard/stats/current-visitors.js
assets/js/transition.js
assets/package-lock.json
assets/package.json
assets/tailwind.config.js
lib/plausible_web/controllers/api/internal_controller.ex
lib/plausible_web/router.ex
lib/plausible_web/templates/stats/stats.html.eex
test/plausible_web/controllers/api/internal_controller_test.exs

Adds a way to quickly navigate from one site's dashboard to another. Additionally, you can go to site settings straight from the dashboard, no need to navigate through /sites anymore.
Closes #103 
Closes #195 
Closes #155

Add site switcher

---

lib/plausible_web/controllers/billing_controller.ex
lib/plausible_web/router.ex
lib/plausible_web/templates/billing/upgrade.html.eex
lib/plausible_web/templates/billing/upgrade_success.html.eex
test/plausible_web/controllers/billing_controller_test.exs

When users upgrade, our database isn't synced up to Paddle immediately. This makes it look like subscribing was unsuccessful because the settings page shows they still have an expired free trial.
I've added an intermediate page to thank the user for upgrading and to allow 3-4 seconds for the Paddle webhook to come through.

Add page after upgrading to paid plan

---

lib/plausible_web/controllers/api/external_controller.ex
test/plausible_web/controllers/api/external_controller_test.exs

This change will decode URL pathnames and sources going forward
Closes #229 
NB: We don't have automated migrations for Clickhouse in place yet. If you're self-hosting and want to change your historical data, run the following commands:
```
ALTER TABLE events UPDATE pathname=decodeURLComponent(pathname), referrer_source=decodeURLComponent(referrer_source) WHERE 1;
```
```
ALTER TABLE sessions UPDATE entry_page=decodeURLComponent(entry_page), exit_page=decodeURLComponent(exit_page), referrer_source=decodeURLComponent(referrer_source) WHERE 1;
```

URL Decode pathnames and sources

---

config/config.exs
config/releases.exs
config/test.exs
lib/plausible_web/captcha.ex
lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/templates/auth/password_reset_request_form.html.eex
lib/plausible_web/templates/auth/register_form.html.eex

Adds optional captcha support on:
* Register page
* Forgot password page
Both of these forms send an email to the specified address so we want to exclude bots from spamming people and lowering our email reputation.

Add HCaptcha support

---

docker-compose-geoip.yml

I was facing an issue with the GeoIP container not starting when deploying Plausible and so countries would not show up on the map. I have updated the **docker-compose-geoip.yml** file accordingly and have also added the default port number 1080(documented on maxmind/geoupdate's Docker Hub). Henceforth, it got fixed. Hope this helps. Thank you for Plausible!

Fix for GeoIP container not starting when deploying Plausible

---

lib/plausible_web/templates/site/settings.html.eex

Self-hosted instances don't serve the docs site anymore, correctly.

Link to docs site rather than current instance

---

HOSTING.md

Remove a word that should not be there

Fix a typo in the Hosting documentation

---

lib/plausible_web/controllers/stats_controller.ex
lib/plausible_web/plugs/upgrade_billing_plug.ex
test/plausible_web/controllers/stats_controller_test.exs

Addresses the code refactoring opportunities addressed in #332. 
NOTE: I had to change my original idea a bit, since, of course Elixir does not support early returns. The preferred way here is to introduce multiple overloading functions and choose the right one with pattern matching.
@ukutaht at the end, It's a matter of taste and code style. I leave the final decision to you. Please, keep in mind that while I added one test to guarantee that the conditions are satisfied, I would still love to see being tested in some sort of integration environment.
Cheers!

#332: Refactor stats controller

---

CHANGELOG.md
lib/plausible_release.ex

Starts all apps including `:ssl` when creating DB. This fixes Postgres connection when `?ssl=true`
Fixes #347

Start all apps when creating DB

---

.gitlab/build-scripts/docker-entrypoint.sh
Dockerfile

This PR removes extra dependencies in the container image to run as a non-root user, instead defaulting all processes to run as root from the entrypoint.
This is important, as an _exec_'s into the container image will not run as root, unlike currently.

Update container image to run as non root

---

.gitlab/build-scripts/docker-entrypoint.sh
Dockerfile

This PR removes extra dependencies in the container image to run as a non-root user, instead defaulting all processes to run as root from the entrypoint.
This is important, as an exec's into the container image will not run as root, unlike currently.
---
The changes of the [previous PR](https://github.com/plausible/analytics/pull/352) were regressed due to https://github.com/plausible/analytics/issues/360.
Initialising succeeds from the following commands:
```
command:
- /bin/sh
- -c
- /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin
```
and shows the logs
```bash
Loading plausible..
Starting …
```

Run container as non root (2)

---

README.md
tracker/LICENSE.md

Changes Javascript Tracker License to MIT

Change Javascript license to MIT

---

CHANGELOG.md
lib/plausible_web/controllers/auth_controller.ex
test/plausible_web/controllers/auth_controller_test.exs

When clicking on an activation link that is still valid but the user has already been created should not show an error. Instead, take the user to set password page instead.

Do not error when activating an account that already exists

---

.gitlab/build-scripts/docker-entrypoint.sh
Dockerfile

**_Currently work-in-progress._**
The final container image can be reduced by ~75% by replacing the base with alpine.
```
plausible/analytics                       bobymcbobs          4fb17172ceb0        10 minutes ago      57.5MB
plausible/analytics                       dev                 a7d58b5d74da        16 hours ago        242MB
```
The size of the container image is important as:
- in some environment there may not be a lot of storage
- nodes can run out of storage and cause problems
- if it can be reduced, it should be

Replace final image base to be alpine

---

assets/js/dashboard/filters.js
assets/js/dashboard/stats/conversions/index.js
assets/js/dashboard/stats/conversions/meta-breakdown.js
assets/js/dashboard/stats/devices.js
lib/plausible/stats/clickhouse.ex

Responding to some early feedback.

Improve event metadata

---

CHANGELOG.md
assets/js/dashboard/stats/visitor-graph.js

Closes #175.
Abbreviate both weekday and month in order to keep horizontal spacing roughly the same as it's been.

Add weekday to the visitor graph

---

tracker/compile.js

Fixes a typo on the tracker script compiler.
Resolves #401

Fix hashmode when using plausible's script with hash and outbound-links at the same time

---

.gitignore
Makefile

Just a quick update for an issue that I noticed after submitting #403 (darn you and your quick merging ;) ). Previously the Clickhouse container would use a volume mounted in the users home directory, if created using the Makefile. Polluting the home directory is no bueno, so this moves the directory into the current directory, and makes it hidden by default. It also adds said directory to `.gitignore`.

Change Docker volume used by Clickhouse to a local directory

---

CHANGELOG.md
lib/plausible_web/templates/site/index.html.eex

Everywhere that the user's site list is displayed, the site domains are accompanied by their respective favicons:
That is, however, not true for the home page, which only displays the domain names:
This PR attempts to make the design more consistent by adding the favicons to the home page:

Display domain's favicon on the home page

---

CHANGELOG.md
lib/plausible/site/schema.ex
test/plausible_web/controllers/site_controller_test.exs

Validates domain format before submitting to the database.

Validate domain format on site creation

---

lib/plausible_web/plugs/tracker.ex

Hey Plausible devs,
I am trying to embed the `plausible.js` onto a page that has the [`require-corp`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy) header set, which means that for every resource that is loaded they must be clearly marked as cross-origin OK.
The tracker script response currently doesn't have that header set, so I can't load it right now. This would solve that.
Note: if anything, it's more permissive.

Add Cross-Origin-Resource-Policy header to script

---

CHANGELOG.md
config/config.exs
config/releases.exs
lib/plausible/site/schema.ex
lib/plausible/site/spike_notification.ex
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/email.ex
lib/plausible_web/router.ex
lib/plausible_web/templates/email/spike_notification.html.eex
lib/plausible_web/templates/site/settings_email_reports.html.eex
lib/workers/spike_notifier.ex
mix.exs
mix.lock
priv/repo/migrations/20201208173543_add_spike_notifications.exs
test/plausible_web/controllers/site_controller_test.exs
test/support/factory.ex
test/workers/spike_notifier_test.exs

Co-authored-by: Jerod Santo <jerod@changelog.com>
Streamed live at https://www.youtube.com/watch?v=dPMn2xQ7DDk
Simple notifications around traffic spikes #172 
Adds a background worker to send notifications for traffic spikes. The behaviour is pretty simple:
* Background worker runs every 15 minutes
* If the current visitors number on the site is higher than configured threshold, sends an email to all recipients
* Any further notifications are suppressed for 12 hours. 
TODO:

Simple notifications around traffic spikes

---

CHANGELOG.md
assets/js/dashboard/query.js

The date param was sticking around even when not specified
resulting in Last Month -> This Month still having last month's
date.
Fixes #439
Frontend doesn't have a test framework

Fix overly-sticky date in query parameters

---

CHANGELOG.md
assets/js/dashboard/datepicker.js
assets/js/dashboard/mount.js
lib/plausible_web/templates/stats/stats.html.eex

Sets minDate on the datepicker to be one day before the site's date of insertion into the database
No test framework on JS
Fixes #446

Prevent choosing a date before site was added in datepicker

---

CHANGELOG.md
assets/js/dashboard/stats/modals/pages.js
lib/plausible/stats/clickhouse.ex
lib/plausible_web/controllers/api/stats_controller.ex
lib/workers/send_email_report.ex

Adds "Load More" capability to pages modal - both top-pages and entry-pages. Allows for a user to get all the way to all pages, not just the top 100. 
Fixed #429 
For clarity: I was running into an issue with this setup where I would receive all `n` pages as expected, but I'd also consistently get a seemingly random `n+1` page sent, which was a complete duplicate of a previously sent entry. I suspect it was just an issue with how I was generating data, as even without my changes it was appearing in my local if I bumped the limit on the pages API call (and not the live demo or my self-hosted instance). But I figured I'd mention it in case you could see any code reason for that happening.

Adds "Load More" functionality to pages modal

---

assets/js/dashboard/stats/sources/search-terms.js

Change color of link in dark mode because of low contrast.
before:
after:

fix: low contrast text in dark mode

---

CHANGELOG.md
assets/js/dashboard/datepicker.js
assets/js/dashboard/query.js

- Ensures that selecting the same day for both entries in Flatpickr doesn't result in an empty graph, and instead changes to "day" view for the single day selected. 
- Does the same as #470 but for `from` and `to` params, which persist when moving from a custom date range to any other period
Fixes #466

Fixes couple of Flatpickr related issues

---

CHANGELOG.md
tracker/src/plausible.js

Allows middle clicks or ctrl+click, cmd+click, shift+click to track to plausible, and open in a new tab if requested, instead of always redirecting the current tab. 
Fixes #451 
This will almost certainly cause conflicts with #489 in the compiled script, so I didn't push them in this PR at all. Once both are merged we can re-compile the merged version.

Allows middle-click and ctrl+click outbound clicks to properly open as user intended

---

.pre-commit-config.yaml
assets/.eslintrc.json
assets/.prettierrc.json
assets/.stylelintrc.json
assets/package-lock.json
assets/package.json

- When you try to commit, Pre-commit will run checks for all three, if
installed, _only_ on staged files, and prevent committing if the linters are
unhappy.
- Several eslint rules that generate a lot of errors are disabled for now.
That's to allow a more gradual transition, so you won't change 1 line and be
told to fix 100 other lines (but maybe like 20 because there are still a lot
of rules enabled).
- Prettier is set to require pragma. That's also to allow a more gradual
transition. As each file is tidied up, run Prettier on it, and it'll add a
special comment that tells it that it's now responsible for keeping that one
tidy.
Oh, and Pre-commit supports custom hooks, too, though there is already one for `mix format` and `mix test`. It's the language-agnostic choice for git pre-commit …

Add eslint, stylelint, prettier, and pre-commit

---

lib/plausible/session/store.ex
test/plausible/session/store_test.exs

Fixes bug with extreme session lengths when events arrive our of order

Fix session duration for out-of-order events

---

lib/plausible/billing/billing.ex
lib/plausible/stats/clickhouse.ex
lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/email.ex
lib/plausible_web/templates/auth/user_settings.html.eex
lib/plausible_web/templates/billing/upgrade.html.eex
lib/plausible_web/templates/email/trial_upgrade_email.html.eex
lib/workers/send_trial_notifications.ex
test/workers/send_trial_notifications_test.exs

Let's be more explicit about the fact that custom events count towards your monthly billable pageviews.

Clarify that custom events are billed separately from events

---

assets/js/dashboard/stats/modals/google-keywords.js
assets/js/dashboard/stats/sources/search-terms.js
lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/templates/stats/stats.html.eex

Fixes #614 
(I'm unsure if you want changelog entries still under 1.1.2, so lmk)

Update References for Settings Redirection

---

CHANGELOG.md
assets/js/dashboard/datepicker.js
assets/js/dashboard/filters.js

I couldn't understand why the dropdown caret/chevron was pink. It actually looks more red on my screen and I thought I had an error on the datepicker. Changed to indigo to match the rest of the theme. Appreciate this might be a preference thing, so feel free to ignore.

Change datepicker caret from pink to indigo

---

CHANGELOG.md
assets/js/dashboard/datepicker.js

- Adds Keybindings for date selection, as per discussion in #625 
I will say, this probably needs some solid stress testing on staging or similar, since I've encountered quite a few edge cases where the menu has remained open, or Flatpickr hasn't opened, stuff like that. I think I've got most of them resolved, but there could be some remaining I suppose. 
- Marko said he might add a `Keyboard Shortcuts` docs page

Adds date selection keybindings

---

Dockerfile

Fixes #666
Re-implements #237 
This doesn't bind it to the host port by default, it's more a hint to tools which integrate with Docker directly.

Expose port 8000 by default

---

lib/plausible_web/controllers/api/external_stats_controller.ex
test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs

Add validations for `date`, `period` and `metrics` variables

Validate API query params

---

CHANGELOG.md
assets/js/dashboard/datepicker.js

- Fixes #707 
- Ensures that keys pressed with a capitalization modifier are properly handled
With 1.2 now released, I'm unsure where you want changelog updates/the new version you're targeting

Fixes case-sensitivity and residual keys in date-keybinds

---

CHANGELOG.md
assets/js/dashboard/datepicker.js
assets/js/dashboard/site-switcher.js

- Changes 30d keybind to `t` from `3`
- Changes 6mo keybind to `s` from `6`
- Adds dynamic keybinds 1-9 for sites 1-9
For now sites >9 don't have any keybindings, maybe in the future there can be a way to favorite/re-order the sites; but I figure most users won't need more than 9 for now, at least.

Adds site switching keybindings

---

assets/js/dashboard/site-switcher.js
assets/tailwind.config.js

Pretty straightforward. 
Before:
After:
- Minor

Fixes text overflow on long site urls in site switcher

---

lib/plausible/session/store.ex
test/support/test_utils.ex

We keep all active sessions in memory. Currently they are keyed with just `user_id` which has caused some collisions to happen. Basically, two different users on two different sites can end up affecting a single session in the database. This PR completely splits them so even if two users on different sites happen to get the same `user_id`, their session stats won't be mixed up.
There is still historical data that is wrong. I will probably rebuild the sessions table on the production server.

Prevent user id collisions in session tracking

---

CHANGELOG.md
lib/plausible_web/templates/site/settings_search_console.html.eex

At the Site settings > Search Console, the notification text was invisible in dark mode.

Fix invisible text in dark mode

---

lib/plausible_web/templates/layout/focus.html.eex

Uses DateTime to find out current year and use for copyright notice in the footer.
While going through the templates I tried to fix https://github.com/plausible/analytics/issues/584, I'm not sure if it is an efficient solution.

Use auto generated copyright year

---

lib/plausible_web/templates/auth/new_api_key.html.eex

Before: 
After: 
(I did add the placeholder there because it was missing, do let me know if you don't want it/want it to be different)

Adds proper dark styles for API key issuance page

---

lib/plausible/stats/clickhouse.ex

Fixes as per the issue introduced with #750

Fixes goal filters for glob goals

---

assets/js/dashboard/site-switcher.js

Fixes #787
I could've sworn the format I had used worked in JS - but seemingly not? I don't know how I didn't notice it the first time around.

Fixes zero-keybind leading to undefined page

---

.github/workflows/elixir.yml
CHANGELOG.md
assets/css/app.css
assets/js/app.js
assets/js/dashboard/historical.js
assets/js/dashboard/mount.js
lib/plausible_web/controllers/stats_controller.ex
lib/plausible_web/templates/layout/_embedded_footer.html.eex
lib/plausible_web/templates/layout/_footer.html.eex
lib/plausible_web/templates/layout/_header.html.eex
lib/plausible_web/templates/layout/_notice.html.eex
lib/plausible_web/templates/layout/app.html.eex
lib/plausible_web/templates/site/settings_visibility.html.eex
lib/plausible_web/templates/stats/stats.html.eex
test/plausible_web/controllers/stats_controller_test.exs

New branch for embed mode based on #772. Mostly the same feature, thanks a lot @aymanterra @bradkane for your research and contributions on this. I'll see if I can add you as addition authors for the commit when I merge it.
The main change from the original PR is that the embed mode is done with no configuration or persistence on the server side. Shared links will always remove `X-Frame-Options` header and set `SameSite: None; secure` for cookies. This relaxed security is only applied to shared links, the rest of the application still uses secure browser headers and restricts cookie domain.
Since shared links are read-only, and specifically meant for sharing stats outside of Plausible, I don't think it introduces any security issues. Happy to be convinced otherwise.
TODO:
EDIT: …

Embeddable dashboard

---

lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/templates/billing/upgrade_success.html.eex
test/plausible_web/controllers/billing_controller_test.exs

Changed instances of "succesfully" to "successfully". This was bugging me 😅 

Fix typo with "succesfully"

---

lib/plausible/stats/aggregate.ex
lib/plausible/stats/base.ex
lib/plausible/stats/breakdown.ex
lib/plausible/stats/query.ex
lib/plausible/stats/timeseries.ex
lib/plausible_web/controllers/api/external_stats_controller.ex
test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
test/plausible_web/controllers/api/stats_controller/main_graph_test.exs

Hopefully the last round of improvements to the stats API before calling it stable.

Stats API improvements

---

CHANGELOG.md
tracker/src/plausible.js

I'm using [Cypress](https://www.cypress.io/) to run end-to-end tests on my website locally, and I'm using Plausible Analytics on that website.
At the time, the website in question wasn't advertised anywhere, it was not indexed by Google, and it didn't have any visitors.
After introducing some Cypress tests, my visitor numbers spiked in a way that I just don't see realistically happening.
Putting one and one together, I think the cause was because Plausible tracked events when being run by Cypress. The existing methods of checking if we're running inside an end-to-end test didn't work because Cypress takes a different approach to running end-to-end tests and doesn't use webdrivers.
- Detect if we're running under Cypress. If we are, stop tracking. [See here for the official Cypress …

Stop analytics tracking if running under Cypress tests

---

assets/js/dashboard/api.js
assets/js/dashboard/historical.js
assets/js/dashboard/lazy-loader.js
assets/js/dashboard/realtime.js
assets/js/dashboard/stats/conversions/index.js
assets/js/dashboard/stats/countries.js
assets/js/dashboard/stats/devices/browsers.js
assets/js/dashboard/stats/devices/index.js
assets/js/dashboard/stats/devices/operating-systems.js
assets/js/dashboard/stats/pages/entry-pages.js
assets/js/dashboard/stats/pages/exit-pages.js
assets/js/dashboard/stats/pages/pages.js
assets/js/dashboard/stats/sources/referrer-list.js
assets/js/dashboard/stats/sources/source-list.js
assets/js/dashboard/stats/visitor-graph.js
lib/plausible_web/controllers/api/stats_controller.ex

I noticed that a lot of queries to CH run considerably faster when run in isolation vs when loading the whole dashboard. When loading the dashboard, we fire about 10 separate queries to Clickhouse. I believe all these concurrent queries are competing for CPU and RAM resources.
By loading only the data that is visible in the user's viewport, we can reduce the number of concurrent queries which should free up resources for the queries that are most important (i.e. visible part of the dashboard)
Thanks @Vigasaurus for the work on sticky header. I'm taking the InteractionObserver code as base for the LazyLoader.

WIP: add lazy loading for dashboard

---

CHANGELOG.md
lib/plausible_web/templates/layout/_tracking.html.eex

Disables self-tracking when self hosted.
In my case, I was staring at mysterious entries for my website. It showed up because I hosted Plausible on a subdomain of my primary site (plausible.example.com) and it accidentally matched my site. This PR disables this, as probably no one self-hosting would want it.

Disable self-tracking with self hosting

---

CHANGELOG.md
lib/plausible/site/shared_link.ex
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/router.ex
lib/plausible_web/templates/site/edit_shared_link.html.eex
lib/plausible_web/templates/site/new_shared_link.html.eex
lib/plausible_web/templates/site/settings_visibility.html.eex
priv/repo/migrations/20210406073254_add_name_to_shared_links.exs
test/plausible_web/controllers/site_controller_test.exs
test/support/factory.ex

See discussion https://github.com/plausible/analytics/discussions/795

Add name to shared links

---

.env.dev

DISABLE_SUBSCRIPTION was removed in commit e873d790e5117f08102e28be1f7f1926ec35d877.

Clean up deprecated option DISABLE_SUBSCRIPTION

---

CHANGELOG.md
lib/plausible_web/templates/email/weekly_report.html.eex
lib/workers/send_email_report.ex
test/workers/send_email_report_test.exs

Bug: weekly reports are sent out on Monday. The time range that stats are calculated for are using the `Query.from(%{"period" => "7d"})` which is problematic because:
* The resulting date range is last Tuesday -> this Monday
* Stats for 'this Monday' are incomplete, so sending a report is for that is wrong
The correct date range is 'last monday' -> 'last sunday'. The stats for that range are complete and that's what most people consider a 'week'.

Fix weekly report time range

---

CHANGELOG.md
lib/plausible_web/controllers/api/external_controller.ex
test/plausible_web/controllers/api/external_controller_test.exs

Send stats to multiple dashboards by configuring the `data-domain` as a comma-separated list:
```html
<script async defer data-domain="test1.plausible.io,test2.plausible.io" src="https://plausible.io/js/plausible.js"></script>
```

Support multiple `data-domain` values

---

CHANGELOG.md
assets/js/dashboard/query.js
assets/js/dashboard/stats/conversions/prop-breakdown.js
assets/js/dashboard/stats/devices/index.js
assets/js/dashboard/stats/pages/index.js
assets/js/dashboard/stats/sources/source-list.js
assets/js/dashboard/storage.js

UI preferences are currently stored in `localStorage`. This breaks the UI when the dashboard is running in embedded mode on a another domain and the browser blocks third-party cookies (and storage).
With this PR the dashboard will just fall back to storing UI preferences in memory instead of localStorage. The preferences will not be remembered for the next time but at least the dashboard will work.
Helps but does not fully address #919

Don't use localStorage when the browser doesn't support it

---

lib/workers/clean_email_verification_codes.ex

Same issue with 64a5b22e8c6ca7e6d1926bd283ffc7b567ff772e.

Add :ok return to CleanEmailVerificationCodes

---

Makefile

This PR solves #1017. The only change is to specify clickhouse and postgres versions for local development in the `Makefile`, bringing it in line with the hosting repo.

Specify clickhouse and postgres versions for local development.

---

CHANGELOG.md
assets/js/dashboard/stats/modals/pages.js
assets/js/dashboard/stats/modals/referrer-drilldown.js
assets/js/dashboard/stats/modals/sources.js
lib/plausible/stats/clickhouse.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/stats_controller/pages_test.exs
test/plausible_web/controllers/api/stats_controller/sources_test.exs
test/support/clickhouse_setup.ex

Title. 
Couple of things here to discuss though - 
1. Yes, adding this 4th column of data to the Top Pages report isn't great for the already rough mobile UI - but I figured I'd leave that to #972 to resolve instead of me causing unnecessary conflicts
2. Currently I've just set up the naive approach to time on page (where we can't compute the time for the exit page of a session) - but if you want, I could add the better method in the form of a beacon and creating a new type of event, `exit`, such that it won't count as a pageview, and will always end a session. (There is another thing to discuss here on if you think using the visibility change method for ending sessions is appropriate - as this can have false positives with users swapping tabs) lmk what you think. 
3. This query isn't …

Adds Time on Page metric to Top Pages report

---

lib/plausible/stats/clickhouse.ex
lib/plausible_web/controllers/api/stats_controller.ex

As per https://github.com/plausible/analytics/pull/1007#issuecomment-843234020
*Notes*:
- I used the same setup as the bounce+time on page async, but with the current and previous query for the rate of change calculation. 
- In the above setup, I reduced the timeout to 5 seconds in this version, since I figure waiting longer for the top graph just for the one stat is probably not the best UX, so if it takes more than 5 seconds, it'll return the entire graph and all top stats except the time on page (it's just not present). 
It's bundled with regular time on page, nbd

Adds time on page as a top stat when a page filter is active

---

CHANGELOG.md
config/runtime.exs
lib/plausible/event/write_buffer.ex
lib/plausible/session/write_buffer.ex

Currently, both "flush interval" and "max buffer size" are hard-coded to relatively small values.
This may cause an unnecessarily high load on the Clickhouse instance.
It makes sense to make those configurable.
Docs haven't been updated, but if you're okay with this PR, I'll open a PR there.

Added parameters for Clickhouse flush interval and max buffer size

---

lib/plausible/stats/base.ex
lib/plausible/stats/breakdown.ex
lib/plausible/stats/query.ex
mix.exs
mix.lock
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs

Adds a new `|` syntax to specify an `IN` or `MEMBER` operator in the API filter expressions. Here's how it looks like:
```
event:page == /plausible.io|/register
```

Stats API: Support IN filter expression

---

lib/plausible_web/views/site_view.ex

Replace `async defer` by `defer` in sniplet from dashboard.
There is

Replace "async defer" by "defer" in sniplet for dashboard

---

CHANGELOG.md
assets/js/dashboard/stats/countries.js
assets/js/dashboard/stats/visitor-graph.js

Fixes React errors+crash when system theme changes on loaded dashboard

---

.tool-versions
CONTRIBUTING.md
Makefile
assets/css/app.css
assets/js/dashboard/fade-in.js
assets/js/dashboard/lazy-loader.js
assets/js/dashboard/stats/countries.js
assets/js/dashboard/stats/devices/browsers.js
assets/js/dashboard/stats/devices/index.js
assets/js/dashboard/stats/devices/operating-systems.js
assets/js/dashboard/stats/more-link.js
assets/js/dashboard/stats/pages/entry-pages.js
assets/js/dashboard/stats/pages/exit-pages.js
assets/js/dashboard/stats/pages/index.js
assets/js/dashboard/stats/pages/pages.js
assets/js/dashboard/stats/sources/referrer-list.js
assets/js/dashboard/stats/sources/search-terms.js
assets/js/dashboard/stats/sources/source-list.js

This is a "first pass" for the details button issue being tracked in #972 titled "Details button issue on Firefox specifically". I'd love some testing and feedback on this. I'm certain I may have missed something! 😅 
While it includes a bunch of changes related to development documentation and (optionally) usage (detailed below), I'd love feedback on https://github.com/hirusi/analytics/commit/4cec202a1b3e6445b4aa66814ed0eff96d47f2fb, which is the one and only commit to ultimately build on and tackle the mobile responsiveness issue.
While I have tried to add some comments at some places, they were not a focus so far. If something is unclear, please let me know, and I'll work on adding some. Context is easy to lose. :)
For development related changes...
- It introduces two more convenience …

Fix for details button misbehaving on mobile

---

CHANGELOG.md
lib/plausible_web/templates/site/new_shared_link.html.eex

Many browsers autofill input fields based on their name, but here it makes no sense to use the user's `name` (email) or even `password` for the shared link.
Turns off form autocompletion for `name` and `password` in the _New shared link_ form.

Turn off form autocompletion for new shared links

---

.gitlab/build-scripts/docker-entrypoint.sh
.gitlab/build-scripts/docker.gitlab.sh
rel/overlays/createdb.sh
rel/overlays/init-admin.sh
rel/overlays/migrate.sh
rel/overlays/rollback.sh
rel/overlays/seed.sh

There were various mistakes in the shell scripts, such as lack of quoting; they would break them immediately e.g. if `BIN_DIR` contained a space.
Pointed out by [`shellcheck`](https://www.shellcheck.net/).

Fix shell scripts

---

tracker/src/plausible.js

The tracker script has logic that disables itself for localhost addresses, and seems to want to handle literal IPv6 addresses but does not do so correctly.
This the default for a few development setups, see for instance: https://github.com/shellscape/webpack-plugin-serve#usage
Spec of literals in urls: https://datatracker.ietf.org/doc/html/rfc2732
Behaviour of literals in practice in javascript:
```js
> new URL('http://[::]:55555').hostname
'[::]'
> new URL('http://[0:0:0:0:0:0:0:1]').hostname
'[::1]'
> new URL('http://[::0000:0000]').hostname
'[::]'
```
Tested with current LTS node and in Firefox and Chromium. The browsers also redirect when a url in typed in the location bar.
IPv6 literals in url hostnames follow RFC 2732 so are enclosed in brackets.
Browsers normalise so matching zeros …

Fix IPv6 localhost detection in tracker script

---

lib/plausible_web/templates/site/settings_general.html.eex

Earlier the plausible CDN snippet was not looking that good as it was showing as plain text. By simply adding a `code` tag around the text, it looks nice as it is shown in a `monospace` font.

Added code tag to the plausible script snippet

---

lib/plausible_web/plugs/tracker.ex
tracker/compile.js
tracker/src/plausible.js

The goal of this PR is to allow users to send analytics from localhost.
In cases like Cordova apps or Capacitor, it's needed.
I added a new variant of plausible.js
I choose to implement it as `allow_local` instead of @metmarkosaric suggestion `debug`, whitch is less opinionated, and define better what it does.
I added handlebar variable `allow_local` to `plausible.js`.
Then I updated builder script as mentioned here : 
https://github.com/plausible/analytics/pull/1125#issuecomment-860290491
Check the doc here: https://github.com/plausible/docs/pull/114
- [X ] Entry has been added to changelog
- [ X] [Docs](https://github.com/plausible/docs) have been updated

feat: add variant local

---

mix.exs

Required by the use of config_env() in config/config.exs

Update minimum elixir version to 1.11

---

CHANGELOG.md
lib/plausible/helpers/config.ex

This change fixes an error I'm experiencing when using secret files (instead of ENV vars) for config. 
- Here's a related discussion: https://github.com/plausible/analytics/discussions/1311
- Here's where I discovered a potential fix: https://github.com/plausible/analytics/issues/1105#issuecomment-915813670

Fix reading config from file

---

config/runtime.exs

Phoenix only requires SECRET_KEY_BASE to be longer than 32 characters. 32 characters even with hex encoding is 128 bits of entropy which is more than enough. Some secret generation tools only generate 32 characters/128 bits by default which makes this relatively arbitrary limit annoying. Let's change it to what Phoenix requires.

Don't enforce longer SECRET_KEY_BASE than Phoenix

---

Dockerfile

Use `--no-cache` with `apk upgrade` instead of additional `apk update`, kind of best practice for the Docker image to be released.

Prevent leaving apk cache in Docker image

---

assets/js/dashboard/stats/conversions/index.js
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/stats_controller/conversions_test.exs

f576fa2 should have updated the conversion metric names so that
`unique_conversions` and `total_conversions` are the two metrics
returned by the conversions API. This updates those so that the CSV
export outputs the correct data.

Fix conversions metrics

---

lib/plausible_web/templates/site/settings_email_reports.html.eex

In "Email Reports" in Site Settings, the little "i" icon for "Traffic spike notifications" leads to https://docs.plausible.io/email-reports/ rather than to https://plausible.io/docs/traffic-spikes. Someone reported on Twitter so I thought I may be able to fix it myself! :)

Traffic spike docs link in Site Settings leads to the wrong docs page

---

CHANGELOG.md
lib/plausible_web/templates/layout/_footer.html.eex

This fixes the issue raised in https://github.com/plausible/analytics/issues/1272, specifically:
> footer menus need to be aligned properly
I have opted for a bit of a hacky approach as far as the alignment for the "Comparisons" column goes (`mt-32`). If that is unwarranted, let me know please.
- Firefox 94
- Edge 96
- Chromium 96

UI fix: footer alignment on mobile

---

.github/workflows/docker.yml
.github/workflows/elixir.yml
.github/workflows/node.yml

Use BuildJet 4vCPU runners instead of the GitHub's built in. Should make all jobs go faster. 
Note: The CI jobs will fail until an admin authorizes BuildJet to be able to “install” the runners to the repo. This can be done in http://app.buildjet.com/onboarding
Thanks!

Upgrade the GitHub Actions runners

---

CHANGELOG.md
lib/plausible_web/controllers/api/external_stats_controller.ex
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs

Add "events" metric to public breakdown endpoint

Add "events" metric to public breakdown endpoint

---

lib/plausible_web/controllers/api/stats_controller.ex
lib/plausible_web/controllers/stats_controller.ex
test/plausible_web/controllers/CSVs/30d-filter-goal/cities.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/regions.csv
test/plausible_web/controllers/CSVs/30d-filter-path/cities.csv
test/plausible_web/controllers/CSVs/30d-filter-path/regions.csv
test/plausible_web/controllers/CSVs/30d/cities.csv
test/plausible_web/controllers/CSVs/30d/regions.csv
test/plausible_web/controllers/CSVs/6m/cities.csv
test/plausible_web/controllers/CSVs/6m/regions.csv
test/plausible_web/controllers/stats_controller_test.exs

This includes the cities and regions data supported by #1449 in the CSV export.

Add cities and regions to exported CSV data

---

README.md

Adds a widget that displays the contributors. 
This is to value all the contributors and make the valued and displayed.

Value and recognise contributors

---

CHANGELOG.md
config/runtime.exs

This enables safer deployments to allow localhost-only or VPN-interface-only listening.

Allow user to specify listen interface via LISTEN_IP

---

CHANGELOG.md
lib/plausible/session/store.ex
test/plausible/session/store_test.exs

If a session is created without a screen size and later requests specify a screen size update the session
fixes #1605

Update session screen_size if unknown

---

lib/plausible_web/templates/email/welcome_email.html.eex

Fixed the link `https://plausible.io/docs/404-error-pages-tracking` -> `https://plausible.io/docs/error-pages-tracking-404` in the "Welcome to Plausible" email

Fix broken docs link in welcome email

---

CHANGELOG.md
lib/plausible_web/controllers/api/external_stats_controller.ex
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs

If the public `breakdown` API is queried with the undocumented `event:goal` property, now custom event properties are returned (within `props`) as the internal `conversions` endpoint does (within `prop_names`).
```
curl -H "Authorization: Bearer ${TOKEN}" "https://plausible.io/api/v1/stats/breakdown?site_id=$SITE_ID&property=event:goal"
```
Response:
```
{
"results": [
{
"goal": "404",
"props": [
"foo",
"method",
"path"
],
"visitors": 2
},
{
"goal": "Visit /test",
"props": [],
"visitors": 1
}
]
}
```
This is useful to find out which custom properties can be queried in general (https://plausible.io/docs/stats-api#custom-props).
Closes #1577

Add custom goal props to breakdown endpoint

---

CHANGELOG.md
config/runtime.exs

I tried to self-host on fly.io, but it uses IPv6 for DB access:
https://hexdocs.pm/phoenix/fly.html#runtime-configuration
This changes follows the current Phoenix generator setup:
https://github.com/phoenixframework/phoenix/blob/master/installer/lib/phx_new/generator.ex#L355
It had been defaulted to inet6:
https://github.com/phoenixframework/phoenix/pull/4289
but that caused an issue:
https://github.com/phoenixframework/phoenix/issues/4389

optional ipv6 for repo

---

lib/plausible_web/templates/billing/change_enterprise_plan.html.eex
lib/plausible_web/templates/billing/change_plan.html.eex
lib/plausible_web/templates/billing/change_plan_preview.html.eex
lib/plausible_web/templates/billing/upgrade.html.eex
lib/plausible_web/templates/billing/upgrade_enterprise_plan.html.eex
lib/plausible_web/templates/billing/upgrade_to_plan.html.eex

The "mailto: support@plausible.io" link has a space in front of the email address which prevents this link from working correctly in some cases. There should be no space in there

removed a space from 6 mailto links

---

assets/js/dashboard/site-switcher.js
config/runtime.exs
lib/plausible/auth/auth.ex
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/controllers/stats_controller.ex
lib/plausible_web/plugs/authorize_site_access.ex
lib/plausible_web/plugs/authorize_stats_api.ex
lib/plausible_web/plugs/crm_auth_plug.ex
lib/plausible_web/templates/stats/stats.html.eex
lib/plausible_web/templates/stats/waiting_first_pageview.html.eex
test/plausible_web/controllers/api/external_stats_controller/auth_test.exs
test/plausible_web/controllers/stats_controller_test.exs

- renamed admin users to `super_admin` (to avoid name overlapping with the site admin role)
- `super_admin` users now have access to public and private locked dashboards 
- removed some code repetition and moved the super_admin user check to `Plausible.Auth` module
- fixed the `stats_controller_test.exs:41` test that did not test the described functionality (site did not exist)

Allow admin access to locked dashboards

---

lib/plausible/auth/user_admin.ex
lib/plausible/site/admin.ex

- Users list now shows a column grace_period
- Clicking on a user, the grace period can be removed from "Actions" on the top right
- CRM now shows a `created at` date for both sites and users

Streamlining support

---

lib/plausible_web/templates/auth/password_reset_request_success.html.eex

A note to use the correct email address for password reset as we regularly get questions on why the password reset email wasn't delivered. In all cases, it's because people try to reset the password of a wrong email address

Use the correct email address for password reset

---

CHANGELOG.md
assets/js/dashboard/stats/visitor-graph.js

Fixes an issue while long pressing on the graph, where the canvas + some other elements on the page get selected. It's pretty common to long press on mobile graphs that have hover effects.
Fix:
https://tailwindcss.com/docs/user-select
Tested in iOS simulator to show the fix:
https://user-images.githubusercontent.com/5155373/160242592-147651c5-1de0-47f7-ba1e-ed23aa0574c2.mp4

Prevent canvas (main graph) from being selected on long press on mobile browsers

---

CHANGELOG.md
assets/js/dashboard/filters.js
assets/js/dashboard/stats/modals/filter.js
assets/package-lock.json
lib/plausible/stats/filters.ex
test/plausible_web/controllers/api/stats_controller/main_graph_test.exs

- Moves `page_entry` and `page_exit` filters to be part of the same filter group as `page`
- Adds a "contains" option as a filter type for page-based filters, which has the same effect as using double asterisks before and after the keyword (i.e. `**<keyword>**`).
- Fixes two small UI bugs (see the screenshots below)
I picked tilde (`~`) as the character to signify a 'contains' query, I hope that's ok?
This is what the new filter type looks like:
The small UI bugs are:
- the 'is not' filter type would display as `is_not` once selected:
- if I select any 'is not' filter, save and then edit the filter, `!` is added in front of the filter keyword:

1421 contains filter

---

assets/package.json

As the whole project is AGPL v3 licensed, this just reflects that in the package.json. This is not changing the tracker JS license.
This change is from the non-merged PR https://github.com/plausible/analytics/pull/757

Set license to AGPL-3.0-or-later for assets package

---

assets/js/dashboard/stats/graph/top-stats.js

Re-adds the underline (now thinner) for the currently selected top stat, & metric, to differentiate the hover state from the actual active state. I noticed this got removed in the cherry picked commit. I figure it wasn't fully intentional, as the hover state and the active state being identical is probably a bit problematic (as can be seen from the recent discussion in #1364), but if it was fully intentional feel free to close this PR.

Re-adds underline to active top stat header

---

lib/plausible/application.ex
lib/telemetry.ex

* Plugin exceptions may silently cover-up database problems such as failed cron job inserts.
* The previously tracked `:circuit` event is no longer emitted.

Expand oban error tracking for plugins/notifiers

---

CHANGELOG.md
config/runtime.exs
lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/templates/auth/login_form.html.eex
lib/plausible_web/templates/layout/_header.html.eex
test/plausible_web/controllers/admin_auth_controller_test.exs

Allows for the `DISABLE_REGISTRATION` config flag to support three states. 
`false` => registration is allowed as normal, for both normal users and invited users
`invite_only` => registration is allowed for those with an invite link, but prevented for normal users
`true` => registration is entirely disabled, regardless of invite status
@jesperordrup - after taking a look, this honestly was too trivial to implement for me to actually expect or accept a bounty for it (assuming it is good enough in its current state). 
I'll add the docs + changelog entry after confirming the implementation.

Adds "invite_only" disable_registration config option

---

lib/plausible_web/templates/layout/_footer.html.eex

i've tried to make the two footers consistent to include the different links we were missing in the in-app footer (terms, dpa...) but also to display the new job opening for those that are logged in. i don't have a way to test it so hopefully i didn't make any mistakes

Keep the public and in-app footers consistent

---

CHANGELOG.md
lib/plausible_web/controllers/api/external_sites_controller.ex
lib/plausible_web/router.ex
test/plausible_web/controllers/api/external_sites_controller_test.exs

Added an API endpoint to get a site based on it's domain. This is required to check if the site exists or not from my terraform provider: https://github.com/mcalpinefree/terraform-provider-plausible

Add API to retrieve site by domain

---

assets/js/dashboard/util/date.js

Fixes #1886 
Safari is modern IE 🤦
I see a pattern.

Fixes inane Safari Date.parse compatibility issue

---

lib/plausible_web/controllers/api/external_controller.ex
mix.exs
mix.lock
test/plausible_web/controllers/api/external_controller_test.exs
test/test_helper.exs

Event ingest can be blocked using the flag `block_event_ingest`

Add feature flag to block event ingest

---

config/runtime.exs

PR add option to configure:
* max hackney pool size for Sentry
* worker size for Geolix

Add option to configure sentry pool size, and geolix worker size

---

CHANGELOG.md
assets/js/dashboard/stats/reports/list.js

This PR adds a tooltip when hovering over list items to show the exact number instead of the formatted short version of the number as suggested in this [discussion](https://github.com/plausible/analytics/discussions/1968).
- [X ] Entry has been added to `CHANGELOG`

Add tooltip to show exact number in lists

---

assets/js/dashboard/datepicker.js

Fix "Yesterday" Shortcut!
When the "Yesterday" shortcut is pressed:
- it sends a "&date" query string to the current URL, to make the filter for the dashboard.
- the "Yesterday" shortcut is not sending a valid date to the `date` query string.
- this PR adjusts the parameters sent to `date`, by using the existing function `formatISO` above the `shiftDays` function
- with this, for the current day = `2022-06-13` instead of sending:
`date=Tue+Jul+12+2022+23%3A04%3A46+GMT-0300+%28Horário+Padrão+de+Brasília%29`
it passes to return the formatted date (`Y-M-D`):
`2022-07-12`

Closes #1994

---

CHANGELOG.md
assets/js/dashboard/stats/conversions/index.js

This pull request closes #1739. More on that on #520. Goals could already be filtered on realtime view, but only by clicking the filter button. This PR makes the goal label clickable as another way of filtering by goal, to keep consistency between views.

Make goals clickable in realtime view

---

CHANGELOG.md
lib/plausible/stats/breakdown.ex
lib/plausible/stats/imported.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/stats_controller/cities_test.exs
test/plausible_web/controllers/api/stats_controller/countries_test.exs
test/plausible_web/controllers/api/stats_controller/regions_test.exs

This commit fixes a bug where location filters were filtering stats but not the locations list. This was caused by a `Map.put/3` call that overrides the user filter. I rolled back 5b571432737fb121e1b2a6c9e977500cb70f8880 changes and removed the `Map.put/3` call.
Closes #1982

Keep user filter when listing cities, countries, and regions stats 

---

.gitignore
CHANGELOG.md
config/test.exs
lib/mix/tasks/download_country_database.ex
lib/plausible_web/controllers/api/external_controller.ex
test/plausible_web/controllers/api/external_controller_test.exs

This commit fixes a bug where regions were not being saved. This was
caused because Geolix response was returning an additional
`:geolocation` map key. It also adds a test case for this.
Closes #2033

Fix geolocation subdivision pattern matching

---

CHANGELOG.md
assets/js/dashboard/stats/graph/graph-util.js

As discussed in the previous [PR](https://github.com/plausible/analytics/pull/1989) a simpler and more pragmatic way of implementing this is to just present the time format based on the system language. From the research I've done it looks like reading the operation system's language isn't straightforward or implemented in all browser. Thus, I've implemented this by leveraging `navigator.language` which per the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language#browser_compatibility) is compatible across all major browsers.

Show time format of graphs based on browser's language

---

lib/plausible_web/controllers/api/external_controller.ex
test/plausible_web/controllers/api/external_controller_test.exs

The NPM package sends events with the `h: 0` option. Currently, the if statement only checks if the hash option is present, not its value. With this change, `h: 0` in the event payload will not track the hash part of the URL.
There's an issue and a PR in the tracker repo, to fix this on the tracker side (https://github.com/plausible/plausible-tracker/issues/42) but I think it makes sense to change this one in our app instead.

added a test and changed hashmode condition

---

lib/oban_error_reporter.ex
lib/plausible/application.ex
lib/plausible/prom_ex.ex
lib/plausible/telemetry/plausible_metrics.ex

* Add Custom telemetry for Plausible.Event.WriteBuffer, Plausible.Event.WriteBuffer and Cachex
* Rename telemetry.ex to avoid confusion with Phoenix Telemetry supervisor

Add Custom telemetry for Plausible.Event.WriteBuffer, Plausible.Event.WriteBuffer and Cachex

---

lib/plausible/application.ex

Enable `Cachex` stats to collect metrics on user agent cache and sessions cache

Enable Cachex stats

---

assets/js/dashboard/stats/sources/search-terms.js
lib/plausible_web/templates/email/welcome_email.html.eex
lib/plausible_web/templates/site/settings_custom_domain.html.eex
lib/plausible_web/templates/site/settings_goals.html.eex
lib/plausible_web/templates/site/settings_search_console.html.eex
lib/plausible_web/templates/site/settings_visibility.html.eex

Some of links to documents are still using `docs.plausible.io`, and this PR updated it.

Update links to documents

---

config/test.exs
fixture/vcr_cassettes/google_analytics_auth#invalid_grant.json
lib/plausible/google/http.ex
lib/plausible_web/templates/site/settings_search_console.html.eex
test/plausible/google/api_test.exs
test/plausible/google/buffer_test.exs

This PR fixes a bug where grant errors were not being caught and adds a custom error message pointing to documentation.

Catch Google Search Console grant error

---

lib/plausible/ingestion/city_overrides.ex
lib/plausible/ingestion/event.ex
lib/plausible/ingestion/ingestion.ex
lib/plausible/ingestion/request.ex
lib/plausible_web/controllers/api/external_controller.ex
test/plausible/ingestion/event_test.exs
test/plausible_web/controllers/api/external_controller_test.exs
test/support/test_utils.ex

This pull request is a follow-up on #2084. I replaced HTTP protocol specific fields from `%Plausible.Ingestion.Request{}` with more specific fields. I also refactored the event creation from a big function with small functions that can be overridden. For example, now user agent and geolocation parsing can be overridden if the function caller has this data. This will be useful for the process per session strategy.
I made small commits that can help reviewing :)

Refactor event struct creation function

---

lib/plausible_web/templates/auth/activate.html.eex
lib/plausible_web/templates/auth/password_reset_request_success.html.eex
lib/plausible_web/templates/auth/register_success.html.eex
lib/plausible_web/templates/billing/change_enterprise_plan.html.eex
lib/plausible_web/templates/billing/change_plan.html.eex
lib/plausible_web/templates/billing/change_plan_preview.html.eex
lib/plausible_web/templates/billing/upgrade.html.eex
lib/plausible_web/templates/billing/upgrade_to_plan.html.eex

Pointed in-app contact links to `https://plausible.io/contact` instead of `mailto:support@plausible.io`. I left the mailto links in the following error messages:
- this domain has already been taken ... please contact `support@plausible.io`
- something went wrong. Please try again or contact support at `support@plausible.io` (when Paddle returns an error on payment)
because:
- it would require a bigger change to embed links in error messages
- it makes sense for a customer to instantly see the support email after encountering an error message

link to contact page instead of mailto

---

fixture/ga_report_empty_rows.json
lib/plausible/google/http.ex
test/plausible/google/api_test.exs

This pull request fixes a bug when trying to import from GA. When the requested report does not have data, the response does not have a `rows` key. The current implementation was expecting a rows key with an empty list.

Add fallback for GA reports without rows

---

lib/plausible/billing/billing.ex
lib/plausible/sites.ex
lib/plausible_web/controllers/site_controller.ex
lib/workers/check_usage.ex

This PR removes some Enum calls to rely on the database for aggregating data. This improves performance when creating new sites, especially if the user has multiple sites.

Perform calculations in SQL instead of app when creating sites

---

lib/plausible_web/controllers/stats_controller.ex
test/plausible_web/controllers/stats_controller_test.exs

This PR makes StatsController respond with `400 Bad Request` in case no `auth` parameter is supplied to shared link request.

Respond with 400 when no auth supplied to shared link request

---

test/plausible/imported/imported_test.exs

The test is constantly failing on my machine with the following assumption not met:
```
1) test Parse and import third party data fetched from Google Analytics Browsers data imported from Google Analytics (Plausible.ImportedTest)
test/plausible/imported/imported_test.exs:809
Assertion with == failed
code:  assert json_response(conn, 200) == [
%{"name" => "Firefox", "visitors" => 2, "percentage" => 50},
%{"name" => "Mobile App", "visitors" => 1, "percentage" => 25},
%{"name" => "Chrome", "visitors" => 1, "percentage" => 25}
]
left:  [%{"name" => "Firefox", "percentage" => 50, "visitors" => 2}, %{"name" => "Chrome", "percentage" => 25, "visitors" => 1}, %{"name" => "Mobile App", "percentage" => 25, "visitors" => 1}]
right: [%{"name" => "Firefox", "percentage" => 50, "visitors" => 2}, …
```

Do not assume any order in browser data import test

---

Makefile

This pins dev clickhouse image to lickhouse/clickhouse-server:21.11.3.6 -- the previous one had tests failing consistently with 
```
** (Clickhousex.Error) Code: 53, e.displayText() = DB::Exception: Type mismatch of columns to JOIN by: country FixedString(2) at left, s1.country String at right (version 21.3.2.5 (official build))
```

Pin clickhouse image to 21.11.3.6

---

lib/plausible/billing/billing.ex
lib/plausible/billing/paddle_api.ex
lib/plausible/google/http.ex
lib/plausible/http_client.ex
lib/plausible_web/captcha.ex
lib/plausible_web/controllers/billing_controller.ex

This PR fixes improper pattern matching on Finch responses
for 3rd party integration as seen in sentry.
By the way, abstracting away some request building details,
encapsulating redundant request encoding.
Type specs were added which immediately made some mismatches
visible via lsp integration.
Potential follow-ups to this:
- a more comprehensive mocking setup for 3rd party
integrations (preferably via https://github.com/dashbitco/mox)
so that erroneous code paths can be tested
- CI linting (such as credo to enforce typespecs/moduledocs in any
files touched in a given PR) + perhaps a dialyzer run

Fix improper pattern matching on Finch responses

---

lib/plausible/http_client.ex

This commit fixes a typo when matching `application/x-www-form-urlencoded` Content-Type headers.
Related: #2181

Add missing `application/` to Content-Type match

---

config/runtime.exs
fixture/ga_list_views.json
lib/plausible/google/api.ex
lib/plausible/google/http.ex
lib/plausible_web/controllers/site_controller.ex
test/plausible_web/controllers/site_controller_test.exs

This commit fixes a bug where different Google Analytics views with the same name and URI were not shown. This was caused because GA views were stored as a map, that naturally doesn't support duplicate keys.
This change updates the GA views list to display view IDs, making it clearer to know what is being imported. The dropdown is now grouped by website URL.
New:
Current:

List all Google Analytics views during import

---

lib/plausible/google/http.ex
test/plausible/http_client_test.exs

Fixes two problems:
- `extra` sent to Sentry is always expected to be a map
- no `String.Chars` protocol is implemented for `Finch.Error` struct
- for now make the `HTTPClient` tests sync so they don't clash with exvcr stuff

Fixup error reporting (ref #2181)

---

assets/js/dashboard/stats/graph/top-stats.js
assets/js/dashboard/stats/graph/visitor-graph.js
assets/js/dashboard/util/tooltip.js

A small improvement to make sure the tooltip doesn't break onto a new line. Had to use `boundary` in Popper.js to make sure the tooltip doesn't overflow the graph container to the left when the line gets long.
**Current:**
**With this PR**

Don't let tooltip text break onto a new line

---

lib/plausible/timezones.ex

This PR fixes a bug where the timezone list was sorted by the standard offset, not considering timezone changes. The list was working properly, but sorting was wrong.
We currently test offsets, but this is a specific case where there is a timezone change (e.g. daylight saving time), and mocking `tzdata` just for this seems overkill. We can add if you think we need.

Sort timezone list by current offset

---

CHANGELOG.md
lib/plausible_web/controllers/api/external_stats_controller.ex
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs

Define an upper boundary for the `limit` parameter used in Stats API.

add upper bound to limit parameter

---

CHANGELOG.md
lib/plausible/stats/breakdown.ex
test/plausible_web/controllers/api/stats_controller/countries_test.exs

Sentry error: https://sentry.plausible.io/organizations/sentry/issues/1095/?environment=prod&project=1&query=is%3Aunresolved
This error is caused by attempting to enrich data for the  `ZZ` country code. This is a special reserved country code for 'unknown country'. The distinction between `ZZ` and `null` return value from the geolocation library is a mystery to me, but there we go.
We [don't accept](https://github.com/plausible/analytics/blob/2692bf4e38dfec9e12496fc000d6d856f7b03d90/lib/plausible/ingestion/event.ex#L245) the `ZZ` country code during ingestion anymore. However, some ZZ values did get into the database and are causing issues now.
An alternative approach would be to run a data migration and remove all the `ZZ` values from Clickhouse. Since we don't accept any new `ZZ` …

Ignore unknown country code

---

lib/plausible/site/membership.ex
lib/plausible_web/controllers/invitation_controller.ex
lib/plausible_web/controllers/site/membership_controller.ex
test/plausible_web/controllers/site/membership_controller_test.exs

Sentry error: https://sentry.plausible.io/organizations/sentry/issues/1945/events/2f6ea4f040284deebea16469384e0f60/?project=1
This error is caused by people taking a reasonable action: someone with `admin` rights wants to grant someone else `admin` rights as well. I think this action should be supported but it currently isn't.

Allow admins to grant admin rights

---

.github/dependabot.yml

This PR adds dependabot integration as per https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
The expectation is to have at most 3 PRs automatically opened with dependency updates.

Add dependabot deps upgrade integration

---

lib/plausible_web/templates/site/settings_general.html.eex

As GA imports are now enabled for everyone, removing this feature flag check makes it also enabled for self-hosters without doing any extra work.

enable google import for everyone

---

lib/plausible/billing/paddle_api.ex
lib/plausible/google/http.ex
lib/plausible/http_client.ex
lib/plausible_web/templates/auth/user_settings.html.eex
lib/plausible_web/templates/site/settings_search_console.html.eex
test/plausible/http_client_test.exs
test/support/paddle_api_mock.ex

We're universally changing the way HTTPClient abstraction works - we'll now tag every non-200 response with an `:error`. Additionally we'll send a Sentry message every time get_invoices/1 fails.

Treat non-200 HTTP responses as errors

---

lib/plausible/google/http.ex

This PR ensures all the extra contexts sent to Sentry can be serialized to JSON.
Going forward we should settle on using only `Logger.error` calls with Sentry backend attached, and once mocks are properly set up, test for errors being logged.

Ensure Sentry extras are maps that can be JSON-encoded

---

lib/plausible/stats/imported.ex
test/plausible_web/controllers/api/stats_controller/countries_test.exs

Follow-up for https://github.com/plausible/analytics/pull/2223
In that PR I forgot to ignore the ZZ country code in imported data as well.

Ignore unknown country in imported data

---

CHANGELOG.md
lib/plausible_web/controllers/stats_controller.ex
mix.exs
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
test/plausible_web/controllers/stats_controller_test.exs

This work started as a bug fix for a [Sentry error](https://sentry.plausible.io/organizations/sentry/issues/258/?environment=prod&project=1&query=is%3Aunresolved). I used the opportunity for some refactoring & docs as well.
During development I found that backwards compatibility for the older format of shared links was broken in [this commit](https://github.com/plausible/analytics/commit/b0b9b9212bb7900e6d4060ae3dc85167f99c9543).

Fix shared link with bad auth

---

lib/plausible/google/api.ex
lib/plausible/google/http.ex
lib/plausible/site/schema.ex
test/plausible/google/api_test.exs

This pull request improves error reporting and documentation for Google Analytics imports. Currently unexpected errors from GA (unauthorized, timeouts, connection closed, etc) are raised as an exception. I changed this to a regular error tuple, reporting the site domain, error and GA response body to Sentry.
I also tested this in our staging Sentry app.

Improve GA Imports error reporting

---

config/runtime.exs
lib/plausible/application.ex

Previous discussion: https://github.com/plausible/analytics/pull/2224
The current pool config eats a lot of memory for self-hosted installations. The pool count seems excessive so this is an attempt to make the app more lean by default.
If it turns out we need beefier pool counts for Plausible.Cloud now or in the future, we can add a config option but keep the lighter pools in the default configuration for easy self-hosting.

Make Finch pools lighter for self-hosting

---

config/runtime.exs
lib/sentry_filter.ex

This configuration change aggregates all the `DBConnection.ConnectionError` events as per https://hexdocs.pm/sentry/readme.html#fingerprinting

Aggregate DBConnection.ConnectionError in Sentry

---

lib/plausible/billing/paddle_api.ex
lib/plausible_web/templates/auth/user_settings.html.eex
test/plausible_web/controllers/auth_controller_test.exs
test/support/paddle_api_mock.ex

Do not attempt to fetch invoices for a free subscription where `paddle_subscription_id=nil`.

do not show invoices for free subscription

---

config/test.exs
lib/plausible/http_client.ex
lib/plausible_web/plugs/favicon.ex
mix.exs
mix.lock
test/plausible/http_client_test.exs
test/plausible_web/plugs/favicon_test.exs
test/test_helper.exs

Some HTTP changes broke header handling for the favicon proxy plug.
We remove the `transfer-encoding` header because it's only meant for one hop and breaks things if it's forwarded to the client. This filter stopped working, probably when we changed HTTP clients, because response headers used to not be processed, but now they are downcased by the HTTP lib.
There were no tests for `PlausibleWeb.Favicon` so I took the opportunity to try out Mox for this use-case. @aerosol curious to see what you think. Recommended to review commit-by-commit.
Closes #2256

Fix favicons

---

lib/plausible/google/api.ex
lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/templates/site/import_from_google_confirm.html.eex
lib/plausible_web/templates/site/import_from_google_user_metric_form.html.eex
lib/plausible_web/templates/site/import_from_google_view_id_form.html.eex
lib/workers/import_google_analytics.ex
test/plausible/google/vcr_test.exs
test/plausible_web/controllers/site_controller_test.exs

Now that we've enabled Google Analytics imports for everyone, the import queue is growing. That is not necessarily a problem, but I noticed a spike on GA authorization errors.
Currently the background job is enqueued with the access token for later use. The issue is the token is only valid for 60 minutes, and we're not refreshing it. This pull request saves refresh and access tokens so we can have valid tokens when a job is waiting for more than an hour.

Refresh Google Analytics token before import

---

lib/plausible/timezones.ex
test/plausible/timezones_test.exs

This commit fixes an exception when calling `Timex.Timezone.get/2` after there has been a timezone change. Similar issues have already been reported in Timex ([bitwaker/timex#691](https://github.com/bitwalker/timex/issues/691), bitwalker/timex#555, bitwalker/timex#625).
This skips timezones from the list when they fail to fetch, and use `Timex.Timezone.get/2` to get the current offset using `DateTime.utc_now/0` instead of the `NaiveDateTime` default.
- https://sentry.plausible.io/organizations/sentry/issues/2075/
- https://sentry.plausible.io/organizations/sentry/issues/2074/

Fix timezone list when time changes

---

.github/workflows/build-public-images.yml
CHANGELOG.md

This PR adds ARM64 builds for plausible docker images.
I tested the builds, and everything worked.
Test builds:
https://github.com/FZR-forks/analytics/pkgs/container/plausible
the latest tag is the self-hosting version
the master version is built to the latest commit
**This PR requires switching from yandex/clickhouse-server to a recent [clickhouse/clickhouse-server](https://hub.docker.com/r/clickhouse/clickhouse-server) image which supports ARM64**
I tested it using the latest version, which has an ARM64 image.
If this PR gets merged, I can create another one to update the hosting repo.
Related:
#1286 
#903

ARM64 support for docker images

---

CHANGELOG.md
lib/plausible/stats/filter_parser.ex
lib/plausible/stats/query.ex
test/plausible/stats/filter_parser_test.exs
test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs

- Allow escaping the `|` character with `\|` in Stats API filter values, to prevent the filter type being parsed to `:member`

Stats API: allow escaping `|` literal character with `\|` when filtering

---

lib/plausible/google/api.ex
lib/plausible_web/controllers/auth_controller.ex

This fix has been cherry picked from stable. It is a follow-up on #2254, fixing the token refresh for GA imports.
We need better testing around this whole feature, but this involves replacing our current mock strategy for GA. I added an item in our backlog.

Fix Google Analytics expires_at key

---

CONTRIBUTING.md
Makefile
lib/mix/tasks/send_pageview.ex

For development we need a convenient way to generate fake pageview events.
Currently this is done via `make dummy_event` but it's not very convenient because you cannot
override parameters from the command line like so:
```bash
$ make dummy_event --ip 127.0.0.2
$ make dummy_event --domain some-test-domain.com
```
In order to support command-line options like this, I thought I would write a small Mix task for it:
```bash
$ mix send_pageview --ip 127.0.0.2
$ mix send_pageview --domain some-test-domain.com
```
I'm not sure of the value of `Make` in this project in general. Mix is a great build tool and task runner, do we need another one?

Add script to send pageview

---

lib/plausible/google/http.ex
test/plausible/google/api_test.exs

This commit increases the receive_timeout from 15s to 30s for Google Analytics import requests. Timeouts have been reported, and I could replay some requests that took 15-20 seconds to complete when fetching 10,000 records in a single request.

Increase GA import request receive_timeout to 30s

---

CHANGELOG.md
lib/plausible/site/schema.ex
lib/plausible_web/templates/site/settings_visibility.html.eex
lib/plausible_web/views/stats_view.ex
test/plausible_web/controllers/api/external_sites_controller_test.exs
test/plausible_web/views/stats_view_test.exs

This PR adds support for IDNs as discussed in #993. I replaced the latin alphanumeric validation with a more broad one, supporting other alphabets. I also made some changes to URI encoding to make sure our URLs are still good looking.

International Domain Names (IDN) Support

---

CHANGELOG.md
lib/plausible/site/schema.ex
lib/plausible/stats/query.ex
test/plausible/site/schema_test.exs
test/plausible/stats/query_test.exs

[Sentry link](https://sentry.plausible.io/organizations/sentry/issues/1289/?environment=prod&project=1&query=is%3Aunresolved&statsPeriod=14d)
The `All time` period is failing for sites where `stats_start_date=nil`. This PR adds a fallback for when this field is missing.

[Sentry APP-189] Fallback to current date in all time parsing

---

mix.exs
mix.lock
test/plausible_web/controllers/api/external_controller_test.exs
test/test_helper.exs

Removes the Mimic mocking library. It was used for a single test of feature flags. The mocking is replaced with letting the app interact with `FunWithFlags` for real.
The way the new test is written means that it cannot run concurrently with any other test for the `feature-flag-test.com` domain.

Remove Mimic dependency

---

lib/plausible_web/controllers/auth_controller.ex

This PR removes potentially sensitive security information from our log output. This information might've been useful in dev environment, however all the e-mails sent can be inspected with [`/sent-emails` endpoint](https://github.com/plausible/analytics/blob/06f09fbb14b4ff21b0155d7993e922d364d51459/lib/plausible_web/router.ex#L52).

Do not log sensitive info

---

Dockerfile

👋
Right now the container image contains a large [`geonames.csv`](https://github.com/plausible/analytics/blob/cc4d4bb8e0e8686c13cd08e5c97584fbabf3d326/Dockerfile#L19) file that makes self-hosting difficult on small instances as it requires additional ~700MB of RAM and slows down `plausible` container startup.
This PR makes `geonames.csv` to not be included in the final container image. `geonames.csv` or a similar file can still be separately mounted in a volume for the same end result.
Container image with this change: [`ghcr.io/ruslandoga/analytics:pr-1`](https://github.com/ruslandoga/analytics/pkgs/container/analytics/40688610?tag=pr-1)
---
Something like the following could be added to docs for self-hosters:
If more accurate city-level tracking is desired, it should be enabled by …

lite geonames by default

---

assets/.prettierrc.json
assets/js/dashboard/components/search-select.js
assets/js/dashboard/datepicker.js
assets/js/dashboard/filters.js
assets/js/dashboard/site-switcher.js
assets/js/dashboard/stats/modals/filter.js
assets/js/dashboard/stats/sources/source-list.js
assets/package-lock.json
assets/package.json
lib/plausible_web/plugs/favicon.ex
lib/plausible_web/templates/site/index.html.eex
test/plausible_web/plugs/favicon_test.exs

Fixes #2286
DDG favicon service does not handle SVG images well. Here's an SVG icon hosted at https://ptable.com/icon/pt-square-192.png which returns `content-type=image/svg+xml`. Requesting this through DDG:
```bash
➜  assets git:(fix-svg-favicons) curl -I https://icons.duckduckgo.com/ip3/ptable.com.ico
HTTP/2 200
server: nginx
date: Mon, 03 Oct 2022 08:33:30 GMT
content-type: image/x-icon
```
It has set `content-type=x-icon`. This incorrect content-type causes browsers to render a broken icon.
I also took the opportunity for some refactoring+cleanup in `assets/js/dashboard/site-switcher.js`. The diff is big because I ran the `prettier` formatter on the file, but this was done in a separate commit so you can still see the meaningful changes in [a commit …

Fix svg favicons

---

lib/plausible_web/endpoint.ex

It looks like we're having some log duplication due to `Plug.Logger` being explicit set for `PlausibleWeb.Endpoint`.
before:
after:

Remove redundant logger

---

CHANGELOG.md
lib/plausible/sites.ex
lib/plausible_web/controllers/api/helpers.ex
lib/plausible_web/controllers/stats_controller.ex
lib/plausible_web/plugs/authorize_stats_api.ex
test/plausible_web/controllers/api/external_stats_controller/auth_test.exs

This PR adds site locked status check to External API authorization.
In case a site is locked, an subscription renewal message is returned along with 402 HTTP status.
I took the liberty of tidying the tests by the way.

Block Stats API for locked sites

---

lib/plausible/site/admin.ex

This change makes the Sites CRM section order by `inserted_at`. We'll also gracefully ignore no `owner` role for a site - a data error to be fixed through data migration probably.

CRM: order sites by latest. Tolerate missing owner

---

lib/plausible_web/plugs/authorize_stats_api.ex
test/plausible_web/controllers/api/external_stats_controller/auth_test.exs

Super admins should be still capable of using the Stats API for locked sites.

Allow super-admin Stats API access for locked sites

---

lib/plausible/site/admin.ex
lib/plausible/site/schema.ex
lib/plausible/sites.ex
lib/plausible/stats/clickhouse.ex
lib/plausible_web/controllers/site_controller.ex

This pull request adds the `stats_start_date` field to the CRM site form. This allows this field to be manually overridden, so Google Analytics imports date ranges can be overridden also.
Reviewing commit-by-commit can help understand some decisions and minor refactoring we made. 
We don't have a test suite for the CRM.

Override stats_start_date in CRM

---

lib/oban_error_reporter.ex
lib/plausible/clickhouse_repo.ex
lib/plausible/imported/site.ex
lib/plausible/purge.ex
lib/plausible/sites.ex
lib/plausible_web/controllers/api/external_sites_controller.ex
lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/controllers/site_controller.ex
lib/workers/import_google_analytics.ex
test/plausible/purge_test.exs

This pull request fixes two bugs when clearing stats:
- Resetting stats left an invalid state of the `stats_start_date` field, used for GA imports, for example
- Deleted sites could leave dangling GA imported stats records
I refactored delete stats code to a new `Plausible.Purge` module. Reviewing commit-by-commit may help :)

Delete stats improvements

---

lib/mix/tasks/send_pageview.ex

This commit adds an option to override `http://localhost:8000` in `mix send_pageview`. This is useful when running the server in another port or with remote servers such as staging.

Add --host option to send_pageview task

---

CONTRIBUTING.md
Makefile

- Mention installing tracker dependencies in CONTRIBUTING.md
- Include `npm install --prefix tracker` command in `make install`

Update contributing.md and makefile to install tracker deps

---

lib/plausible/stats/filter_parser.ex
lib/plausible/stats/query.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible/stats/filter_parser_test.exs
test/plausible_web/controllers/api/stats_controller/suggestions_test.exs
test/plausible_web/controllers/auth_controller_test.exs

This improves our input data validation at various places to address the following Sentry errors:
- APP-1JA
- APP-22Y
- APP-21T
- APP-A6
We now don't crash but rather silently discard the garbage sent our way.

Improve user input validation

---

lib/plausible/auth/invitation.ex
lib/plausible_web/controllers/site/membership_controller.ex
test/plausible_web/controllers/site/membership_controller_test.exs

This fixes a crash on duplicate invitation send attempt. The user is redirected to the people settings page where existing, pending invitation can be removed if need be.

Gracefully handle duplicate invitations

---

lib/plausible/google/api.ex
lib/plausible/google/http.ex
test/plausible/google/api_test.exs

The Google Analytics report request may take some time, especially with big imports with thousands of pages. To mitigate the issue this commit increases the timeout to 60s and lowers the page size to 7,500 records per request.

Increase Google Analytics timeout and lower page size

---

lib/plausible/billing/paddle_api.ex
lib/plausible/google/http.ex
lib/plausible/http_client.ex
test/plausible/http_client_test.exs
test/plausible_web/controllers/site_controller_test.exs

This PR pushes JSON body decoding to the HTTP Client level - if a relevant content-type was detected. This lays out some foundation for further google integration improvements.

Automatically decode JSON payloads from HTTP

---

test/support/test_utils.ex

This pull requests increases the timeout of tests using `eventually/3`, e.g. when waiting for Clickhouse async deletes.

Increase flaky test timeout

---

.github/workflows/build-private-images.yml
.github/workflows/build-public-images.yml

This notifies `BUILD_NOTIFICATION_URL` whenever an image fails to build.

Notify team on image build failures

---

CONTRIBUTING.md
Makefile

This PR updates Makefile's `postgres` version [to the one used in `plausible/hosting` (version 14)](https://github.com/plausible/hosting/blob/a6fe8d13df3566f7bb3625a1a524f5498d56693d/docker-compose.yml#L9) and `clickhouse` -- to the version [that replaced `hyperscan` with `vectorscan` for better arm64 support (version 22.9)](https://github.com/ClickHouse/ClickHouse/pull/38171)
Relevant:
- https://github.com/plausible/analytics/discussions/2292
- https://github.com/plausible/hosting/pull/57
- https://github.com/plausible/analytics/discussions/2342

update clickhouse and postgres images in Makefile

---

lib/plausible_web/templates/email/google_analytics_import.html.eex

This PR changes the email that is sent when a Google Analytics import fails. Rather than simply saying that the import failed and linking to our contact page, it now gives some instant debugging steps that the customers can follow before writing to our support.

add debugging info to failed GA import email template

---

lib/plausible_web/templates/auth/new_api_key.html.eex
lib/plausible_web/templates/site/new_shared_link.html.eex

- Optimize the shared link form for darkmode UI
- Make the style consistent between new API key and shared link forms
https://user-images.githubusercontent.com/56999674/196535829-b4393c16-9532-4d0e-b083-d4f48a22a60c.mp4

Optimize dark mode UI for shared link form

---

.github/workflows/build-public-images.yml

Cont. from https://github.com/plausible/analytics/discussions/2324#discussioncomment-3867370
[More info on `@metadata-action`'s semver](https://github.com/docker/metadata-action#typesemver)
[Demo workflow](https://github.com/ruslandoga/version-tag-test/blob/master/.github/workflows/build.yml)
[Result images](https://github.com/ruslandoga/version-tag-test/pkgs/container/version-tag-test)
```console
$ docker run -ti --rm ghcr.io/ruslandoga/version-tag-test:v1.5.0-rc.4 ash
$ cat meta.json | jq
{
"tags": [
"ghcr.io/ruslandoga/version-tag-test:v1.5.0-rc.4"
],
"labels": {
"org.opencontainers.image.title": "version-tag-test",
"org.opencontainers.image.description": "",
"org.opencontainers.image.url": "https://github.com/ruslandoga/version-tag-test",
"org.opencontainers.image.source": …
```

add `v` prefix to version tags in public images

---

config/runtime.exs

This commit makes the permitted header length more permissive, 8,192 bytes, doubling the Phoenix default.
Related to https://github.com/4lejandrito/next-plausible/issues/67
I tried testing with ExUnit, but I could not reproduce the HTTP 431 Request Header Fields Too Large response. I guess this is because the HTTP server does not actually run in test environment. However, I tested this locally with curl and the HTTP 431 is fixed.

Double maximum header length

---

test/plausible/google/vcr_test.exs

This commit removes a flaky test assertion from the GA suite. The initial purpose of this test was to ensure we are not inserting to Clickhouse more than 1 time per second during an import.
Although it is nice to have an assertion like this, the test is flaky and fails sometimes. To get the total inserts during a time range, it queries Clickhouse internal tables for insert commands, and this number is not deterministic.
In a real-world scenario with Clickhouse, the app runs in multiple nodes not aware of their neighbors' CH calls. In that case, Grafana provides us visibility over CH, and these tests do not suffice.

Remove inserts per second Google Analytics test assertion 

---

lib/plausible/billing/billing.ex
lib/plausible/billing/site_locker.ex
lib/plausible/mailer.ex
lib/plausible/mailer_test.exs
lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/controllers/invitation_controller.ex
lib/plausible_web/controllers/site/membership_controller.ex
lib/plausible_web/controllers/site_controller.ex
lib/workers/check_usage.ex
lib/workers/import_google_analytics.ex
lib/workers/notify_annual_renewal.ex
lib/workers/send_check_stats_emails.ex
lib/workers/send_email_report.ex
lib/workers/send_site_setup_emails.ex
lib/workers/send_trial_notifications.ex
lib/workers/spike_notifier.ex

This commit refactors the Plausible.Mailer module, which is a wrapper around Bamboo. The original behaviour uses exceptions to control flow and reports every error to Sentry. This replaces exceptions with error tuples and parses Bamboo errors to avoid reporting unnecessary noise to Sentry.

Do not report hard bounce e-mail errors to Sentry

---

lib/plausible/imported/site.ex
test/plausible/imported/imported_test.exs

This commit fixes a bug where GA report rows with empty dates were failing to import.
An `(other)` row appears as the last row in a report when the underlying GA database table from which the report is built reaches its row limit.
https://support.google.com/analytics/answer/9309767

Skip rows with empty dates from GA imports

---

lib/plausible/purge.ex
test/plausible/purge_test.exs

This commit fixes a bug where users clearing one import and trying to re-import would get invalid import date ranges. This was caused because the stats_start_date field was not updated to nil after clearing imported stats, as this field defines the end date of the import.

Clear stats_start_date after clearing GA stats

---

lib/plausible/billing/plans.ex
test/workers/check_usage_test.exs

This pull request updates the e-mail sent to outgrown subscriptions. The current template suggest an enterprise plan when the monthly usage is over 20M, however, this should be 10M, our standard plan limit.

Suggest enterprise plan when usage is greater than 10M pageviews

---

lib/plausible/google/api.ex
lib/plausible_web/templates/site/settings_general.html.eex
lib/plausible_web/templates/site/settings_search_console.html.eex
test/plausible_web/controllers/site_controller_test.exs

This PR separates Google oauth scopes -- there is no point in asking for search console permissions when only import is intended and vice-versa.

Separate GA/SC scopes

---

README.md
lib/plausible_web/templates/site/settings_general.html.eex
lib/plausible_web/templates/site/snippet.html.eex
test/plausible_web/controllers/site_controller_test.exs

One person reported that we are spelling JavaScript without capital J and S so I thought I'd fix that and other places where we don't capitalize it correctly.

Correct the spelling of JavaScript

---

lib/plausible/goal/schema.ex
lib/plausible/goals.ex
lib/plausible/stats/breakdown.ex
lib/plausible/stats/filter_suggestions.ex
lib/plausible_web/controllers/site_controller.ex
test/plausible/goals_test.exs

People are likely to enter (copy/paste) goals from external sources
which can lead to whitespace characters appended by accident.
That renders the goal unusable and hard to distinct visually.
Normally to fix up existing goals we would use a data migration,
but this should be good enough to check if the problem
with never appearing goals resurfaces.
Going forward it's a good idea to trim all the input coming from forms,
maybe we could put that in the backlog cc @vinibrsl @RobertJoonas

Trim goals user input

---

lib/plausible_web/templates/email/yearly_renewal_notification.html.eex

Someone mentioned there's no way to cancel from the link we include in this email (https://plausible.io/billing/upgrade) so I'm changing it to the settings page instead https://plausible.io/settings. My own https://plausible.io/billing/upgrade is a bit different than normal subscribers see it so I don't actually know if there's a way to cancel on it. If there is a way there too, feel free to ignore this

Changing the settings link in the renewal email

---

lib/plausible/ingestion/event.ex
lib/plausible/telemetry/plausible_metrics.ex

This PR introduces new Cachex related metrics and fixes up size calculation to use the native interface rather than trying to subtract writes and evictions.
We will be now calculating the hit_ratio too. Old metrics will be pruned.
The PR also reverts profiling metrics introduced via https://github.com/plausible/analytics/commit/101e5a68b5ff907978f1f7b220b17d2cf53da4b6 - they are no longer needed.
```
plausible_prom_ex_plausible_metrics_cache_sessions_hit_ratio 0.0
plausible_prom_ex_plausible_metrics_cache_user_agents_hit_ratio 0.0
plausible_prom_ex_plausible_metrics_cache_user_agents_size 0
plausible_prom_ex_plausible_metrics_cache_sessions_size 0
```

Fix up Cachex metrics

---

priv/repo/migrations/20221109082503_add_rate_limiting_to_sites.exs

This PR adds postgres migration extending the `sites` tagle with metadata fields required for ingestion rate limiting.

Add sites metadata rate limit migration

---

lib/plausible/purge.ex
lib/plausible/stats/fragments.ex
lib/plausible/stats/imported.ex
lib/plausible/stats/interval.ex
lib/plausible/stats/query.ex
lib/plausible/stats/timeseries.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible/imported/imported_test.exs
test/plausible/stats/interval_test.exs
test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
test/plausible_web/controllers/api/stats_controller/suggestions_test.exs

This pull request adds API support for different intervals in queries (weekly, daily, hourly, etc). I cherry-picked @Vigasaurus' changes from the Intervals PR (#1574) so we can release this feature incrementally and review in chunks.

Add API support for intervals

---

lib/plausible/site/cache.ex
lib/plausible/site/cache/warmer.ex
test/plausible/site/cache_test.exs

This is a follow-up PR to https://github.com/plausible/analytics/pull/2434 and a ground work for rate limiting ingestion, cherry-picked from a work in progress PR to hopefully keep the changes isolated and easier to review.
Reviewing commits one by one should give a better picture of how the ideas evolved.
Summary:
- the tests have been reorganized
- the `Cache` interface makes it now possible to either refresh the whole cache or re-query a single item once to account for deleted/missing domains (this will be again addressed later in greater detail)
- warmer responsibility was reduced, tests simplified
- more consistent/comprehensive telemetry instrumentation

Update sites cache implementation

---

assets/package.json

We're running npm@latest so `npm bin` is gone making builds fail. Example https://github.com/plausible/analytics/actions/runs/3479317335/jobs/5818525028

Stop relying on npm-bin (hard deprecated)

---

CONTRIBUTING.md
mix.exs
priv/repo/seeds.exs
test/support/factory.ex

This commit adds basic support for database seeding useful for local testing, especially dashboard changes, like intervals.
It creates two years of pageviews with random timestamps. There is lot of room for improvement, such as adding sources, entry pages, geolocation, devices, custom events, but this already helps us with testing.

Seed database with pageviews

---

lib/plausible/site/cache.ex
lib/plausible/site/cache/rate_limiter.ex
test/plausible/site/cache_test.exs
test/plausible/site/rate_limiter_test.exs

This PR introduces the ingest rate limiting interface utilizing cache (ref #2434 and #2444).
The interface is unused yet, to be incorporated after we ship https://github.com/plausible/analytics/pull/2351.

Outline basic rate-limiting interface

---

lib/plausible_web/templates/stats/stats.html.eex

This commit fixes a bug where opening modals resulted in a `target container is not a DOM element` error. This was caused by a change in #1574, that was not closing the div that mounts React as expected.

Fix target container is not a DOM element

---

priv/repo/migrations/20221123104203_index_updated_at_for_sites.exs

This PR is a migration putting index on `sites.updated_at` - potentially useful for grabbing the newly created/edited sites when a new caching layer is introduced.

Migration: index Sites.updated_at

---

lib/plausible/ingestion/event.ex
lib/plausible/ingestion/request.ex
lib/plausible_web/controllers/api/external_controller.ex
test/plausible/ingestion/event_test.exs

This pull request changes the `Plausible.Ingestion.Request` struct to store the event URL as `%URI{}` instead of string. The domain param can be a comma-separated list of domains, and this PR updates the Request struct domain field to a list instead of string.
It's been cherry-picked from #2085. That pull request was an experiment on different event ingestion strategies, and involved some refactoring worth pushing to master.

Parse event URL and domain in Plausible.Ingestion.Request

---

CHANGELOG.md
lib/plausible_web/controllers/invitation_controller.ex
test/plausible_web/controllers/invitation_controller_test.exs

Fixes invitation links for ownership transfer in self-hosted setups.
More info: https://github.com/plausible/analytics/discussions/2051

fix ownership transfer when is_selfhost=true

---

assets/js/dashboard/datepicker.js
assets/js/dashboard/keybinding.js
assets/js/dashboard/stats/graph/interval-picker.js

This pull request adds keyboard navigation to intervals. Pressing `<i>` will open the interval menu, and pressing `<i>` again will close it. You can navigate with arrows and press `<Enter>` to select an interval.

Add keyboard navigation to intervals

---

assets/js/dashboard/stats/graph/visitor-graph.js
test/plausible_web/controllers/stats_controller_test.exs

This commit adds the interval param to the CSV export client-side request.

Pass interval param to CSV export

---

assets/js/dashboard/stats/graph/interval-picker.js
assets/js/dashboard/stats/sources/source-list.js

⚠️ To be reviewed and merged after #2470, as I created this on top of #2470 to avoid merge conflicts.
This commit standardises the dropdown icon spacing used for "intervals" and "campaigns". The screenshots below help spotting the difference. "Intervals" needed more space, "campagins" had too much.

Standardise dropdown icon margins

---

config/runtime.exs
lib/mix/tasks/send_pageview.ex
lib/plausible/application.ex
lib/plausible/ingestion/event.ex
lib/plausible/ingestion/request.ex
lib/plausible/site/admin.ex
lib/plausible/site/cache.ex
lib/plausible/site/cache/warmer.ex
lib/plausible/site/cache/warmer/all.ex
lib/plausible/site/cache/warmer/recently_updated.ex
lib/plausible/site/gate_keeper.ex
lib/plausible/telemetry/plausible_metrics.ex
lib/plausible_web/controllers/api/external_controller.ex
test/plausible/ingestion/event_telemetry_test.exs
test/plausible/ingestion/event_test.exs
test/plausible/ingestion/request_test.exs
test/plausible/site/cache_test.exs
test/plausible/site/gate_keeper_test.exs
test/plausible_web/controllers/api/external_controller_test.exs

This PR introduces event ingestion pipeline protection and instrumentation. 
Apologies for the sizeable chunk of code in one go; reviewing commit by commit should help with illustrating the thought process as I proceeded.
The event processing logic has been reworked, so that we return any client request errors early if possible. When the initial `Request` validation passes, it's turned into a series of `Ingestion.Event`s (to handle multiple domains uniformly) that are either buffered to ClickHouse or dropped with a reason. We keep telemetry for both cases (counters).
The new behavior from backend perspective is we'll now any drop traffic for sites that are not found in the database/cache.
A new `Site.Cache` warmer is now spawned, refreshing any recently updated/created sites every 30 …

Gatekeep ingestion pipeline

---

lib/plausible/application.ex
lib/plausible/ingestion/request.ex
lib/plausible/site/cache.ex
lib/plausible_web/controllers/api/external_controller.ex
test/plausible/ingestion/request_test.exs
test/plausible/site/cache_test.exs
test/plausible_web/controllers/api/external_controller_test.exs

This PR:
- pushes PromEx to the bottom of supervision stack to avoid Endpoint instrumentation failure
- ensures the site cache is ready by exposing it through the health check endpoint
- fixes event timestamps being calculated at compile time, with regression unit and integration tests

Fix: application startup, event timestamps

---

CHANGELOG.md
assets/js/dashboard/stats/graph/visitor-graph.js
lib/plausible_web/controllers/stats_controller.ex

This commit removes the intervals feature flag, as this feature has already been released to 100% of the users.

Remove intervals feature flag

---

CHANGELOG.md
lib/plausible/helpers/config.ex

Hello friends, I'm trying to self-host plausible on my server and have observed that if I add a file named (for example) `secrets/LISTEN_IP` to configure the bind IP I'll get the following error:
```
Compiling 1 file (.ex)
** (RuntimeError) Invalid LISTEN_IP '172.19.130.83
' error: :einval
/home/serafeim/plausible/config/runtime.exs:20: (file)
```
(notice that I get the same error when configuring the DATABASE_URL or whatever comes first)
It seems that for whatever reason the File.read! will insert a newline at the end of the file. Notice that I have double checked the file with vim and *it does not contain a newline at the end* or at least I don't know *how* to make the file not have a newline at the end.
Thus I'm adding a `String.trim()` there to fix that thing; even if I am doing …

Trim the value in case it contains newlines

---

CHANGELOG.md
lib/plausible_web/plugs/favicon.ex
test/plausible_web/plugs/favicon_test.exs

This commit adds two headers as additional security on favicons.
This commit updates the favicon Plug to set a strict `Content-Security-Policy` header telling the browser not to run scripts. Additionally, it sets `Content-Disposition=attachment` to prevent the SVG from rendering when navigating to `/favicon/sources/:domain` directly.
SVGs may contain `<script>` tags, and as these SVGs come from external sources, we need to prevent untrusted code from running on the browser.

Add Content-Security-Policy to favicon Plug

---

assets/js/dashboard/stats/graph/top-stats.js

This PR adds an `id` attribute to HTML tags in order to facilitate browser testing.
I'm trying to write some very basic headless browser checks using [Checkly](https://www.checklyhq.com).
ID are only added to the top stats. This allows us to write assertions in Playwright tests like: _'make sure unique visitors is > 0 on a dashboard'_.

Add metric ID to HTML

---

CHANGELOG.md
lib/plausible/stats/breakdown.ex
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs

This commit fixes a bug with pagination where breaking down by event:page would always return results despite pagination.
Closes #2255

Return empty list when breaking down by event:page without events

---

assets/js/dashboard/stats/conversions/index.js
assets/js/dashboard/stats/graph/graph-util.js
assets/js/dashboard/stats/graph/interval-picker.js
assets/js/dashboard/stats/graph/visitor-graph.js
assets/js/dashboard/stats/reports/list.js
assets/js/dashboard/stats/sources/source-list.js
assets/js/dashboard/util/storage.js

1. Use the `react-flip-move` library to make updates to `ListReports` look nicer.
2. Unify the color of 'No data yet' in darkmode.
Screencasts to showcase 1 and 2: [before](https://user-images.githubusercontent.com/56999674/208523855-ad1cecd8-3947-4228-b0db-f34b3ce514c6.mp4) -> [after](https://user-images.githubusercontent.com/56999674/208524152-9cbe41e6-ee39-40f4-8880-88961e1c7f8b.mp4) (the "Before" screencast already includes the auto-updating work done in https://github.com/plausible/analytics/pull/2445)
3. Lose the flicker in the graph when updated in the realtime mode. A console log demonstrates the moment when new data is fetched. Screencasts: [before](https://user-images.githubusercontent.com/56999674/208525401-9c7e8b99-d099-441e-bd48-3b56d4f3d49f.mp4) -> …

Visual improvements to automatic realtime updates

---

CHANGELOG.md
lib/plausible/ingestion/request.ex
test/plausible/ingestion/request_test.exs

This pull request makes a change to ingestion that rejects events with data URIs and long URIs.
We haven't seen a practical case for tracking data URIs, and those can actually cause some noise on the dashboard when triggered by a browser extension or any other external source.
Additionally, long URIs are also rejected. I set a maximum length of 2,000 characters for pathnames, which should be a reasonable size. I've searched for an official specification for pathnames, but [RFC 2616](http://www.faqs.org/rfcs/rfc2616.html) says there is no limit, so each browser implements it differently. Modern browsers accept gigantic URIs due data URIs I mentioned before.

Reject events with long URIs and data URIs

---

assets/js/dashboard/stats/graph/interval-picker.js
assets/js/dashboard/stats/graph/visitor-graph.js
assets/js/dashboard/util/storage.js

Remove `interval` from the `VisitorGraph` component state to remove unnecessary code complexity. Just using localStorage for that is enough. If there's no interval stored at the time of fetching data, no interval parameter is sent to the API. This is allowed, because interval is an optional parameter with default values based on the `period` parameter.

remove interval state from VisitorGraph

---

assets/js/dashboard/stats/conversions/prop-breakdown.js

This PR makes the custom event property breakdown automatically update in realtime mode. It also disables the "Load more" button in realtime mode (screenshot of the button I mean), because supporting paginated results in realtime is too complex.
This is how the automatic updates look like (realtime ticks are sped up from 30s to 5s, and there's an artificial delay in fetching the data to make the loading spinner visible):
https://user-images.githubusercontent.com/56999674/208881570-6554f7e0-89ad-49b3-8dc9-ca7073f309ed.mp4
I also considered using `react-flip-move` as in `ListReport`, but as the container size changes, it causes the animation to overflow the container borders:
https://user-images.githubusercontent.com/56999674/208881785-3d8eac28-b265-4ee7-9e56-972f19c64ce5.mp4
That's why I …

Realtime prop breakdown

---

.github/workflows/elixir.yml
config/.env.test
test/plausible/google/api_test.exs
test/plausible/google/buffer_test.exs
test/plausible/google/vcr_test.exs
test/plausible_web/controllers/api/external_controller_test.exs
test/plausible_web/controllers/api/external_sites_controller_test.exs
test/plausible_web/controllers/api/internal_controller_test.exs
test/plausible_web/controllers/api/paddle_controller_test.exs
test/plausible_web/controllers/auth_controller_test.exs
test/plausible_web/controllers/billing_controller_test.exs
test/plausible_web/controllers/unsubscribe_controller_test.exs
test/plausible_web/plugs/auth_plug_test.exs
test/plausible_web/plugs/favicon_test.exs
test/plausible_web/plugs/firewall_test.exs
test/plausible_web/plugs/tracker_test.exs
test/test_helper.exs

This PR speeds up dev workflow by excluding slow tests and marking cases async where applicable (i.e. where no clickhouse/application env patching are involved).
The motivation behind tagging tests as slow instead of addressing the test structure is that the code under test is likely to be removed soon enough.

Run tests in async mode where applicable

---

CHANGELOG.md
priv/repo/migrations/20221228123226_cascade_delete_sent_renewal_notifications.exs
test/plausible_web/controllers/auth_controller_test.exs

This pull request fixes a bug when deleting a user would trigger a database constraint error.

Cascade delete sent_renewal_notifications table when user is deleted

---

lib/plausible/stats/breakdown.ex
lib/plausible/stats/query.ex

This pull request traces breakdown queries with OTEL. This will be useful to know if some properties are being used like `entry_page`, as we want to migrate that for session metrics, for example.
Honeycomb screenshot:

Trace breakdown queries with OTEL

---

CHANGELOG.md
config/test.exs
lib/plausible/ingestion/city_overrides.ex
lib/plausible/ingestion/event.ex
lib/plausible/ingestion/geolocation.ex
test/plausible_web/controllers/api/external_controller_test.exs

There are some country codes we're recording that cannot be displayed. These are not real countries they are:
`XX` - disputed territory (https://sentry.plausible.io/organizations/sentry/issues/1095/events/b01fa99ae92f4712ba3579371416be39/?environment=prod&project=1)
`T1` - Tor exit node (https://sentry.plausible.io/organizations/sentry/issues/1095/events/af5adb05fb79486d9e90f48cf3707be6/?environment=prod&project=1)
Also makes the following changes:
* Do not attempt to look up region and city codes if country is unknown
* Extracts geolocation to a dedicated module

Ignore unknown countries

---

CHANGELOG.md
lib/plausible/stats/breakdown.ex
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
test/plausible_web/controllers/api/stats_controller/countries_test.exs
test/plausible_web/controllers/api/stats_controller/pages_test.exs
test/plausible_web/controllers/api/stats_controller/sources_test.exs

This commit fixes a bug where the subsequent breakdown API pages had the same items as the first page. The fix sorts the underlying ClickHouse query by timestamp, keeping the same order between requests, as we use OFFSET/LIMIT pagination.
Closes #2561

Fix breakdown API pagination when using event metrics

---

assets/js/dashboard/stats/devices/index.js
assets/js/dashboard/stats/locations/index.js
assets/js/dashboard/stats/pages/index.js

Fixes #2338
Enable keyboard navigation for stats tabs by converting list elements to button elements

Enable keyboard navigation for stats tabs by converting list elements to button elements

---

lib/sentry_filter.ex
mix.lock

This adds Clickhousex error fingerprinting. Depends on https://github.com/plausible/clickhousex/pull/19

Fingerprint Clickhousex.Error exceptions in Sentry

---

lib/sentry_filter.ex
mix.lock

This reverts commit 2428a2bf36fbbed2fe74c2bd2183d18a41d28710.
There were stability issues and this is one is likely to be the culprit.

Revert "Fingerprint Clickhousex.Error exceptions in Sentry (#2578)"

---

lib/sentry_filter.ex
mix.lock

Brings back the reverted commit with https://github.com/plausible/clickhousex/pull/20 included

Update clickhousex & fingerprint sentry errors

---

assets/js/dashboard/stats/modals/pages.js

Fixes https://github.com/plausible/analytics/issues/2182
The pageviews column is now displayed in the details modal for top pages when filtering by a source.

Display pageviews in details modal for top pages when filtering by a source

---

CHANGELOG.md
assets/css/app.css
assets/js/dashboard/historical.js
assets/js/dashboard/index.js
assets/js/dashboard/realtime.js
assets/js/dashboard/stats/current-visitors.js
assets/js/dashboard/stats/graph/top-stats.js
assets/js/dashboard/stats/graph/visitor-graph.js
assets/js/dashboard/util/seconds-since-last-load.js
lib/plausible_web/templates/stats/waiting_first_pageview.html.eex

**Reviewing commit-by-commit suggested**
1. When hovering over the current visitors label in the historical view, show this tooltip:
2. When hovering the current visitors metric container in the realtime view, show this tooltip:
the timer resets when:
1) realtime reports update (on the 'tick' event - shown in the first gif)
2) query changes (e.g. remove a filter - shown in the second gif)

Last updated tooltip

---

lib/sentry_filter.ex

This PR fingerprints DBConnection.Error instances correctly in Sentry.
Ref #2590

Fingerprint DBConnection.ConnectionError in Sentry

---

test/e2e/main.tf

Relaxes the Checkly config to alert after 5 minutes of downtime so it's less sensitive.
Ref: https://registry.terraform.io/providers/checkly/checkly/latest/docs/resources/check_group#nestedblock--alert_settings--time_based_escalation

Make checkly alert after 5 minutes of downtime

---

lib/mix/tasks/send_pageview.ex

Adds `-- event` and `--props` variables to `mix send_pageview`. I added this in order to test and verify https://github.com/plausible/analytics/pull/2589#pullrequestreview-1253561670 manually.

Support custom events and props in mix send_pageview

---

assets/js/dashboard/stats/graph/visitor-graph.js

This PR fixes a bug introduced in https://github.com/plausible/analytics/pull/2560. For a reproduction of the bug, go to [this dashboard URL](https://plausible.io/plausible.io?goal=Signup&props=%7B%22logged_in%22%3A%22false%22%7D&period=realtime) and remove the `Signup.logged_in is false` filter. After doing so:
- The graph disappears (main-graph API request returns 500)
- An error is shown in the console: `ApiError: ** (CaseClauseError) no case clause matching: :undefined`
This is because `metric` becomes undefined in the `VisitorGraph` state when setting it to `topStatLabels[0]` [on this line](https://github.com/plausible/analytics/blob/b6349df475a17c8fdc3a30cdeace18e88b29c52d/assets/js/dashboard/stats/graph/visitor-graph.js#L386) (if `topStatLabels` is an empty array).
This PR makes …

Fix metric undefined

---

lib/plausible/geo.ex

This commit stops logging `{:invalid_address, "ip"}` errors. This reduces noise on Sentry, that is capturing error logs. Other errors are still logged.

Stop logging invalid_address errors from Locus

---

lib/plausible/sites.ex
lib/plausible_web/controllers/api/external_sites_controller.ex
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/templates/site/new.html.eex
lib/sentry_filter.ex
test/plausible_web/controllers/site_controller_test.exs

This PR introduces the following changes:
- Domains with existing events cannot be created; either asynchronous deletion is in progress or support intervention is necessary.
- I found user-facing code presenting a warning when site limit is reached, but it was never displayed (raw 4xx error page was returned). It is now shown when applicable:
- The whole site creation process is wrapped with a single Postgres transaction
- Some tests were naively misusing `Repo.exists?` so that it always evaluated to true - this has been fixed

Communicate site creation edge cases to the users

---

assets/tailwind.config.js
lib/plausible_web/views/stats_view.ex

Fixes https://github.com/plausible/analytics/issues/2514
This PR fixes the class name used for embedded dashboards and includes it in a safelist to avoid purging.

fix class name typo and include it in safelist

---

Makefile

This PR adds a missing whitespace in `clickhouse-ci`'s docker command.

fix clickhouse-ci rule in Makefile

---

CHANGELOG.md
lib/plausible/stats/base.ex
test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs

This PR fixes https://github.com/plausible/analytics/issues/1666. The bug was that we were not querying the CollapsingMergeTree table engine correctly, hence the number of pageviews (also custom events) was wrongly inflated when looking at recent periods (`today`, `realtime`).
As the 'sessions' table is using the CollapsingMergeTree engine, we have to select session_id's distinctively in the join subquery. Otherwise we will get multiple rows (with sign -1 and 1) as long as the background merge hasn't happened.

Fix returning more pageviews with a visit property filter

---

assets/js/dashboard/stats/graph/date-formatter.js

This PR fixes the date parsing in the main graph time buckets. The timestamps returned by the API are in `site.timezone`. We should not parse them as UTC.
Here's a GIF showing how it currently behaves. I am in UTC +02, which is why from 2AM (the UTC midnight) the date is changed from 16 -> 17 Jan:
After this change:

parse date labels by local timezone instead of UTC

---

lib/plausible_web/templates/stats/site_locked.html.eex
test/plausible_web/controllers/stats_controller_test.exs

Some changes to be more consistent with the emails we send. Also "valid" subscription rather than "active" subscription fits better for the different cases where this screen is shown

Some changes to the "locked site" copy

---

lib/plausible_web/templates/site/settings_danger_zone.html.eex

The idea is to:
1. Show a transfer site ownership message to owners of the site only. This will make ownership transfer feature more discoverable. Will also help people transfer ownership of a site rather than deleting the whole thing when that makes more sense
2. Add a note that site deletion is a delayed operation
3. Make some other tiny copy changes
What did I break? :)

Changes to the site settings danger zone

---

config/runtime.exs
lib/plausible/purge.ex
lib/plausible/site/removal.ex
lib/plausible_web/controllers/api/external_sites_controller.ex
lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/templates/site/settings_danger_zone.html.eex
lib/workers/stats_removal.ex
test/plausible/purge_test.exs
test/plausible/site/site_removal_test.exs
test/support/test_utils.ex

This PR implements stats/site removal so that the race condition pictured below is mitigated:
Ever since https://github.com/plausible/analytics/pull/2605 was introduced, we've been observing increased frequency of customer support inquiries. This PR along with https://github.com/plausible/analytics/pull/2629 is expected to improve the situation.
Going forward we'll have to manage clickhouse mutations in a smarter way but this is currently out of scope.

Delay stats deletions

---

CHANGELOG.md
assets/js/dashboard/stats/graph/graph-util.js
assets/js/dashboard/stats/graph/top-stats.js
assets/js/dashboard/stats/graph/visitor-graph.js

This PR removes the ability to collapse the main graph. The graph collapsed whenever `metric` was a falsy value (`undefined`, `null`, `""`). I removed all code related to that. `metric` should default to `visitors` always.
We want to add new items to top stats, and this PR will make it easier to change it. Also, there's currently a bug where top stats is randomly collapsing, which should be fixed by this PR.
This pull request also fixes a bug where the graph wasn't fading out when changing metrics.
[preview.webm](https://user-images.githubusercontent.com/5093045/215574524-83b307ce-8dd8-4130-952b-c7ff7f748acf.webm)

Remove the ability to collapse the main graph + transition bug fix

---

lib/plausible_web/controllers/error_report_controller.ex
test/plausible_web/controllers/error_report_controller_test.exs

This PR makes sure no e-mail is sent when the users submit feedback with less than 5 characters.

Prevent error reports from being sent with short feedback

---

config/runtime.exs

Update sentry server_name handling.
Our infrastructure now sets the correct hostname instead of the mutable container name.
The changes introduced in #2317 to set the APP_HOST env var as server_name also did not have any effect, because we server_name needs to be set as an option (not as a tag).

Update sentry server_name handling

---

lib/plausible_web/controllers/api/external_sites_controller.ex
test/plausible_web/controllers/api/external_sites_controller_test.exs

We've been leaking some internal error details. This PR makes the site creation errors (e.g. due to existing events) human readable.

Better error message on site creation error

---

mix.lock

Ref https://github.com/plausible/clickhousex/pull/21
We need this to have the ability of running enormous admin queries still.

Bump clickhousex (per-query timeout override)

---

lib/plausible/site.ex
lib/plausible/sites.ex
test/plausible_web/controllers/api/external_sites_controller_test.exs
test/plausible_web/controllers/site_controller_test.exs

adding the 48 hour delay in data deletion info to this message too to reduce the number of emails we get

Some changes to the "site taken" copy

---

CHANGELOG.md
assets/js/dashboard/filters.js
assets/js/dashboard/stats/devices/index.js
lib/plausible/stats/base.ex
lib/plausible/stats/breakdown.ex
test/plausible_web/controllers/CSVs/30d-filter-goal/browsers.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/devices.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/operating_systems.csv
test/plausible_web/controllers/CSVs/30d-filter-path/browsers.csv
test/plausible_web/controllers/CSVs/30d-filter-path/devices.csv
test/plausible_web/controllers/CSVs/30d-filter-path/operating_systems.csv
test/plausible_web/controllers/CSVs/30d/browsers.csv
test/plausible_web/controllers/CSVs/30d/devices.csv
test/plausible_web/controllers/CSVs/30d/operating_systems.csv
test/plausible_web/controllers/CSVs/6m/browsers.csv
test/plausible_web/controllers/CSVs/6m/devices.csv
test/plausible_web/controllers/CSVs/6m/operating_systems.csv
test/plausible_web/controllers/api/stats_controller/browsers_test.exs
test/plausible_web/controllers/api/stats_controller/operating_systems_test.exs
test/plausible_web/controllers/api/stats_controller/screen_sizes_test.exs

This PR replaces missing device properties with "(not set)".
Screen size, OS/version, Browser/version are optional, in case they are missing, **(not set)** is displayed in the UI/API/export. Sub-filtering by versions is disabled in the UI in case the Browser/OS are not set.
https://user-images.githubusercontent.com/173738/216993178-0bfb83c3-0408-4e9c-a544-5dcf2d76ca8b.mp4

Replace empty OS/screen size/Browser with `(not set)` in UI/API/exports

---

CHANGELOG.md
config/runtime.exs
test/plausible/config_test.exs

This PR is similar to https://github.com/plausible/analytics/pull/2596 but hardcodes all adapters that bamboo ships with and adds some config tests.

Support alternative mailing services (Mailgun, Mandrill, Sendgrid)

---

assets/js/dashboard/api.js
assets/js/dashboard/comparison-input.js
assets/js/dashboard/historical.js
assets/js/dashboard/query.js
assets/js/dashboard/stats/graph/graph-util.js
assets/js/dashboard/stats/graph/visitor-graph.js
lib/plausible_web/controllers/api/stats_controller.ex
lib/plausible_web/controllers/stats_controller.ex

This pull request adds support for comparing the actual showed period on the main graph with the previous one. This is a first pass and it's hidden under a feature flag because it's not feature complete yet as we want to support other comparison modes.
Next PRs will include some refactoring, especially in the graph-utils.js file which is calling for a split. And after that I'll push comparison modes.
Reviewing commit-by-commit may help understanding some of my decisions.
Not sure if it's worth testing the current behavior as next PRs will include comparison modes (previous period, year over year, custom date).

First pass at Comparisons

---

lib/plausible_web/templates/layout/_flash.html.eex

This PR adds flash `:ttl` to set the duration in ms that flash is shown. Useful for longer messages like in https://github.com/plausible/analytics/pull/2651.
Usage
```elixir
conn
|> put_flash(:ttl, 8000)
|> put_flash(:error, "some long error message")
```

add flash ttl

---

.github/workflows/elixir.yml
Makefile

This PR pins clickhouse-server image to 22.8.13.20-alpine unifromly for `make clickhouse-prod` target and CI. `clickhouse-ci` target becomes redundant so it gets removed.

Bump clickhouse images to 22.8.13.20-alpine (prod/CI)

---

CHANGELOG.md
lib/plausible/stats/breakdown.ex
test/plausible_web/controllers/api/stats_controller/conversions_test.exs

Fixes #1789
Small change to query building to make sure we don't `JOIN` with `meta` more than once.

Fix bug with multiple ARRAY JOIN query

---

CHANGELOG.md
lib/plausible/stats/props.ex
test/plausible_web/controllers/api/stats_controller/conversions_test.exs

At some point we changed which data structures are used for props and filters on the `Plausible.Stats.Query` struct. This PR updates some DB query building code to be aligned with the new format.

Fix unknown bind meta

---

lib/plausible_web/templates/layout/_tracking.html.eex

Context: @cnkk is setting up traffic mirroring for live demo data to staging. This means we'll have some nice real-world data to mess around with in staging.
The mirroring doesn't work at the moment because pageviews from the live demo are missing `domain: "plausible.io"` in the JSON body. In this case the backend falls back to parsing the domain from the `url` parameter instead.
This PR adds an explicit `data-domain` for our own tracking script so that HAProxy can parse it and mirror events that have `domain: "plausible.io"`

Add data-domain to dogfooding script tag

---

Dockerfile

If you are sending email via an SMTP server that requires SSL/TLS, you get this warning printed to the output log:
```
'Authenticity is not established by certificate path validation' 
Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'
```
And no emails are send.
Adding ca-certificats to the runtime image solves this.

Added certs to runtime container to enable SSL for SMTP

---

assets/css/app.css
assets/js/dashboard/stats/graph/visitor-graph.js

This PR is the foundation for displaying additional Top Stat metrics on the dashboard. It replaces the manual (absolute) CSS positioning with relative positioning, which significantly simplifies writing code for a varying number of Top Stat metrics.

Refactor top stats and graph positioning

---

CHANGELOG.md
lib/plausible/stats/imported.ex
test/plausible_web/controllers/api/stats_controller/cities_test.exs

This commit fixes a bug where the city report returned `N/A` entries. The functions that build imported data queries were using SQL `COALESCE`, assuming city data is `NULL` when unknown, when actually its unknown value is `0`.
This commit addresses the problem using SQL `NULLIF` combined with the previous `COALESCE` call. With this change both `0` and `NULL` are treated as unknown.
Since 1cb07efe6dd800c906110858e55a6788cc2cdccf cities can be `NULL`, but previously we saved `0` as unknown.
Closes #1960

Reject unknown imported cities from queries

---

lib/plausible/stats/breakdown.ex
lib/plausible/stats/props.ex
lib/plausible_web/controllers/api/external_stats_controller.ex
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs

Do not throw MatchClauseError when API user supplies a bad property name

Validate property key in breakdown API endpoint

---

lib/plausible/stats/base.ex
lib/plausible/stats/breakdown.ex
lib/plausible/stats/imported.ex

In some cases the query composition code will add `visits` metric to the `SELECT` clause because it's needed for merging with imported data. In order to not confuse this internally used metric with the publicly accessible `visits` metric, this PR separates the two and renames internal use to `__internal_visits`.
cc/ @RobertJoonas

Refactor visits metric internals

---

.github/workflows/elixir.yml
test/workers/import_google_analytics_test.exs

Minor change to GitHub action workflow that will make the run fail on uncaught log output. ExUnit comes with tools to handle (and test) logs: 
- https://hexdocs.pm/ex_unit/1.14.3/ExUnit.CaptureLog.html 
- https://hexdocs.pm/ex_unit/1.12.3/ExUnit.Case.html#module-known-tags

Fail the CI if tests emit log errors/warnings

---

assets/js/dashboard/stats/graph/graph-util.js

This PR refactors the graph dataset building functions into three separate functions, one for each plot: main plot, comparison plot, and dashed plot. Additionally, I fixed a bug where some period + interval combinations were not working properly with comparisons. This is because `present_index` is not available in every period, e.g. Last Month. Reviewing commit-by-commit may help :)
Preview of the graph working with the dashed part and comparisons after this pull request:

Refactor: Graph Dataset functions

---

assets/js/dashboard/stats/graph/visitor-graph.js

Previously, the graph element was overlapping with other UI elements such as the period input. This commit fixes this issue by setting the z-index of the graph element to 0, which moves it behind other elements in the stacking order.

Fix graph element z-index

---

lib/plausible_web/controllers/stats_controller.ex
test/test_helper.exs

This makes sure no `MIX_ENV` checks are done in the runtime.

Don't rely on Mix.env check in runtime

---

priv/repo/migrations/20230301095227_add_native_stats_start_date.exs

This adds a `native_stats_start_at` pointer to sites so that we can calculate left stats boundary - "the beginning of time" for native stats.

Migration: native_stats_start_at

---

lib/plausible/site.ex
lib/plausible/site/admin.ex
test/plausible/site/admin_test.exs

Recently added `native_stats_start_date` needs to be adjusted when transferring data between domains.

Update native stats start date when transferring

---

lib/plausible/stats/aggregate.ex
lib/plausible/stats/base.ex
lib/plausible/stats/breakdown.ex
lib/plausible/stats/timeseries.ex
lib/plausible/stats/util.ex
lib/plausible_web/controllers/api/external_stats_controller.ex
test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs

This PR adds a new `pages_per_visit` metric to two endpoints in the Stats API:
* `api/v1/stats/aggregate`
* `api/v1/stats/timeseries`
Supporting the metric in the breakdown endpoint is out of scope.
> Reviewing commit by commit suggested. Comments in-line.

Add new `Pages / Visit` metric to Stats API Aggregate and Timeseries

---

assets/js/dashboard/api.js
assets/js/dashboard/comparison-input.js
assets/js/dashboard/query.js
lib/plausible/stats/comparisons.ex
lib/plausible/stats/query.ex
lib/plausible/stats/timeseries.ex
lib/plausible_web/controllers/api/external_stats_controller.ex
lib/plausible_web/controllers/api/stats_controller.ex
lib/workers/send_email_report.ex
test/plausible/stats/comparisons_test.exs
test/plausible_web/controllers/api/stats_controller/main_graph_test.exs

This pull request adds support for multiple comparison modes, changes the comparison checkbox to a combobox, and implements the year over year / last year comparison mode. The feature is still behind a feature flag.

Implement "Year over Year" comparison mode

---

lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs

This PR fixes a bug where the Top Stats crashed, trying to calculate percent difference for goal filtered data.

Fix a bug in percent change calculation

---

assets/js/dashboard/stats/graph/top-stats.js
lib/plausible/stats/imported.ex
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs

The current behavior is that we don't display this metric at all if imported data is displayed.
This PR fixes the bug where the new `views_per_visit` metric is not displayed when imported data is shown on the dashboard. This adds a new function clause to select this metric as well, when imported stats are being merged with native data.
However, the new function simply fetches the metric from native Plausible tables (since this metric is not imported from GA). To make it clear to the user, the metric tooltip will display the message "_Based only on native data_", when the visible stats include GA data.
That means, for example, when we're viewing a period that only has GA data, the behavior will be this (see video):
https://user-images.githubusercontent.com/56999674/224135238-4b47eabe-bb89-4 …

Bug fix - show `views_per_visit` when stats include imported data

---

lib/plausible/site.ex
test/plausible_web/controllers/site_controller_test.exs

Closes https://github.com/plausible/analytics/issues/2725

Disallow site creation with insufficient input

---

CHANGELOG.md
assets/js/embed.host.js
lib/plausible_web/views/stats_view.ex

Adds a default `1.5rem` padding to embedded dashboards. This allows enough space for the shadows to render properly.
Fixes https://github.com/plausible/analytics/issues/1954
As a small improvement, also configures `iframe-resizer` with `checkOrigin: false`. This seems to have no effect on the actual behaviour but gets rid of an error log in console:

Embedded dashboard fixes

---

lib/plausible/site/cache.ex
test/plausible/site/cache_test.exs

Without addressing the asynchronous start just yet, this makes it less noisy in sentry in case of startup race conditions

Capture no_cache sentry messages together

---

lib/plausible/site/admin.ex

This PR reverts changes to `admin.ex` as they are no longer necessary.

revert admin.ex changes

---

lib/plausible/stats/aggregate.ex
lib/plausible/stats/base.ex
lib/plausible/stats/filter_parser.ex
lib/plausible/stats/filters.ex
lib/plausible/stats/props.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible/stats/filter_parser_test.exs
test/plausible/stats/filters_test.exs
test/plausible_web/controllers/api/stats_controller/conversions_test.exs
test/plausible_web/controllers/api/stats_controller/pages_test.exs
test/plausible_web/controllers/api/stats_controller/screen_sizes_test.exs
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs

Adds support for `member` filter type for UI filters.

Support multiple filters - backend

---

mix.exs
mix.lock

This PR updates the github reference for `:chto` dependency to point to https://github.com/plausible/chto (ruslandoga/chto would still work for awhile)

use github: plausible/chto for chto

---

mix.lock

This PR updates `chto` to fix the missing `telemetry_metadata[:source]` issue.
Relevant: https://github.com/plausible/chto/pull/25

update chto to fix missing source in telemetry events

---

assets/js/dashboard/stats/modals/filter.js

Small bugfix where the backend would return 500 when querying for filter suggestions for `city` with `is_not` filter type.

Remove empty filters from suggestions query

---

lib/plausible_web/controllers/api/external_sites_controller.ex
lib/plausible_web/templates/site/new.html.eex
test/plausible_web/controllers/api/external_sites_controller_test.exs

We need to disable new site creation for a short period of time (max 1 hour) while we migrate the Clickhouse database.

Temporarily disable site creation

---

lib/plausible_web/templates/site/settings_general.html.eex

Removing the extra button panel and aligning buttons to the left, just like everywhere else.
Also displaying an inactive field with current domain in domain change panel.

Tweak general settings display

---

lib/plausible/site.ex
test/plausible_web/controllers/site_controller_test.exs

Small fix up to #2803 - the trigger-raised constraint is now checked on site creation too.

Render an error on site creation with `domain=domain_changed_from`

---

config/runtime.exs

This PR adds `transport_opts: [keepalive: true, show_econnreset: true]` to ClickHouse repos.
Relevant: https://github.com/plausible/ch/pull/23
```elixir
iex> :inet.i
iex> %Connection{} = conn = :sys.get_state(pid(0,1935,0))
iex> conn.mod_state.opts[:transport_opts]
[keepalive: true, show_econnreset: true]
iex> socket = port(0, 152)
iex> :inet.getopts(socket, [:keepalive, :show_econnreset])
{:ok, [keepalive: true, show_econnreset: true]}
```

add transport opts to clickhouse repos

---

assets/js/dashboard/stats/conversions/index.js
assets/js/dashboard/util/filters.js
lib/plausible/stats/filters.ex
test/plausible/stats/filters_test.exs

With the recent addition of the `member` filter type using pipes, goals that contain pipes don't always work. Demo of a case that's broken on master but fixed with this PR:
https://user-images.githubusercontent.com/3731516/229509412-3a240cf0-0949-4c06-8c93-a85029779a2d.mov
- I don't think it's needed since it's a quick fix for something that was released very recently.

Escape pipes in goal names

---

assets/js/dashboard/api.js
assets/js/dashboard/comparison-input.js
assets/js/dashboard/datepicker.js
assets/js/dashboard/query.js
assets/js/dashboard/stats/graph/date-formatter.js
assets/js/dashboard/stats/modals/google-keywords.js
assets/js/dashboard/stats/modals/referrer-drilldown.js
assets/js/dashboard/util/date.js
assets/package-lock.json
assets/package.json

Fixes the two known frontend timezone issues. The bugs are caused by javascript's `new Date` constructor assuming that the dates it is parsing is in the local timezone to the browser. In fact the server always returns dates in the timezone specified by `site.timezone` regardless of what the local time for the browser is.
What we need is for the frontend date handling to completely forget about timezones and just treat each datetime from the backend as if it was a `NaiveDateTime`. This type does not exist in Javascript, but there is a way to force the built-in Date object to ignore timezones by changing the constructor to:
```javascript
new Date(Date.UTC(..parts))
```
and getters to 
```javascript
date.getFullYear -> date.getUTCFullYear
date.getDate -> date.getUTCDate
// etc..
```
We could …

Frontend timezone issues

---

lib/plausible/goals.ex
lib/plausible_web/controllers/api/external_sites_controller.ex
priv/repo/migrations/20230406110926_associate-goals-with-sites.exs
test/plausible/goals_test.exs
test/plausible_web/controllers/api/external_sites_controller_test.exs
test/plausible_web/controllers/site_controller_test.exs

This PR temporarily disables goal creation and partially migrates postgres as per #2828

Migrate and freeze goals creation

---

lib/plausible/goal/schema.ex
lib/plausible/goals.ex
lib/plausible/sites.ex
lib/plausible/stats/breakdown.ex
lib/plausible/stats/filter_suggestions.ex
lib/plausible_web/controllers/api/external_sites_controller.ex
lib/plausible_web/controllers/site_controller.ex
priv/repo/migrations/20230410070312_fixup_goals_sites_assoc.exs
test/plausible/goals_test.exs
test/plausible_web/controllers/api/external_sites_controller_test.exs
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
test/plausible_web/controllers/api/stats_controller/conversions_test.exs
test/plausible_web/controllers/site_controller_test.exs
test/plausible_web/controllers/stats_controller_test.exs

With #2803, we've overlooked the fact that goals were being created with `domain` instead of site's foreign key. This PR addresses that. Requires a staged postgres migration partially introduced in #2833 first - only then I'll rebase this PR and re-enable goals creation.

Associate goals with sites, not domains

---

assets/js/dashboard/comparison-input.js
assets/js/dashboard/datepicker.js
assets/js/dashboard/stats/graph/top-stats.js
assets/js/dashboard/stats/graph/visitor-graph.js
assets/js/dashboard/util/date.js
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs

This pull request adds more details to top stats when comparisons are enabled. The details are: the original query date range, the comparison query date range, and the comparison values.
Preview:
[preview.webm](https://user-images.githubusercontent.com/5093045/228620723-910c9f82-b97c-46c8-bd9f-d27eb26f9d42.webm)

Show detailed comparison dates in top stats

---

assets/js/dashboard/api.js
assets/js/dashboard/comparison-input.js
assets/js/dashboard/query.js
lib/plausible/stats/comparisons.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible/stats/comparisons_test.exs

This pull request adds support for the match day of the week feature for comparisons.
When this option is enabled, the comparison query is shifted to start on the same day of the week as the source query, rather than on the exact same date. For example, if the source query starts on Sunday, January 1st, 2023 and the `year_over_year` comparison query is configured to match day of the week, it will be shifted to start on Sunday, January 2nd, 2022 instead of Saturday, January 1st, 2022.
Preview:
[output.webm](https://user-images.githubusercontent.com/5093045/231193472-c39b29a1-375f-4711-8b49-354ed90a5495.webm)

Match day of the week feature for comparisons

---

lib/plausible_web/plugs/authorize_stats_api.ex

this should make it clearer to people that they can get more API capacity when they encounter the "Too many API requests" error

Adding a note to contact us for more API calls

---

assets/js/dashboard/comparison-input.js
assets/js/dashboard/datepicker.js

This pull request removes the 'vs.' label and the date picker arrows when comparing on smaller devices.

Improve comparisons UI for mobile devices

---

assets/js/dashboard/comparison-input.js
assets/js/dashboard/datepicker.js
assets/js/dashboard/util/date.js

This commit fixes a bug where picking a specific date in custom range takes you to the stats of the day before.
This was caused because Flatpickr returns a Date instance, and we were trying to parse this Date instance into day.js using the `utc` function, assuming it was a ISO-8601 string.
This commit fixes it by casting Date into dayjs using the `dayjs` function instead of `utc`.

Fix date picker shifting day bug

---

assets/js/dashboard/stats/graph/visitor-graph.js

Add more spacing for graph controls

---

lib/plausible/stats/comparisons.ex
lib/plausible/stats/query.ex
lib/plausible_web/controllers/api/stats_controller.ex
priv/repo/seeds.exs
test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
test/support/test_utils.ex

This commit fixes a bug where comparisons would not work with imported data. This is because comparisons copies the source query and modifies the dates only, where it should reevaluate if there is imported data for the new comparison date range.
Closes #2870

Prevent overwriting with_imported when comparing

---

assets/js/dashboard/comparison-input.js
assets/js/dashboard/datepicker.js
assets/js/dashboard/stats/graph/top-stats.js
lib/plausible_web/controllers/api/stats_controller.ex
lib/plausible_web/controllers/stats_controller.ex
priv/repo/seeds.exs
test/plausible/imported/imported_test.exs
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs

This pull request removes the comparisons feature flag, making it visible to all users. It also removes percentages from top stats in default view, leaving those for the comparison view only.

Prepare Comparisons for release

---

CHANGELOG.md
tracker/src/customEvents.js
tracker/test/fixtures/tagged-event.html

A small changes to the regex that matches with the `tagged-events` classnames. Allowing  to write `--` instead of `=` will make the integration easier for CMSs that change the `class` attribute format after adding it from the UI (for example Webflow).

Improve tagged events

---

CHANGELOG.md
lib/plausible/stats/aggregate.ex
lib/plausible/stats/base.ex
lib/plausible/stats/breakdown.ex
lib/plausible/stats/timeseries.ex
lib/plausible_web/controllers/api/external_stats_controller.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs

* When querying for `bounce_rate`, treat a page filter as entry page filter
* Stop displaying the `views_per_visit` metric in Top Stats when a page filter is applied
* Disallow querying for `views_per_visit` with a page filter in the Stats API

Treat page filter as entry page filter only for bounce rate

---

lib/plausible_web/controllers/api/stats_controller.ex
priv/repo/seeds.exs
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs

This commit fixes a bug where unique conversions and the unique visitors of the previous period in comparison view were always the same.
Fixes https://github.com/plausible/analytics/discussions/532#discussioncomment-5760187

Fix conversions top stats bug when comparing

---

.github/workflows/build-public-images.yml
Dockerfile

This PR adds `ERL_FLAGS=+JPperf true` to public image builds to stop it from segfaulting in qemu when building for arm64. More info for why it works: https://github.com/erlang/otp/pull/6340 (once v26 is released, we can switch to `+JMsingle bool`)

fix qemu arm64 builds

---

assets/js/dashboard/stats/graph/top-stats.js
assets/js/dashboard/stats/graph/visitor-graph.js

This commit brings back percentage arrows to default view. These were removed by the recent comparisons work, and we've had reports of people missing it. As we haven't noticed any difference in performance, I've decided to revert that change.

Add percentage difference back to default view

---

lib/plausible/ingestion/request.ex
lib/plausible/stats/filter_parser.ex
lib/plausible/stats/filters.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible/ingestion/request_test.exs
test/plausible/stats/filter_parser_test.exs
test/plausible_web/controllers/api/stats_controller/conversions_test.exs
test/plausible_web/controllers/api/stats_controller/regions_test.exs
test/plausible_web/controllers/api/stats_controller/suggestions_test.exs

This PR improves incoming request validation as per sentry reports where scanners such as https://github.com/sqlmapproject/sqlmap are being run against our endpoints.

Harden API input validation

---

priv/repo/migrations/20230503094245_add_event_prop_allowlist_to_site.exs

This PR only adds a new migration file that adds a field needed to stop showing garbage properties on the dashboard.
For all sites that have this field with the default value of `[]`, we will show all properties that exist in Clickhouse. However, if at least one element exists in that array, we show only the props that are included in that array.
**EDIT: I think in the end it makes sense to keep the default value for this field as `null`.**

Postgres migration to add `allowed_event_props` field to `site`

---

priv/ingest_repo/migrations/20230509124919_clean_up_old_tables_after_v2_migration.exs

This PR adds a housekeeping migration to drop the unused tables ref: #2868 
#2825 #2777

Drop events/sessions tables after V2 migration

---

lib/plausible/site.ex
lib/plausible/site/admin.ex
lib/plausible/stats/custom_props.ex
lib/plausible/stats/filter_suggestions.ex
priv/repo/migrations/20230503094245_add_event_prop_allowlist_to_site.exs
test/plausible_web/controllers/api/stats_controller/conversions_test.exs
test/plausible_web/controllers/api/stats_controller/suggestions_test.exs

This PR builds on top of https://github.com/plausible/analytics/pull/2894 that contains the migration that should be run on production **before this PR is deployed**.
This PR changes the behavior of returning custom properties for:
* property name suggestions
* goal conversions:
The properties returned will now be filtered by the custom allowlist, that can be defined for each site in the CRM. For example, if we were to set the allowlist to `author, logged_in`, the above screenshots would only contain those property names - nothing else.

Filter out garbage props by `site.allowed_event_props`

---

lib/plausible/stats/custom_props.ex
test/plausible_web/controllers/api/stats_controller/conversions_test.exs

The number of bindings in the query passed to `maybe_allowed_props_only` depends on whether there are session filters applied or not. This PR adds a test for that case and fixes the bug by using the `...` syntax in Ecto.Query to only get the last binding that we actually want.

Fix a bug with query bindings

---

lib/plausible/goal/schema.ex
lib/plausible/ingestion/request.ex
test/plausible/goals_test.exs
test/plausible/ingestion/request_test.exs
test/plausible_web/controllers/api/external_controller_test.exs

This pull request adds constraints on user input values during ingestion. The purpose of this PR is to filter out unrealistic or invalid inputs. More comments about each limit inline.

Limit ingestion payload size

---

CHANGELOG.md
lib/plausible/stats/aggregate.ex
lib/plausible/stats/comparisons.ex
lib/plausible/stats/query.ex
lib/plausible/stats/util.ex
lib/plausible_web/controllers/api/external_stats_controller.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible/stats/comparisons_test.exs
test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs

This PR fixes a bug where a Stats API query responded with a 500 error message, because the original query was fetching stats without imported data, but the comparison query tried to fetch stats with imported data.
It also adds support for querying imported data from the Stats API aggregate endpoint. Adding the `with_imported` option to other endpoints (breakdown and timeseries is out of scope of this PR).

Support `with_imported=true` in Stats API aggregate

---

CHANGELOG.md
lib/plausible_web/plugs/favicon.ex
lib/plausible_web/templates/site/index.html.eex
test/plausible_web/plugs/favicon_test.exs

Domains can include slashes, e.g. I have created a site with the "domain" "vangberg.github.io/adventures-in-bioimaging". I am not sure if you are supposed to be able to do that, but it does seem to work.
One thing that does not work, is that the favicon is broken on "My sites" (but not on the stats page for the site itself):
The culprit is that the "domain" is not being escaped before being used in the URL for the image tag. This is done in other parts of the codebase, e.g. in the `SiteSwitcher` component:
https://github.com/plausible/analytics/blob/f29d07a49e91ecfe0aa87de1b4b5c011e26c722a/assets/js/dashboard/site-switcher.js#L11
This pull requests adds URL escaping to the domain in the site index template.

Escape domain when creating URL for favicon

---

CHANGELOG.md
tracker/src/plausible.js

This PR fixes tracker behavior in the situation where an event is ignored. If a callback function is provided within the `options`, we still want to call that, even when the event is ignored.
I'm almost sure that this fixes https://github.com/plausible/analytics/issues/2940.

Fix tracker bug - call callback function when ignoring event

---

lib/plausible/billing/billing.ex
test/plausible/billing/billing_test.exs

Stop throwing Sentry error when subscription cannot be found in Paddle webhook handler.

Ignore missing subscription on update

---

lib/plausible_web/templates/layout/_footer.html.eex

Changes to keep the in-app footer consistent with the main site

Keep the in-app footer consistent with the main site

---

lib/plausible/auth/api_key.ex
lib/plausible_web/templates/auth/new_api_key.html.eex
priv/repo/migrations/20230516131041_add_unique_index_to_api_keys.exs
test/plausible_web/controllers/auth_controller_test.exs

Adds unique constraint to `api_keys` on the `[:user_id, :key_hash]` field combination. This protects from duplicate API keys being created. The UI provides appropriate feedback:

Add unique constraint to api keys

---

assets/tailwind.config.js

Fixes a bug that was introduced in https://github.com/plausible/analytics/pull/2744
Embedded dashboards used to be limited to `max-w-screen-lg` by default. I changed it to `max-w-screen-xl` to provide more space for shadows. But I forgot to update the Tailwind safelist which made the class not apply at all in production.

Limit width of embedded dashboards by default

---

lib/plausible/auth/auth.ex
lib/plausible_web/controllers/auth_controller.ex
test/plausible_web/controllers/auth_controller_test.exs

Reduces the possibility of reaching an inconsistent state with the database. Extracting the `Plausible.Auth.delete_user/1` function also allows us to easily retry failed deletions manually from iex.

Wrap user deletion in DB transaction

---

lib/plausible/stats/base.ex

We have a sampling-related bug which seems to be caused by a query like this:
```sql
SELECT sum(sign) * any(_sample_factor) FROM sessions_v2 SAMPLE 20_000_000 INNER JOIN (SELECT DISTINCT session_id FROM EVENTS SAMPLE 20_000_000);
```
Adding `_sample_factor` to the SELECT part of the right side seems to fix the bug:
```sql
SELECT sum(sign) * any(_sample_factor) FROM sessions_v2 SAMPLE 20_000_000 INNER JOIN (SELECT DISTINCT session_id, _sample_factor FROM EVENTS SAMPLE 20_000_000);
```
This is very hard to test with unit tests, the fix was confirmed using real data with >10m records.
Passing `_sample_factor` from the right side to left seems to help Clickhouse keep the sampling context intact and inflate the numbers correctly on the other side of the join.
In the future we should review our …

Fix issue with sampling and joins

---

lib/plausible/stats/base.ex
lib/plausible/stats/interval.ex
lib/plausible/stats/query.ex
test/plausible/stats/query_test.exs

This PR does not change behaviour much, only:
* refactors the Query module
* whenever a `sample_threshold=<value>` query param is present in an internal dashboard API query, we will cast that string value into an integer and use that as the sample threshold. As opposed to blowing up like before, when trying to use the `string` type as a sample threshold

Allow setting sample_threshold in dashboard API queries

---

priv/ingest_repo/migrations/20230509124919_clean_up_old_tables_after_v2_migration.exs

This PR wraps v1 events and sessions tables drop in a conditional block.

skip v1 table drop in self-host

---

CHANGELOG.md
config/runtime.exs
test/plausible/config_test.exs

This PR adds `MAILGUN_BASE_URI` support as suggested in https://github.com/plausible/analytics/pull/2649#issuecomment-1550467512

add MAILGUN_BASE_URI

---

assets/js/dashboard/stats/modals/referrer-drilldown.js
lib/plausible_web/templates/site/index.html.eex

Quick fix for `/sites` showing all default favicons
* Fix favicon request URLs (remove doble ".ico")
* Use the favicon.ex proxy in referrer drilldown
* Fix the request path in referrer drilldown

Fix favicon request URLS

---

CHANGELOG.md
lib/plausible_web/controllers/page_controller.ex
lib/plausible_web/templates/page/index.html.eex
lib/plausible_web/views/page_view.ex
test/plausible_web/controllers/page_controller_test.exs

This PR adds a landing page in dev and self-hosted setups.
That page shows up when the user is not logged in and makes a `GET /` request.

add landing page

---

lib/plausible/ingestion/request.ex
test/plausible/ingestion/request_test.exs
test/plausible_web/controllers/api/external_controller_test.exs

Currently when an event is sent with a `name` field that is not a String, we run into an Ecto error:
```
CaseClauseError anonymous fn/5 in Ecto.Changeset.validate_length/3
```
This PR makes 2 changes:
1. Accept numeric event names (like `404`)2. 
2. Return validation error if event name is not a String or Integer

Fix event name validation

---

lib/plausible_web/controllers/api/external_stats_controller.ex

We're currently hardcoding `sample_threshold=infinity` in the Stats API. This PR removes the hardcoding so it can be configured, and applies a standard sampling threshold of 20m.

Enable sampling in the Stats API

---

lib/plausible_web/controllers/stats_controller.ex

This PR removes `views_per_visit_metric` flag: https://github.com/plausible/analytics/pull/2996#discussion_r1213557200

remove views_per_visit_metric flag

---

CHANGELOG.md
assets/js/dashboard/filters.js
lib/plausible_web/controllers/stats_controller.ex

This PR enables custom dimension filter for self-hosters.
Relevant discussion: https://github.com/plausible/analytics/discussions/2984
This PR is based on https://github.com/plausible/analytics/pull/2898

remove custom_dimension_filter feature and views_per_visit_metric flags

---

lib/plausible/ingestion/request.ex
test/plausible/ingestion/request_test.exs

This commit adds an upper bound limit to custom props. It fails silently and trims the list instead of dropping the event.
Documentation update PR: https://github.com/plausible/docs/pull/402

Trim prop list to 30 items during ingestion

---

CHANGELOG.md
config/runtime.exs
lib/plausible_web/controllers/auth_controller.ex

This PR disables registration in self-hosted setups. Note that the first user is allowed to register anyway (https://github.com/plausible/analytics/pull/2357).

disable registration by default in self-hosted setups

---

assets/js/dashboard/stats/behaviours/conversions.js
lib/plausible_web/plugs/tracker.ex
tracker/compile.js
tracker/src/plausible.js
tracker/test/fixtures/revenue.html
tracker/test/revenue.spec.js

This pull request adds revenue columns to Goal Conversions on the dashboard. The columns are only displayed when there is revenue data for a goal in the list. It also adds a new script extension to send revenue data.

Revenue tracking: goal conversions and tracker script

---

CHANGELOG.md
lib/plausible/stats/base.ex
test/plausible_web/controllers/api/stats_controller/conversions_test.exs

Fixes DB queries in case where multiple wildcard page goal filters are used, but no custom event goal is included in the filter.

Fix queries with wildcard goals

---

lib/plausible/goals.ex
lib/plausible/ingestion/event.ex
lib/plausible/site/cache.ex
lib/plausible/site/gate_keeper.ex
test/plausible/goals_test.exs
test/plausible/site/cache_test.exs
test/plausible/site/gate_keeper_test.exs
test/support/data_case.ex

Revenue goals need the cached site struct during ingestion to get the goals name and currency. This cache lookup is not necessary as `GateKeeper.check/1`, which is called first in the ingestion pipeline, could already return the site struct from the cache.
This commit changes `GateKeeper.check/1` to return the site struct instead of the site ID. Moreover, this commit changes the ingestion pipeline to avoid calling the sites cache twice.
Related: https://github.com/plausible/analytics/pull/2957#discussion_r1203921549

Pass cached site struct down the ingestion pipeline

---

.gitignore

This PR updates .gitignore with docker volume dirs so they don't pollute git status.

Update gitignore with docker volume dirs

---

test/workers/import_google_analytics_test.exs

This commit tries to fix a flaky test that's failing often on CI. ClickHouse deletes are asynchronous and can take some time before it takes effect. The `eventually/1` function retries the assertion with a backoff.

Add eventually/1 call to flaky test

---

CHANGELOG.md
lib/plausible/stats/query.ex
test/plausible_web/controllers/api/stats_controller/main_graph_test.exs

This commit fixes a bug where timeseries queries - such as the main graph - would fail with imported data in realtime mode. Realtime mode `date` field is not actually a date, but minutes from now. This would cause the imported tables join to fail with this error:
```
(Ch.Error Code: 53. DB::Exception: Can't infer common type for joined
columns: date: Int64 at left, s1.date: Date at right. There is no
supertype for types Int64, Date because some of them are
Date/Date32/DateTime/DateTime64 and some of them are not.
(TYPE_MISMATCH)
```
This commit removes imported data from realtime queries, as it doesn't make sense to include it. Imported data does not have time precision, and would only appear in the first day the data was imported anyways.

Set with_imported=false in realtime mode

---

tracker/src/customEvents.js
tracker/test/fixtures/revenue.html
tracker/test/revenue.spec.js

This commit adds two special classes for tracking revenue with tagged events. The following example sends an event with revenue data when the tracker script has revenue and tagged-events script extensions:
```html
<button class="plausible-revenue-amount=10.29 plausible-revenue-currency=EUR"></button>
```

Add tagged events support for revenue goals

---

Dockerfile

This reverts commit c19a51efb0dbe2da0f8dede8e3d5df167bd7fba1.
@cnkk we have two alpine image references in our Dockerfile and only one got updated. This may lead to unpredictable build oddities.

Pin alpine versions to 3.18.0

---

lib/plausible/stats/breakdown.ex
test/plausible_web/controllers/api/stats_controller/conversions_test.exs

This commit fixes a bug where performing a breakdown by goal with revenue metrics would return data for both event goals and pageview goals. However, revenue data is only applicable for event goals as they hold currency data.
To fix the bug, this commit removes revenue metrics from the pageview breakdown query.

Remove revenue metrics from pageview goal query

---

assets/js/dashboard/stats/graph/top-stats.js
lib/plausible/stats/aggregate.ex
lib/plausible_web/controllers/api/stats_controller.ex
priv/repo/seeds.exs
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs

This PR adds revenue data to top stats. Average and total are displayed when filtering by a revenue goal (or many if they have the same currency set).

Add revenue metrics to top stats

---

lib/plausible/goal/schema.ex
lib/plausible_web/templates/site/new_goal.html.eex
lib/plausible_web/templates/site/new_goal.html.heex
test/test_helper.exs

This pull request changes the UI for revenue goals, replaces the select box with a toggle, and adds a notice. It also polishes up the goal creation UI in general to have the same font sizes and weights compared to the rest of the page.
https://github.com/plausible/analytics/assets/5093045/d43b8d88-b8e3-470b-b33d-e620e94fee55
Thanks to @RobertJoonas for pairing up with me on this one!

Add notice to revenue goals UI

---

assets/js/liveview/live_socket.js
config/runtime.exs
lib/plausible_web/endpoint.ex
lib/plausible_web/templates/layout/app.html.eex
lib/plausible_web/views/layout_view.ex

This PR allows optional configuration for the live view Base URL

Allow configurable websocket URL for live view

---

assets/js/dashboard/stats/behaviours/funnel.js
config/runtime.exs
lib/plausible_web/endpoint.ex

This is an attempt of enforcing the websocket session authentication within the same root domain, otherwise the socket was unable to retrieve the cookie. Ref #3082 - in case we like to provide a fully qualified `wss://` URL.
I have tested it with the following steps:
1. Remove `BASE_URL` from `config/.env.dev` - otherwise it'll override environment variables 😥
2. Adding the following `/etc/hosts` entries:
```
127.0.0.1 plausible.local
127.0.0.1 ws.plausible.local
```
3. Running `BASE_URL=http://plausible.local:8000 WEBSOCKET_URL=ws://ws.plausible.local:8000 iex -S mix`
4. Accessing funnel settings via `http://plausible.local:8000`
Additionally, this PR sets origin check for the live websocket alone, to prevent Cross-Site WebSocket Hijacking (CSWSH) attacks. The setting has been verified …

Reconfigure live websocket

---

config/runtime.exs
lib/plausible_web/endpoint.ex
lib/plausible_web/plugs/runtime_session_adapter.ex

A follow-up to #3087 - turns out we have to pass the domain explicitly to the Endpoint/Session plug configuration as well. Because, with the existing interface, it can be done only at compile time, we can't rely on the `BASE_URL` that's currently configured in `runtime.exs`.
Another way of tackling this would be to have multiple static configs per `MIX_ENV`, but I think we have enough configuration complexity to deal with.
This PR will inject `:domain` option, at runtime, to the `Plug.Session` calls.

Dynamically set up session domain

---

lib/plausible_web/live/funnel_settings.ex
lib/plausible_web/live/funnel_settings/list.ex
test/plausible_web/live/funnel_settings/funnel_settings_test.exs

Somewhere along the way of rebasing the feature,
the integration tests for deletion were lost.
j/k they were never written 🤡

Bugfix: funnel deletion

---

lib/plausible_web/components/generic.ex
lib/plausible_web/live/funnel_settings.ex

Fix spacing between two notices in funnel settings

---

lib/plausible_web/live/funnel_settings.ex
lib/plausible_web/live/funnel_settings/form.ex

Doesn't make the lv crash when superadmin accesses it. This is only extra measure, the main mount point is already guarded via `PlausibleWeb.AuthorizeSiteAccess` plug in the controller.
I'm allowing myself to skip tests on that one, because it requires env patching.

Enable superadmin access to funnel settings

---

assets/js/dashboard/stats/behaviours/funnel-tooltip.js
assets/js/dashboard/stats/behaviours/funnel.js
lib/plausible/stats/funnel.ex
lib/plausible_web/live/funnel_settings/form.ex
test/plausible/funnels_test.exs
test/plausible_web/controllers/api/stats_controller/funnels_test.exs
test/plausible_web/live/funnel_settings/funnel_settings_test.exs

This PR introduces funnel evaluation during funnel creation, so that it's easier to get a grasp of whether the funnel has been configured properly. The funnel form will now show data similar to the funnel chart with every step selection change updating the result. 
By the way, percentage compaction (i.e. `0` instead of `0.00`) was moved server-side, so that it's consistent across the whole stack. Primitives used for percentage calculation are available in the API anyway, in case clients want to use their own representation.
https://github.com/plausible/analytics/assets/173738/398a8e89-3135-47e1-8d11-b6420464e77f
Dark mode:

Evaluate ephemeral funnels before saving

---

assets/js/dashboard/stats/behaviours/funnel.js
lib/plausible/funnel.ex
test/plausible/funnels_test.exs

This PR enables funnels as large as 8 steps maximum.
https://github.com/plausible/analytics/assets/173738/9ec46399-b0ca-4ae2-8be6-6db04f1d7993

Bump funnel max size to 8 steps

---

assets/js/dashboard/historical.js
assets/js/dashboard/index.js
assets/js/dashboard/realtime.js
assets/js/dashboard/stats/bar.js
assets/js/dashboard/stats/devices/index.js
assets/js/dashboard/stats/locations/index.js
assets/js/dashboard/stats/more-link.js
assets/js/dashboard/stats/pages/index.js
assets/js/dashboard/stats/reports/list.js
assets/js/dashboard/stats/reports/metrics.js
assets/js/dashboard/stats/sources/referrer-list.js
assets/js/dashboard/stats/sources/search-terms.js
assets/js/dashboard/stats/sources/source-list.js

* Make the ListReport React component more configurable so that we could use it for other reports (such as Sources, Goal Conversions, and Prop Breakdown).
* Bugfix - on the live demo, when you set the period to realtime, and then apply a goal filter, then we'll keep fetching the old data (without the goal filter applied) on every consequent realtime tick.
* In the devices reports, keep `visitors` and `%` as separate columns, rather than 
--->

Make the ListReport component more flexible

---

lib/plausible_web/controllers/api/internal_controller.ex
lib/plausible_web/controllers/stats_controller.ex
lib/plausible_web/plugs/no_robots.ex
lib/plausible_web/router.ex
lib/plausible_web/templates/layout/app.html.eex
lib/plausible_web/templates/layout/focus.html.eex
test/plausible_web/controllers/api/internal_controller_test.exs
test/plausible_web/controllers/stats_controller_test.exs
test/plausible_web/plugs/no_robots_test.exs

This PR attempts to cut off robots from browsing dashboard and internal APIs.
We're adding the `meta="robots"` HTML tag to dashboard layouts, `x-robots-tag` to HTTP responses ~~and we're checking the user agent against UAInspector DB with Cachex on top (we're already doing it during the ingestion phase, so the plug isn't installed there)~~.

Prevent robots from looking too much into public dashboards

---

lib/workers/send_email_report.ex
test/workers/send_email_report_test.exs

Small fix preventing the background from crashing when the site is gone by the time it fires.

Fix APP-2NA

---

lib/plausible/stats/imported.ex
test/plausible_web/controllers/api/stats_controller/browsers_test.exs

Sentry error was indicating division by zero at percentage calculation at https://github.com/plausible/analytics/blob/df3a5d6de90f372adad779f3b84444a46ed02fb2/lib/plausible_web/controllers/api/stats_controller.ex#L1270 - this PR ensures no imported data is retrieved if the number of visitors stored is 0 (we probably shouldn't be doing it in the first place but it's kind of late for that 😥).

APP-47C: Filter out GA imported data with no visitors recorded

---

lib/plausible_web/controllers/invitation_controller.ex
test/plausible_web/controllers/invitation_controller_test.exs

This fixes a sentry error on trying to retrieve an already accepted invitation.

Fix APP-46E: accept invitation 2nd click

---

config/runtime.exs

Adds optional support for connect to clickhouse over ipv6. Same as #1661, but for clickhouse.

Allow optional IPv6 for clickhouse repo

---

assets/package-lock.json
assets/package.json

This reverts commit efe0d63b74b6eee5204d092377fd55ab40f2aa95.
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: stylelint-config-standard@24.0.0
npm ERR! Found: stylelint@15.10.1
npm ERR! node_modules/stylelint
npm ERR!   dev stylelint@"^15.10.1" from the root project
npm ERR!   peer stylelint@">=11.0.0" from stylelint-config-prettier@9.0.3
npm ERR!   node_modules/stylelint-config-prettier
npm ERR!     dev stylelint-config-prettier@"^9.0.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer stylelint@"^14.0.0" from stylelint-config-standard@24.0.0
npm ERR! node_modules/stylelint-config-standard
npm ERR!   dev stylelint-config-standard@"^24.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer …
```

Revert "Bump stylelint from 14.1.0 to 15.10.1 in /assets (#3115)"

---

CHANGELOG.md
assets/js/dashboard/stats/locations/map.js

Fixes the bug as described in #3086 
The filter label takes the value from the `country_labels` field and not `country_name`.
By changing the property to `country_labels`, the correct name shows up in the filter

Fix the country filter label when clicking on a country on the map

---

assets/js/dashboard/components/lazy-loader.js
assets/js/dashboard/stats/behaviours/conversions.js
assets/js/dashboard/stats/sources/referrer-list.js
assets/js/dashboard/stats/sources/source-list.js
assets/package-lock.json
assets/package.json

* Refactors LazyLoader to a function component using https://www.npmjs.com/package/react-intersection-observer
* Fixes a bug where the currently used `LazyLoader` did not call the `onVisible` function on page refresh when being scrolled down on the dashboard (screencast of the bug below). Note that the bug happened for me only on Chrome.
https://github.com/plausible/analytics/assets/56999674/3b9e6b2b-ddc8-47fc-ad98-446dad2cd35d

refactor LazyLoader and fix bug

---

assets/js/dashboard/stats/locations/index.js

Quick fix for the bug introduced in https://github.com/plausible/analytics/pull/3078 - we don't actually return the CR metric for cities and regions. Only countries. This tells the React frontend not to expect this metric to be in the response, which will not render the `undefined` values anymore.

fix CR undefined bug

---

assets/js/dashboard/stats/behaviours/conversions.js
assets/js/dashboard/stats/behaviours/money.js
assets/js/dashboard/stats/behaviours/prop-breakdown.js
lib/plausible/stats/breakdown.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/stats_controller/conversions_test.exs

This pull request enables prop breakdown for revenue goals. Revenue metrics are queries when filtering by a revenue goal. Preview:

Add revenue metrics to prop breakdown

---

assets/js/dashboard/stats/behaviours/index.js

This PR fixes small bug when the most recently selected funnel name is rendered in bold even though the user is activating the picker from goals.
Before:
After:

Render funnel name in bold only when funnels tab active

---

assets/js/dashboard/stats/modals/referrer-drilldown.js
assets/js/dashboard/stats/reports/list.js
assets/js/dashboard/stats/sources/referrer-list.js
assets/js/dashboard/stats/sources/source-list.js
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/internal_controller_test.exs
test/plausible_web/controllers/api/stats_controller/sources_test.exs

This PR uses the new more flexible ListReport component in the following "Source" reports:
* All Sources (the `All` tab)
* All UTMs
* referrer URL drilldown (i.e. when filtered by a source)
Also, this changes the `/referrers` endpoint response format and excludes `total_visitors` which was not used anywhere annymore.
This PR **does not attempt** to use ListReport in Search Terms, because of several differences in the behavior:
* list entries do not act as filter links
* only metric we ever show is visitors
* has to know how to render errors such as "Google account not linked" or "Cannot show search terms with a goal filter"

Refactor: Use ListReport component in Sources

---

assets/js/liveview/suggestions_dropdown.js
lib/plausible_web/live/components/combo_box.ex
lib/plausible_web/live/funnel_settings/form.ex
test/plausible_web/live/components/combo_box_test.exs

This commit changes the ComboBox component to allow a `creatable` option. This option enables users to create new options along with choosing existing options.
Preview:
https://github.com/plausible/analytics/assets/5093045/985bf2e5-5b10-42d5-bb2b-e3d08c322c94

Add creatable option to ComboBox

---

assets/js/dashboard/stats/sources/source-list.js

This fixes a regression introduced in #3153 causing all clicks lead to the exit page reports rather than the UTM tags report.

Fix UTM Campaigns filtering regression from #3153

---

lib/plausible_web/controllers/api/external_controller.ex

Fixes https://github.com/plausible/analytics/discussions/3166

inspect request in sentry context

---

lib/plausible_web/live/components/combo_box.ex
lib/plausible_web/live/components/combo_box/static_search.ex
test/plausible_web/live/components/combo_box/static_search_test.exs
test/plausible_web/live/components/combo_box_test.exs
test/plausible_web/live/funnel_settings/form_test.exs

This commit makes static search more strict by rejecting matches with a score less than `0.6`. Here's an example of suggestion that was matching with a `0.5` score that should not be suggested.
```
iex> String.jaro_distance("author", "uaa")
0.5
```
This makes the suggestion list smaller and more reasonable.
Co-authored by: Robert Joonas <robertjoonas16@gmail.com>

Refine ComboBox.StaticSearch

---

test/plausible_web/controllers/api/internal_controller/sync_test.exs
test/plausible_web/controllers/api/internal_controller_test.exs
test/support/test_utils.ex

This PR extracts a single test where the application env was patched to its own module. We'll also throw a runtime error in case this is done ever again.

Fix test flakiness due to shared state in asynchronous run

---

CHANGELOG.md
lib/plausible/ingestion/request.ex
lib/plausible_web/controllers/api/external_controller.ex
lib/sentry_filter.ex
test/plausible/ingestion/request_test.exs
test/plausible/sentry_filter_test.exs

derive jason encoder for request

---

lib/plausible/site.ex
lib/plausible/site/admin.ex
lib/plausible/sites.ex
lib/plausible/stats/custom_props.ex
lib/plausible_web/controllers/api/stats_controller.ex
lib/plausible_web/controllers/stats_controller.ex
test/plausible_web/controllers/CSVs/30d-filter-goal/custom_props.csv
test/plausible_web/controllers/CSVs/30d-filter-path/custom_props.csv
test/plausible_web/controllers/CSVs/30d/custom_props.csv
test/plausible_web/controllers/CSVs/6m/custom_props.csv
test/plausible_web/controllers/api/internal_controller_test.exs
test/plausible_web/controllers/api/stats_controller/conversions_test.exs
test/plausible_web/controllers/api/stats_controller/suggestions_test.exs
test/plausible_web/controllers/stats_controller_test.exs
test/test_helper.exs

This PR starts including a new CSV file in the export zip - `custom_props.csv`. This file will only be included in the zip, if the `props` feature flag is enabled for the user triggering the export.
There's also the existing `prop_breakdown.csv` file which will be kept until the `props` feature is globally enabled. This will be a breaking change.

Props into CSV export

---

.github/workflows/elixir.yml

I previously introduced using the dockerhub credentials when pulling images from dockerhub. But this leads to problems when creating PRs from a fork.
And it is not so clear if we really need to use the dockerhub creds, as it seems that there were no problems before.

remove dockerhub credentials from pull

---

lib/plausible/debug_replay_info.ex
lib/plausible/stats.ex
test/plausible/debug_replay_info_test.exs

This PR equips `Plausible.Stats` functions with extra Sentry context containing serialized input for each function.

Add debug_replay_info context to Sentry Stats reports

---

test/workers/expire_domain_change_transitions_test.exs

Fixes CI random failure seen at @vinibrsl's PR: https://github.com/plausible/analytics/actions/runs/5674130039/job/15377104359?pr=3191
I haven't gotten deep into details, it looks like some `Logger` race condition - the message comes from another test after all.
I thought that maybe Elixir v.1.15.4 will magically fix it, alas, the error was still observable randomly with the same seed.
The value of that test is minor anyway.

Fix flaky log assertion

---

CHANGELOG.md
lib/plausible/stats/query.ex
test/plausible/stats/query_test.exs

Previously, the interval was always overwritten with the default value, which is determined based on the age of the site. It should not be overwritten when the interval is explicitly passed by the user
Fixes issue #2982 
The way the query is build for the given params has been edited so that the default interval for the "all" period is only set when there is no interval in the passed params

Fix the interval selection in the all time view

---

CHANGELOG.md
assets/js/dashboard/router.js
assets/js/dashboard/stats/behaviours/props.js
assets/js/dashboard/stats/modals/props.js
assets/js/dashboard/stats/reports/list.js
lib/plausible/stats/breakdown.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible/imported/imported_test.exs
test/plausible_web/controllers/api/stats_controller/browsers_test.exs
test/plausible_web/controllers/api/stats_controller/countries_test.exs
test/plausible_web/controllers/api/stats_controller/custom_prop_breakdown_test.exs
test/plausible_web/controllers/api/stats_controller/operating_systems_test.exs
test/plausible_web/controllers/api/stats_controller/screen_sizes_test.exs

This PR adds a "details" view for custom property value breakdown.
https://github.com/plausible/analytics/assets/56999674/fdeca9f6-26fb-4898-bf3d-4436e923c009
Also fixed two bugs that surfaced along the way:
* Fix percentage metric calculation (make it account for pagination)
* Stop returning (none) values after the first page of results in prop-breakdown (documented in changelog)

Props details view

---

assets/js/dashboard/stats/behaviours/conversions.js
assets/js/dashboard/stats/modals/entry-pages.js
assets/js/dashboard/stats/modals/exit-pages.js
assets/js/dashboard/stats/pages/index.js
assets/js/dashboard/stats/reports/metrics.js
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible/imported/imported_test.exs
test/plausible_web/controllers/api/stats_controller/conversions_test.exs
test/plausible_web/controllers/api/stats_controller/pages_test.exs

just a small consistency improvement - as it's clear what the `visitors`, `visits` and `events` metrics mean internally, there's no need to rename it for different reports or according to the filters being used.
This PR only changes the metric atoms being used internally, without changing any actual behavior.

Refactor: Standardize API metrics used internally

---

assets/js/dashboard/stats/modals/entry-pages.js
assets/js/dashboard/stats/modals/exit-pages.js
assets/js/dashboard/stats/modals/pages.js
assets/js/dashboard/stats/modals/props.js
assets/js/dashboard/stats/pages/index.js
assets/js/dashboard/stats/reports/list.js
assets/js/dashboard/util/url.js
priv/repo/seeds.exs

This PR extends the `trimURL` to fall back to regular strings in case page paths are provided. It's now applied on all the lists and modals.

Trim long URLs, paths and other list items uniformly

---

lib/plausible/auth/auth.ex
lib/plausible/auth/user_admin.ex
lib/plausible/billing/billing.ex
lib/plausible/billing/plans.ex
lib/plausible/billing/site_locker.ex
lib/plausible/users.ex
lib/plausible_web/plugs/auth_plug.ex
lib/workers/send_site_setup_emails.ex
priv/repo/migrations/20230802081520_cascade_delete_user.exs
test/plausible/billing/billing_test.exs
test/plausible/billing/plans_test.exs
test/plausible/billing/site_locker_test.exs
test/plausible_web/controllers/auth_controller_test.exs

There were some cascading deletes missing in postgres schema, this PR takes care of that via a migration. Additionally, all subscription preloads are now done through an unified interface to minimize the risk of preloading a subscription that's not latest (explicit ordering is provided).
BTW CRM user deletion is fixed too.
I think it's fine to deploy this migration with the code in one shot.

[pg migration] Delete account with multiple subscriptions

---

lib/plausible/props.ex
test/plausible/props_test.exs

This commit prevents the `url` and `path` prop keys from being suggested by the props settings page. These props are used internally for file downloads and outbound link clicks, and don't need to be manually allowed.

Remove url and path prop keys from suggestions

---

assets/js/dashboard/router.js

This PR fixes a regression causing filtering locations from details view render empty filter labels.

Fix filter labels when filtering on clicks from ModalTable

---

CHANGELOG.md
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/stats_controller/pages_test.exs

This PR addresses a crash on CR calculation when filtering by goals and using the details view.

Fix breakdown pagination when filtering by goals

---

test/plausible_web/controllers/stats_controller_test.exs

This PR turns StatsControllerTest synchronous so that there's no stale data in clickhouse.
Fixes a failure with seed 483739

Make stats controller tests synchronous

---

assets/js/dashboard/components/combobox.js
assets/js/dashboard/stats/behaviours/conversions.js
assets/js/dashboard/stats/behaviours/goal-conversions.js
assets/js/dashboard/stats/behaviours/index.js
assets/js/dashboard/stats/behaviours/props.js
assets/js/dashboard/stats/modals/conversions.js
assets/js/dashboard/stats/modals/props.js
assets/js/dashboard/stats/more-link.js
assets/js/dashboard/stats/reports/list.js
assets/js/dashboard/util/filters.js

This PR fixes several issues with the new Properties feature behaviour:
* Make the property selector component take up the full width in order to be able to display longer values (far from ideal design, open to alternative suggestions)
* Automatically switch the view from Conversions -> Props, when a goal filter is applied by clicking on an item in the Goal Conversions list. The automatic navigation does not happen in the following scenarios:
* no props configured for the site (or feature disabled)
* the goal clicked is a pageview goal
* the goal clicked is a special goal (404, Outbound Link, File Download, Cloaked Link: Click)
* Start saving prop keys per goal filter in localStorage. This way you don't always have to select a property manually when applying different goal filters that …

Improvements to the Properties feature

---

lib/plausible/ingestion/event.ex

The ua_inspector library has many device types that it reports. We have our own grouping rules to categorize them. For example, "smartphone", "wearable", and "portable media player" are  categorised as "Mobile" in Plausible.
Originally I added a fallback clause that reports any unknown device type to Sentry so that we can add it to our grouping rules if necessary. I wasn't sure if our rules were exhaustive or not, and the library might introduce new ones over time.
Turns out the library sometimes returns "unknown" as the device type. It is not helpful to report this to Sentry since we will never add a grouping rule for it. Since this gets triggered a lot, it's better to ignore the "unknown" device type completely which this PR does.

Ignore unkown device type

---

lib/plausible_web/templates/email/trial_upgrade_email.html.eex
test/workers/send_trial_notifications_test.exs

This commit fixes a bug where the SendTrialNotifications job tried to suggest a plan for users switching to enterprise plans, resulting in the exception below:
```
UndefinedFunctionError: function :enterprise.volume/0 is undefined (module :enterprise is not available)
Module "enterprise", in :enterprise.volume/0
File "lib/plausible_web/templates/email/trial_upgrade_email.html.eex", line 5, in PlausibleWeb.EmailView."trial_upgrade_email.html"/1
File "lib/phoenix_view.ex", line 381, in Phoenix.View.render_within/3
File "lib/phoenix_view.ex", line 557, in Phoenix.View.render_to_iodata/3
File "lib/phoenix_view.ex", line 564, in Phoenix.View.render_to_string/3
File "lib/bamboo_phoenix.ex", line 291, in Bamboo.Phoenix.render_text_or_html_email/1
File "lib/workers/send_trial_notifications.ex", …
```

Avoid suggesting plan for trials switching to enterprise plans

---

assets/js/liveview/live_socket.js
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/live/flash.ex
lib/plausible_web/templates/layout/app.html.eex

And disable the "server blip" message on non-dev
environments. It's non actionable for our customers.

Connect to live socket only on specific pages

---

lib/plausible_web/live/components/combo_box.ex
test/plausible_web/live/components/combo_box_test.exs
test/plausible_web/live/funnel_settings/form_test.exs
test/plausible_web/live/funnel_settings_test.exs
test/plausible_web/live/props_settings_test.exs

This PR fixes a regression in ComboBox cursor keys navigation introduced via #3293 - with the "Create ..." item on top, we need to change indexing so that AlpineJS picks it up properly.

Bugfix: ComboBox navigation with creatable on top

---

lib/plausible/billing/quota.ex

This commit removes a Sentry notification triggered when the user plan can't be
found. This error log is spamming on Sentry because of trials, and we should
skip in that case.

Silence undefined plan Sentry log for trials

---

lib/plausible/billing/quota.ex
lib/plausible/sites.ex
lib/plausible_web/controllers/site/membership_controller.ex
lib/plausible_web/templates/site/index.html.eex
test/plausible/billing/quota_test.exs
test/plausible/site/sites_test.exs

This pull request introduces a series of improvements to ownership transfers
including:
- Refactoring the duplicated code between regular invitations and ownership transfers
- Improving test coverage
- Changing team member limits queries to not count pending transfers as team members

Improve ownership transfers

---

lib/plausible/stats/breakdown.ex
lib/plausible/stats/imported.ex
test/plausible/imported/imported_test.exs
test/plausible_web/controllers/CSVs/30d-filter-goal/utm_campaigns.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/utm_contents.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/utm_mediums.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/utm_sources.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/utm_terms.csv
test/plausible_web/controllers/CSVs/30d-filter-path/utm_campaigns.csv
test/plausible_web/controllers/CSVs/30d-filter-path/utm_contents.csv
test/plausible_web/controllers/CSVs/30d-filter-path/utm_mediums.csv
test/plausible_web/controllers/CSVs/30d-filter-path/utm_sources.csv
test/plausible_web/controllers/CSVs/30d-filter-path/utm_terms.csv
test/plausible_web/controllers/CSVs/30d/utm_campaigns.csv
test/plausible_web/controllers/CSVs/30d/utm_contents.csv
test/plausible_web/controllers/CSVs/30d/utm_mediums.csv
test/plausible_web/controllers/CSVs/30d/utm_sources.csv
test/plausible_web/controllers/CSVs/30d/utm_terms.csv
test/plausible_web/controllers/CSVs/6m/utm_campaigns.csv
test/plausible_web/controllers/CSVs/6m/utm_contents.csv
test/plausible_web/controllers/CSVs/6m/utm_mediums.csv
test/plausible_web/controllers/CSVs/6m/utm_sources.csv
test/plausible_web/controllers/CSVs/6m/utm_terms.csv
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
test/plausible_web/controllers/api/stats_controller/sources_test.exs

This PR effectively removes "Direct / None" entry from all UTM props reports across native UI, CSV exports and external API.
Entries with empty respective UTM prop are filtered out when querying stats. This applies to natively collected stats as well as the ones imported from Google Analytics.
Additionally, [a dead code path](https://github.com/plausible/analytics/pull/3339/files#diff-4bd4f25d18935ddee49a41d09209e22b918a05424ba9ed6368314841aa8108e2L149) was removed from imported stats logic - there's a clause of the same function that explicitly skips processing from `utm_source` property, as it's apparently not exposed by GA (or at least it wasn't at the time it was implemented - we might revise that).

Filter out empty entries when listing stats for UTM props

---

lib/plausible/auth/auth.ex
lib/plausible/site/admin.ex
lib/plausible/sites.ex
test/plausible/site/admin_test.exs
test/plausible/site/sites_test.exs

Adds an action in the CRM to initiate ownership transfers. Uses the `Sites.invite` function that @vinibrsl recently extracted.

Allow admins to initiate ownership transfer from the CRM

---

assets/js/liveview/suggestions_dropdown.js
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/controllers/stats_controller.ex
lib/plausible_web/live/components/combo_box.ex
lib/plausible_web/live/funnel_settings.ex
lib/plausible_web/live/goal_settings.ex
lib/plausible_web/live/goal_settings/form.ex
lib/plausible_web/live/props_settings.ex
lib/plausible_web/live/props_settings/form.ex
lib/plausible_web/live/props_settings/list.ex
lib/plausible_web/templates/site/settings_props.html.heex
lib/plausible_web/views/layout_view.ex
priv/repo/seeds.exs
test/plausible_web/live/components/combo_box_test.exs
test/plausible_web/live/goal_settings/form_test.exs
test/plausible_web/live/props_settings/form_test.exs
test/plausible_web/live/props_settings_test.exs

This PR makes the Custom Props settings UI similar to the one introduced in #3293 
~~The diff is against #3321 - please review/merge that one first, I'll then change the base branch.~~
There's several semi-related changes done by the way:
- the `funnels` feature flag is completely removed now
- live views preload external resources only once, at initial render, leveraging the shared assigns on the secondary render when the socket connects
- in case of "creatable" ComboBox, the "Create ..." option shows on top but also the first suggestion is focused, if available

Props Settings UI to match Goals Settings

---

lib/plausible/goal/schema.ex
priv/repo/migrations/20230918084301_fix_broken_goals.exs
test/plausible/goals_test.exs

See https://github.com/plausible/analytics/commit/118795c1c86d9f45b819b935c69f1da1bafa7ab9 for explanation.
We've decided to favour `event_name` over `page_path`.

[migration] Data fix: rewrite goals for which `event_name` and `page_path` both exist

---

lib/plausible_web/live/goal_settings/form.ex
lib/plausible_web/templates/site/settings_funnels.html.heex
lib/plausible_web/templates/site/settings_props.html.heex
lib/plausible_web/templates/site/settings_search_console.html.eex

A fix to open some of the docs links within the app in new window and a change to the URL of one of the links

Open docs links in new window

---

.github/workflows/build-private-images.yml
.github/workflows/build-public-images.yml
.github/workflows/elixir.yml
.github/workflows/node.yml
.github/workflows/terraform-e2e.yml
.github/workflows/tracker.yml

Ensures that only one workflow is running per branch at a time.
If you are working on a branch and push several commits in succession, any workflows in progress will be cancelled and only the last one will run.

Update Workflow Concurrency

---

.github/workflows/elixir.yml
lib/plausible/data_migration/rewrite_funnel_dupes.ex
lib/plausible/funnels.ex
priv/data_migrations/FunnelDupeGoals/sql/list-funnels-with-dupe-goal-ids.sql.eex
test/plausible/data_migration/rewrite_funnel_dupes_test.exs

We're trying to enforce goal names unique (#3343). But we can't delete duplicate goals (i.e. having the same name within their site scope), since some of them might belong to existing funnel steps.
This migration script (can be run directly from console via `Plausible.DataMigration.RewriteFunnelDupes.run`) aims to fix up existing affected funnels in such way that funnels are either reduced, or in extreme cases (e.g. consisting only of steps that refer goals equally named) deleted completely. The PR does not rewrite `Funnel.Step.step_order` values as those are only used for ordering and that should work still after applying the change.
Please have a look at the tests to get better understanding of what the outcome is.
This is a destructive operation that enables us to apply the migration …

Data Migration: rewrite funnels that contain duplicate goals

---

lib/plausible/goal/schema.ex
priv/repo/migrations/20230914071245_goals_unique.exs
test/plausible/data_migration/rewrite_funnel_dupes_test.exs
test/plausible/goals_test.exs

~~:warning: draft till I figure out how to deal with goals that belong to funnels~~ #3361 
This PR sets up two unique constraints so that goals can be considered unique within their site scope. 
Technically duplicates are not a problem in terms of stats presentation, but we've observed some crashes coming from `Plasusible.Goals.find_or_create` since it expects only one result.
For Wordpress plugin integration we like this to work without surprises.
Because we already have some duplicates on production, an extra query to remove the dupes is needed.
Here we're doing this by deleting everything except the `min(id)` from a `GROUP BY goal_unique_tuple` query. I've tested this locally but since this is a destructive operation I'd like extra eyes on it please - cc @ukutaht @zoldar

Enforce goals unique

---

lib/plausible_web/controllers/invitation_controller.ex
test/plausible_web/controllers/invitation_controller_test.exs

This PR addresses getting redirected to Site Settings page after removing pending invitation in People Settings.

Redirect to People Settings after removing pending invitation

---

lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/templates/layout/_tracking.html.heex
lib/plausible_web/views/layout_view.ex

1. Removes the `skip_plausible_tracking` assign from 2 pages that should be tracked
2. Starts sending our own events to `ingest.plausible.io` for further testing of that endpoint

Fix dogfooding

---

.github/workflows/elixir.yml

This fixes CI for PRs coming from external repos/contributors

Move back to GitHub managed actions runner

---

lib/plausible/billing/billing.ex
lib/plausible/billing/site_locker.ex
lib/plausible/mailer.ex
lib/plausible/site/membership.ex
lib/plausible/site/memberships.ex
lib/plausible/site/memberships/accept_invitation.ex
lib/plausible/site/memberships/invitations.ex
lib/plausible/site/memberships/reject_invitation.ex
lib/plausible/site/memberships/remove_invitation.ex
lib/plausible/sites.ex
lib/plausible_web/controllers/invitation_controller.ex
lib/plausible_web/controllers/site/membership_controller.ex
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/templates/site/index.html.eex
lib/workers/lock_sites.ex
test/plausible/billing/billing_test.exs
test/plausible/billing/site_locker_test.exs
test/plausible/site/memberships/accept_invitation_test.exs
test/plausible/site/memberships/reject_invitation_test.exs
test/plausible/site/memberships/remove_invitation_test.exs
test/plausible/site/sites_test.exs
test/plausible_web/controllers/api/external_stats_controller/auth_test.exs
test/plausible_web/controllers/invitation_controller_test.exs

This PR refactors and fixes a number of issues with invitation flow:
- invitation accepting, rejecting and removing logic moved to dedicated "service" modules
- accepting logic significantly refactored for readability and clearer sepration between ownership transfer and invite flows
- fixed a bug where it was possible to accept transfer ownership on an owner, degrading them to admin and leaving site without an owner
- fix a bug where it was possible to degrade existing member's role with an invite
- fix grace period end handling in invitation acceptance due to a missing relationship preload in SiteLocker
- improve naming and test coverage of surrounding logic
- prevent issuing transfer ownership on owner's email at the time of issuing the invitation
- make acceptance of invitation and …

Fix and refactor invitation logic

---

lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/live/reset_password_form.ex
lib/plausible_web/templates/auth/password_reset_form.html.eex
test/plausible_web/controllers/auth_controller_test.exs
test/plausible_web/live/reset_password_form_test.exs

This change addresses two problems:
* controller action crashing on missing "token" param - it's handled gracefully
now and will not pollute Sentry anymore with http://sentry.plausible.io/organizations/sentry/issues/4319
* LiveView receives email extracted from token on initial page load instead
of reverifying token on every re-mount (which can happen when somebody
leaves form open for an extended period of time; rare but happens and
needlessly pollutes Sentry as well)

Handle missing or expired token in password reset action and LV gracefully

---

lib/plausible/auth/user.ex

This change ensures that password strength check never crashes, always prioritising not breaking affected flows (especially registration and invites). Minimum password length is still enforced anyway,

Ensure that `User.password_strength/1` always returns a value

---

lib/plausible/site.ex
test/plausible_web/controllers/site_controller_test.exs

As in the title. Any extra leading slashes are removed from the name in the process as it does not work well with local HTTP redirects.

Improve domain cleanup on site creation

---

lib/plausible/billing/site_locker.ex
lib/plausible/site/memberships/accept_invitation.ex

Fixes invalid preload of subscription on user in a corner case of sending email about grace period ending right around accepting ownership transfer.

Fix invalid subscription preload in SiteLocker email submission routine

---

priv/repo/migrations/20231010074900_add_unique_index_on_site_memberships_site_id_when_owner.exs
test/plausible/site/membership_test.exs

As in the title. It ensures better data integrity in case such invalid state slips through application-level validations.

Add constraint enforcing at most one owner membership per site

---

lib/plausible_release.ex
priv/repo/migrations/20230914071244_fix_broken_goals.exs
rel/overlays/pending-migrations.sh

The migration in question was renamed in order to fix order of executing migrations when run from the ground up (via https://github.com/plausible/analytics/pull/3378).
As a side effect, it's executed again on databases that had it applied earlier, with a different timestamp prefix.
As this migration is safe to run multiple times, it was modified to make forward migration work gracefully when constraint already exists.
Tested locally by manually removing migration version from `schema_migrations` and rerunning migrations again - behaves fine.

Make FixBrokenGoals migration idempotent

---

CHANGELOG.md
lib/plausible/auth/user.ex
lib/plausible/auth/user_admin.ex
lib/plausible/site/memberships.ex
lib/plausible/sites.ex
lib/plausible/users.ex
lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/plugs/require_account.ex
lib/plausible_web/router.ex
lib/plausible_web/templates/auth/activate.html.eex
lib/plausible_web/templates/auth/user_settings.html.heex
priv/repo/seeds.exs
test/plausible_web/controllers/auth_controller_test.exs

[email_reverification.webm](https://github.com/plausible/analytics/assets/588351/69c2d8eb-3b4a-4bc2-8da4-1f2a4c64d7b0)
Email now must be reverified on change. In order to intiate the change, current user password must be provided.
The settings form was slightly reorganized in the process.
There's ability to cancel reverification from activation view.
Draft of documentation update is prepared in https://github.com/plausible/docs/pull/438

Trigger email reverification on change

---

lib/plausible/auth/user.ex
lib/plausible_web/controllers/auth_controller.ex
test/plausible_web/controllers/auth_controller_sync_test.exs

Follow-up to #3388 that fixes regression in cases of self-hosted setups with email verification disabled.

Fix email update flow for selfhosted setup with verification disabled

---

lib/plausible/plugins/api/tokens.ex
lib/plausible_web/plugins/api/spec.ex
lib/plausible_web/plugs/authorize_plugins_api.ex
test/plausible/plugins/api/tokens_test.exs
test/plausible_web/plugs/authorize_plugins_api_test.exs

This makes it easier to integrate with -- in case data-domain is different than the actual site domain. Tokens are already associated with a single site anyway.

No longer require domain to seek Plugins API Tokens

---

.github/workflows/elixir.yml
priv/ingest_repo/migrations/20231017073642_disable_deduplication_window_for_imports.exs

Disable deduplication of inserted parts for imported tables to improve behavior on reimporting.

Disable deduplication for improted_* tables in CH

---

priv/ingest_repo/migrations/20231017073642_disable_deduplication_window_for_imports.exs

- migration is irreversible for now, likely due to https://github.com/plausible/ecto_ch/issues/81#issuecomment-1624754909 or maybe https://github.com/plausible/ecto_ch/pull/58/files
- IO.inspect call removed

Fixup 4cdf843ad:

---

lib/plausible/billing/feature.ex
lib/plausible/billing/plans.ex
lib/plausible/billing/quota.ex
lib/plausible_web/components/billing.ex
lib/plausible_web/live/choose_plan.ex
lib/plausible_web/live/goal_settings/form.ex
lib/plausible_web/templates/auth/user_settings.html.heex
lib/plausible_web/templates/site/settings_funnels.html.heex
lib/plausible_web/templates/site/settings_props.html.heex
priv/plans_v1.json
priv/plans_v2.json
priv/plans_v3.json
priv/plans_v4.json
priv/sandbox_plans.json
priv/unlisted_plans_v1.json
priv/unlisted_plans_v2.json
test/plausible/billing/quota_test.exs
test/plausible_web/components/billing_test.exs

This refactoring PR is meant to prepare for adding the feature gates and limits information to the new `/billing/choose-plan` page. It will consider `Goals` a feature that is also listed in the JSON files, and removes the abstraction of "extra_features", replacing it with just "features" or "allowed_features" depending on the context.
Reviewing commit by commit might be easier to follow.

Refactor: Add 'goals' feature to JSON plan files

---

lib/plausible/purge.ex

Adds documentation about reasoning behind disabling deduplication and warning about caveats of sharded setup.

Document reasoning behind disabling deduplication in import tables

---

lib/plausible/plugins/api/token.ex
lib/plausible/plugins/api/tokens.ex
lib/plausible_web/live/plugins/api/settings.ex
lib/plausible_web/plugs/authorize_plugins_api.ex
priv/repo/migrations/20231018081657_add_last_used_at_to_plugins_api_tokens.exs
test/plausible/plugins/api/token_test.exs
test/plausible/plugins/api/tokens_test.exs
test/plausible_web/live/plugins_api_tokens_test.exs
test/plausible_web/plugs/authorize_plugins_api_test.exs

Migration is included, but can be deployed along with this PR - there's very little Plugins API usage still.
PR is built on top of #3427 - needs that one merged first, so that base is switched.
We'll now track and display "last used" for Plugins API Tokens:

Track tokens usage

---

lib/plausible/plugins/api/goals.ex
lib/plausible_web/plugins/api/controllers/goals.ex
lib/plausible_web/plugins/api/schemas/payment_required.ex
test/plausible_web/plugins/api/controllers/goals_test.exs

This PR enables error handling on revenue goal creation constrained by subscription/business tier rules.

Plugins API: handle Revenue Goals creation wrt Business Tier

---

lib/plausible_web/templates/layout/_header.html.heex

For some reason the dropdown link was not wired up to the correct helper function.

Fix feedback link

---

lib/plausible/billing/quota.ex

This is a dirty quick fix to allow subscribing to a plan with exceeded pageview limit. We need to figure out how to handle this case more gracefully.

ignore only pv limit exceeded on subscribe

---

assets/js/apply-theme.js
lib/plausible_web/controllers/stats_controller.ex
lib/plausible_web/templates/layout/app.html.eex
lib/plausible_web/templates/stats/stats.html.eex

Ensure app.js is loaded before dashboard.js - this is assumed in the code for dark mode to work correctly in dashboard components.
PS - is there a nicer way to do this instead of an assign?

Fix dark mode race condition

---

lib/plausible_web/live/components/visitors.ex

Fix /sites cut-off for 0 visitors plot

---

lib/plausible/billing/plans.ex
lib/plausible_web/live/choose_plan.ex
lib/plausible_web/templates/email/dashboard_locked.html.eex
lib/plausible_web/templates/email/over_limit.html.eex
lib/plausible_web/templates/email/trial_upgrade_email.html.eex
test/plausible/billing/plans_test.exs
test/plausible_web/live/choose_plan_test.exs
test/workers/check_usage_test.exs
test/workers/send_trial_notifications_test.exs

This PR implement the recommending of a plan tier for trials, based on the premium features they've used. When recommending the tier, we also take into account if the trials started before or after the Business Tiers release. Therefore, this PR consists of two tests that will become redundant after 30 days have passed from the release.
The styling of the recommendation highlight on the UI side is exactly the same as for the currently owned plan. But since these are used for different user groups (trials vs existing subscribers) - we never show the two highlights on the page at the same time.

Recommending a plan

---

lib/plausible_web/live/sites.ex
test/plausible_web/controllers/site_controller_test.exs

shows loading state, so that "0 visitors" doesn't flash before ws connects.
cc @ukutaht - if you like to test/tweak locally, add :timer.sleep(3000) after `connected?` on line 498

Add loading state to site cards

---

lib/plausible/billing/plans.ex
lib/plausible/billing/quota.ex
lib/plausible/site/memberships/create_invitation.ex
lib/plausible/sites.ex
lib/plausible_web/controllers/billing_controller.ex
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/live/choose_plan.ex
lib/workers/check_usage.ex
test/plausible/billing/plans_test.exs
test/plausible/billing/quota_test.exs
test/plausible_web/controllers/billing_controller_test.exs
test/plausible_web/live/choose_plan_test.exs
test/support/paddle_api_mock.ex
test/support/test_utils.ex

> Legacy trials = users who signed up before the business tier release.
* Include `StatsAPI` and `Props` as allowed features for a `free_10k` subscription plan
* Return v3 plans (both Growth and Business) to legacy trials. This allows them to subscribe to a plan with the terms that they signed up for (e.g. unlimited team members)
* Display Growth benefits list instead of grandfathering notice on the upgrade page when the user is a legacy trial

Fix upgrade page for legacy trials + bug fixes

---

lib/plausible_web/plugins/api/schemas/error.ex
lib/plausible_web/plugins/api/schemas/goal/list_response.ex
lib/plausible_web/plugins/api/schemas/link.ex
lib/plausible_web/plugins/api/schemas/not_found.ex
lib/plausible_web/plugins/api/schemas/pagination_metadata.ex
lib/plausible_web/plugins/api/schemas/payment_required.ex
lib/plausible_web/plugins/api/schemas/shared_link/list_response.ex
lib/plausible_web/plugins/api/schemas/unauthorized.ex
lib/plausible_web/plugins/api/schemas/unprocessable_entity.ex

This PR only cleans up the OpenAPI schema - no tests should be harmed and it resolves the errors when using PHP code generator.

Tidy up openapi schema

---

lib/plausible_web/live/sites.ex
priv/repo/migrations/20231109090334_add_site_user_preferences.exs

Changes extracted from #3469 - the migration has to be deployed and run before the changes in logic.
There's also a fix to sites LV which should address problem of excessive DB queries due to firing `phx-change` events on reconnecting websockets. More context: https://hexdocs.pm/phoenix_live_view/form-bindings.html#recovery-following-crashes-or-disconnects

Create `site_user_preferences` table and apply LV fix

---

lib/plausible/open_telemetry.ex
lib/plausible/open_telemetry/sampler.ex

This PR implements ratio-based sampling of OpenTelemetry traces sent to Honeycomb based on trace ID, closely following method used in built-in sampler. Ratio sampling is done _after_ applying exceptions on tables and HTTP routes.

Implement trace ID ratio-based sampling for OpenTelemetry

---

lib/plausible_web/live/sites.ex

Apparently using the `<p>` element breaks x-show/styles cascading. Swapping it with `<div>` renders `x-show` correctly including children elements.
Before:
After:

Fix bug showing invitation popups

---

lib/plausible_web/components/billing.ex
lib/plausible_web/components/generic.ex
lib/plausible_web/templates/layout/_notice.html.heex
test/plausible_web/components/billing_test.exs

* Change the upgrade CTA to say "contact us to upgrade your subscription" instead of "contact us about your enterprise plan" (which is not a good message for Business subscriptions who've hit some limit)
* Implement a `dismissable_id` option to `PlausibleWeb.Components.Generic.notice` which saves the user's preference in their localStorage that a notice with this `dismissable_id` has been dismissed.
* show a notice about losing access to Funnels and Revenue goals (to the site owners that are using either of these features) across the app (i.e. on `/settings`, `/sites`, dashboard, and site settings pages)
* Since we don't want to display the same notice twice, also remove the current private preview end notices from the relevant sections of site settings (i.e. the …

Notice across the app about Funnels and Revenue goals private preview end

---

lib/plausible_web/live/choose_plan.ex
test/plausible_web/live/choose_plan_test.exs

This PR only contains a small refactoring commit in a test file + bug fix to allow cancelled subscriptions subscribe to their currently owned plan before the period they've paid for has actually ended.

Bugfix: Allow cancelled subscriptions to subscribe

---

lib/plausible/billing/billing.ex
lib/plausible/billing/plans.ex
lib/plausible_web/components/billing.ex
lib/plausible_web/components/generic.ex
lib/plausible_web/templates/auth/user_settings.html.heex
lib/plausible_web/templates/layout/_notice.html.heex
test/plausible/billing/plans_test.exs
test/plausible_web/controllers/auth_controller_test.exs
test/plausible_web/live/choose_plan_test.exs
test/support/test_utils.ex

* Stop offering grandfathered plans to subscribers who cancelled and let their subscription expire
* These users will also see a warning (see the first screenshot below)
* Stop offering grandfathered plans to trials who didn't subscribe during, or within the next 10 days after the trial
* Obviously only applies to those who started the trial **before** the business tiers release
* The 10 days limit is silent - they won't be notified about having only 10 days to subscribe to get the grandfathered benefits
The current notice looks like this and it's only displayed on the account settings page:
**With this PR:**
* Move the notice across the app (same scope as the "subscription paused/past-due" notices -`_notice.html`)
* Note about grandfathering as mentioned above
* Change the styling by …

Limit grandfathering to *active* subscribers and trials

---

lib/plausible/ingestion/event.ex
lib/plausible/ingestion/request.ex
test/plausible/ingestion/event_test.exs
test/plausible/ingestion/request_test.exs

We can efficiently classify IP addresses (or other request data) on our load balancer and enrich the event with an additional header.
To start, the header `x-plausible-ip-type: dc_ip` is added when an IP address in the `X-Forwarded-For` header matches an IP in the datacenter list.
The changes in this PR will parse the header and, based on the classification, drop it and add telemetry information with the drop reason.
_Note_: This PR does not drop the event yet, it just adds the telemetry information so that we can see the possible impact before finally enabling this feature. The changes in 9086b84 will need to be reverted to finally drop.

drop IPs classified as datacenter

---

lib/plausible/billing/ecto/feature.ex
lib/plausible/billing/feature.ex

This PR fixes a bug where "Goals" was being listed on the CRM as a feature for enterprise plans.

List only premium features on the CRM

---

lib/plausible/billing/quota.ex
lib/plausible/site/memberships/create_invitation.ex
test/plausible/billing/quota_test.exs
test/plausible/site/memberships/create_invitation_test.exs

Bugfix site transfers

---

lib/plausible_web/live/flash.ex
lib/plausible_web/live/funnel_settings.ex
lib/plausible_web/live/goal_settings.ex
lib/plausible_web/live/plugins/api/settings.ex
lib/plausible_web/live/props_settings.ex
lib/plausible_web/live/sites.ex

This PR abstracts LiveView flash logic and ensures that success and error flash messages are treated independently, each with it's own timer for hiding. Also timer for each flash type is reset when a new flash message is created while the previous one hasn't disappeared yet.
Styling of flash messages is fixed so that notification boxes are stacking vertically without overlapping.
[flashes.webm](https://github.com/plausible/analytics/assets/588351/455cee32-e4ce-4d4a-a0ee-6ed4ca417fd9)
[flashes_small.webm](https://github.com/plausible/analytics/assets/588351/38a79e1b-3ac1-4ef5-bec5-400c46f0befc)

Improve LiveView flash messages

---

lib/mix/tasks/dump_plans.ex
lib/plausible/billing/ecto/limit.ex
lib/plausible/billing/plan.ex
lib/plausible/billing/plans.ex
lib/plausible/billing/quota.ex
priv/repo/migrations/20231121131602_create_plans_table.exs
test/plausible/billing/quota_test.exs

This pull request creates a new internal table called `plans` used for analytical purposes, and a `mix dump_plans` task to seeds the table with plan information. This task can be run multiple times if needed. I also refactored the casting of plans from the JSON files to use Ecto for data casting and validation.
An example of how it looks on the database:
```
| id | generation | kind     | features                                      | monthly_pageview_limit | site_limit | team_member_limit | volume | monthly_cost | monthly_product_id | yearly_cost | yearly_product_id |
|----|------------|----------|-----------------------------------------------|------------------------|------------|-------------------|--------|--------------|--------------------|-------------|-------------------|
| 67 | …
```

Dump plan information to PostgreSQL

---

lib/plausible/props.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/stats_controller/custom_prop_breakdown_test.exs

In the `StatsController.custom_prop_values` action, allow breakdown by prop keys such as `url` and `path` (used with special goals such as 404s or outbound links)

Bugfix: Allow breakdown by internally used prop keys for Growth plans

---

lib/plausible_web/live/choose_plan.ex

This pull request changes the choose plan styling with the landing page. Here's a preview:
Related: https://github.com/plausible/website/pull/507

Match choose plan styling with landing page

---

lib/plausible_web/templates/site/new_shared_link.html.eex

This PR tries to address problem of password managers automatically filling password field on page load when creating new shared link. 
It follows the method described in https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#preventing_autofilling_with_autocompletenew-password. 
I have tested it with Bitwarden browser extension (with autofill on page load temporarily enabled) and it behaves as expected, _not_ autopopulating the field with existing credentials.
It must be noted this is merely a hint though. When triggering auto-fill manually (by selecting credentials from the list in extension pane), the field is still going to be populated. That requires a deliberate action though. Browser compatbility for that property value is also …

Use autocomplete=new-password for shared link password field

---

priv/repo/migrations/20231204151831_backfill_last_bill_date_to_subscriptions.exs

There was a bug in our system, where the `last_bill_date` was not saved upon creating a subscription, and only changed from `nil` to a real date after the second payment on the same subscription. This was fixed for all new/upcoming subscriptions in https://github.com/plausible/analytics/pull/3588.
This PR only contains a migration file that executes SQL to backfill the `last_bill_date` to all existing subscriptions - that means, for all subscriptions that don't have a `last_bill_date`, we will set it to the date when the subscription itself was inserted into our database, i.e. `inserted_at`.

Add a `last_bill_date` to existing subscriptions (migration only)

---

lib/plausible/plugins/api/custom_props.ex
lib/plausible/plugins/api/goals.ex
lib/plausible/props.ex
lib/plausible_web/plugins/api/controllers/custom_props.ex
lib/plausible_web/plugins/api/controllers/goals.ex
lib/plausible_web/plugins/api/router.ex
lib/plausible_web/plugins/api/schemas/custom_prop.ex
lib/plausible_web/plugins/api/schemas/custom_prop/disable_request.ex
lib/plausible_web/plugins/api/schemas/custom_prop/enable_request.ex
lib/plausible_web/plugins/api/schemas/custom_prop/list_response.ex
lib/plausible_web/plugins/api/schemas/goal/delete_bulk_request.ex
lib/plausible_web/plugins/api/views/custom_props.ex
test/plausible_web/plugins/api/controllers/custom_props_test.exs
test/plausible_web/plugins/api/controllers/goals_test.exs

This PR introduces the following changes to Plugins API:
- Goal creation no longer results with polymorphic response; as this is part of OpenAPI v3 specs and client generators won't deal well with `oneOf` annotated-responses (ref https://github.com/OpenAPITools/openapi-generator/issues/10514) - instead, every time a `Goal.ListResponse` is returned, regardless of the input shape
- New endpoint `PUT /custom_props` allowing enabling custom props for a site (either single or in bulk)
- available only for Business Tier clients, otherwise a PaymentRequired is returned
- New endpoint `DELETE /custom_props` allowing disabling custom prop(s) for a site (again, either a single or in bulk)
- New `DELETE /goals` endpoint - allowing goal deletion in bulk (a list of Goal IDs must be provided in …

Plugins API exentsions (custom props, bulk goal delete, goal creation => ListResponse always)

---

lib/plausible/auth/user_admin.ex
lib/plausible/billing/subscription/status.ex
lib/plausible/billing/subscriptions.ex
lib/plausible_web/components/billing.ex
lib/plausible_web/controllers/billing_controller.ex
lib/plausible_web/live/choose_plan.ex
lib/plausible_web/templates/auth/user_settings.html.heex
test/plausible/billing/billing_test.exs
test/plausible/billing/subscription/status_test.exs

This commit improves the subscription status checking in code, and creates convinience functions to work with it, including nil-checking and in?/2 function.

Improve subscription status checking code

---

config/runtime.exs
lib/plausible/ingestion/write_buffer.ex

This PR adds a temporary measure to check what's going on with invalid arrays in inserts.

dump buffer on invalid insert

---

lib/plausible/clickhouse_event_v2.ex
lib/plausible/ingestion/event.ex
lib/plausible/ingestion/request.ex
test/plausible_web/controllers/api/external_controller_test.exs

This patch puts the shields up against custom props payloads ending up as uneven arrays insertions.
```
Elements 'meta.key' and 'meta.value' of Nested data structure 'meta' (Array columns) have different array sizes. (SIZES_OF_ARRAYS_DONT_MATCH)
```

Protect against custom props payloads breaking event insertions

---

lib/plausible_web/components/billing.ex
lib/plausible_web/live/choose_plan.ex
test/plausible_web/live/choose_plan_test.exs

This PR only contains one addition to the upgrade page - not allowing users with `trial_expiry_date=nil` to upgrade. Those are the users that were invited as an admin or a viewer to another site in Plausible, but don't own any sites themselves.
Preview:

Prevent invited users without sites from subscribing

---

test/plausible/session/cache_store_test.exs

This PR adds tests to ensure the correct session collapse order. It should prevent issues similar to https://github.com/plausible/analytics/pull/3511#discussion_r1423382636

add session collapse order test

---

extra/lib/plausible_web/controllers/api/external_sites_controller.ex
lib/plausible/billing/billing.ex
lib/plausible/billing/plans.ex
lib/plausible/billing/quota.ex
lib/plausible/site.ex
lib/plausible/sites.ex
lib/plausible_web/components/billing.ex
lib/plausible_web/controllers/admin_controller.ex
lib/plausible_web/controllers/auth_controller.ex
lib/plausible_web/controllers/site_controller.ex
lib/plausible_web/templates/site/new.html.heex
lib/workers/check_usage.ex
test/plausible/billing/plans_test.exs
test/plausible/billing/quota_test.exs
test/plausible/site/memberships/create_invitation_test.exs
test/plausible_web/controllers/auth_controller_test.exs
test/plausible_web/controllers/site/membership_controller_test.exs
test/plausible_web/controllers/site_controller_test.exs

Clean up legacy trials code + displaying limits

---

test/plausible/session/cache_store_test.exs

The test flakiness introduced via #3622 was reproducible locally by running the `across parts` tests hundred times with a macro generator. This patch no longer leads to failures.

Fix flaky test

---

priv/repo/migrations/20231211092344_add_accept_traffic_until_to_sites.exs

We need to start dropping metrics for sites whose trial has expired or subscription was cancelled. The per-site timestamp gives us flexibility in treating each case separately.

Migration: Add `accept_traffic_until` to "sites"

---

lib/plausible_web/components/billing.ex
lib/plausible_web/components/generic.ex
lib/plausible_web/templates/site/change_domain.html.heex
lib/plausible_web/templates/site/snippet.html.heex

Make it possible to add custom classes to the `styled_link` component. The class attribute was given in several cases, but it was not used by the component.

Fix `class` in `styled_link` and remove existing uses of `class`

---

lib/plausible_web/components/layout.ex
lib/plausible_web/templates/layout/app.html.heex

This PR fixes a bug where the `theme` query parameter was ignored (introduced in https://github.com/plausible/analytics/pull/3625)

Fix applying theme

---

assets/js/dashboard/stats/reports/list.js

Fixes issue where the UI would unexpectedly tab-switch when the user clicks on details.

Remove onClick handler from details link in ListReport

---

lib/plausible/billing/billing.ex
test/plausible/billing/billing_test.exs

This PR addresses a problem where a site owned by a user who does not have trial expiry date set (e.g. they were invited to a site without previously having their own site) who was promoted to an owner.

Fix SiteLocker for case of user without trial expiry date but with active subscription

---

.formatter.exs

This PR enables formatting for `/extra`

format extra

---

assets/js/dashboard/stats/modals/modal.js

This commit replaces the `mousedown` event for `click` to close a modal, such as the detail dialog. This allows the scrollbar to be clicked without firing an event, and right clicks too.
Closes #2872

Prevent scrollbar click to close modal

---

lib/plausible/stats/imported.ex
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs

Similar to https://github.com/plausible/analytics/pull/3123 - apparently some imported pages google sends us look like: 
```
┌─visitors─┬─pageviews─┬─exits─┬─time_on_page─┐
│        1 │         0 │     0 │            0 │
│        1 │         0 │     0 │            0 │
│        1 │         0 │     0 │            0 │
│        1 │         0 │     0 │            0 │
│        1 │         0 │     0 │            0 │
│        1 │         0 │     0 │            0 │
│        1 │         0 │     0 │            0 │
│        1 │         0 │     0 │            0 │
│        1 │         0 │     0 │            0 │
│        1 │         0 │     0 │            0 │
└──────────┴───────────┴───────┴──────────────┘
```
It's questionable whether we should import those records at all, but that's a matter …

Skip breakdown of imported pages with pageviews=0

---

lib/plausible_web/controllers/api/stats_controller.ex
lib/plausible_web/controllers/stats_controller.ex
test/plausible_web/controllers/stats_controller_test.exs

This PR fixes a bug where `custom_props.csv` file was not included in the CSV export for Growth plans using the `url` or `path` props (e.g. with outbound link or file download goals). These props should not be considered a premium feature.

Add `custom_props.csv` back to CSV export for Growth plans

---

lib/plausible/site.ex
test/plausible/site/sites_test.exs
test/plausible_web/controllers/api/external_sites_controller_test.exs

Ensures timezone is within the set known to Timex

Disallow funny business on timezone entry

---

lib/plausible_web/email.ex
lib/workers/accept_traffic_until_notification.ex
test/workers/accept_traffic_until_test.exs

- extend has_stats to 48h
- ensure the user is properly greeted

Update accept_traffic_until notifications

---

CHANGELOG.md
lib/plausible/stats/base.ex
lib/plausible/stats/breakdown.ex
test/plausible_web/controllers/api/stats_controller/conversions_test.exs

This PR fixes the behaviour where custom event goals are returned in the conversions breakdown with a pageview goal filter, and vice versa. Example from the live demo:
After this PR, in the two above cases, only the goal in filter would be returned.
This PR also removes some dead code handling the `:not_member` and `:not_matches_member` filter types for the `event:goal` property. As things stand now, these filter types cannot be used for this property.

Fix goal filter inconsistency

---

lib/plausible/auth/user.ex
test/plausible_web/controllers/auth_controller_sync_test.exs

There is no point in ever disabling it on full build.

Always enable e-mail verification on full build

---

lib/plausible_web/plugs/error_handler.ex

Correction to #3661 
`set_tags_context` is more applicable here, as we can search by it. Per Sentry moduledoc:
```
Merges new fields into the `:tags` context, specific to the current process.
This is used to set fields which should display when looking at a specific
instance of an error. These fields can also be used to search and filter on.
```

Use tags rather than context to annotate support hashes in Sentry

---

assets/js/dashboard/filters.js

Fixes props site property check when rendering filters dropdown which was missed when changing `propsEnabled` => `propsAvailable` in https://github.com/plausible/analytics/pull/3646.

Fix props availability check when listing stats filters in dropdown

---

assets/js/dashboard/comparison-input.js

Fixes https://github.com/plausible/analytics/issues/3304
Before:
After:
Using `md` makes sure the picker button does not jump out of line on larger screen sizes (hence the need for `absolute`).
Verified to work on actual mobile display too - Sunday is visible and selectable on iPhone 12 mini.

Fix calendar picker for comparisons on small screens

---

extra/lib/plausible_web/live/funnel_settings.ex
extra/lib/plausible_web/live/funnel_settings/form.ex
lib/plausible_web.ex
lib/plausible_web/endpoint.ex
lib/plausible_web/live/choose_plan.ex
lib/plausible_web/live/goal_settings.ex
lib/plausible_web/live/goal_settings/form.ex
lib/plausible_web/live/plugins/api/settings.ex
lib/plausible_web/live/plugins/api/token_form.ex
lib/plausible_web/live/props_settings.ex
lib/plausible_web/live/props_settings/form.ex
lib/plausible_web/live/register_form.ex
lib/plausible_web/live/reset_password_form.ex
lib/plausible_web/live/sentry_context.ex
lib/plausible_web/live/sites.ex
test/plausible_web/live/sentry_context_test.exs

This PR adds basic Sentry context to existing LiveViews.
I used https://github.com/dashbitco/bytepack_archive/blob/main/apps/bytepack_web/lib/bytepack_web/request_context.ex as a reference.

Sentry context in live views

---

extra/lib/plausible_web/live/funnel_settings.ex
extra/lib/plausible_web/live/funnel_settings/form.ex
lib/plausible_web.ex
lib/plausible_web/endpoint.ex
lib/plausible_web/live/choose_plan.ex
lib/plausible_web/live/goal_settings.ex
lib/plausible_web/live/goal_settings/form.ex
lib/plausible_web/live/plugins/api/settings.ex
lib/plausible_web/live/plugins/api/token_form.ex
lib/plausible_web/live/props_settings.ex
lib/plausible_web/live/props_settings/form.ex
lib/plausible_web/live/register_form.ex
lib/plausible_web/live/reset_password_form.ex
lib/plausible_web/live/sentry_context.ex
lib/plausible_web/live/sites.ex
lib/plausible_web/templates/billing/choose_plan.html.heex
test/plausible_web/live/goal_settings/form_test.exs
test/plausible_web/live/sentry_context_test.exs

This PR re-applies #3672 with two patches - one fixing a crash on revenue goals selection, and also ensuring the context is only set when the socket is actually connected, so effectively on second mount only.

Reapply sentry context

---

lib/plausible/props.ex
lib/plausible/stats/custom_props.ex
lib/plausible/stats/filter_suggestions.ex
lib/plausible_web/controllers/api/external_stats_controller.ex
test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs

Starting from the v4 generation of subscription plans, Stats API and Custom Properties are both considered premium features. However, there are two possible cases where the user might have access to Stats API, but not Custom Properties.
1. Enterprise plans with the Stats API feature allowed, but props disallowed
2. An invited user on trial / business plan /grandfathered plan is querying with their own API key, but the site owner does not have access to props
These cases in mind, extra checks are required to ensure that the queried breakdown property, or the used filters do not contain custom properties that the site owner does not have access to. Internal prop keys such as `url` and `path` should always be allowed.
This PR also build a single function `allowed_for` that acts as a gateway …

Limit Custom Properties access in Stats API

---

lib/plausible/site/memberships/accept_invitation.ex
test/plausible/site/memberships/accept_invitation_test.exs

This PR ensures that transferred site is unlocked immediately in cases of both, direct transfer and a transfer via invitation.

Run SiteLocker right after site ownership transfer

---

lib/plausible/stats/fragments.ex
test/plausible_web/controllers/api/stats_controller/main_graph_test.exs

This PR fixes a bug where the main graph weekly interval query sometimes returns 0 visitors for the first week, even when there were visitors.
The bug can be reproduced on any dashboard by looking at the main graph, when the following conditions are met:
1. The site timezone is ahead of UTC
2. The first day of the selected period is not a Monday
3. The `week` interval option is selected
This happened because the start of the month defining the first week was missing the UTC -> site.timezone conversion.

Fix weekly interval bug

---

lib/plausible_web/components/billing/plan_box.ex
test/plausible_web/live/choose_plan_test.exs

Fixes a regression caused by https://github.com/plausible/analytics/pull/3683. Explained in the code comment.

Stop expecting `trial_expiry_date` to exist on upgrade

---

lib/plausible_web/remote_ip.ex
test/plausible_web/controllers/api/external_controller_test.exs

Since we already need to replicate this logic in our load balancer setup for session stickiness, we now move the responsibility completely to the load balancers.
The correct IP address is now fully looked up by the load balancer and passed to the backends as `X-Plausible-IP` header.

Prioritize X-Plausible-IP header over everything else

---

Makefile

Updated clickhouse docker image to `clickhouse/clickhouse-server:latest-alpine`. This fixes issue: https://github.com/plausible/analytics/issues/3694

Update clickhouse docker image

---

CHANGELOG.md
assets/js/dashboard/stats/modals/prop-filter-modal.js
assets/js/dashboard/util/filters.js
lib/plausible/stats/base.ex
lib/plausible/stats/breakdown.ex
test/plausible_web/controllers/api/stats_controller/custom_prop_breakdown_test.exs
test/plausible_web/controllers/api/stats_controller/pages_test.exs

This PR a filtering with `contains`/`matches` for custom properties, e.g. "Filter where (custom property) url contains foo"
First PR :raised_hands:

Support `contains`/`matches` for custom properties

---

lib/plausible_web/live/components/combo_box.ex
test/plausible_web/live/components/combo_box_test.exs

This PR fixes a bug where a `creatable` option selection makes the spinner stuck in the combobox input. Instead, in such cases no spinner should be shown, since there is no server roundtrip the user has to wait for.

CombBox bugfix: stale spinner on creatable options selection

---

lib/plausible/stats/aggregate.ex
lib/plausible/stats/breakdown.ex
lib/plausible/stats/query.ex
lib/plausible/stats/timeseries.ex

This is a continuation of [query tracing improvements](https://github.com/plausible/analytics/pull/3704) which might as well have been included in the last PR 🤡.
We'll also want to track how the filters are used in `aggregate` and `timeseries` functions - not only `breakdown`. This PR implements that, and not only filters but the entire query.
Also, we're currently tracing the `breakdown_metrics` field. This PR changes the name of that field to just `metrics`. It doesn't make sense to have a separation between `breakdown_metrics` and every other metric - we already know by `http.route` whether the endpoint returns a breakdown or not. And the same `metrics` field will also be tracked in `aggregate` and `timeseries`.

Trace aggregate and timeseries queries too

---

.github/workflows/build-private-images.yml
.github/workflows/elixir.yml
.github/workflows/node.yml
.github/workflows/terraform-e2e.yml

Chained PRs (like https://github.com/plausible/analytics/pull/3708) don't currently run tests. This PR fixes that.

Github Actions: Run tests on all PRs

---

lib/plausible/stats/base.ex
lib/plausible/stats/breakdown.ex
lib/plausible/stats/clickhouse.ex
lib/plausible/stats/filter_suggestions.ex
lib/plausible/stats/fragments.ex

This PR refactors the backend code to use `meta.value[indexOf(meta.key, 'custom_property')]` over array joins. Doing so has a few benefits:
1. It allows us to more easily add support for multiple custom property filters.
2. Performance - tests showed ~20% performance benefit for some production queries (see [basecamp](https://3.basecamp.com/5308029/buckets/35611491/card_tables/cards/6946026076) for an example)
Note that ARRAY JOINs were retained in places where it still makes sense - e.g. `Plausible.Stats.CustomProps#fetch_prop_names`.
Based on top of https://github.com/plausible/analytics/pull/3687 as that introduced new LEFT JOINs.

Remove ARRAY JOINs

---

lib/plausible/stats/base.ex
lib/plausible/stats/clickhouse.ex
lib/plausible/stats/query.ex
test/plausible/stats/query_test.exs

This should prevent time-sensitive race conditions on subsequent `Plausible.Stats.*` calls for the same query. Not sure if there are more places where now() is
dynamic relative to query life cycle, but it's a start.
Ref https://github.com/plausible/analytics/pull/3720 - thanks @macobo for bringing it up!

Make subsequent query boundaries idempotent

---

lib/plausible/auth/user_admin.ex
lib/plausible/billing/billing.ex
lib/plausible/billing/feature.ex
lib/plausible/billing/quota.ex
lib/plausible/billing/subscriptions.ex
lib/plausible/site/gate_keeper.ex
lib/plausible/site/memberships/invitations.ex
lib/plausible/users.ex
lib/plausible_web/components/billing/notice.ex
lib/plausible_web/templates/email/site_setup_help_email.html.eex
lib/plausible_web/templates/email/site_setup_success_email.html.eex
lib/plausible_web/templates/layout/_header.html.heex
lib/plausible_web/views/layout_view.ex
priv/repo/seeds.exs
test/plausible/auth/users_test.exs
test/plausible/billing/billing_test.exs
test/plausible/billing/quota_test.exs
test/plausible_web/components/billing/notice_test.exs

This PR fixes a bug where expired trials with no subscriptions would still have access to all the business tier features. I did a minor code re-org, reading commit by commit should help. The actual bugfix is https://github.com/plausible/analytics/pull/3740/commits/7365e58636efa80c90b79fa9903dd4dff105e2c3
On top of that, I've changed the `on_trial?` implementation so it always returns `true` for `small` builds.

Bugfix: available features for expired trials, no subscriptions

---

lib/plausible/stats/filters/dashboard_filter_parser.ex
lib/plausible/stats/query.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/stats_controller/sources_test.exs

This PR fixes an issue where filter expression provided for source in referrer drilldown is not parsed and filtered by properly.

Parse referrer filter value when passed separately

---

config/runtime.exs

JOINs are frequently the slowest part of any clickhouse query. We make a lot of them.
I've benchmarked [`join_algorithm` query setting](https://clickhouse.com/docs/en/operations/settings/settings#join_algorithm) and results showed a consistent 50%-200% improvement in slow (>1s) queries. Some fast queries (e.g. <400s) became around 20% slower, which is acceptable and might be statistical noise.
More context under https://3.basecamp.com/5308029/buckets/35611491/messages/7009643334
Question to reviewers: Should this go to changelog?

Use parallel_hash for joins in clickhouse

---

lib/plausible_web/plugs/authorize_stats_api.ex
test/plausible_web/controllers/api/external_stats_controller/auth_test.exs

We recently fixed a bug and took away Stats API (and other features) access from users without a trial or an active subscription. Before we made that change, users might have been using API keys of admin accounts that didn't have an active subscription. Now that we've finally blocked the access, those API keys do not have access anymore, and the current error message is pretty intimidating -
> Stats API is part of the Plausible Business plan. To get access to this feature, please upgrade your account.
Upgrading the owner account will not fix the issue if you keep using the admin key. This PR is a quick fix to improve the communication and tell users about the real problem.

Improve Stats API upgrade required error message

---

assets/css/app.css
assets/js/dashboard/stats/graph/visitor-graph.js
lib/plausible_web/templates/layout/_footer.html.heex
lib/plausible_web/templates/layout/_header.html.heex
lib/plausible_web/views/stats_view.ex

This PR improves print layout at least in chromium-based browsers. Firefox for me will refuse to print anything but the first page :shrug: 
Before:
After:

Improve print dashboard css

---

lib/plausible_web/components/layout.ex
lib/plausible_web/templates/layout/app.html.heex

This seem to be making a difference on staging
ref https://github.com/plausible/analytics/pull/3639/
ref https://github.com/plausible/analytics/pull/3625/
Repro on prod: set dark mode, go to /sites, wait for full load, click plausible logo in the left corner

Fix flashing on reapplying theme

---

lib/plausible_web/controllers/api/stats_controller.ex
lib/plausible_web/live/goal_settings.ex
lib/plausible_web/live/goal_settings/list.ex
test/plausible_web/controllers/api/stats_controller/conversions_test.exs
test/plausible_web/live/goal_settings_test.exs

This PR hides the revenue-related metrics for users who have created Revenue Goals but their plan currently does not support them.
Visual indication of such case is also included in the goals list:

Turn Revenue Goals into Custom Events if the plan doesn't support them

---

lib/plausible/stats/breakdown.ex
test/plausible_web/controllers/CSVs/30d/browser_versions.csv
test/plausible_web/controllers/CSVs/30d/browsers.csv
test/plausible_web/controllers/CSVs/6m/browser_versions.csv
test/plausible_web/controllers/CSVs/6m/browsers.csv

This can add a needless performance overhead. Note that all queries already sort by the _name_ of the breakdown value besides the session start.
Related: https://3.basecamp.com/5308029/buckets/35611491/messages/7061875211

Remove ORDER BY min(session.start)

---

lib/plausible/stats/clickhouse.ex
lib/workers/spike_notifier.ex
test/plausible/stats/clickhouse_test.exs
test/workers/spike_notifier_test.exs

While planning to [improve sessions schema](https://3.basecamp.com/5308029/buckets/35611491/messages/7061875211), spike detection email code [stood out](https://3.basecamp.com/5308029/buckets/35611491/messages/7043364021) in that it queried and grouped sessions differently.
One thing led to another and I ended up removing some dead code as well as bringing what's left in-line with how we query sessions elsewhere.

Refactor spike detection top sources query

---

lib/plausible/migration_utils.ex
priv/ingest_repo/migrations/20231017073642_disable_deduplication_window_for_imports.exs
priv/ingest_repo/migrations/20240209085338_minmax_index_session_timestamp.exs

Related: https://github.com/plausible/analytics/pull/3770
This PR adds a minmax index for sessions_v2.timestamp column. This will make it cheaper to calculate queries like `SELECT * FROM sessions_v2 WHERE start >= ? and timestamp < ?` as clickhouse will know what parts of the data it can skip.
Operationally not sure how we can run these migrations - dear reviewer if you do know, ping me and let's run/document together!

Add migration for minmax indexes on session timestamps

---

lib/plausible_web/templates/stats/stats.html.eex

we haven't changed this copy in 5 years. site settings area is way more powerful now than it used to be so wanted to highlight a couple more things you can do in there. I have tried to keep it short but don't have a way to check how the new copy looks like on the actual dashboard so please doublecheck that it looks good on the actual screen and on smaller devices too. and it should go away on its own after it's been clicked on like it does now

copy changes to the CTA on the top of a new dashboard

---

priv/ingest_repo/migrations/20240123142959_add_import_id_to_imported_tables.exs
priv/repo/migrations/20240123095646_remove_google_analytics_imports_jobs.exs
priv/repo/migrations/20240123144308_add_site_imports.exs

Migrations extracted from https://github.com/plausible/analytics/pull/3724 that have to be applied before releasing the rest of the code changes. Also includes a migration cleaning up Oban queue entries for a now long defunct queue.

Add table migrations for supporting multiple imports per site

---

lib/oban_error_reporter.ex
test/workers/oban_error_reporter_test.exs

This PR makes ObanErrorReporter safer by processing the potentially fallible events in ~~an unlinked process.~~ a try/catch block.

safe(r) Oban telemetry

---

config/runtime.exs

We had an incident where a stray materialized view caused inserts to fail. This setting causes stray mv errors to fail without making the main INSERT error. This is okay for our current usecases where we don't rely on materialized views for business logic.
Further reading: https://clickhouse.com/docs/en/sql-reference/statements/create/view#materialized-view

Set materialized_views_ignore_errors

---

CHANGELOG.md
lib/plausible/stats/compare.ex
lib/plausible_web/controllers/api/external_stats_controller.ex
test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs

1. Calculate `conversion_rate` change by subtracting the percentages (similar to bounce rate), not taking percentages of percentages (involving Top Stats in the dashboard and the `conversion_rate` metric in Stats API aggregate with `compare=previous_period`)
This is how the percentage change is reported on the dashboard currently:
Since with CR we're talking about percentages from 0-100, that change should be -1.4% instead. That should be consistent with the percentage change of `bounce_rate`
2. Use the same percentage change between the dashboard API and Stats API
* The Stats API percentage change for bounce rate is currently calculated by taking percentages of percentages. This PR makes it consistent with the dashboard.
* Exactly the same for `conversion_rate` change - not live yet, but …

Unify percentage change for CR and bounce_rate

---

lib/plausible/billing/feature.ex
lib/plausible/plugins/api/capabilities.ex
lib/plausible_web/plugins/api/controllers/capabilities.ex
lib/plausible_web/plugins/api/schemas/capabilities.ex
lib/plausible_web/plugins/api/views/capabilities.ex
lib/plausible_web/plugs/authorize_plugins_api.ex
lib/plausible_web/router.ex
test/plausible_web/plugins/api/controllers/capabilities_test.exs
test/plausible_web/plugs/authorize_plugins_api_test.exs

It aims to:
- help the client verify the data-domain the token is associated with
- list all the features available for the site's owner (and therefore determine availability of the subset of those for the current Plugins API caller)
The endpoint does not require authentication, in the sense that it'll always respond with 200 OK. However when the token is provided, a verification lookup is made.
https://3.basecamp.com/5308029/buckets/32037438/card_tables/cards/7103031212

Add `GET /capabilities` to Plugins API

---

CHANGELOG.md
assets/js/dashboard/router.js
assets/js/dashboard/stats/locations/index.js
assets/js/dashboard/stats/modals/table.js
lib/plausible/stats/aggregate.ex
lib/plausible/stats/breakdown.ex
lib/plausible/stats/compare.ex
lib/plausible/stats/filters/filters.ex
lib/plausible/stats/timeseries.ex
lib/plausible/stats/util.ex
lib/plausible_web/controllers/api/external_stats_controller.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
test/plausible_web/controllers/api/stats_controller/browsers_test.exs
test/plausible_web/controllers/api/stats_controller/pages_test.exs
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs

This PR reapplies two reverted merge commits from https://github.com/plausible/analytics/pull/3739 and https://github.com/plausible/analytics/pull/3781 which already found their way to prod for half a day.
The reason I decided to revert those was that the CSV export started failing more often with a Sentry error we've seen before, and I decided to investigate that. Also, due to the uncertainty with the conversion rate bug in general, it was a safe play to keep it out of the public API at that point.
The way we are currently adding the CR into the browser version breakdown is broken at the moment - it doesn't crash in most cases, but it doesn't return correct conversion rate either. The recent deployment just made it crash.
The fix introduced in this PR is not pretty, and in fact, although …

Reapply conversion rate into Stats API + bugfixes

---

lib/plausible/data_migration.ex
lib/plausible/data_migration/versioned_sessions.ex
lib/plausible/migration_utils.ex
priv/data_migrations/VersionedSessions/sql/attach-partition.sql.eex
priv/data_migrations/VersionedSessions/sql/check-replicas.sql.eex
priv/data_migrations/VersionedSessions/sql/create-sessions-tmp-table.sql.eex
priv/data_migrations/VersionedSessions/sql/drop-sessions-tmp-table.sql.eex
priv/data_migrations/VersionedSessions/sql/exchange-sessions-tables.sql.eex
priv/data_migrations/VersionedSessions/sql/get-sessions-table-settings.sql.eex
priv/data_migrations/VersionedSessions/sql/list-partitions.sql.eex
priv/data_migrations/VersionedSessions/sql/rename-table.sql.eex

This PR adds a data migration migration move sessions_v2 table to VersionedCollapsingMergeTree. This will allow us to avoid rare data corruption issues around sessions.
Part of [the project to improve sessions and events table schemas](https://3.basecamp.com/5308029/buckets/35611491/messages/7061875211).
The migration will swap out the engine for a new one and leave behind a backup table that will need to be cleaned up manually. We don't need to worry about replication or data ingestion - the queries at work here were instant, which will mean very minimal data loss (<1s)
This has been run both locally and on staging. Once successfully run on production, will add a normal migration to do this on all environments.
This query can help compare the main and temporary tables against each other. …

Add data migration for moving sessions_v2 table to VersionedCollapsingMergeTree

---

CHANGELOG.md
lib/plausible/stats/breakdown.ex
lib/plausible_web/controllers/api/stats_controller.ex
lib/plausible_web/controllers/stats_controller.ex
test/plausible_web/controllers/CSVs/30d-filter-goal/operating_system_versions.csv
test/plausible_web/controllers/CSVs/30d-filter-goal/operating_systems.csv
test/plausible_web/controllers/CSVs/30d-filter-path/operating_system_versions.csv
test/plausible_web/controllers/CSVs/30d/operating_system_versions.csv
test/plausible_web/controllers/CSVs/30d/operating_systems.csv
test/plausible_web/controllers/CSVs/6m/operating_system_versions.csv
test/plausible_web/controllers/CSVs/6m/operating_systems.csv
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
test/plausible_web/controllers/api/stats_controller/operating_systems_test.exs
test/plausible_web/controllers/stats_controller_test.exs

This PR implements grouping the `os_versions` breakdown by the `os` itself. This is exactly the same behaviour that we already have for `browser_versions`. Also, adds the `operating_system_versions.csv` report to CSV export.

Group `os_version` by `os`

---

priv/ingest_repo/migrations/20240220123656_create_sessions_events_compression_options.exs

Part of https://3.basecamp.com/5308029/buckets/35611491/messages/7061875211 
Based on work in https://3.basecamp.com/5308029/buckets/35611491/messages/6949640880#__recording_7015576045
Note that the improved compression options only apply for new incoming data - to get the full benefits, running an `OPTIMIZE TABLE` afterwards is needed (but expensive computationally)
After merging this, planning to:
1. Do a before-and-after of compression ratios
2. Run OPTIMIZE TABLE for both tables during a quiet period

Migration to improve compression options of sessions_v2 and events_v2 tables

---

assets/js/dashboard/stats/behaviours/props.js

Follow-up to https://github.com/plausible/analytics/pull/3719
The previous behavior was predicated on:
- Allowing a single custom property filter
- Allowing breaking down only by the chosen custom property filter
Now these restrictions are removed the previous auto-switching just becomes annoying

Avoid changing Custom properties tab automatically every time filter changes

---

lib/plausible_web/templates/layout/_header.html.heex

Hide user name overlay on mobile

---

.github/workflows/elixir.yml

This PR updates the versions of PostgreSQL to newer ones in the CI. (So that I can update https://github.com/plausible/community-edition/blob/v2.0.0/docker-compose.yml#L8 😅)

use newer postgres versions in the ci

---

CHANGELOG.md
assets/js/dashboard/stats/graph/top-stats.js
lib/plausible/stats/base.ex
lib/plausible/stats/imported.ex
lib/plausible/stats/util.ex
test/plausible/imported/imported_test.exs
test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs

Currently, the `views_per_visit` metric is only queried from native stats. This limitation is arbitrary, since imported data has  both `visits` and `pageviews` needed to calculate the metric.
The motivation behind doing it now is that we could make `with_imported=true` by default in Stats API. Otherwise, we'd need to exclude imported data whenever this metric is queried, or worse, only exclude imported data for this metric without a notice.
On the dashboard we have a tooltip, which is not ideal either as on mobile you wouldn't see it:
This PR removes that arbitrary limitation and starts including imported data in the calculation of `views_per_visit`.

Query imported data for views_per_visit

---

lib/plausible_web/templates/layout/site_settings.html.heex

This picker:
was broken by the way of #3810

Fix settings options mobile

---

lib/plausible_web/components/billing/notice.ex

we've had couple of situations recently where people contact us about this notice that we display in their accounts. 
they don't actually need to contact us as we have already created a new custom plan for them at that stage (we get notified ourselves when they go over their limits) so they can just upgrade directly in their account instead
and in the case that we didn't create a new plan already, the upgrade page will tell them to contact us

Change the CTA to upgrade now rather than contact us

---

CHANGELOG.md
priv/ingest_repo/migrations/20240222082911_sessions_v2_versioned_collapsing_merge_tree.exs

This migration will noop in staging/production as it already has been run. It also leaves behind a backup table that initially takes no extra space but will need to be cleaned up manually.
@ruslandoga Mind if I hand off handling the self-hosted side of this to you from here?

Ecto migration to move sessions_v2 to VersionedCollapsingMergeTree

---

lib/plausible_web/plugins/api/schemas/capabilities.ex
test/plausible_web/plugins/api/controllers/capabilities_test.exs

When no/bad token is provided, `data_domain` is null. The schema must reflect that.

Plugins API: mark data_domain as nullable in capabilities schema

---

test/plausible/stats/clickhouse_test.exs
test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
test/plausible_web/controllers/api/stats_controller/browsers_test.exs
test/plausible_web/controllers/api/stats_controller/cities_test.exs
test/plausible_web/controllers/api/stats_controller/countries_test.exs
test/plausible_web/controllers/api/stats_controller/custom_prop_breakdown_test.exs
test/plausible_web/controllers/api/stats_controller/funnels_test.exs
test/plausible_web/controllers/api/stats_controller/imported_test.exs
test/plausible_web/controllers/api/stats_controller/operating_systems_test.exs
test/plausible_web/controllers/api/stats_controller/regions_test.exs
test/plausible_web/controllers/api/stats_controller/screen_sizes_test.exs
test/plausible_web/controllers/api/stats_controller/sources_test.exs
test/plausible_web/controllers/api/stats_controller/suggestions_test.exs
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
test/plausible_web/controllers/stats_controller_test.exs
test/support/test_utils.ex
test/workers/send_email_report_test.exs

This affects only tests. As part of https://github.com/plausible/analytics/pull/3800, we started writing session properties via `session_`. After working on queries a while I realized this will complicate working with ecto significantly. This PR undoes that change.

Tests: session properties without the prefixes

---

lib/plausible/clickhouse_event_v2.ex
lib/plausible/ingestion/event.ex
lib/plausible/session/cache_store.ex
test/plausible/ingestion/event_test.exs
test/plausible_web/controllers/api/external_controller_test.exs
test/support/factory.ex
test/support/test_utils.ex

Depends on https://github.com/plausible/analytics/pull/3863
After this change, we will write event table session columns as events get ingested. Part of [the project to improve sessions and events table schemas](https://3.basecamp.com/5308029/buckets/35611491/messages/7061875211)

Write event table session columns

---

config/runtime.exs

This can cause issues as 1 day after a deploy the tzdata list is updated from 2021 to 2024. Selecting a timezone thats not supported in 2021 can then break dashboards temporarily following a deploy.
This can be reverted after https://github.com/plausible/analytics/pull/3811

Temporarily disable tzdata auto-updating

---

CHANGELOG.md
lib/plausible/stats/aggregate.ex
lib/plausible/stats/breakdown.ex
lib/plausible/stats/compare.ex
lib/plausible/stats/util.ex
lib/plausible_web/controllers/api/external_stats_controller.ex
lib/plausible_web/controllers/api/stats_controller.ex
test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs

This PR adds support for the time_on_page metric in Stats API.

Stats api time on page

---

lib/plausible/stats/compare.ex

Fixes a bug where Top Stats report crashes because of an ArithmeticError on calculating bounce rate. Introduced in https://github.com/plausible/analytics/pull/3858, more precisely https://github.com/plausible/analytics/pull/3858/commits/dab76296f6300abc630b97bce510a812da008628
Let's get that in quick to fix it. I'll add a test in a follow-up PR

Fix bounce_rate change bug

---

lib/plausible/stats/compare.ex
lib/plausible/stats/imported.ex
test/plausible_web/controllers/api/stats_controller/top_stats_test.exs

This PR tackles the problem that surfaced with https://github.com/plausible/analytics/pull/3858. The PR stopped casting `nil` values into zeros in the aggregate API **after** having fetched those results from ClickHouse:
Consequently some Top Stats queries crashed due to the `calculate_change` function blowing up when getting `nil` as input when expecting a number. This was mitigated with https://github.com/plausible/analytics/pull/3886, but it did not tackle the root cause of the issue. Hence, this PR rolls that change back - we can still keep relying on `bounce_rate` being a number in the `calculate_change` function.

Fix division by zero in imported queries

---

.github/workflows/elixir.yml

This PR attempts to speed up CI by:
- running `MIX_ENV=small_test` and `MIX_ENV=test` test suites in parallel
- building tracker conditionally (if it's missing or if it has changed)
- running static checks (format, credo, dialyzer) separately

Split Elixir CI jobs

---

CHANGELOG.md
lib/plausible_web/views/stats_view.ex

This PR fixes https://github.com/plausible/docs/issues/470
Here's how it looks in `bg-red-200 mx-auto max-w-md` container
And here's how it looks in `bg-red-200` container
And here's how it looks on master (where `max-w-screen-xl` was applied regardless of `width=manual`)

fix manual embed width

---

CHANGELOG.md
rel/overlays/init-admin.sh

This PR removes a self-hosted script that was deprecated in v2.0.0
Related:
- https://3.basecamp.com/5308029/buckets/29267832/card_tables/cards/5654487286
- https://github.com/plausible/analytics/pull/2357/files#diff-77b70fa380a802709c9ea8ed072df0c4194425604a61f0e13390d8717eaee37cR4-R5

remove init-admin.sh

---

CHANGELOG.md
config/runtime.exs

This PR removes deprecation warning for DISABLE_AUTH
Related:
- https://3.basecamp.com/5308029/buckets/29267832/card_tables/cards/5654485136
- DISABLE_AUTH  was deprecated in v2.0.0 https://github.com/plausible/analytics/pull/2357/files#diff-e43c5cbf91db7a8062b6cb860cbf118296c1b4c7ee32fdcf702e54234ba38092R134-R137

remove DISABLE_AUTH deprecation warning

---

lib/plausible_web/templates/page/index.html.eex

This PR adds some space after the logo on the index page.
Before (can be seen on https://who.copycat.fun):
After

add space after logo on the index page

---

CHANGELOG.md
mix.exs
rel/overlays/import_extra_config.exs
test/plausible/config_test.exs

This PR allows importing extra config as suggested in https://github.com/plausible/analytics/pull/3705#issuecomment-2002363143
It can serve as an easy escape hatch for specifying configurations not covered by env vars. Like https://github.com/plausible/analytics/pull/3823
Example:
<sub><kbd>my_config.exs</kbd></sub>
```elixir
import Config
config :plausible, Plausible.Repo,
after_connect: {Postgrex, :query!, ["SET search_path TO global_prefix", []]}
```
<sub><kbd>[docker-compose.yml](https://github.com/plausible/community-edition/blob/v2.1.0/docker-compose.yml)</kbd></sub>
```diff
plausible:
image: ghcr.io/plausible/community-edition:v2.1.0
+ volumes:
+   - ./my_config.exs:/app/my_config.exs
```
<sub><kbd>[plausible-conf.env](https://github.com/plausible/community-edition/blob/v2.1.0/plaus …

Allow importing extra config

---

config/.env.dev
config/.env.test
config/runtime.exs
lib/plausible/imported/csv_importer.ex
lib/plausible/s3.ex
lib/workers/export_csv.ex
test/plausible/config_test.exs
test/plausible/imported/csv_importer_test.exs
test/plausible/s3_test.exs

This PR extracts the "date range in filename" change from https://github.com/plausible/analytics/pull/3845

CSV imports (no UI)

---

CHANGELOG.md
lib/plausible_web/endpoint.ex
priv/static/robots.txt

This PR makes `robots.txt` restrictive by default in self-hosted setups.
Related:
- https://github.com/plausible/analytics/discussions/1798#discussioncomment-8209550
- https://3.basecamp.com/5308029/buckets/29267832/card_tables/cards/6961830456

make robots.txt restrictive by default

---

extra/lib/plausible/stats/goal/revenue.ex
lib/plausible/stats/aggregate.ex
lib/plausible/stats/base.ex
lib/plausible/stats/breakdown.ex
lib/plausible/stats/timeseries.ex
lib/plausible/stats/util.ex
test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
test/plausible_web/controllers/api/stats_controller/conversions_test.exs

Re-applies https://github.com/plausible/analytics/pull/3887
There was a bug when filtering by session attributes due to changed column ordering. See last commit for the reproducing test + fix.

Re-apply Move conversion_rate logic from elixir to clickhouse

---

lib/plausible/stats/breakdown.ex
test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs

Unexpectedly, table.name caused a name clash after CR refactor, so using a unique name for the output column
Sentry issue: https://sentry.plausible.io/organizations/sentry/issues/5612

Fix issue with query name clash
