plausible/analytics

- lib/plausible/exports.ex
- lib/plausible/s3.ex
- lib/plausible/sites.ex
- lib/workers/export_csv.ex
- test/plausible/exports_test.exs
This PR changes how the exported Zip archive is named, from `Plausible.zip` to `#{domain}_#{start_date}_#{end_date}.zip`
> Include domain and dates in zip archive filename

- CHANGELOG.md
- assets/js/dashboard/stats/graph/graph-util.js
- assets/js/dashboard/stats/graph/visitor-graph.js
- lib/plausible/stats/metrics.ex
- lib/plausible/stats/timeseries.ex
- lib/plausible_web/controllers/api/external_stats_controller.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
- test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
This PR adds the `conversion_rate` metric into the Stats API timeseries, and also makes it possible to display it on the main graph.
Keeping this as a draft for now, since it builds upon https://github.com/plausible/analytics/pull/3887
> Timeseries for conversion rate

- assets/js/dashboard/filters.js
Sends a `Filter Menu: Open` custom event when someone clicks on the 'Filter' button in the dashboard.
> Filter button custom event

- lib/plausible/ingestion/event.ex
- lib/plausible_web/refinspector.ex
- test/plausible_web/controllers/api/external_controller_test.exs
Overall task is figuring out if we can separate the Google Discover referral source from Google (the search engine). Some sources say that the referrer `android-app://com.google.android.googlequicksearchbox` is Google Discover but other sources say different things. I want to check our actual data to see which bloggers are most correct.
We currently only store referral sources with `http` and `https` protocol in the URI. With this change we'll also be storing referrers with `android-app://` protocol. This will allow me to correlate this referrer data with proprietary numbers from Google Search Console to see if the number of visitors is similar.
> Store referrers from android apps

- assets/js/dashboard/stats/graph/graph-util.js
This PR only capitalizes a single letter to make a metric on the graph tooltip consistent with the others.
> Capitalize a letter

- CHANGELOG.md
- assets/js/dashboard/stats/sources/source-list.js
I tried making escaping more DRY in general but couldn't make it work with custom prop filters which are special.
Fixes #3893
> Fix escaping of source filters

- .github/workflows/migrations-validation.yml
We discussed that it would be good to catch cases where we try to deploy migrations and app changes at the same time. This PR adds a minimal github action for that.
Example success:
Example failure:
> Add github action to validate whether migrations and app change at the same time

- assets/js/liveview/live_socket.js
- lib/plausible/exports.ex
- lib/plausible/imported/csv_importer.ex
- lib/plausible_web/controllers/site_controller.ex
- lib/plausible_web/live/csv_import.ex
- lib/plausible_web/router.ex
- lib/plausible_web/templates/site/csv_import.html.heex
- lib/plausible_web/templates/site/settings_imports_exports.html.heex
This PR adds UI for CSV imports via S3.
https://github.com/plausible/analytics/assets/67764432/7ee9daf4-411c-4fa0-9f01-b174e8233862
> CSV imports (UI)

- fixture/ga4_end_date.json
- fixture/ga_end_date.json
- fixture/ga_start_date_later.json
- lib/plausible/google/api.ex
- lib/plausible/google/ga4/api.ex
- lib/plausible/google/ga4/http.ex
- lib/plausible/google/ua/api.ex
- lib/plausible/google/ua/http.ex
- lib/plausible/imported.ex
- lib/plausible_web/controllers/google_analytics_controller.ex
- lib/plausible_web/live/imports_exports_settings.ex
- lib/plausible_web/templates/google_analytics/confirm.html.heex
- lib/plausible_web/templates/google_analytics/user_metric_form.html.heex
- test/plausible/google/ga4/api_test.exs
- test/plausible/imported_test.exs
- test/plausible_web/controllers/google_analytics_controller_test.exs
The main change in this PR is introduction of logic setting import's date range. 
Currently import's end date is always set to either native stats start date or today if there are no native stats collected yet. After this change, the end date will be set to the date of the actual last imported stats entry. When doing import in presence of other imported data, the new import's date range will be additionally cropped so that it does not overlap with any existing import - in addition to being cropped by native stats start date.
Other improvements done by the way:
- improved error handling in import process
- pageview numbers in imports list made more legible and redundant prefix dropped
> Implement adjusting imported date range to actual and existing stats

- lib/plausible/data_migration/site_imports.ex
- lib/plausible/imported.ex
- lib/plausible_web/controllers/site_controller.ex
- test/plausible/data_migration/site_imports_test.exs
~Depends on #3943~
This PR implements a data migration that:
1. creates `SiteImport` entries for all existing legacy import that miss it
2. adjusts `end_date` of all `SiteImport` entries to reflect the date of last entry for a given import across all `imported_*` tables in CH
Additionally, there are alterations in `Imported` to account for the fact that legacy `SiteImport` can refer to either entries in CH with Import ID matching it _or_ `0` for the truly legacy, backfilled imports.
> Implement script for backfilling legacy site import entries and adjusting end dates of site imports

- assets/js/dashboard/stats/graph/visitor-graph.js
- lib/plausible/imported.ex
- lib/plausible/site.ex
- lib/plausible/stats/query.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- lib/plausible_web/templates/email/google_analytics_import.html.heex
- test/plausible/imported_test.exs
- test/plausible_web/controllers/api/stats_controller/imported_test.exs
- test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
* Check import presence across all imports and not just the first one
* Simplify imported data toggle rendering to not explicitly refer to the earliest import source.
* Change imported stats toggle icon and tooltip in the dashboard
* Simplifiy failed UA/GA import email copy
> Improve import stats toggle and `with_imported` flag computation

- priv/ingest_repo/migrations/20240327085855_hostnames_in_sessions.exs
This PR adds `exit_page_hostname` to `sessions_v2` table, so that we can filter by hostnames avoiding joining `events_v2` where possible.
https://3.basecamp.com/5308029/buckets/26383192/card_tables/cards/6925576254
> CH Migration: exit page hostname on sessions_v2

- assets/js/dashboard/api.js
- assets/js/dashboard/query.js
- assets/js/dashboard/util/filters.js
- lib/plausible/stats/filter_suggestions.ex
- lib/plausible/stats/query.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- test/plausible_web/controllers/api/stats_controller/pages_test.exs
- test/plausible_web/controllers/api/stats_controller/sources_test.exs
- test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
This PR removes `experimental_hostname_filter` from #3963 making this behaviour default. Hostname filter alone is still kept behind `hostname_filter` feature flag.
> Remove `experimtnal_hostname_filter` and keep it on by default

- lib/plausible_web/templates/stats/site_locked.html.heex
changing the copy here as I think that in some situations the "we're still counting stats" message is now shown even to those dashboards where we've stopped counting stats so best to avoid that
> Changing the copy of the locked screen

- lib/plausible/google/ga4/http.ex
- lib/plausible/google/ua/http.ex
- lib/plausible_web/controllers/google_analytics_controller.ex
- test/plausible_web/controllers/google_analytics_controller_test.exs
This PR improves feedback on Google API timeout errors when doing stats imports.
> Handle Google API timeouts gracefully during imports

- lib/plausible/imported.ex
- lib/plausible/imported/importer.ex
- lib/plausible_web/controllers/google_analytics_controller.ex
- lib/plausible_web/controllers/site_controller.ex
- lib/plausible_web/live/imports_exports_settings.ex
- lib/plausible_web/templates/site/settings_imports_exports.html.heex
- test/plausible/imported/google_analytics4_test.exs
- test/plausible_web/controllers/google_analytics_controller_test.exs
- test/plausible_web/controllers/site_controller_test.exs
This PR ensures that a new import can be started only if all the current ones are in completed state for a given site.
When check import's time range and altering it so that we avoid overlap, only complete imports are considered. If more than a single import is in progress at a time, there's a risk of ending up in inconsistent state where imports do overlap one another.
The check is enforced on UI level for Google imports as well as on Importer level to avoid a situation where multiple jobs get created for the same import due to, for instance, double form submission.
> Improve import procedure to ensure no time range overlaps

- lib/plausible/application.ex
- lib/plausible/request_logger.ex
- lib/plausible_web/endpoint.ex
Ultimate goal is to be able to compare results with and without a flag against each other. To do this we need logging which displays the full request url with parameters.
Example logs:
```
14:46:09.042 request_id=F8MRLSsaKB7BeIkAAAHk [info] (200) GET /api/sites took 17ms
14:46:09.175 request_id=F8MRLTKYV3G-GqEAAAZB [info] (200) GET /api/stats/dummy.site/current-visitors took 24ms
14:46:09.396 request_id=F8MRLUDfav28LIkAAAIE [info] (202) POST /api/event took 5ms
14:46:09.501 request_id=F8MRLUDS_YhftUkAAAAD [info] (200) GET /api/stats/dummy.site/sources?period=30d&date=2024-04-04&filters=%7B%7D&with_imported=true&limit=9 took 111ms
14:46:09.508 request_id=F8MRLUDhHbK8WKUAAAah [info] (200) GET /api/stats/dummy.site/main-graph?period=30d&date=2024-04-04&filters=%7B%7D&with_imported=true&metric …
```
> Include query string when logging the request

- lib/workers/clickhouse_clean_sites.ex
- test/workers/clickhouse_clean_sites_test.exs
Add a new worker to clean deleted sites data from clickhouse.
This will eventually become a cronjob, for now running it manually on cloud.
> Worker to clean site data from ClickHouse

- lib/plausible/imported.ex
- lib/plausible_web/controllers/google_analytics_controller.ex
- test/plausible/imported_test.exs
Refactor `Imported.check_dates` (renamed to `clamp_dates` in the process) to make it more suitable for use outside Google Analytics import flow.
> Refactor `Imported.check_dates` (->`clamp_dates`) for better felxibility

- lib/plausible_web/templates/layout/base_email.html.eex
- lib/plausible_web/templates/layout/priority_email.html.eex
- test/plausible_web/email_test.exs
This PR removes
> Regards
> The Plausible Team 💌
from self-hosted emails.
> remove Plausible Team footer from self-hosted emails

- lib/plausible/data_migration/site_imports.ex
- test/plausible/data_migration/site_imports_test.exs
Alternative, more correct solution in place of #3977.
The legacy `imported_data` are kept in sync as the struct is still used by logic rendering import state in "Integrations" view.
Once we fully switch to the new "Imports & Exports" UI, `imported_data` will be cleared from the logic and removed completely.
> Keep `sites.imported_data` in sync with backfilled `SiteImport` when migrating

- lib/plausible/data_migration/site_imports.ex
- test/plausible/data_migration/site_imports_test.exs
This PR makes further adjustments to ensure only complete site imports and "ok" imported data are considered for migration.
> Ensure only complete imports are considered in site imports data migration

- lib/plausible/stats/props.ex
- lib/plausible_web/controllers/api/external_stats_controller.ex
- test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
- test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
- test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
Currently a 500 is returned instead and logged to sentry.
Long-term it would be great to unify how filters work and unify parsing and validation.
> Return 400 when using invalid filters for stats api

- lib/plausible/stats/breakdown.ex
The [original diff](https://github.com/plausible/analytics/pull/3966) had an important code branch commented out, causing events table to be queried for breakdowns with the flag off. :facepalm:
> Fix experimental_reduced_joins

- lib/plausible/stats/props.ex
- test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
This got in too early, while the hostname filter is still being worked on and its behaviour may be subject to change.
> Remove hostname filter from the external API

- lib/plausible/stats/breakdown.ex
- lib/plausible_web/controllers/api/stats_controller.ex
We currently update the query filtered by hostname to its respective visit props in some cases.
This patch moves it down, from controllers, to the Breakdown module, so any changes in logic will be also reflected in the Stats API.
> Move hostname filter appending to Breakdown module

- lib/plausible/stats/breakdown.ex
- test/plausible_web/controllers/api/stats_controller/sources_test.exs
In reference to https://github.com/plausible/analytics/pull/3998#issuecomment-2046813239 - this PR adds hostname filtering support when the breakdowns are made by `visit:utm*` and `visit:referrer` properties.
> Discard sessions switching hostnames for UTM/referrer breakdowns

- lib/plausible/imported/csv_importer.ex
- lib/plausible_web/templates/email/csv_import.html.heex
This PR adds a new email template for CSV imports and starts using it in CSVImporter instead of the GA one.
> use custom email template for csv imports

- lib/plausible/stats/imported.ex
This PR removes no-op coalesce calls from joined columns.
ClickHouse doesn't make columns Nullable after a full join, instead they become the default value for the type (some kind of zero usually): https://play.clickhouse.com/play?user=play#d2l0aCBhIGFzIChzZWxlY3QgKiBmcm9tIG51bWJlcnMoMTApKSwgYiBhcyAoc2VsZWN0IG51bWJlciArIDUgYXMgbnVtYmVyIGZyb20gbnVtYmVycygxMCkpIHNlbGVjdCBhLm51bWJlciwgYi5udW1iZXIgZnJvbSBhIGZ1bGwgam9pbiBiIG9uIGEubnVtYmVyID0gYi5udW1iZXI7
> remove no-op coalesce calls

- fixture/ga4_report_imported_sources.json
- lib/plausible/google/ga4/report_request.ex
- lib/plausible/imported/google_analytics4.ex
- test/plausible/imported/google_analytics4_test.exs
This PR removes `pageReferrer` from GA4 import. As this is en event-scoped dimension, combining it with session-scoped dimensions results in overcounting due to explosion of combinations (which also means that the results contain significant overlap between sessions and can't be added for calculating aggregates). See also: https://github.com/plausible/analytics/pull/4014/commits/4cbd29789cfaef1f80a7ac42680b1c5eb535790d
> Stop importing page referrer from GA4

- assets/js/dashboard/stats/sources/search-terms.js
slight change to the message we show when no search terms are found to avoid talking about delay for older time periods where it's not relevant
> slight change to the message we show when no search terms are found

- lib/plausible/imported.ex
- test/plausible/imported_test.exs
This PR addresses a bug where when imports done in non-chronological order of their date ranges could cause unwanted overlap.
> Always sort occupied date ranges in `Imported.clamp_dates/3`

- lib/plausible/stats/breakdown.ex
- test/plausible/imported/google_analytics4_test.exs
This PR improves the existing `GoogleAnalytics4Test`, asserting the fixture-imported data using Stats API queries. Builds upon #4003. Only commits relevant to the PR at hand are the ones after https://github.com/plausible/analytics/pull/4014/commits/35cf11f2bbdf58ed890e1ac8d7d6a0c16363a9ff.
In addition to improving the test, this PR also makes a slight change in the `event:page` breakdown, querying the `visits` metric from the `events` table rather than `sessions`.
> Test new imported metrics (GA4)

- lib/plausible_web/templates/stats/waiting_first_pageview.html.heex
we've had people ask how to start by importing their data first before integrating Plausible into their site (and some also want just to import and store their GA stats in Plausible rather than use Plausible to collect new stats) so the idea here is to give people access to the site settings area directly from the "Waiting for first pageview" screen
> Add link to settings on the "Waiting for first pageview" screen

- lib/plausible/google/ua/http.ex
- lib/plausible_web/live/imports_exports_settings.ex
This PR introduces slight visual improvements when rendering failed imports:
* the warning sigh preceding the label is red
* "(Import failed)" preceeds the label for added clarity
* Deletion button states "Discard" to avoid suggesting that it's a functional import
* All in progress and failed imports state "started on DD-MM-YYYY" and "imported on DD-MM-YYYY " is only shown by completed ones)
This should further reduce the chance of missing the fact that the entry is for a failed import which can only be discarded.
Additionally, failed request debug logging for UA was extended to be on par with GA4.
> Improve UI for failed import entry case

- lib/plausible_web/components/billing/plan_box.ex
- lib/plausible_web/live/choose_plan.ex
- test/plausible_web/live/choose_plan_test.exs
This PR adds tooltips about specific limits exceeded if the current usage doesn't allow plan change. The tooltips normally appear on hover, become sticky on click and disappear on click-away.
> Display upgrade tooltips for exceeded limits

- lib/plausible/site/admin.ex
Minor adjustment to Sites CRM.
> Remove "Stats start date" and adjust "Native stats start time" in Sites CRM

- lib/plausible/google/ga4/api.ex
- test/plausible/google/ga4/api_test.exs
Bumps page size to the maximum allowed by GA4.
Also, handles completely empty GA4 properties list response gracefully.
> Bump GA4 import page limit to max 250k

- lib/plausible_web/components/billing/plan_box.ex
- lib/plausible_web/components/generic.ex
- lib/plausible_web/live/choose_plan.ex
- test/plausible_web/live/choose_plan_test.exs
Another iteration of #4032 - pairing with @RobertJoonas 
https://github.com/plausible/analytics/assets/173738/3e871ffd-4e08-40a4-8d84-4d7a38b13eac
> Display tooltips on plan change when limits exceeded

- lib/oban_error_reporter.ex
- lib/plausible/google/ga4/api.ex
- lib/plausible/google/ga4/http.ex
- lib/plausible/imported/google_analytics4.ex
- lib/plausible/imported/importer.ex
- lib/plausible/imported/noop_importer.ex
- lib/plausible_web/components/billing/plan_box.ex
- lib/plausible_web/components/generic.ex
- lib/plausible_web/controllers/google_analytics_controller.ex
- lib/plausible_web/live/imports_exports_settings.ex
- lib/workers/import_analytics.ex
- test/plausible/imported/google_analytics4_test.exs
- test/plausible_web/controllers/google_analytics_controller_test.exs
- test/plausible_web/controllers/site_controller_test.exs
This PR implements graceful handling of rate limiting error (HTTP code 429) returned by Google Data API (GA4). When it occurs, instead of retrying the request immediately or discarding the import entirely, another import job is scheduled for the same exact site import, resuming the import process at the exact dataset and offset position where it failed. The job is scheduled 65 minutes in the future - the hourly rate limit on the property should be reset by then. All the existing data fetched for that import so far are left intact.
In addition, all other HTTP calls to the GA Data API are returning explicit error message on hitting rate limit error so that the user is aware that it should work again when they try later.
The imports list displays a notice tooltip by in-progress import when …
> Implement resumable GA4 imports to work around rate limiting

- lib/plausible/stats.ex
- lib/plausible/stats/aggregate.ex
- lib/plausible/stats/breakdown.ex
- lib/plausible/stats/email_report.ex
- lib/plausible/stats/imported.ex
- lib/plausible/stats/query.ex
- lib/plausible_web/controllers/api/external_stats_controller.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
- test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
This PR adds a `property` field into the `Stats.Query` struct, and uses it around the codebase instead of passing it as a separate argument to `Stats.Breakdown`.
There are no behavioural changes introduced here, except a tiny modification to tracing the `event:page` property in the `event:page` breakdown query (which I think is the desired behaviour). Instead of `visit:entry_page` which is the actual requested breakdown prop.
**Motivation for this change**
With the upcoming changes related to imported custom events and filtering by imported data, evaluating the `include_imported` field in the Query struct depends on the breakdown property.
Simply passing the `property` into the `Query.from` function and **not** persisting it in the struct is not enough. That's because we need to be able …
> Include breakdown property in the Query struct

- CHANGELOG.md
- assets/js/dashboard/datepicker.js
- assets/js/dashboard/util/date.js
Adds Yesterday option to dashboard time range picker. The keyboard shortcut has worked for the past few years already.
Motivation: https://feedback.plausible.io/264, warmup after vacation on a flight
> Add Yesterday as an time range option in the dashboard

- lib/plausible/exports.ex
- lib/plausible/s3.ex
- lib/plausible_web/controllers/site_controller.ex
- lib/plausible_web/email.ex
- lib/plausible_web/live/csv_export.ex
- lib/plausible_web/router.ex
- lib/workers/notify_exported_analytics.ex
- test/plausible/imported/csv_importer_test.exs
- test/workers/notify_exported_analytics_test.exs
https://3.basecamp.com/5308029/buckets/35871979/card_tables/cards/6945042601#__recording_7282802614
> redirect to s3 url when downloading exports

- lib/plausible/stats/timeseries.ex
- test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
- test/test_helper.exs
After this PR:
- For timeseries, sessions are counted each time bucket its active in for hourly/minute timeseries
- `experimental_session_count` flag is tested together with `experimental_reduced_joins`
Motivation: https://3.basecamp.com/5308029/buckets/35611491/messages/7085680123
If graphing timeseries by session.timestamp (end time) we don't show sufficient data. Instead, for hourly and minute graphs we show sessions in each bucket they're active in. We're not doing this for other graphs since the error margin is not worth the extra overhead.
> Return session in each time bucket its active in for hourly/minute timeseries

- lib/plausible/exports.ex
This PR starts using `toDate(sessions_v2.timestamp)` instead of `toDate(sessions_v2.start)` when preparing exports.
It uniformly decreases the differences between native and imported query results in https://github.com/plausible/analytics/pull/4037
> use sessions timestamp for exports' dates

- config/runtime.exs
> run Oban in CE too

- lib/plausible/exports.ex
Addresses a problem of undercounting visits when number of entries processed in the export query exceeds sampling threshold.
> Apply sampling factor multiplication consistently across CSV export queries

- priv/ingest_repo/migrations/20240423094014_add_imported_custom_events.exs
Extracted migration from #4033. Also added `path` column which will be needed later on when exporting 404 goals into CSV.
> Migration: add imported custom events

- lib/plausible/stats/query.ex
- test/plausible/stats/query_test.exs
Previous code wasn't properly omitting event property filters from queries.
Fixing the code causes issues with external_stats_controllers validations so I propose we just drop this.
> Remove `maybe_drop_prop_filter`

- lib/plausible/sites.ex
- lib/plausible/stats/query.ex
- test/plausible/stats/query_test.exs
More info: https://3.basecamp.com/5308029/buckets/35871979/card_tables/cards/7202028179#__recording_7227349424
> drop local_start_date/1

- lib/plausible/exports.ex
This PR makes locations exports non-empty for people with only country mmdb installed.
> allow empty city geonames in exports

- lib/plausible/imported.ex
- lib/plausible_web/controllers/google_analytics_controller.ex
- lib/plausible_web/live/imports_exports_settings.ex
- lib/plausible_web/templates/site/settings_imports_exports.html.heex
- lib/plausible_web/views/layout_view.ex
- priv/repo/seeds.exs
- test/plausible_web/controllers/site_controller_test.exs
- test/test_helper.exs
This PR removes both, `imports_exports` and `csv_imports_exports` flags from the code as they are fully enabled in production now.
> Remove `imports_exports` and `csv_imports_exports` feature flags

- lib/plausible/stats/filter_suggestions.ex
I was starting to use filter_suggestions API for custom event names suggestions and this was the preliminary refactoring. Later on I changed my mind but this can still go in.
> Refactor filter suggestions with a more DRY approach

- lib/plausible/google/ga4/api.ex
- lib/plausible/google/ga4/http.ex
- test/plausible/imported/google_analytics4_test.exs
It turns out that google Data API (GA4 import) payload for dataset without any results is missing `rows` and `rowCount` fields. This change makes import procedure handle such cases gracefully.
> Avoid crashing on empty GA4 HTTP report response

- lib/plausible/goal/schema.ex
- lib/plausible/goals.ex
- lib/plausible/stats/goal_suggestions.ex
- lib/plausible_web/live/goal_settings.ex
- lib/plausible_web/live/goal_settings/form.ex
- lib/plausible_web/live/goal_settings/list.ex
- test/plausible/stats/goal_suggestions_test.exs
- test/plausible_web/live/goal_settings_test.exs
Instead of providing event name suggestions when adding a goal, we've decided for the time being to add an option to "autoconfigure" all event names that we've received as custom event goals. The UX is very similar to how custom properties are added, based on the data from the last 6 months.
> Autoconfigure event goals

- CHANGELOG.md
- config/runtime.exs
- lib/plausible/exports.ex
- lib/plausible/imported/csv_importer.ex
- test/plausible/config_test.exs
This PR adds a new env var DATA_DIR which would configure where exports/imports/mmdb/tzdata go in self-hosted setups. If PERSISTENT_CACHE_DIR is also provided, it takes precedence when configuring where mmdb and tzdata go.
Relevant: https://3.basecamp.com/5308029/buckets/35871979/card_tables/cards/7377179488
> add DATA_DIR

- lib/plausible/clickhouse_repo.ex
- lib/plausible/stats/clickhouse.ex
Currently, the settings page time outs for a user with 14k sites.
This PR speeds things up by:
1. Doing the work in parallel (max 10 queries at once)
2. Increasing chunking size (300 -> 1000)
Note that the query is relatively lightweight on clickhouse - running
these queries manually takes ~70ms. If this becomes slow we can also
introduce a PROJECTION to speed up the calculation, but this wasn't a
bottleneck currently.
On chunking size:
ClickHouse can handle even 10k site_ids in a single query fast if run
via clickhouse-client , but running the same query via ecto_ch it becomes
really slow (60ms vs 1s).
Not sure if this is a driver, serialization or networking issue.
Some other alternative solutions were discarded:
- Making the query async: requires refactoring the settings page …
> Speed up calculating monthly usage for users with many many sites

- lib/plausible/billing/feature.ex
- test/plausible/billing/feature_test.exs
Currently, business tier users created after business tier launch who never used the trial can't access Stats API due to faulty grandfathering logic. This change should fix that.
> Fix StatsAPI access for new accounts on business tier

- lib/plausible/stats/breakdown.ex
- lib/plausible/stats/imported.ex
- lib/plausible_web/controllers/api/external_stats_controller.ex
- test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
- test/plausible_web/controllers/stats_controller_test.exs
This PR improves graceful fallback for unsupported metrics and properties combinations when querying imported stats and also fixes breaking down by `event:hostname` property which turned out to be defunct.
The assisting documentation update is available at https://github.com/plausible/docs/pull/499
> Improve test coverage and fix stats API and dashboard CSV export

- assets/js/dashboard/stats/modals/regular-filter-modal.js
Quick fix for a frontend bug. Explanation: https://cap.link/4sh44v2japssn2w
> Fix unselecting filter from filter modal

- lib/plausible_web/live/plugins/api/settings.ex
- lib/plausible_web/live/plugins/api/token_form.ex
- lib/plausible_web/plugins/api/spec.ex
- lib/plausible_web/templates/site/settings_integrations.html.heex
- test/plausible_web/live/plugins_api_tokens_test.exs
Deployment needs to be coordinated with WordPress plugin update. Reasoning: there's too much confusion coming from the use of the "API" terminology, leading to wrong keys being generated by users.
> Rename Plugins API Token(s) to Plugin Token(s)

- Dockerfile
- lib/plausible.ex
- lib/plausible/auth/totp.ex
- lib/plausible_web/email.ex
- lib/plausible_web/live/register_form.ex
- lib/plausible_web/mjml/templates/stats_report.mjml.eex
- lib/plausible_web/templates/email/approaching_accept_traffic_until.html.heex
- lib/plausible_web/templates/email/dashboard_locked.html.eex
- lib/plausible_web/templates/email/existing_user_invitation.html.eex
- lib/plausible_web/templates/email/export_failure.html.eex
- lib/plausible_web/templates/email/export_success.html.eex
- lib/plausible_web/templates/email/new_user_invitation.html.eex
- lib/plausible_web/templates/email/over_limit.html.eex
- lib/plausible_web/templates/email/ownership_transfer_request.html.eex
- lib/plausible_web/templates/email/yearly_expiration_notification.html.eex
- lib/plausible_web/templates/email/yearly_renewal_notification.html.eex
- lib/plausible_web/templates/layout/focus.html.heex
- lib/plausible_web/templates/page/index.html.eex
- lib/plausible_web/templates/site/settings_search_console.html.heex
- test/plausible/plausible_test.exs
- test/plausible/site/admin_test.exs
- test/plausible/site/memberships/accept_invitation_test.exs
- test/plausible/site/memberships/create_invitation_test.exs
- test/plausible/site/memberships/reject_invitation_test.exs
- test/plausible_web/controllers/page_controller_test.exs
- test/plausible_web/controllers/site/membership_controller_test.exs
This PR removes some of Plausible Analytics mentions from CE builds. There are still places where this mention is kept:
- https://github.com/plausible/analytics/blob/23a6431adbd61553fed1b658485d469c025b492b/assets/js/app.js#L108 since the link leads to plausible.io and not the CE instance
- https://github.com/plausible/analytics/blob/23a6431adbd61553fed1b658485d469c025b492b/lib/plausible_web/controllers/stats_controller.ex#L381 since it's unlikely a CE user would add plausible.io site
- https://github.com/plausible/analytics/blob/23a6431adbd61553fed1b658485d469c025b492b/lib/plausible_web/templates/layout/_footer.html.heex#L23 since the link leads to plausible.io and not the CE instance
- https://github.com/plausible/analytics/blob/23a6431adbd61553fed1b658485d469c025b492b/lib/plausible_web/ …
> remove Plausible Analytics metions from CE

- assets/js/dashboard/stats/behaviours/goal-conversions.js
Follow-up to https://github.com/plausible/analytics/pull/4117
Special goals (e.g. 404, Outbound link click) always reported (none) as results due to a function returning the wrong value.
> Fix special goal conversions

- assets/js/dashboard/stats/modals/filter-modal.js
Follow-up to #4117
Opening a utm modal crashed if there was an existing page filter. Bug struck in during a last-minute renaming. :facepalm:
> Fix opening a filter modal

- lib/plausible/verification/checks/fetch_body.ex
- lib/plausible/verification/checks/installation.ex
- lib/plausible/verification/diagnostics.ex
- priv/verification/verify_plausible_installed.js
- test/plausible/site/verification/checks_test.exs
Various integration verification improvements found out during live testing.
> Verification improvements

- lib/plausible/verification/checks/fetch_body.ex
- lib/plausible/verification/checks/snippet.ex
- lib/plausible/verification/diagnostics.ex
- test/plausible/site/verification/checks/fetch_body_test.exs
- test/plausible/site/verification/checks/snippet_test.exs
- test/plausible/site/verification/checks_test.exs
- extend the list of known attributes
- follow redirect chain host to verify data-domain difference
- display the actual data-domain in error message, not URL
> More fixes to the verification process

- priv/ingest_repo/migrations/20240502115822_alias_api_prop_names.exs
This PR removes some warnings that show up on new CE installations:
```
plausible-1            | Loading plausible..
plausible-1            | Starting dependencies..
plausible-1            | Starting repos..
plausible-1            | Running migrations for Elixir.Plausible.Repo
plausible-1            | Running migrations for Elixir.Plausible.IngestRepo
plausible-1            | warning: code block contains unused literal "Migration adds a ALIAS columns needed to keep DB schema and api\nproperty naming in sync to reduce overhead in code.\n" (remove the literal or assign it to _ to avoid warnings)
plausible-1            | └─ lib/plausible-0.0.1/priv/ingest_repo/migrations/20240502115822_alias_api_prop_names.exs: Plausible.IngestRepo.Migrations.AliasApiPropNames (module)
plausible-1 …
```
> remove warning in migration

- assets/js/dashboard/stats/graph/with-imported-switch.js
Currently, when clicking on the imported exclude/include icon on the dashboard (see `with-imported-switch.js`), it doesn't set the `with_imported` to false due to PlausibleSearchParams class dropping any keys with `false` boolean value. The default for the `with_imported` field is `true` so we need to explicitly set it to false sometimes. Otherwise we'd end up with a URL identical to the current location, and the button simply doesn't work.
What I've done here is set the value as a string instead. Not aware of any other cases of this causing problems but maybe it would be worth to double-check (cc @macobo ). Is it necessary to drop the keys with false values or is it only an optimization?
> Fix setting with_imported to false explicitly in the URL

- lib/plausible.ex
This PR makes Plausible.ce? and Plausible.ee? into functions. No need to `require Plausible` to use them, and no need to worry about the context they are executed in. Related: https://github.com/plausible/analytics/pull/4155#issuecomment-2137036917
> make Plausible.ce? and Plausible.ee? into functions

- lib/plausible/data_migration/site_imports.ex
- lib/plausible/data_migration/versioned_sessions.ex
- priv/repo/migrations/20240528115149_migrate_site_imports.exs
- priv/repo/seeds.exs
This PR makes site_imports be automatically populated from sites.imported_data on startup for CE builds. Right now the self-hosters need to do it manually. See https://github.com/plausible/analytics/discussions/4125#discussioncomment-9580118
> Populate site_imports from sites.imported_data in CE

- assets/js/dashboard/stats/locations/index.js
- assets/js/dashboard/stats/locations/map.js
- assets/js/dashboard/stats/modals/conversions.js
- assets/js/dashboard/stats/modals/entry-pages.js
- assets/js/dashboard/stats/modals/exit-pages.js
- assets/js/dashboard/stats/modals/pages.js
- assets/js/dashboard/stats/modals/props.js
- assets/js/dashboard/stats/modals/referrer-drilldown.js
- assets/js/dashboard/stats/modals/sources.js
- assets/js/dashboard/stats/modals/table.js
- assets/js/dashboard/stats/reports/list.js
With the new imported data filtering feature, we'll start returning warnings in the dashboard API results, which means we'll need to move the actual list of results under a separate `results` key.
This PR is a preparation in order to not break the frontend when suddenly receiving API results under a `results` key. For some time, we'll need to be able to handle both a straight-up list response, or a map, containing the `results` key.
> Make React frontend capable of reading API results under a results key

- lib/plausible/verification/diagnostics.ex
- lib/plausible/verification/errors.ex
- lib/plausible_web/live/components/verification.ex
This PR:
- puts an ellipsis and disables text overflow in case of very long data-domain, upon verification error when the recommendation includes it
- accepts 200 callback status from WordPress sites
> Minor verification improvements

- lib/plausible/data_migration/versioned_sessions.ex
This PR fixes https://github.com/plausible/analytics/discussions/4161
This PR fixes https://github.com/plausible/analytics/issues/4167
> fix VersionedSessions migration

- lib/plausible_web/live/register_form.ex
This PR fixes the registration issue reported in https://github.com/plausible/analytics/discussions/4164 (submitting the form doesn't redirect to the next step)
> fix registration in ce

- lib/plausible/verification/checks/scan_body.ex
- lib/plausible/verification/checks/snippet.ex
- lib/plausible/verification/diagnostics.ex
- lib/plausible/verification/errors.ex
- test/plausible/site/verification/checks/scan_body_test.exs
- test/plausible/site/verification/checks/snippet_test.exs
- test/plausible/site/verification/checks_test.exs
- don't report multiple snippets error if manual script extension is used - the user should know what they're doing at this point
- naively look for cookiebot consent banner when GTM is used, in which case our script may not load just yet
> More verification tweaks

- lib/plausible/imported.ex
- lib/plausible/stats/imported/base.ex
- lib/plausible/stats/imported/imported.ex
- test/plausible/stats/query_test.exs
This PR fixes two bugs:
* stop adding an additional filter in imported.ex through the `maybe_apply_filter` function which was used before imported filtering was possible. This currently crashes in a situation where we're trying to filter by `:member` of the `url` property for example.
* When props are included in the query, we are currently only accounting for the situation where the breakdown property is a special prop - we need to do the same if there's a custom property in filters.
> Fix handling filtering by imported special properties

- priv/repo/migrations/20240528115149_migrate_site_imports.exs
This PR restores the fix https://github.com/plausible/analytics/pull/4155/commits/14fbfc0e52f70d3552224754107b296c86ec7704 for the data migration added in https://github.com/plausible/analytics/pull/4155
> Wrap data migration using with_repo to ensure ClickhouseRepo is running

- assets/js/dashboard/stats/behaviours/index.js
- assets/js/dashboard/stats/devices/index.js
- assets/js/dashboard/stats/graph/visitor-graph.js
- assets/js/dashboard/stats/graph/with-imported-switch.js
- assets/js/dashboard/stats/imported-query-unsupported-warning.js
- assets/js/dashboard/stats/locations/index.js
- assets/js/dashboard/stats/pages/index.js
- assets/js/dashboard/stats/sources/referrer-list.js
- assets/js/dashboard/stats/sources/source-list.js
- lib/plausible/stats/comparisons.ex
- lib/plausible/stats/query.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
The main goal of this PR was to fix some behaviour with the dashboard "with-imported" switch and move its logic into the backend, making its intent more clear and easily testable. I've also included some other changes that I saw necessary. Here's a summary:
* Change the tooltip message when the icon is hovered:
* "Stats do not include imported data" -> "Click to include imported data" 
* "Stats include imported data" -> "Click to exclude imported data"
* Slight refactor: instead of keeping a boolean state of whether the imported query is unsupported, keep the `skipImportedReason` in the state instead and let the `ImportedQueryUnsupportedWarning` component decide how to interpret that.
* When the query does not support imported data and imported data is excluded, disable clicking the …
> Fix with imported switch + warning bubble renders

- assets/js/dashboard/stats/graph/with-imported-switch.js
Follow-up fix to https://github.com/plausible/analytics/pull/4187
The `pointer-events-none` class didn't take effect on Safari, leaving the imported switch still clickable when it was actually supposed to be disabled. This PR changes to an alternate implementation to accomplish the same. Tested manually on Safari, Chrome, and Firefox.
> Small fix for the with-imported-icon on safari

- config/test.exs
- extra/lib/plausible/funnel/step.ex
- extra/lib/plausible/funnels.ex
- extra/lib/plausible/plugins/api/funnels.ex
- extra/lib/plausible_web/plugins/api/controllers/funnels.ex
- extra/lib/plausible_web/plugins/api/schemas/funnel.ex
- extra/lib/plausible_web/plugins/api/schemas/funnel/create_request.ex
- extra/lib/plausible_web/plugins/api/schemas/funnel/list_response.ex
- extra/lib/plausible_web/plugins/api/views/funnel.ex
- lib/plausible_web/router.ex
- test/plausible_web/controllers/api/stats_controller/funnels_test.exs
- test/plausible_web/plugins/api/controllers/funnels_test.exs
This PR implements basic get/create operations for Funnels via the Plugins API, targeting WooCommerce integrations via our official WordPress plugin.
The extension is available only in EE and only for users whose plan setup allows Funnel usage.
No deletions were implemented just yet, as they're likely unnecessary at this point.
First pass - needs to go live so I can work with @Dan0sz on any readjustments needed.
> Plugins API: Get/Create Funnels

- lib/plausible/stats/base.ex
- lib/plausible/stats/query.ex
- lib/plausible/stats/timeseries.ex
- test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
As pointed out by @macobo, some "include imported or not" logic is leaking into general query modifying functions and requires the developer to understand the logic behind it whenever doing operations such as `remove_filters` or `set_property`. This PR aims to avoid that, making it explicit and more close to the business logic where it's used.
I've also included comments in the relevant places and improved test coverage for timeseries.
> Minor refactor: Remove skip_refresh_imported_opts from query modifying functions

- assets/js/dashboard/custom-hooks.js
- assets/js/dashboard/filters.js
- assets/js/dashboard/index.js
Preview: https://pr-4213.review.plausible.io/plausible.io
This PR:
* In the first commit, reapplies the class -> function component refactor that was already deployed earlier (but buggy)
* In the second commit, fixes the bug where `DropdownContent` was expecting a prop with a different name
* In the third commit, fixes another regression caused by the refactor that is currently happening on prod - the refactor started cancelling API requests on the initial render, which was not the case before with `componentDidMount`. I've introduced a custom hook that's basically a `useEffect` but does not run on the initial render.
This prop name mismatch was responsible for two wrong behaviours:
1) Filter button always displaying this (even without any applied filters):
2) When "+ Add filter" was …
> Reapply Filters component refactor + fix regression

- assets/js/dashboard/filters.js
Another regression caused by the class component refactor in `filters.js`. On the initial load on mobile screens, the `viewport` is left to the default `1080` while it should be re-evaluated.
> Make sure initial load re-evaluates viewport width

- assets/js/dashboard/stats/modals/filter-modal-group.js
- assets/js/dashboard/util/filters.js
- extra/lib/plausible/stats/goal/revenue.ex
- lib/plausible/google/search_console/filters.ex
- lib/plausible/stats/base.ex
- lib/plausible/stats/breakdown.ex
- lib/plausible/stats/email_report.ex
- lib/plausible/stats/filters/dashboard_filter_parser.ex
- lib/plausible/stats/filters/filters.ex
- lib/plausible/stats/filters/legacy_dashboard_filter_parser.ex
- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/filters/stats_api_filter_parser.ex
- lib/plausible/stats/filters/utils.ex
- lib/plausible/stats/filters/where_builder.ex
- lib/plausible/stats/imported/base.ex
- lib/plausible/stats/imported/imported.ex
- lib/plausible/stats/query.ex
- lib/plausible_web/controllers/api/external_stats_controller.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- lib/plausible_web/controllers/stats_controller.ex
- test/plausible/google/search_console/filters_test.exs
- test/plausible/stats/dashboard_filter_parser_test.exs
- test/plausible/stats/filters_test.exs
- test/plausible/stats/legacy_dashboard_filter_parser_test.exs
- test/plausible/stats/query_parser_test.exs
- test/plausible/stats/query_test.exs
This PR does a few things:
- It adds a new `multiple_filters` feature flag which allows adding multiple filters on the frontend (except for goals).
- Updates filter serialization on the frontend
- Adds new filter (and query) parsing methods (for a follow-up PR)
- Reduces number of internal filter operators we support, collapsing list and single-item operators
Blocked on https://github.com/plausible/analytics/pull/4118 - will update filtering within after that PR lands.
> Multiple filters on the frontend

- lib/plausible/site.ex
- lib/plausible/sites.ex
- test/plausible_web/controllers/site_controller_test.exs
This change allows the following flow:
1. create site domain=A
2. change domain=A to domain=B
3. create site domain=A
So basically bypassing the 72h transition period, if, and only if, the old domain=A is frozen by the same owner.
> Allow site creation for users owning the `domain_changed_from`

- lib/workers/check_usage.ex
- test/workers/check_usage_test.exs
So that `LockSites` job unlocks the site, encountering no grace period and no upgrade needed.
A bigger refactoring is needed IMHO so that CheckUsage and LockSites aren't separate. There's implicit dependency between the two - one (re)sets the grace period, and the other (un)locks dashboards depending on grace period state.
Thus, there is no trace of the reason for which a site is being unlocked.
> Reset grace period if usage drops within the last cycle

- lib/plausible/data_migration/clean_up_demo_site_referrer_source.ex
Cleans up referrer_source for demo site in cases where `Direct / None` was recorded as an explicit value due to dogfooding of Plausible stats against analytics (the dogfooding is already fixed by ignoring URL params entirely in #4217).
> Add data migration cleaning up referrer source for demo site

- lib/plausible/application.ex
- lib/plausible/billing/paddle_api.ex
- lib/plausible/billing/plans.ex
- lib/plausible/cache/adapter.ex
- lib/plausible_release.ex
- lib/plausible_web/controllers/api/paddle_controller.ex
- lib/plausible_web/controllers/billing_controller.ex
- lib/plausible_web/live/choose_plan.ex
- lib/plausible_web/remote_ip.ex
- lib/plausible_web/router.ex
- lib/plausible_web/templates/billing/choose_plan.html.heex
- test/plausible/billing/paddle_api_test.exs
- test/plausible/billing/plans_test.exs
- test/plausible_web/controllers/api/paddle_controller_test.exs
- test/support/paddle_api_mock.ex
This PR queries Paddle prices with customer IP, in order to utilise their geolocation-based currency selection.
Additionally, `/api/paddle/currency` endpoint is exposed, so that [currency displayed on the website](https://github.com/plausible/website/pull/579) is the same.
> Unify default pricing currency selection

- config/runtime.exs
- lib/plausible/auth/user_admin.ex
- lib/plausible/crm_extensions.ex
- lib/plausible_web/controllers/admin_controller.ex
- lib/plausible_web/views/auth_view.ex
- lib/plausible_web/views/stats_view.ex
- test/plausible_web/controllers/admin_controller_test.exs
A bunch of small improvements to the CRM.
- display usage info directly above user form instead of a separate page opened from list view
- link to respective Paddle subscription profile from `Status` column as well any time paddle ID is available, regardless of the actual status
> Add CRM QoL improvements around usage info and linking Paddle

- lib/plausible/crm_extensions.ex
Kaffy uses inconsistent field ID when changing between select and standard input for large datasets.
This PR accounts for that change when applying prefill.
> Fix enterprise plan CRM form prefill for case with literal input

- lib/plausible_web/components/billing/billing.ex
- test/plausible_web/controllers/auth_controller_test.exs
Only two tiny changes:
* Make `last_cycle` the default tab when displaying pageview usage in user settings
* And never disable clicking on this tab
* Rename "Ongoing cycle" to "Upcoming cycle"
> Make billing cycles less confusing

- lib/plausible/verification/diagnostics.ex
- lib/plausible/verification/errors.ex
- priv/verification/verify_plausible_installed.js
- test/plausible/site/verification/checks_test.exs
This PR adds more cases to the verification diagnostics verdict.
- Prioritize CSP over GTM if both are present
- Tweak timeouts for the headless run a little
- Introduce generic error message that we'll channel all the known but obscure errors into
- Handle malformed script tag such as `<script defer= data-domain="..."></script>` that will be accepted by the headless browser but is going to fail with our server-side parser
> Verification tweaks

- lib/plausible_web/live/register_form.ex
Addresses a problem where registration form is stuck because captcha shows as completed but captcha error is returned.
> Reset captcha when captcha error is returned in registration form

- lib/plausible/billing/billing.ex
- test/plausible/billing/billing_test.exs
Add an exception in `Plausible.Billing.subscription_updated` to ignore a status update from `paused` to `past_due`.
> Ignore irrelevant Paddle webhook

- lib/plausible/open_telemetry/sampler.ex
Slight adjustment to OTEL sampler so that excessive traces triggered by `site_imports` queries are avoided.
> Ignore `site_imports` query traces when sampling for OpenTelemetry

- lib/plausible/site/admin.ex
- test/plausible/site/admin_test.exs
- test/plausible_web/controllers/admin_controller_test.exs
This PR addresses a problem of broken pagination in Sites CRM due to inner join of 1:n relationship of site memberships. Changing the join into a full preload should help avoid issues when applying limit/offset based approach which does not play out well in such cases.
> Fix pagination is Sites CRM

- lib/plausible/billing/plans.ex
- test/plausible_web/live/choose_plan_test.exs
Currently, any grandfathered subscription on a v1 or v2 plan can upgrade to 20M and 50M plans, which are not available in the newer generations of plans.
This PR stops displaying 20M and 50M plans on the `/billing/choose-plan` page unless the user is already on either of those.
* If the user is on a 10M plan or below, they will not see 20M and 50M as options anymore. Instead they have to contact us and get a quote for a custom plan.
* If the user is already on a 20M plan, they can still change their billing interval or downgrade, but they will not be able to upgrade to 50M themselves.
* If the user is on a 50M plan, they can still change their billing interval, and downgrade, even to 20M.
> Hide 20M and 50M legacy plans from the upgrade page

- lib/plausible/crm_extensions.ex
- lib/plausible_web/templates/layout/_header.html.heex
- lib/plausible_web/templates/site/settings_people.html.heex
- test/plausible_web/controllers/site_controller_test.exs
- test/plausible_web/controllers/stats_controller_test.exs
Implements links for easy navigation between CRM and respective entities - sites and members in "People" settings of the site. Only visible to the superadmins.
> Add backlinks between CRM, dashboard and site members

- CHANGELOG.md
- assets/js/dashboard/components/filter-operator-selector.js
- assets/js/dashboard/filters.js
- assets/js/dashboard/stats/modals/filter-modal-group.js
- assets/js/dashboard/stats/modals/filter-modal-props-row.js
- assets/js/dashboard/stats/modals/filter-modal-row.js
- assets/js/dashboard/util/filters.js
- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/filters/where_builder.ex
- lib/plausible_web/controllers/stats_controller.ex
- test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
Based on https://github.com/plausible/analytics/pull/4227, separate PR for easier reviewability
This PR:
- Updates `event:goal` matching support to work with wildcards
- Adds a new `does_not_contain` operation to the backend and frontend
- Uses `contain` instead of `matches` when querying the backend.
Related request: https://feedback.plausible.io/249
> `does_not_contain`, new filters wildcard matching

- lib/plausible/site/admin.ex
> Fix not so safe input

- Dockerfile
This PR allows to get CE-only deps like [happy_tcp.](https://github.com/plausible/analytics/pull/4245) Right now the build fails with
```
14.81 Unchecked dependencies for environment ce:
14.81 * happy_tcp (https://github.com/ruslandoga/happy_tcp.git)
14.81   the dependency is not available, run "mix deps.get"
14.82 ** (Mix) Can't continue due to errors on dependencies
```
> fix CE Docker build

- assets/js/dashboard/stats/devices/index.js
This was broken in https://github.com/plausible/analytics/pull/4246.
See also: https://3.basecamp.com/5308029/buckets/26383192/card_tables/cards/7514532175
> Fix browser version linking

- lib/plausible/billing/qouta/quota.ex
- lib/plausible/billing/qouta/usage.ex
- lib/plausible/site/memberships.ex
- lib/plausible/site/memberships/create_invitation.ex
- lib/plausible/site/memberships/invitations.ex
- lib/plausible_web/components/billing/notice.ex
- lib/plausible_web/components/billing/plan_box.ex
- lib/plausible_web/live/choose_plan.ex
- test/plausible/billing/quota_test.exs
- test/plausible_web/live/choose_plan_test.exs
When the user goes to upgrade to a plan, currently we let them upgrade to a suitable plan based on the usage across their owned sites. When the user has pending ownerships however, they might not be able to accept them, even after upgrading to a seemingly suitable plan, which can be annoying/confusing.
Whenever there are pending site ownerships, a message will be shown to the user:
Counting the usage from pending ownerships means that we are not letting them upgrade to a plan that would not accommodate all the pending sites. Same goes for warning about losing access to a feature used be a pending ownership site.
> Count pending ownership sites towards account usage on the upgrade page

- lib/plausible/stats/aggregate.ex
- lib/plausible/stats/base.ex
- lib/plausible/stats/filters/filters.ex
- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/filters/utils.ex
- lib/plausible/stats/imported/imported.ex
- lib/plausible/stats/metrics.ex
- lib/plausible/stats/query.ex
- lib/plausible/stats/query_optimizer.ex
- lib/plausible/stats/query_result.ex
- lib/plausible/stats/sql/expression.ex
- lib/plausible/stats/sql/query_builder.ex
- lib/plausible/stats/table_decider.ex
- lib/plausible/stats/util.ex
- test/plausible/stats/query_optimizer_test.exs
- test/plausible/stats/query_parser_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
- Aggregates now use new QueryBuilder
- Limited timeseries support in APIv2 - everything works, but results are only returned in bucket they're active in
- `conversion_rate` and `group_conversion_rate` metrics support
- Imports-related changes to support apiv2 - next PR will re-simplify
- Goals are preloaded into `Query` object for validation purposes
- event:goal breakdowns support. Now a single query and system is more flexible for renaming goals.
- event:page breakdows support. QueryOptimizer.split now splits query to two - sessions query uses visit:entry page
- fixed the memory leak around event:props:x creating symbols
> APIv2: Aggregates, timeseries, conversion_rate, hostname

- assets/js/dashboard.js
- assets/js/dashboard/filters.js
- assets/js/dashboard/router.js
- assets/js/dashboard/stats/behaviours/conversions.js
- assets/js/dashboard/stats/behaviours/goal-conversions.js
- assets/js/dashboard/stats/behaviours/props.js
- assets/js/dashboard/stats/graph/stats-export.js
- assets/js/dashboard/stats/locations/index.js
- assets/js/dashboard/stats/locations/map.js
- assets/js/dashboard/stats/modals/conversions.js
- assets/js/dashboard/stats/modals/entry-pages.js
- assets/js/dashboard/stats/modals/exit-pages.js
- assets/js/dashboard/stats/modals/filter-modal.js
- assets/js/dashboard/stats/modals/google-keywords.js
- assets/js/dashboard/stats/modals/modal.js
- assets/js/dashboard/stats/modals/pages.js
- assets/js/dashboard/stats/modals/props.js
- assets/js/dashboard/stats/modals/referrer-drilldown.js
- assets/js/dashboard/stats/modals/sources.js
- assets/js/dashboard/stats/modals/table.js
- assets/js/dashboard/stats/more-link.js
- assets/js/dashboard/stats/pages/index.js
- assets/js/dashboard/stats/sources/referrer-list.js
- assets/js/dashboard/stats/sources/search-terms.js
- assets/js/dashboard/stats/sources/source-list.js
- assets/js/dashboard/util/url.js
> Fix new tab links + shared links losing URL context

- lib/plausible/verification/checks/snippet.ex
- test/plausible/site/verification/checks_test.exs
This change requires src attribute when looking for snippet during verification
> Require src attribute when seeking snippet for verification

- CHANGELOG.md
- lib/plausible/stats/base.ex
- lib/plausible/stats/breakdown.ex
- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/filters/where_builder.ex
- lib/plausible/stats/imported/base.ex
- lib/plausible/stats/imported/imported.ex
- lib/plausible/stats/metrics.ex
- lib/plausible/stats/query.ex
- lib/plausible/stats/query_optimizer.ex
- lib/plausible/stats/sql/expression.ex
- lib/plausible/stats/sql/query_builder.ex
- lib/plausible/stats/table_decider.ex
- test/plausible/imported/csv_importer_test.exs
- test/plausible/imported/google_analytics4_test.exs
- test/plausible/stats/table_decider_test.exs
- test/plausible_web/controllers/CSVs/30d-filter-path/pages.csv
- test/plausible_web/controllers/CSVs/30d/pages.csv
- test/plausible_web/controllers/CSVs/6m/pages.csv
- test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
- test/plausible_web/controllers/api/stats_controller/conversions_test.exs
- test/plausible_web/controllers/api/stats_controller/imported_test.exs
- test/plausible_web/controllers/api/stats_controller/pages_test.exs
- test/plausible_web/controllers/api/stats_controller/sources_test.exs
Reverts plausible/analytics#4283
This is causing 500-s right now with external Stats API: https://sentry.plausible.io/organizations/plausible/issues/94/?query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0
Issue seems to be `pageviews` metric which was previously incorrectly calculated off of sessions table.
> Revert "APIv2: Replace breakdown module with QueryBuilder"

- lib/plausible/crm_extensions.ex
This change fixes links for non-standard domain names, like subsite paths with "/" in the middle.
> Encode domain name in "Open in dashboard" link from CRM

- CHANGELOG.md
- lib/plausible/stats/base.ex
- lib/plausible/stats/breakdown.ex
- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/filters/where_builder.ex
- lib/plausible/stats/imported/base.ex
- lib/plausible/stats/imported/imported.ex
- lib/plausible/stats/metrics.ex
- lib/plausible/stats/query.ex
- lib/plausible/stats/query_optimizer.ex
- lib/plausible/stats/sql/expression.ex
- lib/plausible/stats/sql/query_builder.ex
- lib/plausible/stats/table_decider.ex
- test/plausible/imported/csv_importer_test.exs
- test/plausible/imported/google_analytics4_test.exs
- test/plausible/stats/table_decider_test.exs
- test/plausible_web/controllers/CSVs/30d-filter-path/pages.csv
- test/plausible_web/controllers/CSVs/30d/pages.csv
- test/plausible_web/controllers/CSVs/6m/pages.csv
- test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
- test/plausible_web/controllers/api/stats_controller/conversions_test.exs
- test/plausible_web/controllers/api/stats_controller/imported_test.exs
- test/plausible_web/controllers/api/stats_controller/pages_test.exs
- test/plausible_web/controllers/api/stats_controller/sources_test.exs
Reverts this revert: https://github.com/plausible/analytics/pull/4292
External API users were querying pageviews and events when breaking down by a session dimension, which causes errors as the new querying API doesn't allow that due to inaccuracies with shorter time ranges.
But it seems okay-ish to allow using session data here. Will figure out a good solution (e.g. warning in meta?) for apiv2 in the future.
See last commit for changes.
> APIv2: Replace breakdown module with QueryBuilder

- assets/js/dashboard/stats/behaviours/props.js
Another regression planted via #4278 
Custom Props modal shows up without carrying over window.location.search (filters).
> Bugfix: custom props modal opens up with no filters

- extra/lib/plausible/stats/funnel.ex
- extra/lib/plausible/stats/goal/revenue.ex
- lib/plausible/exports.ex
- lib/plausible/stats/aggregate.ex
- lib/plausible/stats/base.ex
- lib/plausible/stats/breakdown.ex
- lib/plausible/stats/clickhouse.ex
- lib/plausible/stats/current_visitors.ex
- lib/plausible/stats/filter_suggestions.ex
- lib/plausible/stats/filters/where_builder.ex
- lib/plausible/stats/imported/base.ex
- lib/plausible/stats/imported/imported.ex
- lib/plausible/stats/sql/expression.ex
- lib/plausible/stats/sql/fragments.ex
- lib/plausible/stats/sql/query_builder.ex
- lib/plausible/stats/sql/where_builder.ex
- lib/plausible/stats/timeseries.ex
- lib/plausible/stats/util.ex
- test/plausible/stats/sql/fragments_test.exs
Cleanup PR. 
QueryBuilder requires selected fields to be aliased via both field names passed to `select_merge` as well as setting `selected_as`. This PR introduces utility macros to reduce this sort of boilerplate.
It also moves more code under Plausible.Stats.SQL
> APIv2: macros, SQL cleanup

- assets/js/dashboard/query.js
This prevents the date picker from updating the URL with data domain on each subsequent use. Only the query string should be updated.
Possibly regression introduced via #4278
> Fix URLs breaking on date picker navigation

- CHANGELOG.md
- assets/js/dashboard/stats/reports/list.js
A small follow up to #4318 - Update the changelog, and address a [review suggestion](https://github.com/plausible/analytics/pull/4318#discussion_r1670224938) left without attention in the last PR.
> Modal Search Continued

- assets/js/dashboard/util/filters.js
- lib/plausible/stats/filters/query_parser.ex
- test/plausible/stats/query_parser_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
This simplifies querying as we pass the list of cities as numbers to clients.
> APIv2: Allow sending numbers for visit:city along with strings

- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/sql/where_builder.ex
- test/plausible/stats/query_parser_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_validations_test.exs
Currently, APIv2 can run into bugs when filtering by:
1. visit:country == USA
2. contains US
This PR fixes both issues.
> APIv2: Bugfixes to location filtering

- CHANGELOG.md
- assets/js/dashboard/util/filters.js
Previously, if a filter was applied then filter modal suggestions would _always_ apply the previous suggestion. Now when say applying a `page` filter suggestions we remove the previous `page` filter.
> fix(suggestions): Properly provide suggestions

- lib/plausible/stats/imported/sql/builder.ex
- test/plausible_web/controllers/api/stats_controller/conversions_test.exs
Previously, revenue metrics were reported as 0.0$ when imports were included with APIv2. This is because the metrics were not properly included/forwarded by the imports query.
Not sure how long this bug has persisted, but eh.
> fix(APIv2): Calculate revenue metrics correctly when including imports

- lib/plausible_web/controllers/api/stats_controller.ex
- test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
Some comparisons return __blank__ values. After recent time series fix, this blew up when trying to parse __blank__ as a date.
This fixes the issue and adds a test for a period with __blank__ values
> fix(main-graph): fix 12mo and other comparisons with blanks

- .github/workflows/elixir.yml
This might fix Dialyzer failing in recent PRs.
> Bump cache version for Elixir CI

- lib/plausible/stats/sql/query_builder.ex
Some users are reporting wrong results for stats querying from events table but with session filters.
This seems to be caused by sampling: Namely both tables end up sampled and the incorrect sample rate seems to get used.
This is sadly impossible to test for in our test suite, but reveals itself in production with the following query:
```sql
SELECT
toUInt64 (round(uniq (se0.user_id) * any(_sample_factor))) AS visitors
FROM
events_v2 AS se0 SAMPLE 20000000
INNER JOIN (
SELECT
sss0.session_id AS session_id,
any(_sample_factor) AS _sample_factor
FROM
sessions_v2 AS sss0 SAMPLE 20000000
WHERE
(sss0.site_id = _CAST (8195000, 'Int64'))
AND (sss0.timestamp >= _CAST (1720497600, 'DateTime'))
AND (sss0.start < _CAST (1720584000, 'DateTime'))
AND (sss0.entry_page IN ('/'))
AND (sss0.sign = 1)
GROUP …
```
> fix: Remove SAMPLE BY from an events query that joins sessions

- assets/js/app.js
- lib/plausible_web/live/components/modal.ex
- lib/plausible_web/live/verification.ex
- lib/plausible_web/templates/email/drop_notification.html.eex
- lib/plausible_web/templates/site/settings_general.html.heex
- lib/workers/traffic_change_notifier.ex
- test/plausible_web/live/verification_test.exs
Make sure that following the drop notification e-mail link automatically opens up the modal and scrolls down the viewport to the Snippet section.
Sample link: https://pr-4344.review.plausible.io/dummy.site/settings/general?launch_verification=true#snippet
> Open verification modal when following drop notification link

- config/.env.test
- lib/plausible/verification.ex
- lib/plausible_web/templates/site/settings_email_reports.html.heex
- lib/plausible_web/templates/site/settings_general.html.heex
- lib/plausible_web/templates/site/snippet.html.heex
- lib/plausible_web/templates/stats/waiting_first_pageview.html.heex
- test/test_helper.exs
- `:verification` flag is no longer needed, however we'll keep the old "awaiting first pageview" flow for Community Edition where verification is not enabled by default
- `:traffic_drop_notifications` have been tested and can be enabled for everyone
> Remove verification related feature flags

- config/runtime.exs
- test/plausible/config_test.exs
This PR fixes the error reported in https://github.com/plausible/analytics/pull/4289#issuecomment-2198601831 by allowing using SMTP relays without authentication.
> fix relay-without-auth mua config

- CHANGELOG.md
- config/runtime.exs
- test/plausible/config_test.exs
This PR standardizes PostgreSQL connection configuration on DATABASE_URL by soft-deprecating DATABASE_SOCKET_DIR and adding Unix sockets support in DATABASE_URL.
Relevant: https://github.com/plausible/community-edition/pull/136
> Improve PG unix sockets configuration

- extra/lib/plausible/help_scout.ex
- extra/lib/plausible_web/views/help_scout_view.ex
- lib/plausible/site/admin.ex
- test/plausible/help_scout_test.exs
Further refinement of HelpScout integration introducing number of owned sites with a link to sites list CRM filtered by owner email.
> Show number of owned sites in HS integration with a link to sites list in CRM

- lib/plausible_web/controllers/api/stats_controller.ex
- test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
In the main graph, the 'current' interval should be shown with a dotted line instead of a solid line. This is accomplished with the `present_index` variable which broke recently.
- Since this behaviour was broken and fixed during a single CE release cycle, no changelog is needed.
> Fix present_index for daily, weekly and monthly intervals

- assets/js/dashboard/components/combobox.js
- assets/js/dashboard/custom-hooks.js
- assets/js/dashboard/stats/modals/breakdown-modal.js
- assets/package-lock.json
- assets/package.json
A new, cleaner version of https://github.com/plausible/analytics/pull/4331 with the review comments addressed.
> Fix debounce

- CHANGELOG.md
- assets/tailwind.config.js
- config/dev.exs
- extra/lib/plausible/funnel.ex
- extra/lib/plausible/funnels.ex
- extra/lib/plausible_web/live/funnel_settings.ex
- extra/lib/plausible_web/live/funnel_settings/form.ex
- extra/lib/plausible_web/live/funnel_settings/list.ex
- lib/plausible_web/live/components/combo_box.ex
- test/plausible/funnels_test.exs
- test/plausible_web/live/components/combo_box_test.exs
- test/plausible_web/live/funnel_settings/form_test.exs
- test/plausible_web/live/funnel_settings_test.exs
This PR adds the option to edit exiting funnels and btw fixes the UI CSS quirks as a result of improper tailwind build configuration. The modal now displays nicer.
> Implement UI to edit existing funnels

- assets/js/dashboard/stats/modals/locations-modal.js
- assets/js/dashboard/stats/modals/sources.js
Fixes a bug introduced a moment ago in #4361. Currently opening a sources or countries modal > closing it > opening it again will result in a 404. This PR makes sure we're sending reportInfo as a new object and not modifying the source of truth itself.
> Fix sending endpoint prop from sources and countries modals

- lib/mix/tasks/download_country_database.ex
- lib/plausible/auth/grace_period.ex
- lib/plausible/auth/user.ex
- lib/plausible/billing/paddle_api.ex
- lib/plausible/billing/qouta/usage.ex
- lib/plausible/billing/subscriptions.ex
- lib/plausible/google/ga4/http.ex
- lib/plausible/imported.ex
- lib/plausible/users.ex
- lib/plausible_web/components/billing/plan_box.ex
- lib/plausible_web/views/layout_view.ex
- lib/workers/check_usage.ex
- lib/workers/send_trial_notifications.ex
Continues #4338
This PR continues [the removal of Timex](https://3.basecamp.com/5308029/buckets/29267832/card_tables/cards/7479197128) by replacing [`Timex.today/0`](https://hexdocs.pm/timex/Timex.html#today/0) with `Date.utc_today/0` which was already being [delegated to.](https://github.com/bitwalker/timex/blob/c45b9a734074ac2a56355ec52ebf931b932223b7/lib/timex.ex#L47-L51) Additionally, it replaces a single instance of [`Timex.today/1`](https://hexdocs.pm/timex/Timex.html#today/1) with [similar `DateTime` functions.](https://github.com/bitwalker/timex/blob/c45b9a734074ac2a56355ec52ebf931b932223b7/lib/timex.ex#L53-L78) I'm using "similar" and not "equivalent" because now we raise an error on an invalid timezone instead of returning an error tuple, which previously could cause match …
> Remove Timex.today

- lib/plausible/props.ex
- test/plausible/props_test.exs
This PR adds `search_query` among internal props. Our official Wordpress integration tracks search events, sending "WP Search Queries" event along with `search_query` property. This change makes breaking down by `search_query` property always available, regardless of customer plan.
> Add `search_query` to internal props

- assets/js/dashboard/filters.js
- assets/js/liveview/live_socket.js
- lib/plausible_web/live/register_form.ex
- lib/plausible_web/templates/layout/_tracking.html.heex
- test/plausible_web/live/register_form_test.exs
* Attach custom properties defined in `_tracking.html` to all custom events (i.e. `Signup`, `Signup via invitation`, and `Filter Menu: Open`)
* Make sure all one-time invitation pages are tracked as `"/register/invitation/:invitation_id"`
* Do not send the `theme` property with the value `system` when user is not logged in.
In addition to this PR, some tracking improvements are pending in plausible/docs and plausible/website repositories.
* https://github.com/plausible/docs/pull/524
* https://github.com/plausible/website/pull/595
> Tracking improvements

- extra/lib/plausible/help_scout.ex
- extra/lib/plausible_web/controllers/help_scout_controller.ex
- extra/lib/plausible_web/views/help_scout_view.ex
- lib/plausible_web/router.ex
- test/plausible/help_scout_test.exs
- test/plausible_web/controllers/help_scout_controller_test.exs
This PR implements capability to search user directly from HelpScout integration. The input search term is compared against user emails and site domains. Up to 5 first matches sorted by most owned sites first are displayed. After clicking one of the matches, the details view is opened. Search can be repeat several times.
Each time a different email/user is picked, it's remembered for the HelpScout customer ID which initiated the given conversation and will be defaulted to in future conversations of that customer. Every search and picking another email in either this or subsequent conversations will reset the mapping between customer ID and email and fall back to what automatic matching determines.
When a callback for a given conversation is initially called and signature is successfully …
> Add ability to lookup by email and site domain in HelpScout integration

- assets/js/dashboard/filters.js
- assets/js/dashboard/stats/modals/breakdown-modal.js
- assets/js/dashboard/stats/reports/list.js
- assets/js/dashboard/util/filters.js
Improves readability for long URLs:
1. In modals, do not truncate URLs (screenshots below)
2. When displaying filters, show the full filter value in tooltip
Before:
After:
> Improve how long URLs are displayed in dashboard

- lib/plausible_web/live/shields/hostname_rules.ex
this is to avoid people mistakenly blocking the traffic from their main domain name from being recorded
> Change the example in the hostname block

- assets/js/dashboard/query.js
https://github.com/plausible/analytics/pull/4408 move away from PlausibleSearchParams ([link](https://github.com/plausible/analytics/pull/4408/files#diff-8dcef7f492b734b83bc8ccb460c4e9d06a27a056b4ef986ead16673ab5aca1ffR129)) caused a bug that resulted in the new filters being constructed wrong, and not being applied properly. 
This fixes the issue.
> Fix legacy compatibility redirect

- CHANGELOG.md
- assets/js/liveview/combo-box.js
- assets/js/liveview/phx_events.js
- extra/lib/plausible/goal/revenue.ex
- extra/lib/plausible_web/controllers/api/external_sites_controller.ex
- extra/lib/plausible_web/live/funnel_settings/form.ex
- lib/plausible/goal/schema.ex
- lib/plausible/goals/goals.ex
- lib/plausible/plugins/api/goals.ex
- lib/plausible/stats/filter_suggestions.ex
- lib/plausible_web/controllers/api/external_stats_controller.ex
- lib/plausible_web/live/components/combo_box.ex
- lib/plausible_web/live/components/modal.ex
- lib/plausible_web/live/goal_settings.ex
- lib/plausible_web/live/goal_settings/form.ex
- lib/plausible_web/live/goal_settings/list.ex
- lib/plausible_web/plugins/api/views/goal.ex
- lib/plausible_web/views/error_helpers.ex
- priv/repo/migrations/20240801052903_make_goal_display_names_unique.exs
- priv/repo/seeds.exs
- test/plausible/goals_test.exs
- test/plausible_web/controllers/api/external_sites_controller_test.exs
- test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
- test/plausible_web/live/components/combo_box_test.exs
- test/plausible_web/live/goal_settings/form_test.exs
- test/plausible_web/live/goal_settings_test.exs
- test/support/factory.ex
This PR introduces new capabilities of:
- editing goals
- setting up display names for goals
The display name is meant to decouple event names (used in tracking integration) from what dashboard/site settings users see. Especially useful in case of long/cryptic page paths, allowing marketing-oriented users quickly identify their meaning.
It's also used in the Stats/Sites API as the primary filtering identifier, replacing conditional naming used thus far. The API docs will need an update, a relevant PR will be referenced here.
By design, it's not possible to change the goal type when editing. So for example a custom event cannot be turned into a revenue goal or a pageview. We only allow editing initially provided set of data, otherwise goal deletion is recommended.
By default, all the …
> Edit goals with display names

- priv/repo/migrations/20240809100853_turn_google_auth_tokens_into_text.exs
To address occasional ERROR 22001 (string_data_right_truncation)  [Sentry](https://sentry.plausible.io/organizations/plausible/issues/437)
> Migration: turn google auth tokens into text column type

- lib/plausible/auth/auth.ex
- lib/plausible_web/controllers/auth_controller.ex
- test/plausible_web/controllers/auth_controller/logs_test.exs
- test/plausible_web/controllers/auth_controller_test.exs
- test/support/conn_case.ex
This PR adds a safeguard against flaky auth rate limiting due to fixed time rate limit buckets.
> Fix flaky auth rate limit tests

- lib/plausible/auth/user_admin.ex
- lib/plausible/billing/paddle_api.ex
- lib/plausible/data_migration/populate_event_session_columns.ex
- lib/plausible/data_migration/versioned_sessions.ex
- lib/plausible/exports.ex
- lib/plausible/site/admin.ex
- lib/plausible/stats/time.ex
- lib/plausible_web/components/billing/notice.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- lib/plausible_web/controllers/stats_controller.ex
- lib/plausible_web/email.ex
- lib/plausible_web/live/shields/country_rules.ex
- lib/plausible_web/live/shields/hostname_rules.ex
- lib/plausible_web/live/shields/ip_rules.ex
- lib/plausible_web/live/shields/page_rules.ex
- lib/plausible_web/mjml/templates/stats_report.mjml.eex
- lib/plausible_web/templates/auth/user_settings.html.heex
- lib/plausible_web/views/auth_view.ex
- lib/plausible_web/views/billing_view.ex
- lib/plausible_web/views/email_view.ex
- lib/plausible_web/views/text_helpers.ex
- lib/workers/send_email_report.ex
Continues #4338
This PR continues [the removal of Timex](https://3.basecamp.com/5308029/buckets/29267832/card_tables/cards/7479197128) by replacing `Timex.format!/2` with `Calendar.strftime/2` and, in some cases, `Date.to_iso8601/1`.
> Remove Timex.format

- assets/css/app.css
- assets/css/flatpickr.css
- assets/css/modal.css
Stylelint advised a new color format, and didn't detect that it's invalid. This fixes it according to https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb#values
> Fix invalid rgba in stylesheet

- config/runtime.exs
This caused quite a bit of confusion for cenk and I. This code is overridden below.
> Clean up dead code in runtime.exs

- CHANGELOG.md
- assets/js/dashboard/stats/modals/locations-modal.js
Use the new `country_name`, `city_name` and `region_name` fields to enable searching locations in Details views.
> Enable search for Countries, Cities, and Regions Details views

- .github/workflows/all-checks-pass.yml
We want to check that all checks pass before merging a PR.
GitHub does not currently support requiring all checks to pass by default. You will need to manually configure any required checks in the branch protection rule.
> validate that all checks passed

- CHANGELOG.md
- lib/plausible/clickhouse_repo.ex
- lib/plausible/data_migration/locations_sync.ex
- lib/plausible/data_migration/populate_event_session_columns.ex
- lib/plausible/data_migration/versioned_sessions.ex
- lib/plausible/ingest_repo.ex
- lib/plausible/migration_utils.ex
- lib/plausible/stats.ex
- lib/plausible/stats/aggregate.ex
- lib/plausible/stats/breakdown.ex
- lib/plausible/stats/legacy/legacy_query_builder.ex
- lib/plausible/stats/query.ex
- lib/plausible/stats/timeseries.ex
- lib/plausible_web/controllers/api/external_query_api_controller.ex
- lib/plausible_web/controllers/api/external_stats_controller.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- lib/plausible_web/controllers/debug_controller.ex
- lib/plausible_web/controllers/helpers.ex
- lib/plausible_web/controllers/stats_controller.ex
- lib/plausible_web/plugs/super_admin_only_plug.ex
- lib/plausible_web/router.ex
- lib/plausible_web/templates/debug/clickhouse.html.heex
- lib/plausible_web/views/debug_view.ex
- priv/ingest_repo/migrations/20240423094014_add_imported_custom_events.exs
This PR:
- Starts populating Clickhouse system.query_log table log_comment column with metadata about the query. This will be useful for debugging performance issues and using clickhouse for query performance analysis.
- Adds a /debug/clickhouse route which shows a table containing information about recent queries by user
> Populate log_comment with debug information, /debug/clickhouse route

- .github/workflows/node.yml
- .gitignore
- CHANGELOG.md
- assets/.eslintrc.json
- assets/jest.config.json
- assets/js/dashboard/comparison-input.js
- assets/js/dashboard/datepicker.js
- assets/js/dashboard/extra/funnel.js
- assets/js/dashboard/query-dates.test.tsx
- assets/js/dashboard/router.js
- assets/js/dashboard/stats/graph/graph-tooltip.js
- assets/js/dashboard/stats/graph/interval-picker.js
- assets/js/dashboard/stats/graph/top-stats.js
- assets/js/dashboard/stats/locations/map.tsx
- assets/js/dashboard/util/url-search-params.test.ts
- assets/js/dashboard/util/url.test.ts
- assets/js/dashboard/util/url.ts
- assets/package-lock.json
- assets/package.json
- assets/test-utils/app-context-providers.tsx
- assets/test-utils/extend-expect.ts
- assets/test-utils/reset-state.ts
- assets/test-utils/set-fixed-timezone.ts
- assets/tsconfig.json
* Removes invalid .js file extensions from some imports
* Adds jest testing framework for /assets
* Adds react testing library
* Adopts FE testing principle of colocating the test with the module, not in a separate directory tree
* Tests url module
* Tests date picking logic
* Adds test command to the CI
> Add testing framework

- lib/plausible/auth/auth.ex
- lib/plausible/site/admin.ex
- lib/plausible/site/memberships/create_invitation.ex
- lib/plausible_web/controllers/auth_controller.ex
- lib/plausible_web/live/register_form.ex
- lib/plausible_web/router.ex
- lib/plausible_web/templates/page/index.html.eex
- test/plausible_web/controllers/auth_controller_test.exs
- test/plausible_web/live/register_form_test.exs
A pure refactor meant to slightly improve logic around login. Rate limiting is now applied more consistently as well.
Originally, I had a couple attempts at more extensive refactors but failed to come up with anything sensible. For now I'm settling for an incremental improvement.
> Unify and refactor login regardless of trigger source (explicit/register)

- .github/workflows/node.yml
- assets/tsconfig.json
* Adds /assets type checking to CI (previous incorrect assumption was that the esbuild command would fail if there's Typescript errors)
* Updates tsconfig.json to make doubly sure that no files are emitted on disk
> Update Typescript config and add typecheck to CI

- priv/ingest_repo/migrations/20240502115822_alias_api_prop_names.exs
This PR fixes the following warning when running migrations:
```
warning: code block contains unused literal "Migration adds a ALIAS columns needed to keep DB schema and api\nproperty naming in sync to reduce overhead in code.\n" (remove the literal or assign it to _ to avoid warnings)
└─ lib/plausible-0.0.1/priv/ingest_repo/migrations/20240502115822_alias_api_prop_names.exs: Plausible.IngestRepo.Migrations.AliasApiPropNames (module)
```
> Fix ALIAS migration warning

- .github/workflows/build-private-images-ghcr.yml
- .github/workflows/build-public-images-ghcr.yml
- .github/workflows/build-public-images.yml
- .github/workflows/node.yml
- .github/workflows/tracker.yml
> use GH runner instead of buildjet to overcome docker hub rate limits

- Dockerfile
This PR fixes a warning shown in newer Docker versions:
```
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 5)
```
> Fix Dockerfile warning

- lib/plausible/imported.ex
- lib/plausible/props.ex
- test/plausible_web/controllers/api/external_stats_controller/query_imported_test.exs
- test/plausible_web/controllers/api/stats_controller/custom_prop_breakdown_test.exs
This PR addresses a problem of a property not (currently) supported for imported data being queried for in imported logic, resulting in a crash.
> Do not try querying imported data for unsupported props

- CHANGELOG.md
- config/runtime.exs
- test/plausible/config_test.exs
This PR removes `ssl_opts` that are no longer necessary after https://github.com/elixir-ecto/postgrex/pull/677 (and https://github.com/plausible/analytics/pull/4457)
> Update Postgrex SSL config

- assets/js/dashboard/filters.js
- assets/js/dashboard/stats/graph/line-graph.js
The destructuring results in ignoring existing search params which are not modified by a given navigation call - in case of removing filters it's date range and in case of time range selection from graph, it's filters.
> Fix invalid parameter destructuring in `navigate` calls

- lib/plausible/stats/breakdown.ex
- lib/plausible/stats/legacy/legacy_query_builder.ex
- test/plausible/stats/query_test.exs
- test/plausible_web/controllers/api/stats_controller/sources_test.exs
* Adds support for order_by in URL params of breakdown endpoints
> Support order_by in URL params of breakdown endpoints

- lib/plausible/stats/sql/expression.ex
- test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
Quick fix to account for realtime periods to select timeslots in UTC rather than site.timezone. Needs a proper fix to also work for API v2 (which doesn't have the `query.period` field set).
realtime periods are currently not supported in API v2 so that's not a real issue yet.
> Fix realtime periods returning wrong date range for non-UTC timezone sites

- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/legacy/legacy_query_builder.ex
- lib/plausible/stats/sql/expression.ex
- test/plausible/stats/query_parser_test.exs
Follow up to https://github.com/plausible/analytics/pull/4508 with a proper fix that will also work for API v2.
The solution is actually much simpler than what I essentially did in that PR. The problem was that we were selecting the time dimensions by shifting the timestamps into `query.timezone` **which was always `site.timezone`, and yet the actual `query.date_range` for realtime was in UTC**.
So eventually the bug surfaced in `Plausible.Stats.Timeseries.build_timeseries_result` from something like this:
```elixir
%Plausible.Stats.QueryResult{
results: [%{metrics: [1], dimensions: ["2024-09-03 08:30:00"]}],
meta: %{
time_labels: ["2024-09-03 05:20:00", "2024-09-03 05:21:00", ..., "2024-09-03 05:49:00"]
},
...
}
```
**The fix**
`query.timezone` does not have to be equivalent to …
> Proper fix for realtime timeseries queries

- test/plausible_web/plugs/user_session_touch_test.exs
Fixes a test so that session is actually shifted 1 day back before checking if the plug works.
> Fix faulty `UserSessionTouchTest` setup

- CHANGELOG.md
- fixture/ga4_api_disabled_error.json
- lib/plausible/google/ga4/http.ex
- lib/plausible_web/controllers/google_analytics_controller.ex
- test/plausible/imported/google_analytics4_test.exs
- test/plausible_web/controllers/google_analytics_controller_test.exs
Right now the Google's error message for 401 and 403 responses is replaced by 
> We were unable to authenticate your Google Analytics account. Please check that you have granted us permission to 'See and download your Google Analytics data' and try again.
This error message is not helpful in CE where extra configuration steps are involved.
This PR makes the real error message be displayed in the Plausible CE instead:
> Google Analytics Admin API has not been used in project 381312896460 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/analyticsadmin.googleapis.com/overview?project=381312896460 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
It looks ugly but provides …
> Better Google error messages in CE

- lib/plausible_web/plugs/session_timeout_plug.ex
- test/plausible_web/plugs/session_timeout_plug_test.exs
After recent update in #4463, an error slipped in where when the _legacy_ session times out, the conn is halted but no body is sent. This results in 500 error (`Plug.Conn.NotSentError`).
This PR fixes it by redirecting to login page.
> Redirect to login on expired legacy session

- CHANGELOG.md
- assets/js/dashboard/stats/graph/visitor-graph.js
- lib/plausible/stats/query.ex
- lib/plausible/stats/query_result.ex
- lib/plausible/stats/timeseries.ex
- lib/plausible_web/controllers/api/external_stats_controller.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- lib/plausible_web/controllers/stats_controller.ex
- test/plausible_web/controllers/api/external_stats_controller/query_imported_test.exs
- test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
- test/plausible_web/controllers/api/stats_controller/imported_test.exs
- test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
This PR is to be merged into https://github.com/plausible/analytics/pull/4504
* Return a warning in Stats API timeseries when interval is too short for imported data
* Display a warning bubble on the dashboard when imported data is excluded from the graph due to interval length
This PR also stops returning the `imports_exist` and `includes_imported` fields from the `main_graph` action, as they're unused.
> Imported disabled graph notice

- priv/ingest_repo/migrations/20240801091615_capitalize_known_sources.exs
Previous migration took forever on prod, likely because Map lookups are linear time in complexity. `transform/3` helps achieve the same functionality with the help of a hash table and updated WHERE clause allows skipping most rows which dont need updating.
I've tested the migration on a dummy table on prod. Updated a months data in 2022 in seconds where the previous migration ran for hours with little progress before we cancelled it.
> Update 20240801091615_capitalize_known_sources.exs migration

- CHANGELOG.md
- lib/plausible_web/endpoint.ex
This PR removes `domain` option from cookies in CE making it possible to access dashboards from non-BASE_URL websites.
- https://github.com/plausible/analytics/issues/4126
- https://github.com/plausible/community-edition/issues/146
> Return domain-less cookies in CE

- .github/workflows/elixir.yml
- CHANGELOG.md
- lib/plausible_release.ex
- rel/overlays/migrate.sh
- rel/overlays/pending-migrations.sh
- test/plausible/release_test.exs
- test/test_helper.exs
This PR makes [`/entrypoint.sh db migrate`](https://github.com/plausible/community-edition/blob/4e949e84f787702835ec0654c7f663dc2fb61dbe/docker-compose.yml#L28C63-L28C88) and `/entrypoint.sh db pending-migrations` order all pending migrations and run them in a single queue instead of per-repo.
Related card: https://3.basecamp.com/5308029/buckets/29267832/card_tables/cards/7508896723
<details><summary>Contents of that card</summary>
<br/>
> Some migrations in PostgreSQL implicitly depend on migrations in ClickHouse (there is at least one such migration), and because PostgreSQL migrations run first, they fail because from their point of view ClickHouse schemas are now "outdated":
> 
> How migrations were added (example):
> - add table to PostgreSQL db
> - add column to ClickHouse table
> - …
> Run migrations in order across repos

- lib/plausible/auth/user_admin.ex
- lib/plausible/data_migration/populate_event_session_columns.ex
- lib/plausible/data_migration/versioned_sessions.ex
- lib/plausible/google/api.ex
- lib/plausible/session/salts.ex
- lib/plausible/stats/comparisons.ex
- lib/plausible/stats/legacy/legacy_query_builder.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- lib/workers/schedule_email_reports.ex
- lib/workers/send_email_report.ex
- lib/workers/send_site_setup_emails.ex
- test/plausible/stats/query_test.exs
Continues https://github.com/plausible/analytics/pull/4338
This PR continues [the removal of Timex](https://3.basecamp.com/5308029/buckets/29267832/card_tables/cards/7479197128) by replacing Timex.now with ~~equivalent~~ (one test had to change, so I guess not exactly equivalent) Date and DateTime functions:
- Timex.now/0 is replaced by [DateTime.utc_now](https://hexdocs.pm/elixir/DateTime.html#utc_now/1) which Timex was already [delegating to](https://github.com/bitwalker/timex/blob/c45b9a734074ac2a56355ec52ebf931b932223b7/lib/timex.ex#L59-L63)
- Timex.now/1 is replaced by [DateTime.now!](https://hexdocs.pm/elixir/DateTime.html#now!/2) which differs from what Timex [was doing](https://github.com/bitwalker/timex/blob/c45b9a734074ac2a56355ec52ebf931b932223b7/lib/timex.ex#L65-L78) …
> Remove Timex.now

- lib/plausible_release.ex
- test/plausible/release_test.exs
This PR adds a status check before creating the database. This way we don't attempt to create one when it already exists.
This removes these errors from the logs:
> plausible_events_db-1  | 2024.08.02 15:38:17.634785 [ 49 ] {c466dd00-dd1e-44a5-81e6-d7819cd7393d} <Error> DynamicQueryHandler: Code: 82. DB::Exception: Database plausible_events_db already exists. (DATABASE_ALREADY_EXISTS), Stack trace (when copying this message, always include the lines below):
As suggested in https://github.com/plausible/analytics/discussions/3077#discussioncomment-9540178
> Don't attempt to create a database if it already exists

- assets/js/dashboard/components/combobox.js
- assets/js/dashboard/components/filter-operator-selector.js
- assets/js/dashboard/last-load-context.tsx
- assets/js/dashboard/query-context.tsx
- assets/js/dashboard/router.tsx
- assets/js/dashboard/stats/current-visitors.js
- assets/js/dashboard/stats/graph/top-stats.js
- assets/js/dashboard/stats/modals/filter-modal-props-row.js
- assets/js/dashboard/stats/modals/filter-modal-row.js
- assets/js/dashboard/util/filters.js
* Display a loading spinner in the combobox when fetching suggestions for `is` and `is_not` filter operators.
* Extract lastLoadTimestamp from QueryContext into a new, separate context. This is currently causing unnecessary re-renders of any components depending on the queryContext. For instance, when keeping the combobox open, new options are fetched again every 30 seconds.
* Always consider `contains` and `not_contains` as `freeChoice` filter operators. Currently, the condition on which we consider a filter to be freeChoice is whether the filter key is one of `['screen', 'country', 'region', 'city']`. This is wrong because these filters are simply the ones that do not support contains. It has nothing to do with being able to select a custom value to filter by.
* Fix `does_not_contain` …
> Filter modal fixes

- test/plausible_web/controllers/api/stats_controller/sources_test.exs
Today one test started consistently failing across local dev envs and CI:
```
1) test GET /api/stats/:domain/sources order_by [[visit_duration, asc], [visit:source, desc]]] is respected and flipping the sort orders works (PlausibleWeb.Api.StatsController.SourcesTest)
Error:      test/plausible_web/controllers/api/stats_controller/sources_test.exs:544
Assertion with == failed
code:  assert json_response(conn1, 200)["results"] == [
%{"name" => "Z", "visitors" => 1, "bounce_rate" => 100, "visit_duration" => 0},
%{"name" => "A", "visitors" => 2, "bounce_rate" => 100, "visit_duration" => 0},
%{"name" => "C", "visitors" => 1, "bounce_rate" => 0, "visit_duration" => 30},
%{"name" => "B", "visitors" => 1, "bounce_rate" => 0, "visit_duration" => 45}
]
left:  [
%{
"bounce_rate" => 100,
"name" => …
```
> Fix test failing due to timestamp setup

- lib/plausible/stats/sql/expression.ex
- lib/plausible/stats/sql/fragments.ex
- test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
Since #4493 got deployed, faulty session records stopped appearing. This PR introduces a change to bounce computation (for native stats), which safeguards against negative bounce rate value overflow for historical records, ultimately caused by those races occurring in the past.
> Safeguard queries relying on `sign` from faulty old session entries

- lib/plausible/stats/json_schema.ex
- priv/json-schemas/query-api-schema.json
- test/plausible/stats/query_parser_test.exs
This reasserts the tuples in the json schemas, so the autocomplete / autoverify in the playground would inform users when they are constructing invalid filters.
* Some whitespace changes due to prettier.
* Slight refactor to lift out filtering operation definitions (benefit: simpler references)
> Reassert tuples in query JSON schema

- CHANGELOG.md
- lib/plausible_web/plugs/authorize_site_access.ex
- lib/plausible_web/router.ex
- test/plausible_web/controllers/api/stats_controller/authorization_test.exs
- test/plausible_web/plugs/authorise_site_access_test.exs
After this:
- Docs Query API routes are not queriable by viewers/public
- API routes return a JSON error over html page
Solves https://3.basecamp.com/5308029/buckets/37310803/card_tables/cards/7782351091
There might be a follow-up docs change to tweak behavior when user has insufficient access or isn't logged in.
> Limit docs query API, return 401 for API routes

- lib/plausible/session/cache_store.ex
`persist_session/1` is used in `populate_native_stats/1` test helper to merge session data. It sometimes gets `:ok` instead of the actual session data so that tests randomly fail with:
```
** (BadMapError) expected a map, got: :ok
code: populate_stats(site, [build(:pageview)])
stacktrace:
(elixir 1.17.1) lib/map.ex:486: Map.take/2
(plausible 0.0.1) lib/plausible/clickhouse_event_v2.ex:92: Plausible.ClickhouseEventV2.merge_session/2
(plausible 0.0.1) test/support/test_utils.ex:188: anonymous fn/2 in Plausible.TestUtils.populate_native_stats/1
(elixir 1.17.1) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
(plausible 0.0.1) test/support/test_utils.ex:184: Plausible.TestUtils.populate_native_stats/1
(plausible 0.0.1) test/support/test_utils.ex:179: Plausible.TestUtils.populate_stats/1 …
```
> Fix race condition merging session data when cache returns

- assets/js/dashboard/components/search-input.tsx
- assets/js/dashboard/stats/modals/breakdown-modal.tsx
Adds the ability to focus the search input by pressing the `/` key in breakdown modals.
Also stops rendering the search input box in screen sizes modal (currently on master it's rendered but not functional). It's not needed since the list will never have more than 5 entries.
> Breakdown modal search shortcut

- config/.env.test
- config/test.exs
This should help with random pool timeouts, at least on AMD Linux with 24 cores.
Helps narrowing down more test flakiness later on.
> Set postgres pool size to 2*cores for test env

- lib/plausible/cache/adapter.ex
- lib/plausible/ingestion/event.ex
- lib/plausible/session/cache_store.ex
- test/plausible/ingestion/event_test.exs
- test/plausible/session/cache_store_test.exs
- test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
- test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_goal_dimension_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_imported_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
- test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
- test/plausible_web/controllers/api/stats_controller/conversions_test.exs
- test/plausible_web/controllers/api/stats_controller/funnels_test.exs
- test/plausible_web/controllers/api/stats_controller/imported_test.exs
- test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
- test/plausible_web/controllers/api/stats_controller/pages_test.exs
- test/plausible_web/controllers/api/stats_controller/sources_test.exs
- test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
- test/support/test_utils.ex
Currently, the `CacheStore.on_event` call for timed out lock case returns `:ok` instead of session, which leads to a pretty opaque error when trying to merge session data with event.
This change makes timeout handling explicit and drops the timed out event with `:lock_timeout` set as reason.
> Drop event explicitly on session lock timeout 

- Dockerfile
Building Dockerfile seems to be failing now with the following error:
```
Dockerfile:72
--------------------
70 |       && if [ "$MIX_ENV" = "ce" ]; then apk add --no-cache certbot; fi
71 |
72 | >>> COPY --from=buildcontainer --chmod=a+rX /app/_build/${MIX_ENV}/rel/plausible /app
73 |     COPY --chmod=755 ./rel/docker-entrypoint.sh /entrypoint.sh
74 |
--------------------
ERROR: failed to solve: invalid chmod parameter: 'a+rX'. it should be octal string and between 0 and 07777
```
Link: https://github.com/plausible/analytics/actions/runs/10898788870/job/30242872415
~~Not sure _why_ given this line hasn't changed in ages, but perhaps something to do with buildx changes. If preview deploy succeeds in this, it should fix the issue.~~
From @zoldar:
> …
> Solve build failure

- lib/plausible/stats/filter_suggestions.ex
- test/plausible_web/controllers/api/stats_controller/suggestions_test.exs
Currently, when clicking on a city in the Locations report to filter by it, the city code will become an integer in the filter.
However, when applying the city filter from the filter modal, the city code will become a string in the filter, because the value returned from city filter suggestions is a string.
When applying filters only from the filter modal, it works. But when applying a filter first by clicking on a city in the Locations report, then editing the filter, and adding another city - it breaks because string and integer types are mixed.
This PR fixes that by returning integers instead of strings from the filter suggestions API. It's also consistent with the cities breakdown report where integers are returned.
> Fix applying city filters

- lib/plausible_web/plugs/authorize_site_access.ex
- lib/plausible_web/router.ex
- test/plausible_web/controllers/api/internal_controller/docs_query_test.exs
Makes the authorize site access plug aware of another way to pass the domain.
> Fix auth issue with POST /api/docs/query

- config/runtime.exs
- lib/plausible/open_telemetry.ex
Added a new field to Sentry and Honeycomb to make it easier to see which node the application was running on.
> enrich with information about app node

- lib/plausible_web/templates/auth/login_form.html.heex
Fixes https://github.com/plausible/analytics/pull/4459#discussion_r1758515119 in CE.
> Don't render empty list element in CE

- lib/plausible_web/live/sites.ex
Fixes non-iterpolated `flow` in the query string after clicking "+ Add Website" from the sites dashboard:
Before: https://staging.plausible.io/sites/new?flow=#{PlausibleWeb.Flows.provisioning()}
After: https://pr-4605.review.plausible.io/sites/new?flow=provisioning
> Fix progress header not showing up when adding a new site

- lib/plausible_web/views/layout_view.ex
This PR removes unnecessary `Enum.reject(..., &is_nil/1)` call since the list is static and all values are non-nil.
> Remove unnecessary Enum.reject/2 call

- lib/plausible/billing/billing.ex
- lib/workers/check_usage.ex
- test/workers/check_usage_test.exs
So that over limit e-mails and grace period is handled regardless - they're still subscribers.
> Check usage for users with active/cancelled/past due subscriptions

- lib/workers/clean_invitations.ex
- test/workers/clean_invitations_test.exs
Fixes a problem where tests fail due to timezone shift when run locally against a DB with non-UTC timezone configured. The database of course should be configured properly in the first place but this change has an added benefit of making it more consistent with other time-dependent checks where the timestamp for comparison is usually provided from the app-side and not calculated directly in the database.
> Make invitations cleanup worker rely on UTC time

- extra/lib/plausible/help_scout.ex
- extra/lib/plausible_web/views/help_scout_view.ex
- lib/plausible/auth/user.ex
- lib/plausible/auth/user_admin.ex
- test/plausible_web/controllers/help_scout_controller_test.exs
Depends on https://github.com/plausible/analytics/pull/4612
Implements ability to leave notes on a particular user in CRM.
The notes are also exposed (read-only) via HS integration.
> Implement user notes in CRM and HelpScout integration

- lib/plausible_web/endpoint.ex
Fix for https://github.com/plausible/analytics/discussions/4618#discussioncomment-10751271
What is happening (probably):
- after POST /login browsers store two cookies, legacy-session one for .\<domain\> and new-session one for \<domain\> for the same key
- (some?) browsers put legacy-session cookie first in the cookie header
- Plug uses maps, so only one _plausible_prod cookie gets in, and in the current implementation, it's the first one that appears in the cookie header
- if legacy-session cookie ends up in the session map, auth plugs fail and redirect back to /login
This PR just changes the cookie key to `_plausible_key` so that there wouldn't be any conflicts.
> Change cookie key in CE

- lib/plausible_web/controllers/site_controller.ex
- lib/plausible_web/controllers/unsubscribe_controller.ex
- lib/plausible_web/live/installation.ex
- lib/plausible_web/live/verification.ex
- lib/plausible_web/plugs/authorize_site_access.ex
- lib/plausible_web/router.ex
- test/plausible_web/controllers/google_analytics_controller_test.exs
- test/plausible_web/controllers/invitation_controller_test.exs
- test/plausible_web/controllers/site/membership_controller_test.exs
- test/plausible_web/controllers/site_controller_test.exs
- test/plausible_web/controllers/stats_controller_test.exs
- test/plausible_web/controllers/unsubscribe_controller_test.exs
- test/plausible_web/live/funnel_settings_test.exs
- test/plausible_web/live/goal_settings_test.exs
- test/plausible_web/live/plugins_api_tokens_test.exs
- test/plausible_web/live/props_settings_test.exs
- test/plausible_web/plugs/authorize_site_access_test.exs
While addressing `AuthorizeSiteAccess` plug refactor, it occurred to us that `:website` and `:domain` path params in routes are basically redundant. This PR replaces all the occurrences of `:website` with `:domain`. We make an exception with `dogfood_page_path` where we leave it intact. This way we avoid duplicate entries in demo dashboard.
> Use `:domain` uniformly for all routes instead of `:website`

- config/dev.exs
- lib/plausible_web/plugs/authorize_site_access.ex
- lib/plausible_web/router.ex
- test/plausible_web/controllers/api/internal_controller/docs_query_test.exs
- test/plausible_web/plugs/authorize_site_access_test.exs
- test/support/test_controller.ex
- Allow auth site access plug to specify that domain is found in request body at some key, needed for api/docs/query endpoint where :domain or :website does not appear in path params
- Nuisance: Stop typescript --watch command clearing previous server stdout when running make server
> Allow configuring `AuthorizeSiteAccess` plug site param

- CHANGELOG.md
After-the-fact release of [v2.1.3,](https://github.com/plausible/analytics/discussions/4629) just to update the changelog.
> Release v2.1.3

- lib/plausible/application.ex
This PR makes `Plausible.Auth.TOTP.Vault` start (and create ets table, and save initial config) before `Plausible.Site.Cache` runs refreshers.
Fixes #4619
> Start TOTP vault early

- CHANGELOG.md
- assets/js/dashboard/stats/reports/list.js
Previously these tooltips said `Add filter: Country is undefined` because new labels were yet to be in `query`.
cc @apata - curious on your thoughts on if or how best test this
Basecamp: https://3.basecamp.com/5308029/buckets/36789884/card_tables/cards/7816925449
> Dashboard: Fix countries/regions/cities tooltips

- CHANGELOG.md
- lib/plausible/auth/user_sessions.ex
- lib/plausible_web/controllers/auth_controller.ex
- lib/plausible_web/router.ex
- lib/plausible_web/templates/auth/user_settings.html.heex
- lib/plausible_web/user_auth.ex
- test/plausible/auth/user_sessions_test.exs
- test/plausible_web/controllers/auth_controller_test.exs
- test/plausible_web/user_auth_test.exs
This PR adds ability to review and revoke particular active logged in user sessions.
> Implement listing user sessions in user settings

- extra/lib/plausible_web/dogfood.ex
- lib/plausible/goal/schema.ex
- lib/plausible/ingestion/event.ex
- lib/plausible/session/cache_store.ex
- lib/plausible/stats/aggregate.ex
- lib/plausible/stats/breakdown.ex
- lib/plausible/stats/clickhouse.ex
- lib/plausible/stats/sql/expression.ex
- lib/plausible_web/plugs/tracker.ex
- test/plausible/billing/quota_test.exs
- test/plausible/goals_test.exs
- test/plausible/ingestion/event_test.exs
- test/plausible/session/cache_store_test.exs
- test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
- test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
- tracker/compile.js
- tracker/src/plausible.js
With a future goal of implementing the `scroll_depth` metric, this PR introduces an experimental script variant for tracking `pageleave` events. 
Sending analytics data when the page is unloaded is unreliable by nature. Hence the first objective is to find out the percentage of pageleave events that we can expect (100% would mean that the number of pageleaves equals the number of pageviews).
If the percentage is reasonable, the next step would be to track a `scroll_depth` parameter with `pageleave` events, and eventually start reporting the average of that value on the dashboard, per page.
Here's a more technical description of the changes introduced in this PR:
* Implement a `script.pageleave.js` script variant.
* The script will start triggering `pageleaves` on the `pagehide` browser …
> Experimental pageleave events

- lib/plausible/file.ex
- lib/plausible_web/live/csv_import.ex
- lib/workers/export_analytics.ex
- test/plausible/imported/csv_importer_test.exs
This PR replaces `File.rename!` with a custom `Plausible.File.mv!` functions that tries `File.rename!` first and falls back to `File.cp!` and `File.rm` in case of EXDEV error:
> EXDEV oldpath and newpath are not on the same mounted filesystem. (Linux permits a filesystem to be mounted at multiple points, but rename() does not work across different mount points, even if the same filesystem is mounted on both.)
Closes https://github.com/plausible/analytics/issues/4638
---
Since EE uses S3 instead of local disk for exports/imports, this PR only affects CE.
> Handle cross-device file move

- CHANGELOG.md
- lib/plausible/auth/auth.ex
- lib/plausible/auth/user.ex
- lib/plausible_web/components/two_factor.ex
- lib/plausible_web/controllers/auth_controller.ex
- lib/plausible_web/router.ex
- lib/plausible_web/templates/auth/user_settings.html.heex
- lib/plausible_web/user_auth.ex
- lib/plausible_web/views/error_helpers.ex
- test/plausible_web/controllers/auth_controller_test.exs
This PR adds a password change capability to account settings.
UI-wise it will receive more love in a follow-up iteration - we're planning to rewrite the account settings completely (as part of Team Accounts project).
> Settings password reset

- CHANGELOG.md
- extra/lib/plausible/stats/goal/revenue.ex
- test/plausible_web/controllers/api/stats_controller/custom_prop_breakdown_test.exs
- test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
Seems since https://github.com/plausible/analytics/pull/4415 or https://github.com/plausible/analytics/pull/4391, revenue metrics have not been correctly displayed on the dashboard if the goal display name has been changed from the default.
Discovered while refactoring this code, wanted to PR the fix separately.
> Fix revenue metrics if custom display name is used

- lib/plausible_web/templates/layout/_tracking.html.heex
- tracker/src/plausible.js
While experimenting with pageleave events we've discovered that pageviews are not being fired when a page is loaded from bfcache.
This PR fixes that, for now, only in the context of the pageleave script variant. I'm leaving the default script untouched for now as the pageleave variant will also be merged into the default script at some point.
The fix itself is to listen for the `pageshow` event and fire a pageview if the `event.persisted` property is `true`.
Note that we only add the 'pageshow' listener if the script is **not in manual mode**. If it's manual, the listener needs to be added manually as well.
Since we're using the manual variant ourselves (in both this repo, and in plausible/website):
1. the PR at hand updates `_tracking.html` to add the 'pageshow' listener
2. [this …
> Trigger pageviews on pages loaded from bfcache

- CHANGELOG.md
- lib/oban_error_reporter.ex
This PR adds logging for Oban errors. The reasoning is that most self-hosters don't have Sentry configured which makes these errors invisible.
Here's how it'd look after this PR:
> Log Oban errors (and still report them to Sentry)

- CHANGELOG.md
- priv/repo/structure.sql
This PR updates changelog and [structure.sql](https://github.com/plausible/analytics/pull/4481) dumps for v2.1.4 patch release.
> Release v2.1.4

- assets/js/types/query-api.d.ts
- extra/lib/plausible/stats/goal/revenue.ex
- lib/plausible/goals/filters.ex
- lib/plausible/stats/aggregate.ex
- lib/plausible/stats/breakdown.ex
- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/legacy/legacy_query_builder.ex
- lib/plausible/stats/query.ex
- lib/plausible/stats/query_optimizer.ex
- lib/plausible/stats/query_runner.ex
- lib/plausible/stats/timeseries.ex
- priv/json-schemas/query-api-schema.json
- test/plausible/stats/query_parser_test.exs
- test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
This PR brings revenue metrics to APIv2. They are still not yet publicly available but are now fully functional for dashboard use.
Notes:
- No behavioral changes for users
- Revenue currencies are stored on `Query` similar to goals with associated business logic
- Revenue metric access is validated properly
- Old behavior of removing revenue metrics when unavailable is done via a Query flag and QueryOptimizer behavior.
Needed to bring breakdowns frontend to APIv2.
> APIv2: Revenue metrics

- tracker/src/plausible.js
- tracker/test/fixtures/manual.html
- tracker/test/manual.spec.js
Fixes two bugs with the experimental script:
1. After the initial pageview is triggered, the current script sets an eventListener to trigger pageleave with the **URL of the initial page**, when `pagehide` occurs. That doesn't make sense in Single Page Apps. Instead, every time SPA navigation takes place, that URL should change to that of the last pageview.
2. Currently, pageleave events in SPAs are being fired regardless of exclusion rules (incl localhost and bot traffic). The second commit of this PR fixes that by adding an additional condition: only fire pageleaves on SPA navigation if `listeningPageLeave` is `true`. That value will never become true until a pageview has been sent.
> Fix experimental pageleaves script (SPAs)

- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
otherwise it falls back to `visitors` descending,
which AFAIU is 2 for both metrics leading to random order effectively.
> Add explicit `order by` to a flaky test

- lib/plausible/ingestion/event.ex
- lib/plausible/ingestion/request.ex
- test/plausible/ingestion/event_test.exs
This is not a bug, but more of a micro-optimization. If the hostname is known to be `(none)`, there's no need try and compute root domain. 
:eyes: At the same, it looks like ingestion had a dead clause trying to match `nil` hostname. `Plausible.Ingestion.Request` should reject such cases before they reach `Plausible.Ingestion.Event` processing. 
Ref https://3.basecamp.com/5308029/buckets/26383192/card_tables/cards/7916301991
> Set root domain `(none)` for ingests without hostname

- lib/plausible_web/templates/email/site_setup_success_email.html.heex
Addresses an issue where site domain name is not properly interpolated in email sent to the user.
> Properly interpolate site name in site setup success email

- lib/plausible_web/templates/email/welcome_email.html.heex
This PR removes a bracket after "404 error pages" in the Welcome email:
> Remove bracket from welcome email

- lib/plausible/data_migration/backfill_teams.ex
Minor adjustment to the backfill script so that it does not hog too much resources when run in prod.
> Limit resource usage in teams backfill data migration

- lib/plausible/stats/comparisons.ex
- lib/plausible/stats/filters/filters.ex
- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/imported/sql/where_builder.ex
- lib/plausible/stats/query.ex
- lib/plausible/stats/query_optimizer.ex
- lib/plausible/stats/query_runner.ex
- lib/plausible/stats/sql/special_metrics.ex
- lib/plausible/stats/sql/where_builder.ex
- lib/plausible/stats/time.ex
- lib/plausible_web/controllers/api/external_query_api_controller.ex
- lib/plausible_web/router.ex
- test/plausible/stats/comparisons_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_comparisons_test.exs
- test/plausible_web/controllers/api/stats_controller/browsers_test.exs
Depends on https://github.com/plausible/analytics/pull/4692
Currently, when doing comparisons when breaking down by e.g. `visit:browser` dimension, zeroes would be incorrectly applied when small limits are in place. This is because the top 10 browsers today might not be the same as in previous period.
This PR fixes that by OR-ing together all dimension values from main result in comparison filter. Additionally, this filter is ignored when calculating totals as is needed for percentage/conversion rate calculations.
Rather than test every old endpoint separately, this PR adds a test-only endpoint for testing query logic as well.
> Comparisons pagination fixes

- lib/plausible/google/ga4/api.ex
- lib/plausible/google/ga4/http.ex
- lib/plausible/imported/google_analytics4.ex
- test/plausible/imported/google_analytics4_test.exs
This PR improves error handling in GA4 imports.
- Fetch errors are consistently logged with "warning" level
- socket and 5xx errors are treated as recoverable (even after retry-with-backoff fails) - the import is resumed after and hour, like in case of rate limit being exceeded
> Improve GA4 import error handling

- assets/js/dashboard/stats/graph/top-stats.js
These werent being graphed due to incorrect conditional. The root cause of the error Artur flagged was the <Maybe /> children being eagerly evaluated, causing incorrect values to be passed to formatters.
Missed this since my trial had run out locally :sweat_smile: 
Ref: https://3.basecamp.com/5308029/buckets/36789884/card_tables/cards/7945586401
> Restore average/total revenue to top stats

- assets/js/dashboard/stats/reports/metric-formatter.ts
- assets/js/dashboard/util/money.ts
Another follow-up to https://github.com/plausible/analytics/pull/4716 and https://github.com/plausible/analytics/pull/4692
This change:
1. Restores `conversions` graph tooltips
2. Displays money values on graph correctly
> Fix money values on graphs and `conversions` graph tooltips

- CHANGELOG.md
- assets/js/dashboard/stats/modals/filter-modal-props-row.js
- lib/plausible/stats.ex
- lib/plausible/stats/filter_suggestions.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- lib/plausible_web/router.ex
- test/plausible_web/controllers/api/stats_controller/suggestions_test.exs
This has been broken since filtering by multiple custom props became possible. 
To reproduce the bug:
1. Go to the live demo
2. Open the filter modal and apply a filter like "browser_language is en-US"
3. Click on the filter card above the dashboard to edit the filter (the filter modal will open again)
4. Click "+ Add another"
5. Select a property other than `browser_language`, e.g. `logged_in`
6. Click on the prop value field to fetch suggestions
7. BUG: suggestions are fetched for `browser_language` rather than `logged_in`
The current logic in the `/:domain/suggestions` endpoint for custom prop values is not accounting for the fact that there might be multiple filters with the `event:props` prefix.
This PR fixes that, introducing a new endpoint with a `prop_key` path parameter which …
> Fix custom property value filter suggestions

- lib/plausible/stats/filters/filters.ex
- test/plausible_web/controllers/api/stats_controller/pages_test.exs
Previously the code would use the incorrect operator and lead to nesting. This broke pages report in hard-to-reproduce ways.
> Comparisons: Fix filter transformations

- assets/js/dashboard/stats/graph/top-stats.js
This fixes a bug from navigation:
1. Comparison disabled, choose a non-realtime period (e.g. press T for "Last 30 days")
2. Enable comparison mode (press X)
3. Choose the realtime period (press R)
4. Choose a non-realtime period again (press T)
Kudos to robert for discovering the repro case.
> Comparisons: Only render comparisons in top stats when both query and data supports it

- extra/lib/plausible_web/controllers/api/external_sites_controller.ex
- lib/plausible/auth/auth.ex
- lib/plausible/data_migration/teams_consistency_check.ex
- lib/plausible/site/removal.ex
- lib/plausible/sites.ex
- lib/plausible_web/controllers/site_controller.ex
- test/plausible/goals_test.exs
- test/plausible/site/site_removal_test.exs
- Extend consistency checks - checking if there are no excess memberships in the new schemas
- Sync team right after creating site against current user state
- Prune orphaned team guest memberships and invitations on site removal
> Extend team consistency checks and improve syncing team and memberships

- lib/plausible/billing/enterprise_plan.ex
- lib/plausible/billing/plan.ex
- lib/plausible/billing/plans.ex
- lib/plausible_web/components/billing/notice.ex
- lib/plausible_web/templates/site/settings_funnels.html.heex
- lib/plausible_web/templates/site/settings_props.html.heex
- test/plausible_web/live/funnel_settings_test.exs
- test/plausible_web/live/props_settings_test.exs
https://3.basecamp.com/5308029/buckets/36789884/card_tables/cards/7959193799
This change brings back premium feature notices to funnels and custom props, such as:
it also adds relevant tests, so it's not accidentally removed in the future.
We also stop asking users to e-mail us, upgrade should be a viable option for everyone.
> Bring back premium feature notices (+no "email us" notice for trials)

- .github/workflows/node.yml
- tracker/package.json
- tracker/report-sizes.js
Currently opted for a selection of filenames that are "interesting to know". Printing out file sizes for every file is pretty noisy (> 2000 lines) and irrelevant, I think. The default `plausible.js` script size is the one that matters.
> Add size reporter GH action

- lib/plausible/data_migration/backfill_teams.ex
- lib/plausible/site/memberships/accept_invitation.ex
- lib/workers/clean_invitations.ex
- test/support/factory.ex
- test/workers/clean_invitations_test.exs
- always run invitations and site transfers accept sync inside transaction along with the current logic
- clean expired site transfers
- add dry run mode to teams backfill
> Address team syncing discrepancies

- lib/plausible/teams/invitations.ex
- test/plausible/site/memberships/accept_invitation_test.exs
Addresses another issue with teams schema sync.
> Ensure upserted invitations and memberships are up to date on conflict

- assets/js/dashboard/stats/graph/visitor-graph.js
Fixes dashboard crashing when comparisons are enabled in the query and changing from realtime period to a historical period.
The [previous attempt](https://github.com/plausible/analytics/pull/4732) to fix this did half of the work, but since the `comparing_from` and `comparing_to` fields were returned from the backend even for realtime queries, the bug is still there.
Reproduction:
1. Comparison disabled, choose a non-realtime period (e.g. press T for "Last 30 days")
2. Enable comparison mode (press X)
3. Choose the realtime period (press R)
4. Choose a non-realtime period again (press T)
> Fix dashboard crash

- lib/plausible/google/ga4/api.ex
- lib/plausible/google/ga4/http.ex
Adjustment to the GA4 import in the hopes of improving reliability for more complicated cases.
> Adjust GA4 import timeout and page size to reduce risk of 502s and timeouts

- assets/js/dashboard/query.ts
- assets/js/dashboard/stats/graph/graph-tooltip.js
- assets/js/dashboard/stats/modals/breakdown-modal.tsx
- assets/js/dashboard/stats/reports/change-arrow.test.tsx
- assets/js/dashboard/stats/reports/change-arrow.tsx
- assets/js/dashboard/stats/reports/list.js
- assets/js/dashboard/stats/reports/metric-value.test.tsx
- assets/js/dashboard/stats/reports/metric-value.tsx
- assets/js/dashboard/stats/reports/metrics.js
- assets/js/dashboard/util/url-search-params.test.ts
- lib/plausible/stats/breakdown.ex
- lib/plausible/stats/comparisons.ex
- lib/plausible/stats/query.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- lib/plausible_web/live/sites.ex
- test/plausible_web/controllers/api/stats_controller/browsers_test.exs
- test/plausible_web/controllers/api/stats_controller/sources_test.exs
This PR:
- Updates arrows across the app
- Fixes a small bug when calculating bounce_rate in comparisons
- Returns main and comparison date ranges in breakdown endpoints
- Updates comparison tooltip designs to include comparison date ranges
- Removes wavy arrow from being shown when no change in breakdown lists
- Makes Graph tooltip render via react for consistency and easier reuse of arrows
Notes:
- I also experimented with varying stroke widths for arrows, but IMO it did not look good. Feel free to build upon this: https://github.com/plausible/analytics/pull/4719/commits/23a97ba506d2fd9042cde598639bb75a28ddaa33
- The screenshots show some oddity around comparison date range calculations. ~~This seems like an older bug, investigating separately.~~ This comes from day-of-week matching, …
> Breakdown comparisons: Tooltip UX, arrows 

- assets/js/dashboard/stats/graph/stats-export.js
- config/runtime.exs
This PR:
1. Increases `max_parser_depth` setting. See https://github.com/plausible/analytics/commit/6399cf54318c40434dd3686df253ab09ef4d3c3c for full context
2. Removes comparisons querying from exports endpoint - the data would never be used anyways.
> Comparisons: Fix exports issue

- extra/lib/plausible/stats/sampling.ex
- lib/plausible/stats/legacy/legacy_query_builder.ex
- lib/plausible/stats/query.ex
We found cases where using a numeric sample rate would cause issues when joining two tables due to different _sample_factor. Ref: https://3.basecamp.com/5308029/buckets/26383192/card_tables/cards/7973456592#__recording_7978780711
The proper fix is to use fractional sample rates everywhere, but this is a whole project due to not wanting to sample small sites. For now, hard-code sample rate for specific sites having the issue [while we work on a larger fix](https://3.basecamp.com/5308029/buckets/39750953/messages/7978775089).
> Hard-code sample rate based on fractional_hardcoded_sample_rate flag

- .github/workflows/elixir.yml
- lib/plausible_web/live/sites.ex
- test/plausible_web/live/sites_test.exs
- test/support/teams/test.ex
- test/test_helper.exs
This PR introduces full test suite runs with `read_team_schemas` feature flag up and down on CI. It's meant to reduce the risk of regressions during future further changes.
We are replacing the existing setup for `experimental_reduced_joins` which wasn't actively used and will be removed some time in the future. This way we don't make CI run longer than necessary.
> Run full test suite against `read_team_schemas` FF on CI

- assets/js/dashboard/components/dropdown.tsx
- assets/js/dashboard/datepicker.tsx
- assets/js/dashboard/filters.js
- assets/js/dashboard/index.tsx
- assets/js/dashboard/nav-menu/filter-menu.tsx
- assets/js/dashboard/nav-menu/filter-pill.tsx
- assets/js/dashboard/nav-menu/filter-pills-list.tsx
- assets/js/dashboard/nav-menu/filters-bar.test.tsx
- assets/js/dashboard/nav-menu/filters-bar.tsx
- assets/js/dashboard/nav-menu/top-bar.test.tsx
- assets/js/dashboard/nav-menu/top-bar.tsx
- assets/js/dashboard/site-context.tsx
- assets/js/dashboard/site-switcher.js
- assets/js/dashboard/stats/current-visitors.js
- assets/test-utils/index.ts
- lib/plausible_web/controllers/stats_controller.ex
* Shows Filters on a separate line if feature flag `saved_segments` is true
* Makes minor adjustments to elements on the first line (rolled out to all, too minor to guard with FF)
* icons won't shrink on small screens
* elements have fixed height at `h-9`
* Makes the dropdown component less opinionated: more configurable.
> Show filters on a separate line

- lib/plausible/data_migration/backfill_teams.ex
Another addition to the backfill to fix existing inconsistency in synced data.
> Add removing guest memberships with mismatched team to backfill script

- lib/plausible/data_migration/backfill_teams.ex
- lib/plausible/teams/sites.ex
This PR:
- removes "prosthetic" relying on the old schema in new sites list query logic
- fixes a bug in recent update to the backfill script
> Get rid of memberships prosthetic for `Teams.Sites.list_with_invitations`

- lib/plausible/ingestion/acquisition.ex
- lib/plausible/ingestion/event.ex
- test/plausible_web/controllers/api/external_controller_test.exs
I messed up with channels & source merging. The way we've been collecting data, some information gets lost. Specifically, when someone uses `?ref=googleads`, for example, it will be stored as `source=Google` and `channel=Organic Search` with no ability for the user to filter or split that traffic after the fact.
Previously `googleads` would show up separately in the Sources report but after https://github.com/plausible/analytics/pull/4751 it's merged with `Google`. This means customers who rely on manually tagged `?ref` and `?source` params lost some data.
This PR intends to fix this going forward with 2 functional changes:
* Makes `?ref` and `?source` query params a true alias for `?utm_source` so they are handled identically and stored in the `utm_source` column.
* For channel data, …
> Fixes for `?source` and `?ref` params

- lib/plausible/auth/grace_period.ex
- lib/plausible/billing/feature.ex
- lib/plausible/billing/site_locker.ex
- lib/plausible/data_migration/backfill_teams.ex
- lib/plausible/site/memberships/invitations.ex
- lib/plausible/teams.ex
- lib/plausible/teams/billing.ex
- lib/plausible/teams/invitations.ex
- lib/plausible/teams/users.ex
- lib/plausible_web/live/register_form.ex
- lib/plausible_web/live/sites.ex
- test/plausible_web/controllers/site_controller_test.exs
- test/plausible_web/live/sites_test.exs
- test/support/teams/test.ex
> Finish moving /sites LV reads to team schemas behind FF

- lib/plausible/teams/invitations.ex
Removes erroneous preloads which broke accepting transfers with pending invitations.
> Fix accept invitation sync

- lib/mix/tasks/clean_clickhouse.ex
- lib/plausible/data_migration.ex
- lib/plausible/data_migration/acquisition_channel.ex
- priv/data_migrations/AcquisitionChannel/sql/acquisition_channel_functions.sql.eex
The previous `has` queries proved to be problematic and causing a lot of
CPU overhead. We can improve this by using dictionaries instead.
Benchmarked via this query:
```sql
SELECT
channel,
count(),
countIf(acquisition_channel(referrer_source, utm_medium, utm_campaign, utm_source, click_id_param) = channel) AS matches
FROM events_v2
WHERE timestamp > now() - toIntervalHour(48)
GROUP BY channel
ORDER BY count() desc
```
Before this fix:
```
query_duration_ms:                                                57960
DiskReadElapsedMs:                                                374.712
RealTimeMs:                                                       2891200.667
UserTimeMs:                                                       2704024.783
SystemTimeMs: …
```
> Channels: Speed up clickhouse calculations

- priv/repo/migrations/20241107120000_create_segments.exs
Creates the saved segments table.
```
List of data types
Schema |     Name     | Description 
--------+--------------+-------------
public | segment_type | 
Table "public.segments"
Column    |              Type              | Collation | Nullable |               Default                
--------------+--------------------------------+-----------+----------+--------------------------------------
id           | bigint                         |           | not null | nextval('segments_id_seq'::regclass)
name         | character varying(255)         |           | not null | 
type         | segment_type                   |           | not null | 'personal'::segment_type
segment_data | jsonb                          |           | not null | 
site_id      | bigint                         | …
```
> Saved segments/create table

- lib/plausible/data_migration/acquisition_channel.ex
- lib/plausible/ingest_repo.ex
- priv/data_migrations/AcquisitionChannel/sql/acquisition_channel_functions.sql.eex
CREATE TABLE AS SELECT syntax did not work on cluster.
Instead, let's do a normal insert. For safety and to avoid timing issues, ensure that TRUNCATE/INSERT waits for data to be in sync in all the replicas.
> Channels: Fix ON CLUSTER behavior

- .github/workflows/migrations-validation.yml
- lib/plausible/data_migration/acquisition_channel.ex
- priv/data_migrations/AcquisitionChannel/sql/acquisition_channel_add_materialized_column.sql.eex
- priv/data_migrations/AcquisitionChannel/sql/acquisition_channel_backfill_materialized_column.sql.eex
- priv/data_migrations/AcquisitionChannel/sql/acquisition_channel_functions.sql.eex
- priv/data_migrations/AcquisitionChannel/sql/acquisition_channel_update_materialized_column.sql.eex
- priv/ingest_repo/migrations/20241111084056_create_acquisition_channel_column.exs
This change adds `acqusition_channel` columns to events_v2 and sessions_v2 tables. These columns are materialized - we don't ingest into them directly. Instead they're calculated based on other columns.
The data migration changes now allow to also backfill the column.
Tested the ability to change definitions by changing the function definitions and re-running the migration with backfill. Confirmed that the underlying data changed as expected.
Before merging this:
- Merge https://github.com/plausible/analytics/pull/4789
After this:
- Run migration on cloud
- Backfill `click_id_param` on cloud
- Kick off a backfill
- Spot-check the results and impact on ingestion, etc
- PR a change to stop ingesting into the old column, to read from new one
> Channels: Migration to add materialized column, backfill code

- lib/plausible/stats/query.ex
- test/plausible/stats/comparisons_test.exs
- test/plausible/stats/query_test.exs
`query.now` is in utc but the date range was in the querys timezone
This is visible in the pattern on the graph, with peaks around UTC midnight:
Ref: https://3.basecamp.com/5308029/buckets/39750953/card_tables/cards/7999429743
> Solve noisy warnings about `a negative range was inferred for Date.range/2`

- priv/repo/migrations/20241111094545_set_teams_allow_next_upgrade_override_default.exs
There will be a follow-up migration setting NOT NULL constraint on that column as well (released separately after this migration is run and all out-of-sync teams entries are fixed by backfill).
> Set default for `teams.allow_next_upgrade_override` schema column

- lib/plausible/clickhouse_event_v2.ex
- lib/plausible/clickhouse_session_v2.ex
- lib/plausible/ingestion/event.ex
- lib/plausible/ingestion/write_buffer.ex
- lib/plausible/session/cache_store.ex
- lib/plausible/stats/filter_suggestions.ex
- lib/plausible/stats/sql/expression.ex
- lib/plausible/stats/sql/where_builder.ex
- test/plausible_web/controllers/CSVs/30d-filter-goal/channels.csv
- test/plausible_web/controllers/CSVs/30d/channels.csv
- test/plausible_web/controllers/CSVs/6m/channels.csv
- test/plausible_web/controllers/api/external_controller_test.exs
- test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
- test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
- test/plausible_web/controllers/api/stats_controller/sources_test.exs
- test/plausible_web/controllers/api/stats_controller/suggestions_test.exs
- test/plausible_web/controllers/stats_controller_test.exs
- test/support/test_utils.ex
Follow-up to https://github.com/plausible/analytics/pull/4798
Once this change is in, we'll read from the new `acquisition_channel` column.
> Channels: Read from new column, don't write

- lib/plausible/teams/invitations.ex
- test/plausible_web/controllers/invitation_controller_test.exs
Addresses faulty sync logic for transfer ownership removal.
> Fix team sync on ownership transfer removal

- test/plausible/ingestion/event_test.exs
Can't tell for sure as this test fail is hard to reproduce, but I suspect there might be situations where reaching session processing step in the first ingest takes longer than the sleep before spinning up the second ingest.
> Try to make ingest lock timeout tests less flaky

- lib/plausible/sites.ex
- lib/plausible/teams.ex
- lib/plausible/teams/adapter.ex
- lib/plausible/teams/adapter/read/billing.ex
- lib/plausible/teams/adapter/read/ownership.ex
- lib/plausible/teams/adapter/read/sites.ex
- lib/plausible/teams/billing.ex
- lib/plausible_web/controllers/site_controller.ex
- test/plausible/billing/quota_test.exs
- test/plausible_web/controllers/api/external_sites_controller_test.exs
- test/plausible_web/controllers/site_controller_test.exs
- test/support/teams/test.ex
- test/test_helper.exs
Read team schemas, on creating a new sites, if feature flag is enabled.
> Switch sites creation to read teams schemas

- lib/plausible_web/plugs/favicon.ex
- priv/custom_sources.json
Very small update from browsing the live demo:
* Merge teams.microsoft.com -> Microsoft Teams (not important enough to backfill this IMO)
* Display favicon for Linkedin source
> Tiny source data update

- CHANGELOG.md
- assets/js/dashboard/stats/behaviours/goal-conversions.js
- assets/js/dashboard/stats/modals/props.js
- assets/js/dashboard/stats/modals/referrer-drilldown.js
- assets/js/dashboard/stats/sources/referrer-list.js
- assets/js/dashboard/util/url.ts
1) Passing a react-router path param with a forward slash in it, like "Direct / None", breaks the route. There's two routes that have params that take user input (filter modals has fixed param values), and this PR encodes such params. 
2) useParams gives us a decoded value for the params, therefore we need to re-encode them to make successful API calls.
> Hotfix Direct / None modal

- lib/plausible/stats/query.ex
- test/plausible/stats/query_test.exs
Follow-up to https://github.com/plausible/analytics/pull/4803
We could still get warnings about negative date ranges when the date being queried is in the future.
This could happen if the users local time is in the future for some reason or they manually edit the url.
Ref: https://3.basecamp.com/5308029/buckets/39750953/card_tables/cards/7999429743
> Follow-up to Solve noisy warnings about a negative range was inferred for Date.range/2

- lib/plausible/stats/goal_suggestions.ex
- test/plausible/stats/goal_suggestions_test.exs
- test/plausible_web/controllers/api/stats_controller/suggestions_test.exs
A small leftover from when I disabled adding a goal with the name `pageleave`. Also need to make sure they're not suggested.
Also noticed that the filter_suggestions endpoint for the `goal` dimension is missing a real test, so added that too.
> Stop suggesting pageleave as a custom event goal name

- lib/plausible/ingestion/event.ex
- test/plausible_web/controllers/api/external_controller_test.exs
Adds entries for (gclid) and (msclkid) to utm mediums in case when:
* UTM Medium is not present
* Paid Search channel is inferred from click_id_param and referrer_source
Will add changelog when channels are ready to go live
Will add docs when feature is ready to go live
> Infer medium from click id if not present

- CHANGELOG.md
- priv/ingest_repo/migrations/20241118112238_backfill_utm_medium_click_id_param.exs
Follow-up to https://github.com/plausible/analytics/pull/4817
The key idea is to show data in the utm medium report when looking at paid search.
Ref: https://3.basecamp.com/5308029/buckets/39036182/card_tables/cards/8022470793
> Channels: backfill utm_medium based on click_param_id

- extra/lib/plausible/stats/sampling.ex
- extra/lib/plausible/stats/sampling_cache.ex
- lib/plausible/application.ex
- lib/plausible/cache.ex
- test/plausible/stats/query_test.exs
- test/plausible/stats/sampling_cache_test.exs
- test/plausible/stats/sampling_test.exs
Our old sampling mechanism used SAMPLE 20000000 syntax. This was wonderful since it allowed essentially dynamic sampling based on the data being queried. However this ran into many issues relating to JOINs and sample rate being different for different tables.
Instead, we now start to dynamically vary sample rates fractionally.
At query time we check the time window being queried and estimate how many rows this query might reach. For large queries, we then dynamically decide the sample rate.
For getting the traffic estimate for a site, we have a new SampingCache class which queries `ingest_counters`.
Future work:
- The query being cached is slightly expensive and can be sped up with a ClickHouse projection. This will be added in a follow-up PR.
- Reducing sample rate if `query.filters` is …
> fractional_sample_rate: Vary sample rate according to traffic estimation

- lib/plausible_web/live/installation.ex
Just a minor addition for cases when GTM isn't detected due to a cookie banner.
> Add GTM installation option, when no GTM detected

- config/runtime.exs
- lib/plausible/data_migration/acquisition_channel.ex
- lib/plausible/data_migration/locations_sync.ex
- lib/plausible/data_migration/numeric_ids.ex
- lib/plausible/migration_utils.ex
- priv/data_migrations/AcquisitionChannel/sql/acquisition_channel_functions.sql.eex
- priv/data_migrations/LocationsSync/sql/create-location-data-table.sql.eex
- priv/ingest_repo/migrations/20200915070607_create_events_and_sessions.exs
- priv/ingest_repo/migrations/20211112130238_create_imported_tables.exs
- priv/ingest_repo/migrations/20230214114402_create_ingest_counters_table.exs
- priv/ingest_repo/migrations/20230320094327_create_v2_schemas.exs
- priv/ingest_repo/migrations/20240423094014_add_imported_custom_events.exs
In production we use `storage_policy = 'tiered'` by default but this is not reflected in any migrations.
This change fixes that by introducing a new environment variable and plumbing to be used in new (and old) migrations
Tested via setting env, doing `mix ecto.drop; mix ecto.create; mix ecto.migrate` and checking resulting table schemas.
> CLICKHOUSE_DEFAULT_STORAGE_POLICY env

- lib/plausible_web/controllers/debug_controller.ex
This fixes an issue with /debug/clickhouse route - site_domain query param didn't work properly.
> Fix debug controller domain filtering

- config/runtime.exs
- lib/plausible/application.ex
This PR switches from Logger backends to `:logger` handlers.
Card: https://3.basecamp.com/5308029/buckets/29267832/card_tables/cards/7610404292
Some time later, once or if there is a need for structured logging, we can also replace ExJsonFormatter with [something else.](https://github.com/plausible/analytics/pull/4855)
> Drop Logger backends

- lib/plausible/segment.ex
- test/plausible/segment_schema_test.exs
Registers segments schema with Ecto.
> Register segments schema

- priv/repo/migrations/20241126103023_make_user_id_nullable_on_subscriptions_enterprise_plans.exs
Migration extracted from #4860
> Drop null constraint on user_id from subscriptions and enterprise_plans

- lib/plausible/teams/adapter/read/sites.ex
- lib/plausible_web/components/billing/notice.ex
- lib/plausible_web/live/goal_settings.ex
- test/plausible_web/controllers/settings_controller_test.exs
This PR addresses a problem where `current_team` is empty when opening goal creation form in goal settings view. In static view, the `AuthorizeSiteAccess` plug ensures `current_team` is populated with current site's team (overriding user's `current_team` from `AuthPlug`). In LV, `AuthContext` replicates what `AuthPlug` does but there's no respective mechanism for override by site's team. Currently only Goal Settings LV relies on `current_team` value, so this fix addresses this one particular case for now.
A smiliar problem occurs when assuming current team is always present in views where there's no site in context. The "Account Settings > API Keys" view is an example of that. The billing notice components used across static and LV views got updated here to handle missing team gracefully. …
> Provide site-related team for current team in goal settings LV

- lib/plausible/ingestion/request.ex
- test/plausible/ingestion/request_test.exs
Currently we're failing to read a subsequent chunk of a >1M bytes request on ingest.
Those are rare and likely unintentional: https://sentry.plausible.io/organizations/plausible/issues/55/?environment=prod&project=2&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0
Either way, this change only takes care responding with an error gracefully, rather than producing a crash. Details on what the limits should be and whether it's beneficial to produce a specific error message in such cases, is out of scope. Existing limit is kept as is for now.
> Don't crash ingesting >1M bytes payloads

- lib/plausible/teams/invitations.ex
- test/plausible/site/memberships/create_invitation_test.exs
Fix to a regression which surfaced after enabling `read_team_schema` FF.
> Send correct invitation ID in email for new users

- CHANGELOG.md
- lib/plausible/stats/imported/imported.ex
- lib/plausible/stats/imported/sql/expression.ex
- lib/plausible/stats/query_optimizer.ex
- lib/plausible/stats/sql/query_builder.ex
- lib/plausible/stats/sql/special_metrics.ex
- test/plausible_web/controllers/api/external_stats_controller/query_imported_test.exs
Ref: https://3.basecamp.com/5308029/buckets/39750953/card_tables/cards/8052057081
JOINs in ClickHouse are slow. In one degenerate case I found a user had over 20 million unique paths in an import, which resulted in extremely slow JOINs. This introduces a sort-of hacky solution to it by limiting the amount of data analyzed.
Query timing without this change:
```
9 rows in set. Elapsed: 11.383 sec. Processed 49.16 million rows, 5.75 GB (4.32 million rows/s., 505.29 MB/s.)
Peak memory usage: 14.75 GiB.
```
After:
```
9 rows in set. Elapsed: 0.572 sec. Processed 49.18 million rows, 5.75 GB (86.03 million rows/s., 10.06 GB/s.)
Peak memory usage: 9.01 GiB.
```
> Improve report performance with high-cardinality import joins

- lib/plausible/data_migration/missing_scroll_depth.ex
- lib/plausible/ingestion/request.ex
- lib/plausible/stats/query_runner.ex
- lib/plausible/stats/sql/special_metrics.ex
- test/plausible_web/controllers/api/external_controller_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
- test/plausible_web/controllers/api/stats_controller/pages_test.exs
* Start ingesting missing scroll depth values as 255 (max `UInt8`) rather than 0 for pageleave events
* Display "-" instead of 0 when no scroll depth data in range
* Add a data migration setting scroll depth of pageleaves to 255 if it's 0
Reasoning:
A scroll depth of 0 currently represents a missing value, but it can also be a valid scroll depth in case of extremely short viewports and long documents. Also, 0's are currently counted towards average which we don't want to do in case of missing values
> Average Scroll Depth Metric: handle missing data better

- lib/plausible/billing/enterprise_plan_admin.ex
- lib/plausible/site/admin.ex
- lib/plausible_web/controllers/admin_controller.ex
This is a quick fix for CRM search which got broken after full switch to team schemas. Searching by member/owner emails is temporarily disabled in Sites and Enterprise Plan CRMs and a temporary list of owned sites is exposed in user CRM.
> Disable searching by member/owner emails in sites and enterprise plan CRMs (temporary)

- lib/plausible/billing/enterprise_plan_admin.ex
- lib/plausible/crm_extensions.ex
- lib/plausible/site/admin.ex
Addresses a regression in CRM capabilities after switching to teams schema exclusively.
> Bring back search by member email and name in Sites/Plans CRM

- priv/ingest_repo/migrations/20241216133031_add_scroll_depth_to_imported_pages.exs
This PR only contains the migration adding the `scroll_depth UInt8` column to the `imported_pages` ClickHouse table.
The column will have a default value of 255 which hints that the value is non-existent (a valid scroll depth has to be from 0 to 100). The alternatives default values are:
* 0 - cannot use because it can be a valid value in rare cases
* NULL - bad performance in ClickHouse
When querying scroll depth from imported data, we'll simply filter out rows where `scroll_depth` is more than 100.
> Migration: Add scroll_depth to imported_pages

- lib/plausible/billing/enterprise_plan.ex
- lib/plausible/crm_extensions.ex
- lib/plausible_web/controllers/admin_controller.ex
- lib/plausible_web/router.ex
Another functional regression in CRM addressed - user lookup mechanism + fix to plan prefill.
> Reimplement user search in enterprise plans CRM and fix plan prefill

- lib/plausible/site/memberships/create_invitation.ex
This -- together with `Membership.t()` -- fails CI for some of my PRs: https://github.com/plausible/analytics/actions/runs/12373633123/job/34534378559
I'll open a separate PR for `Membership.t()`
> Remove old `Plausible.Auth.Invitation` references

- lib/plausible_web/templates/layout/settings.html.heex
This PR hides "Subscription" and "Invoices" sections from "User Settings" page.
Context: https://github.com/plausible/community-edition/issues/181#issuecomment-2532104651
> Hide billings and upgrade from CE

- config/runtime.exs
- lib/plausible/application.ex
This PR reverts the Sentry part of https://github.com/plausible/analytics/pull/4862 since in 10.2.0 the logger handler implementation is incomplete: https://github.com/plausible/analytics/pull/4914
> Revert to `Sentry.LoggerBackend`

- Makefile
- priv/repo/seeds.exs
Improves the script that generates seeds. The improvements compared to `master` are:
* Imported and native visitor numbers are roughly similar now (~10x difference on master)
* No empty page in "Top Pages"
* Events are generated as part of a session with a stable user id and steadily increasing timestamp
* Visit duration looks more realistic
* Views per visit looks more realistic
* Time on page looks more realistic
* Configures the `logged_in` prop during seeds so you don't have to do it manually
* Adds some `utm_medium`s so that channels report is more interesting
* Potentially some more stuff that doesn't cross my mind at the moment
> Improve seeds

- lib/workers/check_usage.ex
- test/workers/check_usage_test.exs
This fixes a bug, for when the customer having two enterprise plans, triggers a wrongful CRM notification about limits exceeded. Previously, we'd have joined a single enterprise plan instance, but at random (with undefined order). Currently the join is guaranteed to be done on latest subscription's `paddle_plan_id`, providing the latest enterprise plan quotas to check against.
> Only check usage for EPs by _current_ subscription

- Dockerfile
- assets/js/dashboard/query-dates.test.tsx
* Hotfix for resolving a mismatch between NPM and Node JS versions in `build-private-images.yml`.
* Fix a FE test that started failing due to year change from 2024 to 2025.
> Fix docker build + FE test

- lib/plausible/mailer.ex
This PR improves Plausible.Mailer error messages in CE.
Requested in https://github.com/plausible/analytics/discussions/4844#discussioncomment-11321492
> Log Mailer errors

- priv/ingest_repo/migrations/20241231083407_add_pageleave_visitors_to_imported_pages.exs
When merging imported data into stats queries, we cannot simply divide `scroll_depth` / `visitors` to get the imported scroll depth. That’s wrong because `visitors` is based on pageviews, not pageleaves. Therefore, we’ll need to export an additional metric - `pageleave_visitors` which we can use specifically for that calculation.
Note: This field should also be used for our new time on page in the future
> Average Scroll Depth Metric: another imported schema migration

- CHANGELOG.md
- lib/plausible/stats/comparisons.ex
- test/plausible/stats/comparisons_test.exs
When comparing dates year-over-year, the previous logic always shifted by 365 days, which caused issues with leap years.
This means when comparing e.g. last 7 days vs a year ago in 2025, you would compare Jan 6th and Jan 7th.
The new logic uses `Date.shift` while ensuring that the compared date range stays the same length as original date range. This can cause some oddities around Feb 29th where dates can get offset by 1 at the end of the range (see tests)
Helpscout ref: https://secure.helpscout.net/conversation/2809180400/22224?viewId=6980900
> Fix year-over-year comparisons for leap years

- priv/ingest_repo/migrations/20241120064325_create_ingest_counters_site_traffic_projection.exs
Companion to https://github.com/plausible/analytics/pull/4839
A projection speeds up ClickHouse queries by storing data in a different order in each part. In this case, it pre-aggregates results by site, speeding up the query and requiring less resources at query-time.
Query stats before:
```
-- 10 rows in set. Elapsed: 1.134 sec. Processed 1.45 billion rows, 21.65 GB (1.28 billion rows/s., 19.09 GB/s.)
-- Peak memory usage: 53.41 MiB.
```
After:
```
-- 10 rows in set. Elapsed: 0.321 sec. Processed 39.70 million rows, 1.07 GB (123.51 million rows/s., 3.33 GB/s.)
-- Peak memory usage: 97.43 MiB.
```
> Speed up counting past 30 day traffic via ingest_counters

- extra/lib/plausible/stats/goal/revenue.ex
- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/json_schema.ex
- lib/plausible/stats/legacy/legacy_query_builder.ex
- lib/plausible/stats/query.ex
- lib/plausible/stats/query_result.ex
- priv/json-schemas/query-api-schema.json
- test/plausible/stats/query_parser_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
- test/plausible_web/controllers/api/stats_controller/conversions_test.exs
- test/plausible_web/controllers/api/stats_controller/custom_prop_breakdown_test.exs
- test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
This PR exposes revenue metrics in APIv2 (only on ee).
There are a few scenarios where revenue metrics can't be calculated. On the dashboard we automagically remove these metrics but this isn't a great fit for APIv2. Instead, we return nulls and produce warnings under `response.meta`. This is similar to imports where we still return results for the rest of the query. 
Ref: https://3.basecamp.com/5308029/buckets/39750953/card_tables/cards/8070760266
Docs PR: https://github.com/plausible/docs/pull/571. Will wait for a :+1: from Looker integration before merging.
> Revenue metrics in APIv2

- lib/plausible/teams.ex
- lib/plausible/teams/team.ex
- lib/plausible_web/controllers/settings_controller.ex
- lib/plausible_web/live/components/form.ex
- lib/plausible_web/router.ex
- lib/plausible_web/templates/layout/settings.html.heex
- lib/plausible_web/templates/layout/site_settings.html.heex
- lib/plausible_web/templates/settings/team_general.html.heex
- lib/plausible_web/views/layout_view.ex
- test/plausible_web/controllers/settings_controller_test.exs
- test/test_helper.exs
This PR adds basic "change team name" ability within new Team Settings sidebar section. This is feature-flagged and will serve as a base for upcoming Teams UI changes.
https://github.com/user-attachments/assets/a7c972a9-678f-4449-ab93-13d516431a5d
> Spike Team Settings section

- lib/plausible/teams/team.ex
- test/support/factory.ex
Once https://github.com/plausible/analytics/pull/4943 is merged
> Teams setup schema

- lib/plausible_web/controllers/api/stats_controller.ex
Fixes a bug that surfaced in Sentry after I deployed #4915 today.
A page filter + include_imported query should not include time on page and bounce rate in Top Stats. The condition got messed up with the addition of scroll depth.
This only concerns the case where scroll depth flag is off. I did not bother covering this with a test since the test setup has the flag enabled globally. This was just a typo.
> Fix Top Stats crashing with imported data + page filter

- .github/workflows/build-private-images-ghcr.yml
- Dockerfile
Proposed follow-up to https://github.com/plausible/analytics/pull/4933
Alpine index only exposes a single version of nodejs, which this PR now explicitly pins against. See also: https://pkgs.alpinelinux.org/packages?name=nodejs-current&branch=v3.20&repo=&arch=x86_64&origin=&flagged=&maintainer=
> [WIP] Pin nodejs version to be the same as .tool-versions

- assets/js/dashboard/stats/modals/breakdown-modal.tsx
- assets/js/dashboard/stats/reports/list.js
- assets/js/dashboard/stats/reports/metric-value.tsx
Locally I ran into a FE race condition bug on loading breakdown modal data due to how items and `response.meta` was handled. This fixes that by handling meta not being loaded yet gracefully.
> Fix race condition loading breakdown modals

- lib/plausible/teams/invitation.ex
- lib/plausible/teams/invitations.ex
- lib/plausible/teams/invitations/invite_to_team.ex
- lib/plausible/teams/membership.ex
- lib/plausible_web/email.ex
- lib/plausible_web/live/register_form.ex
- lib/plausible_web/templates/email/existing_user_team_invitation.html.heex
- lib/plausible_web/templates/email/new_user_team_invitation.html.heex
- test/plausible/teams/invitations/invite_to_team_test.exs
- test/plausible_web/live/register_form_test.exs
- test/support/teams/test.ex
This service implements a service for inviting new members on a team.
- if there's an existing team invite for a given email, it's overwritten
- if overwritten invite is a guest invite, its guest invitation entries (site-bound) are pruned
- only an owner can invite another owner
- inviting members on a team is only possible for admins and up
- registering from invitation link now supports team invitation id as well
> Implement service for inviting to a team

- CHANGELOG.md
- lib/plausible/stats/comparisons.ex
- test/plausible_web/controllers/api/external_stats_controller/query_comparisons_test.exs
https://github.com/plausible/analytics/pull/4697 introduced some comparisons fixes which changed how comparisons interacted with main queries. Sadly this broke under pagination and due to lack of coverage wasn't caught.
The bug can also be tested manually on localhost:
- Change assets/js/dashboard/hooks/api-client.ts LIMIT to e.g. 3
- Open any modal, click load more
- Check tooltips
Before the fix this would have displayed 0 values, after the fix this works as expected.
> Fix breakdown comparisons breaking after pagination

- lib/plausible_web/templates/layout/base_error.html.heex
For [storybook integration](https://github.com/plausible/analytics/pull/4947) we had to scope all of our styling to the `.plausible` parent class. This class should have been added to all layouts but I missed the `base_error.html.heex` layout.
> Fix error layout

- lib/plausible/ingestion/event.ex
- lib/plausible/ingestion/source.ex
- test/plausible_web/controllers/api/external_controller_test.exs
Internal referrals were not historically stored by design. I changed that inadvertently with the channels work. This PR makes sure this behaviour is tested and fixes it along the way.
Unfortunately we collected some bad data over the last 2 months. Probably need a data migration to fix it.
> Stop storing internal referrer

- lib/plausible_web/plugs/authorize_site_access.ex
- test/plausible_web/plugs/authorize_site_access_test.exs
Stops internal server errors stemming from binary but non-string input reaching postgres queries.
> Handle non-string binary input before postgres

- lib/plausible_web/live/components/combo_box.ex
- test/plausible_web/live/components/combo_box_test.exs
Combobox spinner sometimes stays spinning, which will be confusing to users. It's not a critical part of the app that it spins in the first place, so this PR disables it until a fix can be made.
> Temporarily disable combobox spinner

- test/plausible_web/controllers/api/external_controller_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
- tracker/.eslintrc.json
- tracker/src/customEvents.js
- tracker/src/plausible.js
- tracker/test/custom-event-edge-cases.spec.js
- tracker/test/file-downloads.spec.js
- tracker/test/fixtures/pageleave-hash-pageview-props.html
- tracker/test/fixtures/pageleave-manual.html
- tracker/test/fixtures/pageleave-pageview-props.html
- tracker/test/manual.spec.js
- tracker/test/outbound-links.spec.js
- tracker/test/pageleave.spec.js
- tracker/test/revenue.spec.js
- tracker/test/scroll-depth.spec.js
- tracker/test/support/test-utils.js
- tracker/test/tagged-events.spec.js
_NOTE: Reviewing this PR commit by commit is highly recommended._
The main intent of this PR is to make scroll depth data available also in queries where a custom property dimension is used. That means that we'll start tracking custom props on pageleaves as well. The implementation is fairly straight forward - simply keep track of the props that were sent with the pageview and send them along with the pageleave as well.
In addition, this PR:
* Fixes an important bug with tracking pageleaves on ignored pages (a test asserting the broken behaviour was accidentally passing due to pageleaves being throttled)
* Refactors the `currentPageleaveURL` logic - I overcomplicated things in the beginning. 
* Refactors the tracker test suite quite a bit
> Average Scroll Depth Metric: Track custom props on pageleaves

- CHANGELOG.md
[v2.1.5-rc.1](https://github.com/plausible/analytics/discussions/4986) was released from a cherry-picked branch https://github.com/plausible/analytics/pull/4884 so it needs to be "backported" into the changelog.
> Include v2.1.5-rc.1 cherry-picked release in the changelog

- lib/plausible_web/email.ex
- test/plausible_web/email_test.exs
This PR stops CE from settings MessageStream=priority in emails.
The issue was reported here: https://github.com/plausible/analytics/discussions/4986#discussioncomment-11883709
> Remove "priority" Postmark message stream from CE

- .github/workflows/build-public-images-ghcr.yml
Based on: https://github.com/gartnera/actions-arm64-native-example
News: https://news.ycombinator.com/item?id=42728015
**tl;dr** cross-platform CE images now get built in [seven](https://github.com/plausible/analytics/actions/runs/12867985546) minutes instead of [thirty three](https://github.com/plausible/analytics/actions/runs/12810709605) :)
> Use ARM runners to build public images for ARM

- assets/tailwind.config.js
Not sure how important it is 🥁 - introduced via https://github.com/plausible/analytics/pull/4947 - but it fixes jumpy external links on hover.
@ukutaht advise please
> Remove tailwind important config

- lib/plausible/data_migration/backfill_teams.ex
- priv/repo/migrations/20250117122435_backfill_teams.exs
Context: #4925
I'm going to leave some comments inline.
> Backfill teams CE in a single transaction

- CHANGELOG.md
- assets/js/types/query-api.d.ts
- extra/lib/plausible/stats/goal/revenue.ex
- lib/plausible/goals/filters.ex
- lib/plausible/stats/base.ex
- lib/plausible/stats/clickhouse.ex
- lib/plausible/stats/filters/filters.ex
- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/imported/base.ex
- lib/plausible/stats/imported/imported.ex
- lib/plausible/stats/legacy/legacy_query_builder.ex
- lib/plausible/stats/query.ex
- lib/plausible/stats/query_runner.ex
- lib/plausible/stats/sql/query_builder.ex
- lib/plausible/stats/sql/special_metrics.ex
- lib/plausible/stats/sql/where_builder.ex
- lib/plausible/stats/time.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- lib/plausible_web/controllers/stats_controller.ex
- priv/json-schemas/query-api-schema.json
- test/plausible/stats/query_parser_test.exs
- test/plausible/stats/query_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_imported_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
This PR adds support for behavioral filtering by adding two new operators `has_done` and `has_not_done` to APIv2.
These operators can be used to filter whether users have completed (or not completed) a given at any point in their session. This can be used to exclude goals or check whether a user has done an additional action in their session.
In the following example, we could pageviews and visitors on /pricing page, but only by users who _have_ opened support chat but have not registered or logged in either before or after visiting the page.
```json
{
"site_id": "dummy.site",
"metrics": ["visitors", "pageviews"],
"date_range": "7d",
"filters": [
["is", "event:page", ["/pricing"]],
["has_done", ["is", "event:goal", ["Open Support Chat"]]],
["has_not_done", ["is", "event:goal", …
```
> APIv2: Behavioral filtering

- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/query.ex
- lib/plausible/stats/query_optimizer.ex
- test/plausible/stats/table_decider_test.exs
In a previous PR, using both `dimension` and `filter_key` to refer to filter dimension caused confusion. This PR refactors the code to only refer to dimension or filter_dimension.
Depends on https://github.com/plausible/analytics/pull/4980
> Refactor: Remove `filter_key` terminology from backend

- .codespellignore
- tracker/src/plausible.js
- tracker/test/file-downloads.spec.js
- tracker/test/fixtures/manual.html
- tracker/test/fixtures/pageleave-pageview-props.html
- tracker/test/fixtures/pageleave.html
- tracker/test/pageleave.spec.js
- tracker/test/support/test-utils.js
Currently, pageleave listener is only registered when a successful response is received from plausible API.
After this change pageleave listener is registered immediately when pageview is triggered, hopefully increasing capture rate.
TODO after deploy:
> Scroll depth: Register `pageleave` listener earlier

- lib/plausible/billing/billing.ex
- test/plausible/billing/billing_test.exs
- test/plausible_web/controllers/api/paddle_controller_test.exs
- test/plausible_web/live/sites_test.exs
Follow-up to #4938 
On hold for now
> Remove support for legacy Paddle webhook passthrough formats

- lib/plausible/billing/billing.ex
- test/plausible/billing/billing_test.exs
- test/plausible_web/controllers/api/paddle_controller_test.exs
- test/plausible_web/live/sites_test.exs
Removal of legacy passthrough support in #4939 was too aggressive and removed support for a still legit case of user without a team. We will eventually drop it in order to facilitate multi-team membership but this requires a different approach.
> Fix passthrough processing billing callback

- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/table_decider.ex
- test/plausible/stats/query_parser_test.exs
- test/plausible/stats/table_decider_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_validations_test.exs
Currently the following query results in a 500:
```json
{
"site_id": "plausible.io",
"metrics": ["visitors", "events", "pageviews"],
"dimensions": ["visit:exit_page"],
"date_range": "7d"
}
```
This adds proper validation for that case that was previously missing.
In the future we might be able to remove _some_ of these validations by selecting the appropriate value(s) from sessions table.
Basecamp ref: https://3.basecamp.com/5308029/buckets/39750953/card_tables/cards/8251923578
> APIv2: validate combining event-only metrics with session-only dimensions

- assets/js/dashboard/stats/behaviours/goal-conversions.js
- lib/plausible/imported.ex
- lib/plausible/props.ex
- test/plausible/props_test.exs
- test/plausible_web/controllers/api/stats_controller/custom_prop_breakdown_test.exs
https://3.basecamp.com/5308029/buckets/32037438/card_tables/cards/6013863433#__recording_8250028578
Adds a new special goal (`WP Form Completion`) with a special property (`path`). This will behave exactly the same as the `404` goal (that has the `path` property too):
* It will be included in the full Plausible CSV export (`imported_custom_events.csv`) with the `path` prop
* it will be included from imported data in stats queries if it exists (from imports where it doesn't, e.g. GA4, we will silently not return any data for this goal)
* In the dashboard, clicking on the goal in the goals breakdown, the "special goal contents" will pop up in the conversions tab:
> Add a special goal: "WP Form Completions"

- tracker/src/plausible.js
- tracker/test/fixtures/pageleave-hash-exclusions.html
- tracker/test/fixtures/pageleave-hash-pageview-props.html
- tracker/test/fixtures/pageleave-hash.html
- tracker/test/fixtures/pageleave-manual.html
- tracker/test/fixtures/pageleave-pageview-props.html
- tracker/test/fixtures/pageleave.html
- tracker/test/fixtures/scroll-depth-content-onscroll.html
- tracker/test/fixtures/scroll-depth-dynamic-content-load.html
- tracker/test/fixtures/scroll-depth-hash.html
- tracker/test/fixtures/scroll-depth-slow-window-load.html
- tracker/test/fixtures/scroll-depth.html
:facepalm: I didn't realize pageleaves had their own tracking code. After this change fetch with keepalive is used instead of beacon.
> Tracker: Use fetch with keepalive over beacon for pageleaves

- lib/plausible/imported.ex
- lib/plausible/site.ex
- lib/plausible/sites.ex
- lib/plausible/stats/aggregate.ex
- lib/plausible/stats/breakdown.ex
- lib/plausible/stats/comparisons.ex
- lib/plausible/stats/email_report.ex
- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/goal_suggestions.ex
- lib/plausible/stats/imported/base.ex
- lib/plausible/stats/legacy/legacy_query_builder.ex
- lib/plausible/stats/query.ex
- lib/plausible/stats/query_result.ex
- lib/plausible/stats/query_runner.ex
- lib/plausible_web/controllers/api/external_stats_controller.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- lib/plausible_web/live/goal_settings.ex
- lib/plausible_web/plugs/authorize_public_api.ex
- lib/plausible_web/plugs/authorize_site_access.ex
- test/plausible/imported_test.exs
- test/plausible/stats/query_parser_test.exs
- test/plausible/stats/query_result_test.exs
- test/plausible/stats/query_test.exs
- test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
- test/plausible_web/controllers/site_controller_test.exs
This PR prepares the codebase with a refactor in order to make `SiteImport` structs available in stats queries. The plan is to use `SiteImport`s to decide whether or not `scroll_depth` gets included from imported data or not. This information will be included in `meta.metric_warnings`.
This PR also aims to move the logic of responding with imported flags (such as `imports_included` and `skip_imported_reason`) into a single place - `QueryResult`. The values for these fields depend on both `query` and `comparison_query` which this PR makes available in `QueryResult`.
> Refactor including imports in stats queries

- assets/js/dashboard/util/filter-text.test.tsx
- assets/js/dashboard/util/filter-text.tsx
- lib/plausible/stats/legacy/legacy_query_builder.ex
- test/plausible/stats/table_decider_test.exs
- test/plausible_web/controllers/api/stats_controller/countries_test.exs
* Adds resolve segments logic in Query.from
* Changes filter-text utility arg type to handle the labels stored within segment.segment_data
> Expand segments also when using Query.from

- CHANGELOG.md
- lib/plausible_web/controllers/api/stats_controller.ex
- test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
In the current dashboard, "Unique users" denotes the number of users who match the filter _except_ in one case: When filtering by a goal. In that case this number means number of users without the goal filter.
This caused confusion in another review and I find this confusing. I confirmed this with @metmarkosaric that this might be a historical quirk that's safe to remove.
This can cause extra confusion since "excluding" goals would not behave the same.
Sending this to @ukutaht since he has historical context. I'm not confident in this change and the goal is to spark a discussion.
Before:
After:
> Proposal: Remove `unique users` from dashboard when filtering by goal

- lib/plausible/ingestion/request.ex
- lib/plausible/session/cache_store.ex
- test/plausible_web/controllers/api/external_controller_test.exs
- tracker/src/plausible.js
- tracker/test/pageleave.spec.js
- tracker/test/scroll-depth.spec.js
- tracker/test/support/test-utils.js
Consider this an experiement to see whether engagement events would do the trick. 
`visibilitychange` nicely fires when the page is loaded, user closes or switches the tab or when they navigate away from the page.
To avoid sending redundant events we:
1. Don't send engagement events when pageview was ignored and on initial page load 
2. When user has not scrolled in-between tab-in-and-tab-out (initial engagement event is always sent)
For the future:
1. If we find this doesn't help us, I'll revert the PR and delete the redundant events
2. If we find this _does_ help us:
1. I'll update the rest of the backend codebase to work off of engagement events 
2. migrate historical data on cloud
3. figure out whether we need a workaround for old Safari implementation issues: …
> Tracker: Send `engagement` events on visibilitychange (if pageleave extension)

- lib/plausible/billing/qouta/quota.ex
- lib/plausible/teams/billing.ex
- lib/plausible/teams/invitations.ex
- test/plausible/billing/quota_test.exs
- test/plausible_web/controllers/site_controller_test.exs
This PR fixes an old bug, where users on grandfathered plans would be unable to accept site transfer ownership above their subscription's site limit.
The changes rely on teams migration rewriting owner's `inserted_at` onto the `Team` schema.
> Allow over-limit site ownership transfer for users having grandfathered plans

- priv/repo/migrations/20250122100320_add_autocreated_to_team_memberships.exs
This is a pre-requisite for enabling support for multiple owners per team.
> Create migration adding `is_autocreated` to `team_memberships`

- priv/repo/migrations/20250129120520_change_team_memberships_is_autocreated_default_to_true.exs
A follow-up to #5002. Intially, `is_autocreated` default must be `true` becuase otherwise there's a non-zero chance of an owner team membership getting added  with it set to false in between #5002 and #5003 which might eventually result in user becoming owner on two teams - we don't want to risk it. Eventually this default will be set back to `false` after logic switch in #5003 (it will have to be altered accordingly).
> Change `team_memberships.is_autocreated` default to `true`

- lib/plausible/teams.ex
- lib/plausible/teams/billing.ex
- lib/plausible/teams/grace_period.ex
- lib/plausible/teams/membership.ex
- lib/plausible/teams/team.ex
- lib/plausible_web/templates/layout/_notice.html.heex
- test/plausible/billing/billing_test.exs
- test/plausible/billing/site_locker_test.exs
- test/plausible/teams/grace_period_test.exs
- test/workers/check_usage_test.exs
This PR switches upsert used for creating team membership in `Teams.get_or_create/1`  to the newly introduced constraint which opens up the capability of user being a member in more than one team. The final step to follow will be removal of the `one_team_per_user` constraint. Only after this it will be possible to implement and test the rest of the logic relying on that constraint being loosened.
The change in question is done in https://github.com/plausible/analytics/pull/5003/commits/2910de304da7d91b625fd8d036ebec02d5b19a94 while https://github.com/plausible/analytics/pull/5003/commits/a1e97b59879f63f15f6c7f66ea7f7de72698fc4c is purely a refactor moving `Auth.GracePeriod` under `Teams.GracePeriod` and correcting phrasing of the docs strings which were out of date.
Depends on #5002
> Rework team creation constraints

- priv/repo/migrations/20250129132629_drop_old_one_team_per_user_constraint.exs
Dropping that constraint opens capability to support meany team meberships per user and many owner user per team.
This migration also sets `team_memberships.is_autocreated` value back to `false` for consistency.
Depends on #5003
> Drop `one_team_per_user` constraint from `team_memberships`

- lib/plausible_web/live/components/modal.ex
- lib/plausible_web/live/goal_settings.ex
- test/plausible_web/live/goal_settings_test.exs
This PR fixes an issue where, on a fresh view load, when trying to open edit dialog for an existing goal, the form is not loaded properly. The preloading optimisation (meant load modal contents in the background in a  state defined on page load - in this case, an empty form) breaks it, as first open does not force contents to be reloaded when they should. The modal preopen routine can probably be improved to account for this case with a switch of sorts but currently this is the simplest solution for that particular case.
All the other current uses of the modal component do not have "edit" state currently (Funnel settings still rely on a custom-made solution).
> Don't preload goal settings modal to avoid issues with opening in edit mode

- .formatter.exs
- test/plausible/stats/time_test.exs
- test/plausible_web/controllers/api/internal_controller/segments_controller_test.exs
- test/support/assert_matches.ex
- test/support/conn_case.ex
- test/support/data_case.ex
This is a proposal for implementing a more expressive match assertion mechanism. It was prompted by the original idea by @macobo in #5019.
The idea here is that the pin (^) operator does not only rebind existing binding in the scope but also allows embedding basically any other expression to match against the given part of the pattern. Normal pattern matching is also supported and both can be mixed. The only caveat so far is that when normal patterns fail, only they are listed in the error even if there are potentially failing expressions. However, once the normal pattern is fixed, they surface.
Currently, the following expressions can be pinned:
* `any(:atom)`
* `any(:string)`
* `any(:binary)`
* `any(:integer)`
* `any(:float)`
* `any(:boolean)`
* `any(:map)`
* `any(:list)`
* all above …
> Implement `assert_matches` with expanded expressions support in match assertions

- CHANGELOG.md
- lib/plausible_web/templates/layout/_tracking.html.heex
- tracker/src/plausible.js
- tracker/test/fixtures/pageleave-hash-exclusions.html
- tracker/test/fixtures/pageleave-hash-pageview-props.html
- tracker/test/fixtures/pageleave-hash.html
- tracker/test/fixtures/pageleave-manual.html
- tracker/test/fixtures/pageleave-pageview-props.html
- tracker/test/fixtures/pageleave.html
- tracker/test/fixtures/scroll-depth-content-onscroll.html
- tracker/test/fixtures/scroll-depth-dynamic-content-load.html
- tracker/test/fixtures/scroll-depth-hash.html
- tracker/test/fixtures/scroll-depth-slow-window-load.html
- tracker/test/fixtures/scroll-depth.html
`fetch` allows us to use the keepalive flag, which more reliably delivers data to us. It's also required for reliable scroll depth capturing down the line.
The only major browser not to support fetch is Internet Explorer. Clients who care about IE traffic can use the `.compat` variant of our script (documented in
https://plausible.io/docs/script-extensions#scriptcompatjs). As of this commit, IE makes up less than ~0.003% of incoming traffic to plausible.
@ukutaht should we make an announcement on the product side or is the changelog sufficient?
> Use `fetch` over `XMLHttpRequest` in plausible.js

- lib/plausible/application.ex
- lib/plausible/exports.ex
- lib/plausible/ingestion/event.ex
- lib/plausible/ingestion/scroll_depth_visible_at.ex
- lib/plausible/site/cache.ex
- lib/plausible/stats/scroll_depth.ex
- lib/plausible_web/controllers/stats_controller.ex
- test/plausible/imported/csv_importer_test.exs
- test/plausible/ingestion/scroll_depth_visible_at_test.exs
- test/plausible_web/controllers/api/external_controller_test.exs
- test/plausible_web/controllers/stats_controller_test.exs
We decide what metrics to show dynamically based on whether site has sent us scroll depth data.
Previously, this data was queried dynamically from ClickHouse on page loads, but this approach adds 50-200ms to _every_ page load until a site has sent us scroll depth data.
Instead, we now update `site.scroll_depth_visible_at` in ingestion. To limit impact on ingestion:
1. `scroll_depth_visible_at` is now cached along with other ingestion site data.
2. updates are processed using ets, making sure only one database update is ever done per site
3. handles errors gracefully if postgres is ever in e.g. read-only mode or otherwise unavailable.
I'm curious whether I'm taking a sane approach with the GenServer here. cc @zoldar for feedback on that front.
> Scroll depth: update `site.scroll_depth_visible_at` in ingestion

- lib/plausible/segments/segments.ex
When investigating some traces, we found that there's more database queries happening than needed. This removes one of them, which was running on all stats requests.
> Stop segment queries when not needed

- tracker/test/pageleave.spec.js
- tracker/test/scroll-depth.spec.js
No more beacon means no more reason to skip any tests.
> Tracker: Run tests on safari

- tracker/src/plausible.js
I previously ran into an issue where the deferred plausible script ran into an error while loading, due to `document.body` being unavailable. This in turn results in no events being tracked for that page load.
I was _not_ able to reproduce the issue today despite 2 hours of trying, but here's a quick patch for the underlying issue making method access just a bit safer.
> Tracker: Handle `document.body` not being available gracefully

- lib/plausible/exports.ex
- lib/plausible/goal/schema.ex
- lib/plausible/stats/clickhouse.ex
- lib/plausible/stats/goal_suggestions.ex
- lib/plausible/stats/goals.ex
- lib/plausible/stats/legacy/time_on_page.ex
- lib/plausible/stats/scroll_depth.ex
- lib/plausible/stats/sql/expression.ex
- lib/plausible/stats/sql/special_metrics.ex
- test/plausible/billing/quota_test.exs
- test/plausible/goals_test.exs
- test/plausible/imported/csv_importer_test.exs
- test/plausible/stats/goal_suggestions_test.exs
- test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
- test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_goal_dimension_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_imported_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
- test/plausible_web/controllers/api/stats_controller/conversions_test.exs
- test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
- test/plausible_web/controllers/api/stats_controller/pages_test.exs
- test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
- test/plausible_web/controllers/stats_controller_test.exs
- test/support/factory.ex
Note that export pageleave_visitors column has not been updated here.
> Update queries to work off of `engagement` events over pageleaves

- assets/js/dashboard/components/sort-button.tsx
- assets/js/dashboard/components/table.tsx
- assets/js/dashboard/query.ts
- assets/js/dashboard/stats/graph/top-stats.js
- assets/js/dashboard/stats/modals/breakdown-modal.tsx
- lib/plausible/data_migration/site_imports.ex
- lib/plausible/imported.ex
- lib/plausible/imported/csv_importer.ex
- lib/plausible/imported/site_import.ex
- lib/plausible/stats/query_result.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- priv/repo/migrations/20250203183445_add_has_scroll_depth_to_site_import.exs
- test/plausible/data_migration/site_imports_test.exs
- test/plausible/imported/csv_importer_test.exs
- test/plausible/imported_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_imported_test.exs
- test/plausible_web/controllers/api/stats_controller/pages_test.exs
- test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
Return a `scroll_depth` warning under `meta.metric_warnings` in the API response if imported data was included in the response, but no scroll depth data was found.
In the dashboard, we'll display warnings in two places (where the scroll depth metric is surfaced) - Top Stats and Top Pages > Details.
Screen recordings of how the dashboard tooltips work can be found at: https://3.basecamp.com/5308029/buckets/39034214/card_tables/cards/8130992150
This PR also changes `Plausible.DataMigration.SiteImports` to stop relying on the up-to-date SiteImport schema, defining an inline snapshot of the schema instead. Also does the same thing with the `imported_*` CH tables - defining a fixed list of imported tables that existed at that time.
> Scroll depth dashboard warnings (imported data)

- CHANGELOG.md
- lib/plausible_web/controllers/api/external_controller.ex
- lib/plausible_web/controllers/api/system_controller.ex
- lib/plausible_web/router.ex
Adds two new endpoints:
1. `/api/system/health/live` does nothing more than return 200 OK with a JSON body `{"ok": "true"}`
2. `/api/system/health/ready` checks all the necessary dependencies for accepting traffic (identical to old `/api/health` behaviour):
2.1 Postgres reachable
2.2 Clickhouse reachable
2.3 Ingestion caches ready
The old `/api/health` endpoint is still usable to give time to migrate external checks.
Technically ingestion can keep working as long as caches are loaded but postgres is unreachable. Future possibility is separating ingestion readiness check from app readiness.
> Separate liveness and readiness checks

- CHANGELOG.md
- lib/plausible/clickhouse_event_v2.ex
- lib/plausible/session/cache_store.ex
- test/plausible_web/controllers/api/external_controller_test.exs
Consider the following scenario:
1. We receive a pageview from a user A
2. Salts are rotated after day end
3. We receive another pageview
Previously, this would result in:
- 2 sessions with different user_ids
- 2 events where each would have different user_ids
This fixes the problem by removing the previous faulty session updating
and forcing the event.user_id to be updated after we found a session
with the previous salt.
> Fix mismatch between session and event user_ids after salts are rotated

- lib/plausible/application.ex
Minor addition to #5048 
This increases the odds of getting to "ingest-ready" state a bit quicker.
> Reorder application supervision tree

- lib/plausible/application.ex
As per [con_cache docs](https://hexdocs.pm/con_cache/ConCache.html#start_link/1-choosing-ttl_check_interval-time):
> Thus, a lower value of ttl_check_interval time means more frequent purging which may reduce your memory consumption, but could also cause performance penalties. Higher values put less pressure on processing, but item expiry is less precise.
The intention of this PR is to shift cache resource usage towards using more memory and putting less pressure on processing. The item expiry precision for these tables is not crucial in any way. If a session lingers in cache longer than 30 minutes it will still be [ignored](https://github.com/plausible/analytics/blob/a7ff6faf0098cc4593d8f313732e8f031c12b478/lib/plausible/session/cache_store.ex#L66).
For user agents I think the ideal …
> Increase sessions and user agents cache ttl check interval

- lib/plausible/goals/goals.ex
- lib/plausible/segments/segments.ex
- test/plausible/goals_test.exs
When a goal's display name is updated, this PR makes it so the segments containing that goal are also updated accordingly
> Update goal in segment

- lib/plausible/ingestion/event.ex
- lib/plausible/session/cache_store.ex
- test/plausible/session/cache_store_test.exs
This will drop less events when session was actually active but didn't have any pageviews/custom events arrive.
Ref: https://3.basecamp.com/5308029/buckets/39034214/card_tables/cards/8314968048
> Scroll depth: Engagement events should refresh in-memory session cache

- lib/plausible/session/salts.ex
- test/plausible/session/salts_test.exs
A tiny patch to bypass synchronous gen server calls when looking up salts. Updates are still serialized.
> Speed up salts lookup by serving them off ets

- lib/plausible/exports.ex
- lib/plausible/imported/csv_importer.ex
- lib/plausible/imported/page.ex
- lib/plausible/stats/imported/sql/expression.ex
- lib/plausible/stats/sql/special_metrics.ex
- priv/ingest_repo/migrations/20250212100953_imported_pages_new_scroll_depth_columns.exs
- test/plausible/imported/csv_importer_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_imported_test.exs
- test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
- test/plausible_web/controllers/api/stats_controller/pages_test.exs
- test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
Pre-requisite to https://github.com/plausible/analytics/pull/5072, see that PR for deployment plan.
The new columns are:
- `total_scroll_depth UInt64`
- `total_scroll_depth_visits UInt64`
This should hopefully make it clear in queries that these columns are used as numerator and denominator.
This PR changes code and migrations at the same time. Generally this can cause issues, but the code modifications just remove the ability to _read_ the columns that were changed. As such, this is okay to merge (will do so via admin priviledges).
> Scroll depth: Rename imported_pages columns to reflect whats desired

- lib/plausible/imported.ex
- lib/plausible/stats/breakdown.ex
- lib/plausible/stats/comparisons.ex
- lib/plausible/stats/email_report.ex
- lib/plausible/stats/legacy/legacy_query_builder.ex
- lib/plausible/stats/query.ex
- lib/plausible/stats/query_result.ex
- lib/plausible/stats/query_runner.ex
- lib/plausible/stats/timeseries.ex
- lib/plausible_web/controllers/api/external_stats_controller.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- test/plausible/imported_test.exs
- test/plausible/stats/comparisons_test.exs
- test/support/factory.ex
Refactor with changes discussed with @macobo:
* add a `comparison_utc_time_range` into the Query struct (happens right before `put_imported_opts` in the query-building pipeline)
* Use `query.comparison_utc_time_range` for:
* deciding `query.include_imported` and `query.skip_imported_reason`
* constructing the comparison query
* Simplify QueryResult (imports_included and metric_warnings.scroll_depth computation can now rely only on `query` without having to worry about `comparison_query`)
Also, what we didn't discuss before - add `imports_in_range` field to Query struct as well. This actually changes the behaviour a bit. Before, the start of query date range being **before** the last import end date meant that imported data was included. Now it does not, and there must be at least one …
> Refactor comparison query & including imported data

- extra/lib/plausible/stats/funnel.ex
- lib/plausible/stats/goals.ex
- test/plausible_web/controllers/api/stats_controller/funnels_test.exs
Make sure page scroll goals can be added as funnel steps.
One single engagement event can count as multiple conversions in a funnel. E.g. we can add a funnel with goals like `Scroll 10`, `Scroll 20`, `Scroll 30`, ... `Scroll 90`, and see that a single `engagement` event with 70% scroll depth has completed every funnel step up to `Scroll 70`.
> Make page scroll goals work in funnels

- lib/plausible/stats/goals.ex
- lib/plausible/stats/imported/imported.ex
- lib/plausible/stats/sql/expression.ex
- test/plausible_web/controllers/api/external_stats_controller/query_goal_dimension_test.exs
Follow-up to https://github.com/plausible/analytics/pull/5029. The conversions query became slow after this change.
The root cause was:
1. The extra string equality checks
2. The extra regex operations
This change fixes that by shuffling operations around and not matching e.g. page paths on custom event goals.
[Before:](https://staging.plausible.io/plausible.io/conversions?period=12mo&keybindHint=L) 14.4s
[After:](https://pr-5084.review.plausible.io/plausible.io/conversions?period=12mo&keybindHint=L) 1.1s
> Perf: Speed up conversions query

- lib/plausible/goals/goals.ex
- test/plausible_web/live/goal_settings/form_test.exs
When goal display name, page path or event name is not unique we should display an error. A recent [PR](https://github.com/plausible/analytics/pull/5027) broke that behaviour, bringing it back now.
> Make sure goal changeset error can be handled outside transaction

- lib/sentry_filter.ex
- test/plausible/sentry_filter_test.exs
After a recent dependency bump, we have observed excess of new errors in Sentry combing from cowboy in a following format:
```
Ranch listener PlausibleWeb.Endpoint.HTTP, connection process #PID<...>, 
stream .. had its request process #PID<...> exit with reason ...
```
After some digging, it turned out that between cowboy 2.12 and 2.13 there's https://github.com/ninenines/cowboy/commit/fbd680f0f6fb5fe99c4345b838cb42aa1afb3283 which plugs an apparent missed pattern case for and starts triggering error messages. This in turn seems to escape the special-cased pattern matching of ranch/cowboy errors in https://github.com/getsentry/sentry-elixir/commit/a14e3f85748e694492bb51d59fb1df9e95bbac16.
This patch is meant as a temporary measure meant to reduce the noise in sentry.
> Ignore excess logger errors from Cowboy when sending to Sentry

- test/plausible_web/controllers/api/external_controller_test.exs
Kind of a nothing-PR but while poking around in ingestion I thought I found an issue where we could ingest blank event names. This would cause problems in imports queries down the line.
Turns out we do validate event name length. I've added a (previously missing) test to this effect.
> Ingestion: Add test demonstrating blank event name is not accepted

- lib/plausible/clickhouse_event_v2.ex
- lib/plausible/ingestion/event.ex
- lib/plausible/ingestion/request.ex
- test/plausible/ingestion/request_test.exs
- test/plausible_web/controllers/api/external_controller_test.exs
Straight-forward ingestion logic for engagement_time column. Depends on https://github.com/plausible/analytics/pull/5092
> time-on-page: Ingestion logic for engagement_time

- tracker/src/plausible.js
- tracker/test/engagement.spec.js
- tracker/test/fixtures/engagement-hash.html
- tracker/test/support/test-utils.js
In `pageleave` extension plausible.js, we now track engagement_time for engagement events. This represents the number of milliseconds the user was _active_ on the page.
To calculate the variable, we keep track of:
- When the page became last active (currentEngagementStartTime)
- How many milliseconds was the page active before going to the background the last time (currentEngagementBeforeHideTime)
We also continue to avoid sending engagement events if there isn't much interesting to report (new max scroll depth or engagement_time above 1s)
> time-on-page: track engagement time in plausible.js

- lib/plausible/teams.ex
- lib/plausible/teams/team.ex
- lib/plausible/teams/team_admin.ex
Due to a regression in #5008, it was impossible to update `%Team{}` via CRM. Kaffy calls the regular `schema.changeset` before looking up an `update_changeset` override. This caused a crash. Additionally, `crm_sync_changeset` was left unused.
> Bugfix: allow Team updates via CRM

- lib/plausible/ingestion/event.ex
- test/plausible/ingestion/event_test.exs
- test/test_helper.exs
Implements a straight-forward feature flag check to drop engagements and not process them. The `engagements` flag should already be enabled for all sites that are currently getting engagements (including e.g. plausible.io).
We can use the feature flag to incrementally crank up the percentage of sites for which we **will** process engagements.
> Scroll Depth Release: ingestion flag check for incremental load increase

- test/plausible_web/plugs/tracker_test.exs
- tracker/report-sizes.js
- tracker/src/plausible.js
- tracker/test/fixtures/engagement-hash-exclusions.html
- tracker/test/fixtures/engagement-hash-pageview-props.html
- tracker/test/fixtures/engagement-hash.html
- tracker/test/fixtures/engagement-manual.html
- tracker/test/fixtures/engagement-pageview-props.html
- tracker/test/fixtures/engagement.html
- tracker/test/fixtures/scroll-depth-content-onscroll.html
- tracker/test/fixtures/scroll-depth-dynamic-content-load.html
- tracker/test/fixtures/scroll-depth-hash.html
- tracker/test/fixtures/scroll-depth-slow-window-load.html
- tracker/test/fixtures/scroll-depth.html
This PR makes scroll depth and engagement time tracking part of the default `script.js`.
We will still continue serving the `pageleave` extension (as just a blank extension with no extra functionality) for as long as people are still using it.
> Scroll Depth Release: make pageleave script the new default

- CHANGELOG.md
- lib/plausible/stats/imported/imported.ex
- lib/plausible/stats/sql/query_builder.ex
- lib/plausible/stats/util.ex
- test/plausible_web/controllers/api/external_stats_controller/query_special_metrics_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
Previously APIv2 would return a 500 up for a query like the follows:
```json
{
"site_id": "plausible.io",
"metrics": ["percentage"],
"date_range": "7d",
"dimensions": ["visit:browser"]
}
```
This was because of a missing visitors metric. This PR fixes that issue and another related query issue along the way.
Ref: https://3.basecamp.com/5308029/buckets/36789884/card_tables/cards/8335318634
> APIv2: Fix `percentage` metric 500s

- config/runtime.exs
- lib/plausible/application.ex
- lib/plausible/ingestion/event.ex
- lib/plausible/session/balancer.ex
- lib/plausible/session/balancer_supervisor.ex
- lib/plausible/session/cache_store.ex
- test/plausible/ingestion/event_test.exs
- test/plausible/session/cache_store_test.exs
- test/support/test_utils.ex
Experimental PR to see whether session locking is our bottleneck. Replacing explicit locking with implicit locking via gen server queues, throttles the ingestion a little bit, at the same time doing less work monitoring cache locks. 
100 workers is completely arbitrary, but I've tried various settings locally (including multiplications of schedulers online etc.) and this seemed to render somewhat best results (with obviously flawed, local `wrk` shots). For that reason, partitioning of the sessions cache was disabled too.
Processing is still synchronous, as we respond to the HTTP client with whether the event was dropped etc.
In the end there's still a single Session.WriteBuffer sink anyway but the goal here is to see what's the impact of not using ConCache's locks.
> Alt serialize sessions

- lib/plausible/segments/filters.ex
- test/plausible/stats/query_parser_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
Currently, segment BC (_containing filters `[B, C]`_) is resolved in the following way:
`[A, segment BC] -> [A, [:and, [B, C]]]`. 
That's a problem when B or C is an `event:goal` filter, because that's only allowed at the top level. 
This PR leverages the logical equivalency between `[A, [:and, [B, C]]]` and `[A, B, C]` to circumvent the problem.
> Flatten :and groups stemming from segment filters on first level

- lib/plausible/segments/filters.ex
- lib/plausible/segments/segment.ex
- lib/plausible/stats/filters/query_parser.ex
- test/plausible/stats/query_parser_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
- test/plausible_web/controllers/api/internal_controller/segments_controller_test.exs
- Permits has_not_done filter in segments
- Adds extra tests about having non-existing goals within segments. 
- Slightly changes error message upon having non-existing goals within segments, to bring it in line with other errors about selected filters. 
- Removes JS-style triple equals comparison from backend: it isn't standard
> Permit :has_not_done filter in segments

- config/runtime.exs
Even with the new queues (https://github.com/plausible/analytics/pull/5113), ConCache _might_ be overloaded by `set_ttl` casts.
Bumping the number of partitions seems to help in that scenario.
> use 100 sessions partitions

- assets/js/dashboard/filtering/segments.ts
- assets/js/dashboard/nav-menu/segments/searchable-segments-section.tsx
- assets/js/dashboard/segments/segment-authorship.test.tsx
- assets/js/dashboard/segments/segment-authorship.tsx
- assets/js/dashboard/segments/segment-modals.tsx
- assets/js/dashboard/site-context.test.tsx
- assets/js/dashboard/site-context.tsx
- assets/js/dashboard/util/date.test.ts
- assets/test-utils/app-context-providers.tsx
- lib/plausible/segments/segment.ex
- lib/plausible/segments/segments.ex
- lib/plausible_web/controllers/api/internal/segments_controller.ex
- lib/plausible_web/controllers/stats_controller.ex
- lib/plausible_web/templates/stats/stats.html.heex
- test/plausible_web/controllers/api/internal_controller/segments_controller_test.exs
- test/plausible_web/controllers/stats_controller_test.exs
* Removes workaround with segment owner names and dates. Keeps the date util just in case.
* Indicates clearly the different segments index payloads (one for public dashboards and one for site members).
* Adds tests about claiming ownership of dangling segment. 
* Centralizes segment type label
> Resolve segment owner names and dates in site timezone in the BE

- lib/plausible/segments/segments.ex
- lib/plausible_web/controllers/api/internal/segments_controller.ex
- test/plausible_web/controllers/api/internal_controller/segments_controller_test.exs
Limits the possible count of segments to 500 per site to prevent system abuse.
> Limit to 500 segments per site

- test/plausible/site/cache_test.exs
Increases the time limit on cache merge test.
> Stop cache test flaking

- lib/plausible/application.ex
- lib/plausible/ingestion/source.ex
- test/plausible/ingestion/source_test.exs
- test/plausible_web/plugs/tracker_test.exs
Micro optimization for the put_source_info ingest step: looks like the ets table is unnecessary in `Ingestion.Source` module, as we can easily generate all the required function clauses at compile-time.
> Use compile-time Ingestion.Source lookups

- assets/js/dashboard/nav-menu/top-bar.test.tsx
- assets/js/dashboard/nav-menu/top-bar.tsx
- assets/js/dashboard/segments/routeless-segment-modals.tsx
- assets/js/dashboard/site-context.tsx
- assets/js/dashboard/util/filters.js
- assets/js/dashboard/util/filters.test.ts
- lib/plausible_web/controllers/stats_controller.ex
- lib/plausible_web/live/choose_plan.ex
Needed to prevent unexpected 404s when `saved_segments` feature flag has propagated to the node that serves the dashboard, but not to *all* app nodes.
To use successfully, we'd first enable `saved_segments` feature flag, ensure it is propagated, then enable `saved_segments_fe` flag. That signals dashboards to start making segment related requests.
> Prepare FE feature flag for launching smoothly

- priv/repo/migrations/20250306083000_add_site_segments_feature_to_enterprise_plans.exs
Adds :site_segments feature to some plans.
Up
```
plausible_dev=# select id,features from enterprise_plans;
id |                features                 
----+-----------------------------------------
1 | {stats_api,props,funnels,revenue_goals}
2 | {stats_api,props}
(2 rows)
plausible_dev=#     UPDATE enterprise_plans
SET features = array_append(features, 'site_segments')
WHERE features @> ARRAY['props', 'stats_api', 'funnels', 'revenue_goals']::varchar[]
AND NOT (features @> ARRAY['site_segments']::varchar[]);
UPDATE 1
plausible_dev=# select id,features from enterprise_plans;
id |                       features                        
----+-------------------------------------------------------
2 | {stats_api,props}
1 | {stats_api,props,funnels,revenue_goals,site_segments}
(2 rows)
``` …
> Add site_segments feature to enterprise plans

- CHANGELOG.md
- priv/json-schemas/query-api-schema.json
- test/plausible/stats/query_parser_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
Reveals segment filter in v2 Stats API. 
docs: https://github.com/plausible/docs/pull/586
> Reveal segment filters in v2 Stats API

- .github/workflows/elixir.yml
- test/plausible_web/plugs/tracker_test.exs
A test in test/plausible_web/plugs/tracker_test.exs was failing due to cached version of tracker script being used in other PRs.
The reason it didn't fail in the original PR adding the test was that changes in tracker script bypassed the cache **for that pr**. The old cached data was still used for other PRs, causing them to fail.
> Bump elixir.yml cache version to fix a test

- CHANGELOG.md
- assets/js/dashboard/stats/graph/graph-tooltip.js
- assets/js/dashboard/stats/graph/graph-util.js
- assets/js/dashboard/stats/reports/metric-formatter.ts
- lib/plausible/stats/metrics.ex
- lib/plausible/stats/query_runner.ex
- lib/plausible/stats/timeseries.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
- test/plausible_web/controllers/api/stats_controller/sources_test.exs
This PR improves main graph by:
- showing revenue with relevant currency symbol when hovering a data point
- showing `-` instead of `0` for visit duration, scroll depth when hovering a data point with no visit data
This is preparatory work for new time-on-page metric (which will be graphable).
> Improve dashboard main graph - revenue metrics, nulls

- CHANGELOG.md
- assets/js/dashboard/stats/graph/graph-util.js
- assets/js/dashboard/stats/graph/top-stats.js
- assets/js/dashboard/stats/graph/visitor-graph.js
- lib/plausible_web/controllers/api/stats_controller.ex
Fixes the issue with filters inside segments not being counted properly for top stats.
> Provide top stats graphable metrics from BE

- lib/plausible/stats/current_visitors.ex
- test/plausible_web/controllers/api/stats_controller/current_visitors_test.exs
This was unexpected breakage from releasing new tracker script with engagement tracking to the world. Users are seeing inflated current visitors counts compared to top sources report.
[Helpscout link](https://secure.helpscout.net/conversation/2869053683/23571?viewId=6980900)
> Stop counting engagement events into current visitors

- lib/plausible_web/live/sites.ex
Unclear why phx-mounted was used
>   Show site placeholders on 1st mount

- CHANGELOG.md
- assets/js/dashboard/site-context.tsx
- assets/js/dashboard/stats/modals/filter-modal.js
BE doesn't pass this FF any more, since https://github.com/plausible/analytics/pull/4972.
> Fix Channels filter input appearing when clicking "Channel is..." filter pill

- priv/ingest_repo/migrations/20250221124625_imported_pages_total_time_on_page.exs
- priv/ingest_repo/migrations/20250304074501_populate_imported_pages_total_time_on_page.exs
This PR adds 2 migrations:
- Adding new columns to `imported_pages`
- Updating the columns to be populated for old GA4 imports
> time-on-page: `imported_pages` new columns

- assets/js/dashboard/api.ts
- assets/js/dashboard/stats/graph/stats-export.js
This fixes a bug with doing csv exports on shared links.
How to reproduce (on master):
1. Open http://localhost:8000/dummy.site/settings/visibility
2. Make sure stats are _not_ publicly accessible
3. Create a shared link
4. Visit shared link in incognito
5. Click to export
Expected result:
1. Export succeeds
Actual result:
1. Export fails with 404
This bug was introduced by a refactor that removed the `auth` search param from link in https://github.com/plausible/analytics/pull/5154
> Fix shared links export

- assets/js/dashboard/user-context.tsx
- lib/plausible/billing/billing.ex
- lib/plausible/billing/site_locker.ex
- lib/plausible/segments/segments.ex
- lib/plausible/teams/membership.ex
- lib/plausible/teams/memberships/update_role.ex
- lib/plausible/teams/team.ex
- lib/plausible_web/controllers/billing_controller.ex
- lib/plausible_web/controllers/settings_controller.ex
- lib/plausible_web/live/auth_context.ex
- lib/plausible_web/live/team_management.ex
- lib/plausible_web/plugs/auth_plug.ex
- lib/plausible_web/plugs/authorize_team_access.ex
- lib/plausible_web/templates/settings/team_general.html.heex
- lib/plausible_web/views/layout_view.ex
- lib/workers/check_usage.ex
- lib/workers/notify_annual_renewal.ex
- lib/workers/send_trial_notifications.ex
- test/plausible/billing/billing_test.exs
- test/plausible/billing/site_locker_test.exs
- test/plausible_web/controllers/billing_controller_test.exs
- test/plausible_web/live/team_management_test.exs
- test/plausible_web/plugs/auth_plug_test.exs
- test/plausible_web/plugs/authorize_team_access_test.exs
- test/workers/check_usage_test.exs
- test/workers/notify_annual_renewal_test.exs
- test/workers/send_trial_notifications_test.exs
This PR introduces `:billing` team role; billing members receive all the subscription related notifications and can manage subscriptions.
> Add billing role

- CHANGELOG.md
- assets/js/dashboard/api.ts
- assets/js/dashboard/query-context.tsx
- assets/js/dashboard/query.ts
- assets/js/dashboard/site-context.test.tsx
- assets/js/dashboard/site-context.tsx
- assets/js/dashboard/stats/graph/graph-util.js
- assets/js/dashboard/stats/graph/top-stats.js
- assets/js/dashboard/stats/modals/breakdown-modal.tsx
- assets/js/dashboard/stats/reports/metrics.js
- assets/test-utils/app-context-providers.tsx
- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/legacy/legacy_query_builder.ex
- lib/plausible/stats/query_result.ex
- lib/plausible/stats/query_runner.ex
- lib/plausible/stats/sql/expression.ex
- lib/plausible/stats/time_on_page.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- lib/plausible_web/controllers/stats_controller.ex
- lib/plausible_web/templates/stats/stats.html.heex
- test/plausible/stats/query_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_time_on_page_test.exs
This PR adds support for new time-on-page metric to dashboard. The new functionality is behind a feature flag named `new_time_on_page`.
New functionality is (click on a header to see screenshots):
<details>
<summary><strong>1. time-on-page is now graphable</strong></summary>
</details>
<details>
<summary><strong>2. time-on-page is now sortable in modals</strong></summary>
</details>
<details>
<summary><strong>3. metric warnings when legacy time-on-data is shown</strong></summary>
</details>
<strong>4. Improved query: comparisons & timeseries tests</strong>
If feature flag is enabled, `include.legacy_time_on_page_cutoff` is sent with each query to the backend. This date determines when the new time-on-data metric is shown.
By default for now, the cutoff is 4 days ago, however for internal …
> time-on-page: dashboard + timeseries support

- tracker/src/plausible.js
The bug was:
1. Site sends an `engagement` event, which resets runningEnagementStart to null
2. Page visibility state changes to `hidden` before next pageview (and without visibilityState being changed to visible).
3. `currentEngagementTime = Date.now() - null` which reports Date.now() as engagement_time
I didn't find a way to test this as it relies heavily on timing we can't easily reproduce.
One scenario would be:
1. User clicks SPA link to exit page
2. `engagement` is sent, runningEngagementStart is reset 3.a. page is closed, triggering bug
3.b. pageview is sent, doing a correct reset
Usually, 3.b would happen before 3.a but there's no way to re-create this scenario in tests.
Along the way added some more defensive code.
> time-on-page: Fix bug causing massive `engagement_time` values

- assets/js/dashboard/stats/graph/top-stats.js
Follow-up to https://github.com/plausible/analytics/pull/5174#discussion_r1991031149
I believe the asterisk was never rendered due to being broken by a refactor.
> Fix top stats metric warning asterisk asterisk

- lib/plausible/imported/google_analytics4.ex
- lib/plausible/imported/page.ex
- test/plausible/imported/google_analytics4_test.exs
Ref: https://3.basecamp.com/5308029/buckets/41123095/card_tables/cards/8391930289
This column was speculatively added for time-on-page but we don't need it.
> time-on-page: Don't read/write active_visitors from GA4

- priv/ingest_repo/migrations/20250312063938_imported_pages_remove_old_time_on_page_columns.exs
Ref: https://3.basecamp.com/5308029/buckets/41123095/card_tables/cards/8391930289
Depends on https://github.com/plausible/analytics/pull/5178, don't forget to change target branch when merging :sweat_smile:
> Drop old (unused) time-on-page columns from imported_pages

- assets/js/dashboard/stats/modals/conversions.js
Sentry error: https://sentry.plausible.io/organizations/plausible/issues/1038/?environment=prod&project=2&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=90d&stream_index=0&utc=true
The frontend was passing invalid order_by values to the backend that a refactor started unaccepting.
This PR makes it so we don't pass an invalid order_by anymore. LocalStorage isn't an issue since there's already an internal validations system this value would fail.
Follow-up to https://github.com/plausible/analytics/pull/5174
> Fix invalid default `order_by` in conversions report

- lib/plausible/ingestion/event.ex
- lib/plausible/ingestion/request.ex
- test/plausible/ingestion/event_test.exs
- test/plausible/stats/query_test.exs
- test/plausible_web/controllers/api/external_controller_test.exs
- test/test_helper.exs
* Accept strings for scroll depth and engagement time (parsing them to integers)
* Remove the `ff_throttle` engagement dropping and replace it with dropping blank engagments instead
* Fix a flaky test
> Ingest scroll depth and engagment time from string + drop blanks

- lib/plausible_web/components/billing/notice.ex
- lib/plausible_web/live/auth_context.ex
- lib/plausible_web/live/goal_settings.ex
- lib/plausible_web/live/goal_settings/form.ex
- lib/plausible_web/live/team_management.ex
- lib/plausible_web/plugs/auth_plug.ex
- lib/plausible_web/plugs/authorize_site_access.ex
- lib/plausible_web/plugs/authorize_team_access.ex
- lib/plausible_web/templates/settings/api_keys.html.heex
- lib/plausible_web/templates/settings/team_general.html.heex
- lib/plausible_web/templates/site/membership/invite_member_form.html.heex
- lib/plausible_web/templates/site/new.html.heex
- lib/plausible_web/templates/site/settings_funnels.html.heex
- lib/plausible_web/templates/site/settings_props.html.heex
- lib/plausible_web/templates/stats/site_locked.html.heex
- lib/plausible_web/views/layout_view.ex
- lib/workers/notify_annual_renewal.ex
- test/plausible_web/components/billing/notice_test.exs
- test/plausible_web/controllers/stats_controller_test.exs
- test/plausible_web/plugs/auth_plug_test.exs
- test/plausible_web/plugs/authorize_site_access_test.exs
- test/plausible_web/plugs/authorize_team_access_test.exs
As of #5171 we have `current_role` in assigns.
> Get rid of `billable_user` in favour of `current_team_role` (or `site_role` if need be)

- assets/js/dashboard/query-context.tsx
This broke in a refactor - originally api.ts also checked for the feature flag before sending include.legacy_time_on_page_cutoff but this was incorrectly removed due to conflicting changes.
> Don't show new time-on-page metric for customers without flag

- lib/plausible/ingestion/request.ex
- test/plausible_web/controllers/api/external_controller_test.exs
Follow-up to https://github.com/plausible/analytics/pull/5181
Users might have the old version of the script cached for a while yet so avoid ingesting invalid data while that's the case
> time-on-page: Mark unreasonably high engagement_time values as 0-s

- CHANGELOG.md
Ref: https://3.basecamp.com/5308029/buckets/39034214/card_tables/cards/8420137962
Given we're planning to reach out to some sites using the proxy, I thought it makes sense to document this in the changelog as well.
> Add changelog entry on tracker script changes

- lib/plausible/teams/memberships/update_role.ex
- lib/plausible_web/email.ex
- lib/plausible_web/templates/email/guest_to_team_member_promotion.html.heex
- test/plausible/teams/memberships/update_role_test.exs
- test/plausible_web/live/team_management_test.exs
Send out an e-mail indicating team member promotion for users previously being site guests.
> Email notification on guest->team member promotion

- lib/plausible/crm_extensions.ex
Adds the en-GB number format to Enterprise Plan :site_limit field as well.
> Make setting sites limit slightly more convenient

- CHANGELOG.md
- assets/js/dashboard.tsx
- assets/js/dashboard/filtering/segments-context.test.tsx
- assets/js/dashboard/filtering/segments-context.tsx
- assets/js/dashboard/filtering/segments.test.ts
- assets/js/dashboard/filtering/segments.ts
- assets/js/dashboard/nav-menu/segments/searchable-segments-section.tsx
- assets/js/dashboard/query-context.tsx
- assets/js/dashboard/query.ts
- assets/js/dashboard/segments/routeless-segment-modals.tsx
- assets/js/dashboard/segments/segment-authorship.tsx
- assets/js/dashboard/segments/segment-modals.test.tsx
- assets/js/dashboard/segments/segment-modals.tsx
- assets/js/dashboard/stats/modals/filter-modal.js
- assets/js/dashboard/util/filters.js
- assets/test-utils/app-context-providers.tsx
- lib/plausible/segments/segment.ex
- lib/plausible/segments/segments.ex
- lib/plausible_web/controllers/api/internal/segments_controller.ex
- lib/plausible_web/controllers/stats_controller.ex
- lib/plausible_web/router.ex
- lib/plausible_web/templates/stats/stats.html.heex
- test/plausible_web/controllers/api/internal_controller/segments_controller_test.exs
- test/plausible_web/controllers/stats_controller_test.exs
* Replaces `GET /api/:domain/segments` and `GET /api/:domain/segments/:segment_id` requests by stuffing all segments into the server rendered HTML
* This list is updated in the FE on successful segment add, update, delete actions, and a new fresh list is provided any time the user refreshes the dashboard
* Adds calculated `resolvedFilters` to query context, for filters related utilities not to lose track of the metrics the FE should request 
* makes use of `resolvedFilters` in `hasConversionGoalFilter` utility, which is called in most metrics reports
> Fix dashboard report behavior when goals are in segments - variant C

- priv/repo/migrations/20250313132408_drop_site_scroll_depth_visible_at.exs
Migration to drop the `site.scroll_depth_visible_at` column which is no longer needed.
> Migration: Drop `site.scroll_depth_visible_at`

- lib/plausible/verification/checks/snippet.ex
- lib/plausible/verification/diagnostics.ex
- test/plausible/site/verification/checks/snippet_test.exs
- test/plausible/site/verification/checks_test.exs
For when both GTM & WordPress Plugin are detected, give WP priority. Also, consider `data-cfasync`
a known attribute since it's the plugin that
adds that.
> Improve verification diagnostics

- lib/plausible/ingestion/counters.ex
- lib/plausible/ingestion/counters/buffer.ex
- lib/plausible/ingestion/counters/record.ex
- lib/plausible/ingestion/counters/telemetry_handler.ex
- lib/plausible/ingestion/event.ex
- lib/plausible/ingestion/request.ex
- priv/ingest_repo/migrations/20250316182725_ingest_counters_tracker_script_version.exs
- test/plausible/ingestion/counters/buffer_test.exs
- test/plausible/ingestion/counters/telemetry_handler_test.exs
- test/plausible/ingestion/counters_test.exs
- test/plausible/ingestion/request_test.exs
This will enable tracking how many events per tracker_script_version to track the rollout for any issues.
Migration PR: https://github.com/plausible/analytics/pull/5202 (to be deployed first)
Tracker PR: https://github.com/plausible/analytics/pull/5198
> Store `tracker_script_version` under `ingest_counters`

- tracker/src/plausible.js
- tracker/test/engagement.spec.js
- tracker/test/support/test-utils.js
Consider this scenario:
1. User opens page /blog
2. 3 seconds later, alt-tabs to another window
3. minute later, alt-tabs to the page and closes it
Previously, this would be reported as 1m03s engagement_time. Now this would be reported as 3s engagement_time.
> Tracker: Pause engagement_time when browser loses focus

- tracker/src/plausible.js
- tracker/test/engagement.spec.js
- tracker/test/scroll-depth.spec.js
- tracker/test/support/test-utils.js
Removes redundant engagement cooldown of 300ms (this was currently not even used and the comment about SPA navigation was wrong because our script adds a listener for either hashchange or pushstate/popstate - not both)
> Tracker: Remove redundant engagement cooldown

- lib/plausible/site/admin.ex
- lib/plausible/site/memberships/accept_invitation.ex
- lib/plausible/site/memberships/create_invitation.ex
- lib/plausible/teams/invitations.ex
- lib/plausible/teams/sites.ex
- lib/plausible_web/controllers/invitation_controller.ex
- lib/plausible_web/controllers/site/membership_controller.ex
- lib/plausible_web/views/layout_view.ex
- test/plausible/site/admin_test.exs
- test/plausible/site/memberships/accept_invitation_test.exs
- test/plausible/site/memberships/create_invitation_test.exs
- test/plausible/site/sites_test.exs
- test/plausible_web/controllers/invitation_controller_test.exs
This PR adjusts site transfer logic to allow transferring sites between different teams of the same user.
> Allow site transfer between different teams of the same user

- lib/plausible/auth/auth.ex
- lib/plausible/teams.ex
- lib/plausible_web/controllers/auth_controller.ex
- lib/plausible_web/controllers/settings_controller.ex
- lib/plausible_web/live/team_management.ex
- lib/plausible_web/live/team_setup.ex
- lib/plausible_web/router.ex
- lib/plausible_web/templates/layout/_header.html.heex
- lib/plausible_web/templates/settings/danger_zone.html.heex
- lib/plausible_web/templates/settings/team_danger_zone.html.heex
- lib/plausible_web/templates/settings/team_general.html.heex
- lib/plausible_web/views/layout_view.ex
- test/plausible/teams_test.exs
- test/plausible_web/controllers/auth_controller_test.exs
- test/plausible_web/controllers/settings_controller_test.exs
- test/plausible_web/live/team_management_test.exs
- test/support/teams/test.ex
This PR adds capability to delete current team from a dedicated section under "Team Settings > Danger Zone". 
User deletion procedure was refactored as well to explicitly prevent deletion if associated personal team has an active subscription. The user deletion routine will be further extended in a follow-up with more explicit messaging for cases of setup teams with the user for sole owner. 
The team deletion procedure also accounts for ensuring the subscription is canceled first before allowing to delete the team.
Team deletion can be carried out only by one of the team owners.
> Implement team deletion and refactor user deletion

- lib/plausible/teams/memberships.ex
- lib/plausible_web/templates/site/settings_people.html.heex
- test/plausible_web/controllers/site/membership_controller_test.exs
Extracted from https://github.com/plausible/analytics/pull/5210 which is blocked until teams feature is released.
Fixes:
- allow admin to update site role (permission check was missing relevant clauses)
- display ownership transfer option under Site Settings > People to admin as well
> Fix Team Admin permissions

- lib/plausible/teams.ex
- lib/plausible_web/live/sites.ex
- lib/plausible_web/live/team_setup.ex
- lib/plausible_web/plugs/authorize_team_access.ex
- lib/plausible_web/templates/layout/_header.html.heex
- lib/plausible_web/templates/layout/settings.html.heex
- lib/plausible_web/views/layout_view.ex
Teams feature flag scoped to a team is not very practical for limited roll-out. Switching on user makes more sense as we can enable that for a limited set of users to run some final tests in production.
> Switch Teams feature flag to scope by user instead of a team

- assets/js/dashboard/nav-menu/filters-bar.test.tsx
- assets/js/dashboard/nav-menu/filters-bar.tsx
Bare minimum in response to https://feedback.plausible.io/582 while we think of something better.
**Now:** 
**Before:** 
showed "See more" always
> Indicate extra filters count on triple dot menu hover

- extra/lib/plausible_web/controllers/api/external_sites_controller.ex
- lib/plausible/sites.ex
- lib/plausible_web/router.ex
- test/plausible_web/controllers/api/external_sites_controller_test.exs
This PR adds Create/List/Delete operations for "guests" via the Sites API.
Implementation follows existing conventions. 
`accepted` boolean payload attribute indicates difference between invitation and a membership. `email` is used as a universal identifier for either guest invitation or a guest membership.
Docs: https://github.com/plausible/docs/pull/591
> Guest Memberships via Sites API

- extra/lib/plausible_web/controllers/api/external_sites_controller.ex
- lib/plausible/sites.ex
- lib/plausible/teams/users.ex
- lib/plausible_web/router.ex
- lib/plausible_web/templates/settings/team_general.html.heex
- test/plausible_web/controllers/api/external_sites_controller_test.exs
- test/plausible_web/controllers/auth_controller_test.exs
- test/plausible_web/controllers/settings_controller_test.exs
This PR adds a Sites API endpoint for listing teams the user is a member in. The team identifier from that endpoint can be used when either creating sites via `POST /api/v1/sites` to create a site under a particular team or scope the list of sites  to a particular team with `GET /api/v1/sites?team_id=...`.
The team identifier input was removed from Team Settings to avoid confusing users who don't actively use the API, which is the only place where identifier is explicitly used so far.
The endpoint is under scope which is implicitly available to all API keys. The `api_available` field on team entry determines if the team has Stats API feature enabled. If it's disabled, it's not possible to create sites under it (or, for that matter, run other API queries against its sites).
The `GET …
> Add `GET /api/v1/sites/teams` endpoint and make related adjustments

- lib/plausible/auth/api_key.ex
- lib/plausible/billing/billing.ex
- lib/plausible/data_migration/backfill_teams_hourly_api_request_limit.ex
- lib/plausible/teams/team.ex
- test/plausible/billing/billing_test.exs
- test/plausible/data_migration/backfill_teams_hourly_request_limit_test.exs
- test/plausible/teams_test.exs
This PR is a follow-up to #5225. It adds `Team.hourly_api_request_limit` schema field and starts updating it along with `ApiKey` on plan change via Paddle webhook.
Extracted from https://github.com/plausible/analytics/pull/5224/commits/ea3438fc11066268ebb4b4a0764300798a1d7a0f
> Add `Team.hourly_api_request_limit` and update it on plan change

- lib/plausible/billing/site_locker.ex
- lib/plausible/teams/billing.ex
- lib/plausible_web/live/sites.ex
- lib/workers/check_usage.ex
- test/plausible/billing/billing_test.exs
- test/plausible/billing/site_locker_test.exs
- test/plausible_web/controllers/site_controller_test.exs
- test/support/test_utils.ex
- test/workers/lock_sites_test.exs
This PR fixes a bug described below:
Our `CheckUsage` and `SiteLocker` jobs are two independent workers. The first is setting grace periods for users and the other one is acting upon them. The bug is that the `SiteLocker` doesn't look at the usage. It just blindly locks a team when their grace period is over.
Because of that, it's possible that when a user lowers their usage (e.g. deletes or transfers some sites) at the last moment (i.e. after the last CheckUsage job that runs daily at 2PM UTC **AND** before midnight UTC the next day) they might still get locked
This PR introduces a "final check" before we actually proceed with locking the team and sending the "Your stats are now locked" email. If they turn out to have lowered their usage. They'll remain unlocked and their grace period …
> Add final usage check before locking sites

- lib/plausible/auth/api_key.ex
- lib/plausible/auth/api_key_admin.ex
- lib/plausible/auth/auth.ex
- lib/plausible/billing/billing.ex
- lib/plausible_web/plugs/authorize_public_api.ex
- lib/plausible_web/router.ex
- test/plausible/auth/auth_test.exs
- test/plausible/billing/billing_test.exs
- test/plausible_web/controllers/api/external_sites_controller_test.exs
- test/plausible_web/controllers/api/external_stats_controller/auth_test.exs
- test/plausible_web/controllers/api/stats_controller/sources_test.exs
- test/plausible_web/plugs/authorize_public_api_test.exs
This PR switches Sites and Stats API rate limiting to use `Team.hourly_api_request_limit` for checking, with fallback to hardcoded default. The limit is no longer stored and read from `ApiKey.hourly_request_limit`. This change makes rate limit enforcement more consistent and prepares groundwork for team-bound API keys support.
> Limit rate of requests for Stats/Sites API via Team directly

- priv/repo/migrations/20250324142615_add_api_keys_team_id.exs
Adds a new relation to `api_keys` which will enable team-bound API keys later on.
> Add `team_id` relation to `api_keys`

- priv/repo/migrations/20250325144254_alter_api_keys_team_id_index.exs
I have hastily assumed that team_id/user_id combination should be unique for API keys, while it obviously shouldn't, as a single user might very well have more than one key per team.
> Adjust `api_keys.team_id` index, making it non-unique

- CHANGELOG.md
- assets/js/types/query-api.d.ts
- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/sql/query_builder.ex
- lib/plausible/stats/table_decider.ex
- priv/json-schemas/query-api-schema.json
- test/plausible/stats/query_parser_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
- test/plausible_web/controllers/api/stats_controller/sources_test.exs
This PR fixes a bug: `visitors.csv` in the CSV export are reporting different `visitors` and `visits` numbers than the main graph (while they should be equivalent reports).
There are two reasons for why those numbers are different:
1. A query optimization (`TableDecider` reducing joins) selecting a different table from which to query
* For the main graph, both `visitors` and `visits` are queried from the sessions table
* For the csv export, both `visitors` and `visits` are queried from the events table
The difference comes from the fact that the CSV export is querying all metrics at once, while main graph is asking for a single graph metric at a time.
2. We count sessions in all time buckets they were active in
Let’s say user A sent us a pageview at 12:00 and another pageview at 12:10. If …
> Fix visitors.csv vs main graph discrepancy

- assets/js/dashboard/components/popover.tsx
- assets/js/dashboard/components/remove-filter-button.tsx
- assets/js/dashboard/keybinding.tsx
- assets/js/dashboard/nav-menu/filter-pills-list.tsx
- assets/js/dashboard/nav-menu/filters-bar.test.tsx
- assets/js/dashboard/nav-menu/filters-bar.tsx
- assets/js/dashboard/segments/segment-modals.tsx
- assets/js/dashboard/stats/modals/filter-modal.js
> Make 'Remove filter' / 'Clear all filters' buttons less threatening & other tweaks

- lib/plausible/auth/user_admin.ex
- lib/plausible/teams/team_admin.ex
- test/plausible_web/controllers/admin_controller_test.exs
The user delete action wasn't properly tested and was returning wrong result format. The error format turned out wrong too. Team delete action was missing. This PR fixes both CRM actions and adds tests against them.
> Fix user and team deletion from CRM

- lib/plausible_web/components/billing/pageview_slider.ex
- lib/plausible_web/live/choose_plan.ex
* Fixes the pageviews slider on Firefox by aligning the base of the range input with the base of various texts that appear next to it. 
* For that, it needs to have same top and bottom margin and vertical-align: middle, which I opted to give using style not TW classes, just to keep it the same as in website #pricing section. 
* Stops slider output text from wrapping around the 1024px screen width mark by changing the font size and removing custom large screen horizontal padding from choose plan page. 
See comment for before / after images.
> Fix pageviews slider

- lib/plausible/site/memberships/accept_invitation.ex
- lib/plausible/teams/users.ex
- lib/plausible_web/controllers/site/membership_controller.ex
- lib/plausible_web/router.ex
- lib/plausible_web/templates/site/membership/change_team_form.html.heex
- lib/plausible_web/templates/site/settings_danger_zone.html.heex
- test/plausible/site/memberships/accept_invitation_test.exs
- test/plausible_web/controllers/site_controller_test.exs
In case the user belongs to more than 1 team, in either admin or owner roles, Site's Danger Zone section allows changing the team. Team change is effectively identical to inviting user's own e-mail to site transfer, except bypasses the invitation flow.
> Change site team

- lib/plausible/application.ex
- lib/plausible/ingestion/event.ex
- lib/plausible/telemetry/plausible_metrics.ex
- test/plausible/ingestion/event_test.exs
Be vigilant about UA parsing congestion by ensuring a maxmium execution time is enforced.
> Supervise user agent parsing

- CHANGELOG.md
- lib/plausible/stats/sql/special_metrics.ex
- test/plausible/imported/csv_importer_test.exs
- test/plausible/imported/google_analytics4_test.exs
- test/plausible_web/controllers/CSVs/30d-filter-goal/channels.csv
- test/plausible_web/controllers/CSVs/30d-filter-goal/sources.csv
- test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
- test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_special_metrics_test.exs
- test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
- test/plausible_web/controllers/api/stats_controller/browsers_test.exs
- test/plausible_web/controllers/api/stats_controller/conversions_test.exs
- test/plausible_web/controllers/api/stats_controller/custom_prop_breakdown_test.exs
- test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
- test/plausible_web/controllers/api/stats_controller/pages_test.exs
- test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
Change the ClickHouse select statement to round conversion rate to 2 decimal places.
Feedback: https://feedback.plausible.io/235
> Increase Conversion Rate precision by one decimal place

- CHANGELOG.md
- lib/plausible/site/traffic_change_notification.ex
- lib/plausible/stats/clickhouse.ex
- lib/plausible_web/email.ex
- lib/plausible_web/templates/email/spike_notification.html.heex
- lib/workers/traffic_change_notifier.ex
- test/plausible/stats/clickhouse_test.exs
- test/workers/traffic_change_notifier_test.exs
Slight doc adjustment when this goes live: https://github.com/plausible/docs/pull/597
* Improve `TrafficChangeNotifierTest` and add a few missing tests
* Leverage `Stats.query` instead of building the `Ecto.Query` for top 3 sources from scratch
* Add the top 3 pages below the sources in the email (see screenshots below)
Before (multiple sources exist):
After (multiple source exist):
Before (all traffic is "Direct / None"; _NOTE: we don't display sources at all in this case_):
After (all traffic is "Direct / None"):
> Add top 3 pages to traffic spike email

- test/plausible/imported/csv_importer_test.exs
This probably doesn't fix the flakiness with this test suite (which I managed to reproduce locally, see Basecamp card), but it fixes Oban options in the test (https://hexdocs.pm/oban/Oban.html#drain_queue/2-options) and clarifies the private unzip testing function to better show what part of the operation failed.
> Fix Oban option, split operations in CSV import export test

- .github/workflows/elixir.yml
- extra/lib/plausible_web/controllers/api/external_sites_controller.ex
- lib/plausible/auth/api_key.ex
- lib/plausible/auth/api_key_admin.ex
- lib/plausible/auth/auth.ex
- lib/plausible/teams.ex
- lib/plausible_web/controllers/settings_controller.ex
- lib/plausible_web/plugs/authorize_public_api.ex
- lib/plausible_web/views/layout_view.ex
- test/plausible/auth/auth_test.exs
- test/plausible_web/controllers/admin_controller_test.exs
- test/plausible_web/controllers/api/external_sites_controller_test.exs
- test/plausible_web/controllers/settings_controller_test.exs
- test/plausible_web/plugs/authorize_public_api_test.exs
- test/support/test_utils.ex
- test/test_helper.exs
This PR starts populating `team_id` relation in ApiKey on creation. When created by user, `current_team` is used. From CRM, when left empty, it defaults to user's personal team. When explicit team identifier is provided, the API key is bound to that key.
When creating the key from "Account Settings" the new key is always bound to the current team.
All existing keys are left intact and still allow querying sites from all teams where user has access - either via guest or full membership, provided the site's team has Stats API capability enabled.
NOTE: The test suite will now throw a following warning even on a clean run:
```elixir
warning: using map.field notation (without parentheses) to invoke function Plausible.Auth.ApiKey.__struct__() is deprecated, you must add parenthes
es instead: …
```
> Populate `team_id` when provisioning API key

- CHANGELOG.md
- lib/plausible_web/plugs/favicon.ex
- test/plausible_web/plugs/favicon_test.exs
https://3.basecamp.com/5308029/buckets/36789884/card_tables/cards/8360831680
Fixes fetching favicons from DuckDuckGo if there's a subfolder provided with the domain name. DuckDuckGo only resolves favicons at a domain level, so we need to strip the pathname before we send the request to DDG.
For example, in our [referer_favicon_domains.json](https://github.com/plausible/analytics/blob/master/priv/referer_favicon_domains.json) we have a few sources that include forward slashes:
```json
{
"Orange Webmail": "orange.fr/webmail",
"Bing Images": "bing.com/images/search",
"Google Product Search": "google.ac/products",
}
```
* https://icons.duckduckgo.com/ip3/orange.fr/webmail.ico -> returns placeholder
* https://icons.duckduckgo.com/ip3/orange.fr.ico -> returns the favicon
Stripping the pathname …
> Fix favicons for domains including a subfolder

- lib/plausible/teams/users.ex
- lib/plausible_web/live/sites.ex
- test/plausible_web/live/sites_test.exs
Upgrade nag notice fix to not show it when it shouldn't be visible. Currently it's shown when user has no current team set but they have another team setup (but are not switched to it). This is going to be a pretty common scenario for users setting up teams for the first team and switching back to "Personal Sites" again. While at it, a case of a current team having no sites (much less common) is handled properly as well.
> Only show nag screen when the current team has any sites

- CHANGELOG.md
Changelog update. Change in scope of Editor's permissions can be added separately together with https://github.com/plausible/analytics/pull/5210
> Update CHANGELOG.md with teams support

- lib/plausible_web/templates/site/membership/invite_member_form.html.heex
- lib/plausible_web/templates/site/settings_people.html.heex
- lib/plausible_web/views/site_view.ex
- test/plausible_web/controllers/site_controller_test.exs
Make a strictly visual change, prefixing site roles with "Guest " in order to reduce confusion between site and team roles. Notifications toasts and notification email still use phrasing without the prefix.
> Prefix site roles with "Guest " in UI

- lib/plausible/site/admin.ex
Fix the links in CRM as they now lead to 404 instead of user CRM form.
> Fix links to users under "Other Members" in Site CRM

- lib/plausible/site/memberships/accept_invitation.ex
- lib/plausible/teams/invitations.ex
- lib/plausible_web/email.ex
- lib/plausible_web/templates/email/team_changed.html.heex
- test/plausible/site/memberships/accept_invitation_test.exs
This PR implements sending email notifications on changing team of the site via "Change Team" operation. The notification is sent to all owners of the new team.
> Send e-mail to new owners when site team is changed

- CHANGELOG.md
- lib/plausible/site/admin.ex
- lib/plausible/sites.ex
- lib/plausible/teams/memberships.ex
- lib/plausible_web/components/team/notice.ex
- lib/plausible_web/controllers/invitation_controller.ex
- lib/plausible_web/controllers/site/membership_controller.ex
- lib/plausible_web/controllers/site_controller.ex
- lib/plausible_web/templates/email/ownership_transfer_accepted.html.heex
- lib/plausible_web/templates/site/membership/invite_member_form.html.heex
- lib/plausible_web/templates/site/membership/transfer_ownership_form.html.heex
- lib/plausible_web/templates/site/settings_people.html.heex
- lib/plausible_web/views/site_view.ex
- test/plausible_web/controllers/api/external_sites_controller_test.exs
- test/plausible_web/controllers/invitation_controller_test.exs
- test/plausible_web/controllers/site/membership_controller_test.exs
- test/plausible_web/controllers/site_controller_test.exs
Depends on https://github.com/plausible/analytics/pull/5267
This PR removes Editor -> Admin from Site Settings > People. It also restricts Editor role's permissions, removing ability to:
- delete a site
- initiate transfer of site ownership
- reset stats
- create site guest invitations
- remove site guest invitations
- remove site guests
- change site guests roles (between Viewer and Editor)
> Remove Editor->Admin site role conversion and limit permissions

- test/plausible_web/live/components/combo_box_test.exs
Currently, every now and then the async combo box tests fail, probably due to timing races. This is a rudementary attempt at fixing this by making the test less sensitive to timing.
To any live view experts out there - if there are resources on more idiomatic ways to solve this in elixir, feel free to share them.
> Make combo box tests less flaky

- CHANGELOG.md
- assets/js/dashboard/stats/graph/graph-tooltip.js
- assets/js/dashboard/stats/graph/graph-util.js
- assets/js/dashboard/stats/graph/line-graph.js
The graph ticks already had this feature, but this was missing from tooltips. Hope this sparks some joy.
Basecamp ref: https://3.basecamp.com/5308029/buckets/36789884/card_tables/cards/7630914606
Screenshot before:
Screenshot after:
> Show year (if multi-year graph) in graph tooltips

- priv/repo/migrations/20250403093826_backfill_teams_hourly_api_request_limit.exs
Wrap existing backfill data script in a migration to run only against CE instances.
> Add teams hourly api request limit backfill to CE-only migration

- assets/js/dashboard/api.ts
- assets/js/dashboard/query-context.tsx
- assets/js/dashboard/query.ts
- assets/js/dashboard/site-context.test.tsx
- assets/js/dashboard/site-context.tsx
- assets/js/types/query-api.d.ts
- assets/test-utils/app-context-providers.tsx
- lib/plausible/exports.ex
- lib/plausible/sites.ex
- lib/plausible/stats/legacy/legacy_query_builder.ex
- lib/plausible/stats/query.ex
- lib/plausible/stats/query_optimizer.ex
- lib/plausible/stats/query_result.ex
- lib/plausible/stats/time_on_page.ex
- lib/plausible_web/controllers/api/external_query_api_controller.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- lib/plausible_web/controllers/stats_controller.ex
- lib/plausible_web/live/csv_export.ex
- lib/plausible_web/templates/stats/stats.html.heex
- lib/workers/export_analytics.ex
- priv/json-schemas/query-api-schema.json
- test/plausible/exports_test.exs
- test/plausible/imported/csv_importer_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_time_on_page_test.exs
This PR:
1. Adds CSV import/export support for time-on-page
2. Removes previous code handling time-on-page via frontend include flag. Now the behavior is determined by site.legacy_time_on_page_cutoff and feature flag state.
After this PR (assuming documentation is updated) the feature can be released.
> time-on-page: csv import/export support, preparation for release

- CHANGELOG.md
- priv/json-schemas/query-api-schema.json
- test/plausible/stats/query_parser_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
The functionality has been there for a while but not yet released for the public. 
Docs PR: https://github.com/plausible/docs/pull/600
> APIv2: Release `has_done`/`has_not_done`

- CHANGELOG.md
- assets/js/dashboard/site-context.tsx
- assets/js/dashboard/stats/graph/top-stats.js
- assets/js/dashboard/stats/modals/breakdown-modal.tsx
- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/time_on_page.ex
- lib/plausible_web/controllers/stats_controller.ex
- priv/json-schemas/query-api-schema.json
- test/plausible/imported/csv_importer_test.exs
- test/plausible/imported/google_analytics4_test.exs
- test/plausible/stats/query_parser_test.exs
- test/plausible_web/controllers/CSVs/30d-filter-path/pages.csv
- test/plausible_web/controllers/CSVs/30d-filter-path/visitors.csv
- test/plausible_web/controllers/CSVs/30d/pages.csv
- test/plausible_web/controllers/CSVs/6m/pages.csv
- test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
- test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_time_on_page_test.exs
- test/plausible_web/controllers/api/stats_controller/imported_test.exs
- test/plausible_web/controllers/api/stats_controller/pages_test.exs
- test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
- test/plausible_web/controllers/stats_controller_test.exs
This PR:
1. Removes `new_time_on_page` feature flga
2. Updates CHANGELOG.md for the new feature
3. Enables time_on_page metric in APIv2
4. Updates tests still relying on legacy time-on-page calculation methods
Depends on https://github.com/plausible/analytics/pull/5274
> time-on-page: Remove flag, CHANGELOG.md, time_on_page in APIv2, update old tests

- lib/plausible/teams/invitations.ex
- lib/plausible/teams/membership.ex
- lib/plausible/teams/memberships.ex
- lib/plausible_web/controllers/api/internal_controller.ex
- lib/plausible_web/controllers/api/stats_controller.ex
- lib/plausible_web/email.ex
- lib/plausible_web/live/goal_settings.ex
- lib/plausible_web/plugs/authorize_site_access.ex
- lib/plausible_web/templates/email/ownership_transfer_accepted.html.heex
- test/plausible/site/memberships/create_invitation_test.exs
- test/plausible_web/plugs/authorize_site_access_test.exs
This PR enforces setting `current_team` to authorized site's team if it's different but only when user has a team membership in it.
Also, service-level checks for invitations were fixed to exclude editor role from managing invitations (it's currently enforced on plug level anyway but this change makes the service consistent with plug behavior).
> Set current_team when user has team membership in viewed site 

- CHANGELOG.md
- lib/plausible/teams/billing.ex
- test/plausible/billing/quota_test.exs
- test/plausible/teams/management/layout_test.exs
- test/plausible_web/live/team_management_test.exs
- test/plausible_web/live/team_setup_test.exs
Refs https://github.com/plausible/community-edition/issues/226
This PR addresses an issue where site and member limits equal trial user limits in Community Edition by setting them to always unlimited for CE.
Some of the test code had to be excluded at compile time as Elixir 1.18 kept throwing warnings about integer == :unlimited comparisons in tests.
The team management layout test relied on limits to trigger pending team invitation case which is currently not possible in CE. It got split into two distinct versions, specific to EE and CE.
> Set site and member limits to unlimited for CE

- assets/js/types/query-api.d.ts
- priv/json-schemas/query-api-schema.json
- test/plausible/stats/query_parser_test.exs
Filters autocomplete only showed `"is", "segment"` under autocomplete instead of all options. This is due to limitations in the vscode autocomplete package which I don't fully understand but have to do with partially overlapping `oneOf` definitions. As such the fix was to make each `oneOf` element as independent of each other as possible.
To test this, run plausible/docs under port 8001 with caddy and check out this autocompletion:
Basecamp ref: https://3.basecamp.com/5308029/buckets/36789884/card_tables/cards/8515448386
> APIv2: Fix autocomplete in Stats API playground

- tracker/package.json
- tracker/src/plausible.js
Without this, errors from the API result in uncaught exceptions in clients pages.
Ref: https://3.basecamp.com/5308029/buckets/36789884/card_tables/cards/8490110926
> Tracker: `fetch.catch`

- extra/lib/plausible/stats/sampling.ex
- test/plausible/stats/sampling_cache_test.exs
- test/plausible/stats/sampling_test.exs
This PR:
- Removes code around a feature flag that has been enabled in production for months
- Reduces sampling rate (some users near current threshold have reported issues)
Basecamp ref: https://3.basecamp.com/5308029/buckets/36789884/card_tables/cards/8505102605
> Remove sampling flag code and reduce sampling threshold

- CHANGELOG.md
- assets/js/types/query-api.d.ts
- lib/plausible/stats/filters/query_parser.ex
- priv/json-schemas/query-api-schema.json
- test/plausible/stats/query_parser_test.exs
I was using APIv2 today and got pissed off that I couldn't do `"date_range": "3d"`. So I went ahead and fixed this issue...
> APIv2: More tolerant shorthands for date ranges

- CHANGELOG.md
- assets/js/dashboard/query-context.tsx
- assets/js/dashboard/query-time-periods.test.ts
- assets/js/dashboard/query-time-periods.ts
- assets/js/dashboard/util/date.js
- assets/test-utils/app-context-providers.tsx
Default query period to `today` rather than `28d` for brand new dashboards (i.e. created today). When a user lands on the dashboard for the first time, they should see the graph display visitors straight away.
On the next day, when the user returns to the dashboard, the period will default to `28d` *unless* they interact with the datepicker on the first day already which will store the preference in localStorage.
Basecamp ref: https://3.basecamp.com/5308029/buckets/36789884/card_tables/cards/8509441108
**Tricky:**
The `site.native_stats_start_at` field is the best fit for checking this. However, it gets recorded in UTC (`naive_datetime`), and therefore it's value might end up being one day before or after "today" in `site.timezone`.
When deciding whether to default to today, we are …
> Change default period to today for brand new sites

- tracker/package.json
- tracker/src/plausible.js
- tracker/test/engagement.spec.js
- tracker/test/fixtures/engagement-hash-manual.html
Fixes a tracker bug - when pageviews are triggered manually on single page apps, we are not sending engagements when the user navigates to the next page.
> Tracker bug: engagements not fired on manual trigger SPAs

- priv/repo/migrations/20250409113820_add_teams_locked.exs
Refs https://github.com/plausible/analytics/pull/5304
First step towards moving from `sites.locked` to `teams.locked`. Adds the relevant column to "teams" schema.
> Add `locked` column to `teams`

- CHANGELOG.md
- lib/plausible_web/controllers/stats_controller.ex
- lib/plausible_web/templates/layout/app.html.heex
- lib/plausible_web/templates/layout/site_settings.html.heex
- test/plausible_web/controllers/site_controller_test.exs
- test/plausible_web/controllers/stats_controller_test.exs
Conditionally hides footer. Bolded logic was already present.
- **Dashboard is embedded -> no show footer**
- **Dashboard is from a CE install -> show footer**
- **User viewing public dashboard or accessing a dashboard with a shared link -> show footer**
- User is logged in to Plausible and has a role related to the site (role~"viewer" or above) -> no show footer
- **Special plausible.io/plausible.io case, regardless of login state or role -> show footer**
**-> show footer**
> Hide footer when viewing stats

- lib/plausible/site/memberships/create_invitation.ex
- lib/plausible/teams.ex
- lib/plausible/teams/invitations.ex
- lib/plausible_web/templates/settings/security.html.heex
- test/plausible/site/memberships/create_invitation_test.exs
- test/plausible/teams/invitations/invite_to_team_test.exs
A couple fixes of issues observed in the wild when monitoring the app. Also, cleanup of teams creation logic which was useful during transitioning to teams but is no longer necessary.
> Fix error handling of invitations, 2fa form and clean up team creation

- lib/plausible/teams/team_admin.ex
- lib/plausible_web/controllers/admin_controller.ex
Adds clear indication of whether the team is setup or not in CRM.
> Expose team setup state in CRM

- extra/lib/plausible/help_scout.ex
- lib/plausible/billing/billing.ex
- lib/plausible/billing/site_locker.ex
- lib/plausible/site.ex
- lib/plausible/sites.ex
- lib/plausible/teams.ex
- lib/plausible/teams/invitations.ex
- lib/plausible_web/controllers/stats_controller.ex
- lib/plausible_web/plugs/authorize_public_api.ex
- lib/plausible_web/templates/stats/stats.html.heex
- lib/workers/lock_sites.ex
- lib/workers/schedule_email_reports.ex
- lib/workers/traffic_change_notifier.ex
- mix.exs
- test/plausible/billing/billing_test.exs
- test/plausible/billing/site_locker_test.exs
- test/plausible/help_scout_test.exs
- test/plausible/site/memberships/accept_invitation_test.exs
- test/plausible_web/controllers/api/external_stats_controller/auth_test.exs
- test/plausible_web/controllers/stats_controller_test.exs
- test/plausible_web/plugs/authorize_public_api_test.exs
- test/support/test_utils.ex
- test/workers/lock_sites_test.exs
- test/workers/schedule_email_reports_test.exs
- test/workers/traffic_change_notifier_test.exs
Move site lock state from individual sites to team.
The changes will be deployed in stages:
- ~first, changes up on updating `team.locked` in parallel with `site.locked`~
- ~next, backfill migration~
- after backfill migration is run and team.locked state confirmed to be consistent, switch to `team.locked` entirely
> Switch from `Site.locked` to `Team.locked`

- priv/repo/migrations/20250407110434_remove_unused_tables_and_columns.exs
Migration cleaning up Postgres schema from tables and columns which are no longer used after migrating to teams.
The constraints are modified to cascade as well to ensure data integrity and no orphaned entries.
The migration will be only run on EE. CE will be handled separately when preparing to cut another release.
> Remove tables and columns that are unused after migrating to teams

- lib/plausible_web/controllers/auth_controller.ex
- lib/plausible_web/controllers/google_analytics_controller.ex
- lib/plausible_web/controllers/invitation_controller.ex
- lib/plausible_web/controllers/site/membership_controller.ex
- lib/plausible_web/controllers/site_controller.ex
- lib/plausible_web/controllers/stats_controller.ex
- lib/plausible_web/live/csv_export.ex
- lib/plausible_web/live/csv_import.ex
- lib/plausible_web/live/verification.ex
- test/plausible_web/controllers/invitation_controller_test.exs
- test/plausible_web/live/verification_test.exs
We've been using redirect(external: ...) for all paths containing domain because in the past, Phoenix's redirect was overzealous when sanitizing the URL, effectively rejecting URL-encoded UTF8 characters (starting with %). Current version of phoenix has that sanitization relaxed and relying on external redirects is no longer necessary.
> Change redirects from external to internal where possible

- lib/plausible/stats/datetime_range.ex
- test/plausible/stats/datetime_range_test.exs
We're seeing warnings as follows:
```
(plausible 0.0.1) lib/plausible/stats/legacy/legacy_query_builder.ex:32: Plausible.Stats.Legacy.QueryBuilder.from/4 |
|  (plausible 0.0.1) lib/plausible/stats/query.ex:143: Plausible.Stats.Query.put_imported_opts/2 |
|  (plausible 0.0.1) lib/plausible/stats/query.ex:163: Plausible.Stats.Query.get_imports_in_range/2 |
|  (plausible 0.0.1) lib/plausible/imported.ex:98: Plausible.Imported.completed_imports_in_query_range/2 |
|  (plausible 0.0.1) lib/plausible/stats/query.ex:65: Plausible.Stats.Query.date_range/2 |
|  (elixir 1.17.3) lib/calendar/date.ex:111: Date.range/2 |
|
warning: a negative range was inferred for Date.range/2, call Date.range/3 instead with -1 as third argument
```
As well as some Stats API queries with the date time range reversed. …
> Explicitly handle reverse order DateTimeRange

- CHANGELOG.md
- assets/js/dashboard/nav-menu/query-periods/query-period-menu.tsx
- assets/js/dashboard/query-time-periods.ts
Fixes tiny issue with period picker menu, see changelog.
> Make clicking Compare / Disable Comparison in period picker menu close the menu

- lib/plausible_web/controllers/settings_controller.ex
- lib/plausible_web/views/layout_view.ex
Gates "Subscription" following how "Invoices" are gated.
> Don't show "Subscription" settings item when user role not permitted

- CHANGELOG.md
- lib/plausible/clickhouse_event_v2.ex
- lib/plausible/ingestion/event.ex
- lib/plausible/ingestion/request.ex
- lib/plausible/ingestion/write_buffer.ex
- lib/plausible/session/cache_store.ex
- test/plausible/ingestion/request_test.exs
- test/plausible/session/cache_store_test.exs
- test/support/test_utils.ex
- test/workers/send_email_report_test.exs
- test/workers/send_site_setup_emails_test.exs
- tracker/package.json
- tracker/src/plausible.js
- tracker/test/custom-event-edge-cases.spec.js
- tracker/test/fixtures/custom-event-edge-case.html
- Custom events can now be marked as non-interactive in events API and tracker script. Events marked as non-interactive are not counted towards bounce rate.
- To track custom event in tracker, do `plausible('custom event', { interactive: false })`
- In events API, set `interactive` parameter to false.
- A session is now marked as a bounce if it has less than 2 pageviews and no interactive custom events.
Note that custom events configured via css can not be marked as non-interactive as they require the user to interact with the site.
Basecamp ref: https://3.basecamp.com/5308029/buckets/26383192/card_tables/cards/8450017341
Docs: https://github.com/plausible/docs/pull/601
> Allow marking custom events as non-interactive

- lib/plausible_web/components/billing/notice.ex
- lib/plausible_web/controllers/billing_controller.ex
- lib/plausible_web/controllers/settings_controller.ex
- lib/plausible_web/live/team_management.ex
- lib/plausible_web/templates/site/membership/invite_member_form.html.heex
- lib/plausible_web/views/layout_view.ex
- test/plausible_web/components/billing/notice_test.exs
- test/plausible_web/controllers/site/membership_controller_test.exs
- test/plausible_web/controllers/site_controller_test.exs
- test/plausible_web/live/team_setup_test.exs
- test/support/dev/controllers/dev_subscription_controller.ex
This PR changes generic notices so they refer to "This team" instead of "Your account" whenever suitable. 
[Only owner and billing roles can access/manage subscriptions](https://github.com/plausible/analytics/commit/c9d9b88a5351514c6e0d0d31d9103c754f3d2b4c)
[Change how Team Settings options are exposed:](https://github.com/plausible/analytics/commit/3e586c0ea9bf0312f54508797e2882312af1f310)
- Subscription only available to owner/billing roles
- Invoices only available to owner/billing roles
- API Keys only available to owner/billing/admin/editor roles
[Only owner/billing can manage dev subscriptions](https://github.com/plausible/analytics/commit/73cbba56bbf817151f97463814c3ec82dfb048f8)
> Adjust notices & permissions

- lib/plausible_web/templates/settings/security.html.heex
Other places where e-mail is accepted already use type="email" input.
> Change email input under Account Settings > Security to proper type

- extra/lib/plausible_web/controllers/api/external_sites_controller.ex
- lib/plausible/billing/qouta/quota.ex
- lib/plausible/site/admin.ex
- lib/plausible/teams/billing.ex
- lib/plausible/teams/invitations.ex
- lib/plausible/teams/invitations/accept.ex
- lib/plausible/teams/invitations/invite_to_site.ex
- lib/plausible/teams/invitations/invite_to_team.ex
- lib/plausible/teams/invitations/reject.ex
- lib/plausible/teams/invitations/remove_from_site.ex
- lib/plausible/teams/memberships.ex
- lib/plausible/teams/sites/transfer.ex
- lib/plausible_web/controllers/invitation_controller.ex
- lib/plausible_web/controllers/site/membership_controller.ex
- test/plausible/teams/invitations/accept_test.exs
- test/plausible/teams/invitations/invite_to_site_test.exs
- test/plausible/teams/invitations/reject_test.exs
- test/plausible/teams/invitations/remove_from_site_test.exs
- test/plausible/teams/sites/transfer_test.exs
This is purely a refactoring of Teams context. Transfer service functions are isolated to their own module, service function names are renamed to improve clarity and reduce redundancy and some minor code formatting improvements are done as well. No actual logic is changed.
> Tidy up Teams logic and improve service functions names

- lib/plausible/teams/invitations.ex
- lib/plausible_web/controllers/auth_controller.ex
- lib/plausible_web/live/register_form.ex
- lib/plausible_web/templates/auth/activate.html.heex
- test/plausible_web/controllers/auth_controller_test.exs
- test/plausible_web/live/register_form_test.exs
This PR simplifies registration flow when registering from team invitation. Now, the invitation is accepted immediately after registering and the user is switched to the new team at once.
In case of email verification flow only "happy path" with verification code already issued is concerned with implicit team invite approval and redirect to team sites.
> Accept after register via team invite

- lib/plausible/billing/feature.ex
- lib/plausible/teams/billing.ex
- lib/plausible_web/plugins/api/schemas/capabilities.ex
- test/plausible/billing/quota_test.exs
- test/plausible_web/plugins/api/controllers/capabilities_test.exs
Extracted from https://github.com/plausible/analytics/pull/5361.
Introduces new billing feature, Sites API access, which is a prerequisite to supporting Sites API key provisioning by customers.
The feature is only available as a part of enterprise plans which have it explicitly configured.
> Add SitesAPI plan feature

- priv/repo/migrations/20250429093725_backfill_enterise_plans_feautres_sites_api.exs
Migration extracted from https://github.com/plausible/analytics/pull/5361
Adds "sites_api" feature to all existing enterprise plans which 1) have "stats_api" feature already set 2) have members with Sites API enabled API keys (queried the same way feature usage is done via billing).
> Implement backfill migration for enterprise plans

- test/support/dev/templates/dev_subscription/cancel_dev_subscription.heex
https://github.com/plausible/analytics/pull/5328 accidentally added a console.log to a test template. This minor change removes that.
> Remove accidental console.log

- rel/vm.args.eex
> +Mdai max|<amount> - Set amount of dirty allocator instances used. Defaults to 0. That is, by default no instances will be used. The maximum amount of instances equals the amount of dirty CPU schedulers on the system.
> By default, each normal scheduler thread has its own allocator instance for each allocator. All other threads in the system, including dirty schedulers, share one instance for each allocator. By enabling dirty allocator instances, dirty schedulers will get and use their own set of allocator instances. Note that these instances are not exclusive to each dirty scheduler, but instead shared among dirty schedulers. The more instances used the less risk of lock contention on these allocator instances. Memory consumption do however increase with increased amount of dirty …
> Add +Mdai max emulator flag

- lib/plausible/auth/api_key.ex
- lib/plausible/auth/auth.ex
- lib/plausible/crm_extensions.ex
- lib/plausible_web/controllers/settings_controller.ex
- lib/plausible_web/live/components/form.ex
- lib/plausible_web/templates/settings/api_keys.html.heex
- lib/plausible_web/templates/settings/new_api_key.html.heex
- lib/plausible_web/views/settings_view.ex
- test/plausible/auth/auth_test.exs
- test/plausible_web/controllers/settings_controller_test.exs
This PR adds ability for user to create a Sites API enabled API key by themselves instead of having to reach out to customer support, provided the feature is enabled for their team's enterprise plan.
Additionally, Enterprise Plan CRM now ensures that Stats API is always checked when Sites API is checked and that Sites API is unchecked if Stats API gets unchecked, to ensure consistency.
> Add ability to create Sites API keys from Account Settings

- config/test.exs
- lib/plausible/billing/plan.ex
- lib/plausible/billing/plans.ex
- lib/plausible/billing/qouta/quota.ex
- lib/plausible_web/components/billing/legacy_plan_benefits.ex
- lib/plausible_web/components/billing/legacy_plan_box.ex
- lib/plausible_web/components/billing/plan_benefits.ex
- lib/plausible_web/components/billing/plan_box.ex
- lib/plausible_web/components/generic.ex
- lib/plausible_web/controllers/billing_controller.ex
- lib/plausible_web/live/choose_plan.ex
- lib/plausible_web/live/legacy_choose_plan.ex
- lib/plausible_web/templates/billing/choose_plan.html.heex
- lib/plausible_web/templates/layout/app.html.heex
- priv/plans_v5.json
- priv/sandbox_plans_v5.json
- test/plausible/billing/plans_test.exs
- test/plausible/billing/quota_test.exs
- test/plausible/help_scout_test.exs
- test/plausible/release_test.exs
- test/plausible_web/controllers/billing_controller_test.exs
- test/plausible_web/live/choose_plan_test.exs
- test/plausible_web/live/legacy_choose_plan_test.exs
- test/support/test_paddle_api_mock.ex
- test/test_helper.exs
This PR introduces a new upgrade page under a `starter_tier` feature flag. To make the separation cleaner, all existing upgrade page logic will continue to live in modules/functions with a `legacy` prefix (all of which can safely be deleted once the feature flag is live):
* `choose_plan.ex` -> `legacy_choose_plan.ex`
* `plan_box.ex` -> `legacy_plan_box.ex`
* `plan_benefits.ex` -> `legacy_plan_benefits.ex`
* `choose_plan_test.exs` -> `legacy_choose_plan_test.exs`
* `Plausible.Billing.Quota.suggest_tier` -> `Plausible.Billing.Quota.legacy_suggest_tier`
Adds Starter plans on the upgrade page along with some other changes:
* Removes header (Plausible Logo and account dropdown) - replaces it with a simple "<- back to settings" link
* Yearly price is now selected by default (unless the user is …
> Starter tier: Upgrade page remodelling

- .github/workflows/elixir.yml
- lib/plausible_web/endpoint.ex
- lib/plausible_web/plugs/tracker_plug.ex
- lib/plausible_web/tracker.ex
- test/plausible_web/plugs/tracker_plug_test.exs
- test/plausible_web/tracker_test.exs
Follow-up to https://github.com/plausible/analytics/pull/5375, this PR adds support for interpolating script config into plausible-main template and serving it under `/js/s-<id>.js`.
Notes for the reviewer
- We are currently using site.installation_meta['id'], an auto-generated column for the id. We'll separately switch over to a more friendly, shorter id format in an subsequent PR.
- I'm planning for the `PlausibleWeb.Tracker` module to also contain the caching/CDN cache-busting logic down the line
- `site.installation_meta` has subtly different key names from script config. Ideally we'd fix this, but this requires a whole migration cycle, so delaying this.
> ScriptV2: plausible-main application code

- lib/plausible/teams.ex
- lib/plausible/teams/billing.ex
Small refactor of `Teams.owned_sites/1` and its uses.
> Replace uses of `Teams.owned_sites/1` with better functions where applicable

- extra/lib/plausible/customer_support/resource/site.ex
- extra/lib/plausible/customer_support/resource/team.ex
- extra/lib/plausible_web/live/customer_support/live/user.ex
- test/plausible_web/live/customer_support/sites_test.exs
- test/plausible_web/live/customer_support/teams_test.exs
- test/plausible_web/live/customer_support/users_test.exs
- test/plausible_web/live/sites_test.exs
A tiny update to CS tests + clipboard input with user ID.
Fixed an always true assertion in sites tests btw.
> CS: update tests + display user ID

- lib/plausible/session/salts.ex
Attempt at debugging session transfer.
This _temporary_ logging of salts hash might be helpful in identifying if there is a mismatch in salts during session transfer: subsequent `current` or `generated` (old node that gives sessions away) and `current` (new node that takes over the sessions) salt hashes are expected to be the same for the same app node.
> Log salts hash

- extra/lib/plausible_web/live/customer_support/live/site.ex
- lib/plausible/teams/invitations/invite_to_site.ex
- lib/plausible/teams/sites/transfer.ex
- test/plausible_web/live/customer_support/sites_test.exs
Another CS follow-up: Sites tab now get "Rescue Zone" tab where a transfer request can be initiated in case of customer lock-out.
> CRM: Expose site transfer

- extra/lib/plausible/auth/sso/domain.ex
- extra/lib/plausible/auth/sso/domains.ex
- test/plausible/auth/sso/domains_test.exs
Depends on #5416.
Adds implementations of `SSO.Domains.add/2` and `SSO.Domains.lookup/1`.
Also adds a provisional implementation of `SSO.Domains.verify/1` to enable testing.
> Implement `SSO.Domains.lookup` and `SSO.Domains.add`

- extra/lib/plausible/customer_support/enterprise_plan.ex
- extra/lib/plausible_web/live/customer_support.ex
- extra/lib/plausible_web/live/customer_support/live/team.ex
- test/plausible/customer_support/enterprise_plan_test.exs
- test/plausible_web/live/customer_support/teams_test.exs
This PR adds an "input with clipboard" widget containing price estimation for a custom plan, depending on its parameters (such as limits, billing interval etc.)
> CRM: Render price estimation in enterprise plans

- lib/plausible/data_migration/backfill_tracker_script_configuration.ex
- lib/plausible/ecto/types/nanoid.ex
- lib/plausible/site.ex
- lib/plausible/site/installation_meta.ex
- lib/plausible/site/tracker_script_configuration.ex
- lib/plausible_web/live/installation.ex
- lib/plausible_web/tracker.ex
- priv/repo/migrations/20250515164952_add_tracker_script_configuration_table.exs
- priv/repo/migrations/20250520073535_backfill_tracker_script_configuration.exs
- test/plausible/site/tracker_script_configuration_test.exs
- test/plausible_web/live/installation_test.exs
PR in a series:
1. `tracker_script_configuration` migration (https://github.com/plausible/analytics/pull/5406)
2. `tracker_script_configuration` schema, double-writes (https://github.com/plausible/analytics/pull/5407)
3. **`tracker_script_configuration` backfill (this PR)**
4. `tracker_script_configuration`: drop writes and reads to `installation_meta` (https://github.com/plausible/analytics/pull/5409)
5. Plugins API for `tracker_script_configuration` (https://github.com/plausible/analytics/pull/5410)
See sections below for more details:
<details><summary><b>On schema</b></summary>
- `id` uses Nanoid library to generate ids for nice and readable ids as these will be used for serving scripts. Example: `qyhkWtOWaTN0YPkhrcJgy`
- `installation_type` is marked as nullable since old …
> tracker_script_configuration: backfill (step 3)

- lib/plausible/site/tracker_script_configuration.ex
- lib/plausible/sites.ex
- lib/plausible_web/live/installation.ex
- lib/plausible_web/plugs/tracker_plug.ex
- lib/plausible_web/tracker.ex
- test/plausible_web/live/installation_test.exs
- test/plausible_web/plugs/tracker_plug_test.exs
- test/plausible_web/tracker_test.exs
PR in a series:
1. `tracker_script_configuration` migration (https://github.com/plausible/analytics/pull/5406)
2. `tracker_script_configuration` schema, double-writes (https://github.com/plausible/analytics/pull/5407)
3. `tracker_script_configuration` backfill (https://github.com/plausible/analytics/pull/5408)
4. **`tracker_script_configuration`: drop writes and reads to `installation_meta` (this PR)**
5. Plugins API for `tracker_script_configuration` (https://github.com/plausible/analytics/pull/5410)
See sections below for more details:
<details><summary><b>On schema</b></summary>
- `id` uses Nanoid library to generate ids for nice and readable ids as these will be used for serving scripts. Example: `qyhkWtOWaTN0YPkhrcJgy`
- `installation_type` is marked as nullable since old …
> tracker_script_configuration: drop writes and reads to `installation_meta` (step 4)

- extra/lib/plausible/auth/sso.ex
- extra/lib/plausible/auth/sso/identity.ex
- lib/plausible_web/user_auth.ex
- test/plausible/auth/sso_test.exs
- test/plausible_web/user_auth_test.exs
This PR adds logic for provisioning SSO user during during login, including conversion of existing user and creation of new user on the fly.
NOTE: Session expiration will be handled in a follow-up PR
> Implement `SSO.provision_user/1` and extend `UserAuth.log_in_user/3`

- lib/plausible/auth/user_session.ex
- lib/plausible_web/user_auth.ex
- test/plausible_web/plugs/user_session_touch_test.exs
- test/plausible_web/user_auth_test.exs
Ensures SSO user sessions always expires after `identity.expires_at`.
> Always expire SSO User sessions after `identity.expires_at`

- config/runtime.exs
- lib/plausible_web/tracker.ex
- lib/workers/purge_cdn_cache.ex
- test/workers/purge_cdn_cache_test.exs
After this change, each time TrackerScriptConfiguration is changed (via onboarding or plugins API), we schedule to purge the cached script from BunnyCDN.
Related k8s commit: https://github.com/plausible/plausible-app-k8s/commit/dbdae29f39e057e1f1c93611e76cef03780c7ec3
> ScriptV2: BunnyCDN cache purging

- config/runtime.exs
As part of https://github.com/plausible/analytics/pull/5435, I could not get scheduled jobs working locally. After removing `plugins: false` (defaults to empty list) it works, got an idea from reading  unrelated bug reports.
Ref: https://hexdocs.pm/oban/Oban.html#start_link/1-primary-options
> Make scheduled jobs work in development

- extra/lib/plausible_web/live/customer_support/live/site.ex
- extra/lib/plausible_web/live/customer_support/live/team.ex
- lib/plausible/teams.ex
- lib/plausible/teams/team.ex
- lib/plausible_web/templates/layout/_notice.html.heex
- lib/workers/schedule_email_reports.ex
- lib/workers/traffic_change_notifier.ex
- test/plausible_web/live/customer_support/teams_test.exs
- test/workers/schedule_email_reports_test.exs
- test/workers/traffic_change_notifier_test.exs
On top of #5438 this PR implements Team (un)locking capability in CRM.
If grace period is present it'll be ended (on lock) or removed (on unlock). 
Otherwise, the manually applied lock will hold and prevent users from accessing dashboards, regardless of any background quota/usage checks. This means, the only way to remove CRM-applied lock, is to manually remove it via CRM.
> CRM: team (un)lock regardless of grace period

- lib/plausible_web/live/team_setup.ex
we've had some people stuck on this screen, expecting the team to be created and invitations to be sent even without clicking on the "Create team" button.... then when nothing gets sent, they refresh the screen and lose all changes they made... so just changing the top copy a little bit to clarify that... let's see if it helps 
cc @zoldar
> Slight copy tweak for the "Create a team" page

- lib/plausible/billing/site_locker.ex
- lib/plausible/site/removal.ex
- lib/plausible/sites.ex
- test/plausible/billing/site_locker_test.exs
- test/plausible/site/site_removal_test.exs
- test/plausible/site/sites_test.exs
The dashboard lock flag was move from individual sites to teams some time ago. However, the locked state was not re-evaluated when adding and removing sites however. This PR addresses it.
> Ensure team locked state is updated on site creation and removal

- priv/repo/migrations/20250604094230_add_unique_index_on_users_sso_identity_id.exs
This index was missing. Given we currently expect SSO user emails being unique across the system, the same expectation should be set for NameID/identity ID (though it's yet to be proved whether we can truly rely on it).
> Add unique index on `users.sso_identity_id`

- extra/lib/plausible_web/live/customer_support/live/site.ex
- extra/lib/plausible_web/live/customer_support/live/team.ex
- lib/plausible/teams.ex
- lib/plausible/teams/team.ex
- lib/plausible_web/templates/layout/_notice.html.heex
- lib/workers/schedule_email_reports.ex
- lib/workers/traffic_change_notifier.ex
- test/plausible_web/live/customer_support/teams_test.exs
- test/workers/schedule_email_reports_test.exs
- test/workers/traffic_change_notifier_test.exs
#5440 was a misunderstanding - we needed to flesh out more precise requirements, to be addressed separately. This PR only implements CRM locking parity with kaffy.
> CRM: revert #5440; implement lock/unlock for grace period 

- extra/lib/plausible_web/live/customer_support/live/team.ex
- test/plausible_web/live/customer_support/teams_test.exs
Team dates are now date-type inputs
Custom plans limits have extra field previews next to them
> CRM: UX tweaks

- extra/lib/plausible_web/controllers/api/external_sites_controller.ex
- lib/plausible/plugins/api/shared_links.ex
- lib/plausible/segments/segments.ex
- lib/plausible/site/shared_link.ex
- lib/plausible/sites.ex
- lib/plausible/teams/billing.ex
- lib/plausible_web/controllers/site_controller.ex
- lib/plausible_web/controllers/stats_controller.ex
- lib/plausible_web/templates/site/settings_visibility.html.heex
- lib/plausible_web/templates/stats/site_locked.html.heex
- test/plausible/billing/feature_test.exs
- test/plausible/billing/quota_test.exs
- test/plausible_web/controllers/api/external_sites_controller_test.exs
- test/plausible_web/controllers/site_controller_test.exs
- test/plausible_web/controllers/stats_controller_test.exs
- test/plausible_web/plugins/api/controllers/capabilities_test.exs
- test/plausible_web/plugins/api/controllers/shared_links_test.exs
This PR implements API feature gates for shared links, while granting special access per `shared_link.name` to links created by the plugin API (i.e. by our WP plugin).
Here's the breakdown of changes in this PR:
* With https://github.com/plausible/analytics/pull/5472 migrated, every enterprise plan has access to the SharedLinks feature according to the data. This PR stops granting `SharedLinks` access to enterprise plans in code.
* Also, removes SharedLinks access from expired trials. Note that this will take effect immediately - it is not controlled by the `starter_tier` feature flag. The dashboards are locked for them anyway, so this should be OK.
* Shared Links API feature gates 
* Disable shared link creation without access to SharedLinks (exception: allowed via Plugins API)
* Declare …
> Starter Tier: Shared Link Feature Gates

- tracker/npm_package/README.md
Ref: https://3.basecamp.com/5308029/buckets/42034199/card_tables/cards/8709676872
This not being clear caused multiple users to file issues against https://github.com/plausible/plausible-tracker
> ScriptV2: Add note that NPM libary only works in browser environments

- config/runtime.exs
- extra/lib/plausible/auth/sso/domain.ex
- extra/lib/plausible/auth/sso/domain/validation/worker.ex
- extra/lib/plausible/auth/sso/domains.ex
- lib/plausible_web/email.ex
- lib/plausible_web/templates/email/sso_domain_validation_failure.html.heex
- lib/plausible_web/templates/email/sso_domain_validation_success.html.heex
- test/plausible/auth/sso/domains_test.exs
- test/workers/sso_domain_validation_worker_test.exs
This PR implements background worker for SSO domain validation. The job gets exponential snooze on validation failure, leading up to 14 retries over roughly ~34 hours. Instead of deleting already running jobs, a retry is always called on `enqueue`, effectively scheduling the job for immediate execution (to provide the ability to quickly restart the process via UI).
New status indicators per `SSO.Domain` have been introduced: `in_progress` and `invalid` to mirror job's status. Each unique enqueue resets the status to `in_progress`. For now, nothing actually enqueues the job - a follow-up PR will be submitted with end to end integration.
On domain validation success/failure e-mail notifications will be sent to the relevant team's owners. Copy is subject to change, but paging @metmarkosaric …
> SSO: implement domain validation background service

- extra/lib/plausible/stats/sampling.ex
- test/plausible/stats/sampling_test.exs
This PR adjusts sampling logic:
- Moving minimum sample rate to 0.007
- Adjusting sample rate if filters are present. Essentially each filter is assumed to filter out 1/20th the data.
This should help with edge cases where highly selective filters being present results in off-looking data.
(All new logic is feature flagged)
> Experiment: Adjust sampling minimum and by filters

- config/runtime.exs
- lib/plausible/application.ex
- lib/plausible/cache.ex
- lib/plausible_web/endpoint.ex
- lib/plausible_web/plugs/tracker_plug.ex
- lib/plausible_web/tracker.ex
- lib/plausible_web/tracker_script_cache.ex
- test/plausible_web/tracker_script_cache_test.exs
This PR leverages Plausible.Cache to provide a cached script delivery mechanism on self-hosted.
> ScriptV2: Self hosted tracker script cache

- config/runtime.exs
- extra/lib/plausible/auth/sso/domain/verification.ex
This PR makes sure no empty nameservers list is passed to `:inet_res.lookup`
This prevented us from running the verification end to end in the wild, with no configured SSO nameservers.
> Bugfix: enable nameservers fallback when no DNS configured explicitly for SSO

- extra/lib/plausible/auth/sso/domain/verification/worker.ex
> Remove fallback to empty list for nameservers option in SSO config

- lib/plausible_web/tracker.ex
- test/plausible_web/plugs/tracker_plug_test.exs
- test/plausible_web/tracker_test.exs
New onboarding _does not_ have a checkbox for hash based routing, so remove it from server-interpolated config
> ScriptV2: Remove hashBasedRouting from server-interpolated config

- test/plausible_web/live/choose_plan_test.exs
Fix Elixir CI - the test was failing due to separate logic - rendering new vs legacy upgrade page based on trial expiry date. I've removed assertions of starter tier boxes so that this logic wouldn't intervene in this test.
> remove starter tier assertions in test

- lib/plausible/teams/billing.ex
- test/plausible/auth/sso_test.exs
- test/plausible/billing/quota_test.exs
- test/plausible/teams/invitations/invite_to_site_test.exs
- test/plausible/teams/invitations/invite_to_team_test.exs
- test/plausible/teams/management/layout_test.exs
- test/plausible_web/controllers/site/membership_controller_test.exs
- test/plausible_web/live/team_management_test.exs
- test/plausible_web/live/team_setup_test.exs
- test/plausible_web/user_auth_test.exs
With the new plans, it makes sense for trials to have the same team member limit as Business tiers. They already have the same number of sites allowed (10). Ref: https://3.basecamp.com/5308029/buckets/41857003/card_tables/cards/8788606725
> Increase trial team member limit to 10

- tracker/npm_package/CHANGELOG.md
- tracker/package.json
- tracker/src/custom-events.js
- tracker/test/features-hierarchy-on-overlap.spec.ts
- tracker/test/form-submissions.spec.ts
- tracker/test/support/html-fixtures.ts
- tracker/test/support/test-utils.js
- tracker/test/support/types.ts
- tracker/test/tagged-events.spec.ts
- Stops duplicate events if formSubmissions tracking is enabled and the form is tagged.
- Also removes some noise from formSubmissions tests
> Script v2: Do not send Form: Submission events for tagged forms

- assets/js/dashboard/nav-menu/filter-menu.tsx
- assets/js/dashboard/nav-menu/segments/searchable-segments-section.tsx
- assets/js/dashboard/util/tooltip.tsx
Renders tooltips in searchable segment menu outside the scrollable container using createPortal to stop them from being cut off.
> Stop segments tooltip cutoff

- CHANGELOG.md
- lib/plausible/exports.ex
- lib/plausible/goals/system_goals.ex
- lib/plausible/imported.ex
- lib/plausible/ingestion/request.ex
- lib/plausible/stats/imported/base.ex
- lib/plausible/stats/imported/imported.ex
- test/plausible/goals_test.exs
- test/plausible/ingestion/request_test.exs
- test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_imported_test.exs
- test/plausible_web/controllers/api/stats_controller/custom_prop_breakdown_test.exs
- test/support/factory.ex
- tracker/npm_package/CHANGELOG.md
- tracker/package.json
- tracker/src/custom-events.js
- tracker/test/form-submissions.spec.ts
If this PR is merged, then special path-based system goals (new term / module, name up for debate) won't need to have event.props.path defined during tracking requests. 
These goals/events are "WP Form Completions", "Form: Submission", "404".
It will instead be set on receiving the event to be the same as event.pathname, unless event.props.path is explicitly defined. 
We don't override it when it is explicitly defined to remain backwards compatible with users that are already sending these events with a particular value. 
From our side, we can't distinguish intentional values and unintentional values for event.props.path, so the benefits of the sync will mostly apply to new customers, or customers that begin using these features after this PR is merged.
This approach stores the same …
> Script v2: Sync event.props.path for special path-based events from event.pathname

- test/plausible/installation_support/checks_test.exs
Single line changed - capture log in tests so the warnings don't litter stdout.
> Silence logger warnings in tests

- extra/lib/plausible/auth/sso.ex
- extra/lib/plausible/auth/sso/saml_config.ex
- extra/lib/plausible_web/controllers/sso_controller.ex
- extra/lib/plausible_web/live/sso_management.ex
- extra/lib/plausible_web/templates/sso/login_form.html.heex
- extra/lib/plausible_web/templates/sso/saml_signin.html.heex
- extra/lib/plausible_web/templates/sso/team_sessions.html.heex
- lib/plausible/auth/auth.ex
- lib/plausible/teams/memberships/update_role.ex
- lib/plausible_web/controllers/auth_controller.ex
- lib/plausible_web/live/team_management.ex
- test/plausible/auth/sso_test.exs
- test/plausible/teams/memberships/update_role_test.exs
- test/plausible_web/controllers/sso_controller_test.exs
- test/plausible_web/live/sso_management_test.exs
- test/plausible_web/live/team_management_test.exs
This PR: 
- improves consistency of copy related to SSO across the app
- adds an improvement to setup procedure, allowing pasting certificate PEM without boundary delimiters (Okta provides it this way for copy-pasting)
- adds IP-based rate limiting to SSO login endpoint to curb email lookup abuse
> Improve SSO naming and setup

- extra/lib/plausible/auth/sso.ex
- extra/lib/plausible/auth/sso/identity.ex
- extra/lib/plausible_web/sso/fake_saml_adapter.ex
- extra/lib/plausible_web/sso/real_saml_adapter.ex
- test/plausible/auth/sso/domains_test.exs
- test/plausible/auth/sso_test.exs
- test/plausible/auth/user_sessions_test.exs
- test/plausible/site/sites_test.exs
- test/plausible/teams/memberships/update_role_test.exs
- test/plausible_web/controllers/auth_controller_test.exs
- test/plausible_web/controllers/sso_controller_test.exs
- test/plausible_web/live/customer_support/teams_test.exs
- test/plausible_web/live/sso_management_test.exs
- test/plausible_web/live/team_management_test.exs
- test/plausible_web/plugs/sso_team_access_test.exs
- test/plausible_web/user_auth_test.exs
- test/support/test_utils.ex
Ensures the integration from SAML authentication session is used for further verification during provisioning of user.
> Use integration from identity during verification

- tracker/npm_package/CHANGELOG.md
- tracker/package.json
- tracker/src/plausible.js
Fixes order of setting window.plausible.l = true
Needed because otherwise even if window.plausible.l = true, window.plausible.s and window.plausible.v might be undefined.
> Fix order of setting window.plausible.l = true

- extra/lib/plausible/audit/entry.ex
- extra/lib/plausible/auth/sso/domain.ex
- extra/lib/plausible/auth/sso/domains.ex
- extra/lib/plausible/auth/sso/identity.ex
- extra/lib/plausible/auth/sso/integration.ex
- extra/lib/plausible/auth/sso/saml_config.ex
- extra/lib/plausible_web/live/customer_support/live/team.ex
- extra/lib/plausible_web/live/customer_support/live/user.ex
- extra/lib/plausible_web/sso/fake_saml_adapter.ex
- extra/lib/plausible_web/sso/real_saml_adapter.ex
- lib/plausible_web/live/components/form.ex
- test/plausible/audit_test.exs
- test/plausible/auth/sso/domains_test.exs
- test/plausible_web/controllers/sso_controller_sync_test.exs
- test/plausible_web/live/customer_support/teams_test.exs
- test/support/teams/test.ex
This PR is an initial spin of CRM-Audit integration. For now we'll only display (non-paginated) audit entries under Team/Audit tab. Currently only SSO events are audited. 
Additionally, this PR instruments SAML consumption failure/success with audit entries for completeness so we don't rely on users having to tell customer support the errors they're getting (that might end up cryptic for them anyway).
> CRM: implement basic SSO audit browser

- extra/lib/plausible_web/live/customer_support/live/team.ex
- test/plausible_web/live/customer_support/teams_test.exs
Audit logs store non-constrained identifiers. So in case the user does not exist anymore, we should still render something.
> Don't crash audit browser with weak user association missing

- extra/lib/plausible/audit.ex
- extra/lib/plausible_web/live/customer_support.ex
- extra/lib/plausible_web/live/customer_support/live/team.ex
- test/plausible_web/live/customer_support/teams_test.exs
This PR adds basic pagination to Audit logs CRM browser.
Default item limit per page is `15` but one can alter the URL. 
Next up we'll have to restructure the whole Customer Support <-> tabs code organization before adding any new features. Delegating all the work to a single god-component let us iterate relatively fast on this, but is getting hard to maintain and reason about.
> CRM Audit browser: implement basic pagination

- lib/plausible/installation_support/checks/installation.ex
Retry verifier-v1 execution when client JS navigates and destroys current page context.
I've tested this with a local Browserless instance against a few sites that end up with the following warning log on current master:
```
[warning] [VERIFICATION] Browserless JS error: "Protocol error (Runtime.callFunctionOn): Execution context was destroyed."
```
With the changes introduced in this PR, the local Browserless call returns successful diagnostics. Therefore, merging this, I would expect the volume of these specific error cases to drop significantly.
Unfortunately, as stated in a code comment, this behaviour is currently not testable.
> Verifier v1: Retry verification on JS navigation

- lib/plausible/installation_support/checks/installation.ex
Tackles one specific case that surfaces in Sentry from time to time:
```
Error running check Plausible.InstallationSupport.Checks.Installation on https://some.website: {:case_clause, {:ok, %Req.Response{status: 400, headers: %{"connection" => ["keep-alive"], "content-type" => ["text/plain; charset=UTF-8"], "date" => ["Tue, 29 Jul 2025 09:09:01 GMT"], "server" => ["openresty/1.27.1.2"], "transfer-encoding" => ["chunked"]}, body: "Protocol error (Runtime.callFunctionOn): Target closed\n", trailers: %{}, private: %{}}}}
```
This error appears to be thrown from Browserless even before our verification code runs. Instead of a JSON body with a known `error` key, we get status 400 with a `text/plain` body. Currently, since there's no case clause matching, the LiveView keeps re-attempting the …
> Handle another Browserless error response

- lib/plausible/installation_support/checks/installation_v2.ex
- lib/plausible/installation_support/verification/diagnostics.ex
- lib/plausible_web/live/components/verification.ex
- lib/plausible_web/live/verification.ex
- tracker/test/installation_support/verifier-v2.spec.ts
- tracker/test/support/installation-support-playwright-wrappers.ts
Like legacy verifier, v2 verifier should handle verifying sites where there's an immediate JS redirect. 
To do so, this PR adds logic to catch puppeteer errors about 'execution context' being canceled (which is the signal that navigation happened in the browser tab, canceling the function that was being evaluated), and to reattempt verification in the new location.
It also fixes the installation v2 module verifier loading logic to match the improved v1 module logic.
> Script v2: Handle verifying sites where there's an immediate JS redirect

- lib/plausible/installation_support/verification/diagnostics.ex
- test/plausible/installation_support/verification/diagnostics_test.exs
- tracker/test/installation_support/verifier-v2.spec.ts
- tracker/test/support/initialize-page-dynamically.ts
- Adds more diagnostics cases to verifier v2
- Breaks up diagnostic function to have separate clauses
- Adds CSP related tests to verifier v2
> Script v2: Add more diagnostics cases to verifier v2, more tests for verifier v2

- .github/workflows/tracker-script-npm-release.yml
Tiny quality-of-life tweak: When we release a new NPM tracker script version, we will start to also link to the NPM page.
> ScriptV2: On NPM release, link to NPM in basecamp

- lib/plausible/stats/filter_suggestions.ex
- test/plausible_web/controllers/api/stats_controller/suggestions_test.exs
We support "Direct / None" source filtering via dashboard click, but it doesn't show up as a filter suggestion when typing. This PR fixes that.
> Include "Direct / None" in source filter suggestions

- lib/plausible_web/live/shields/page_rules.ex
- test/plausible_web/live/shields/pages_test.exs
Once a page is blocked already, don't suggest it in the combobox
> Exclude pages already added in page shields suggestions

- lib/plausible/site/tracker_script_configuration.ex
- test/plausible_web/live/installationv2_test.exs
It wasn't possible to save tracker config on the npm tab, which caused a server error when pressing "Verify NPM installation"
> Script v2: Allow saving npm installation type

- lib/plausible_web/controllers/auth_controller.ex
- test/plausible_web/controllers/auth_controller_test.exs
Sending garbage to /dev/null instead of polluting sentry for no reason
> Mute automated login attempts

- test/plausible/installation_support/checks_test.exs
- test/plausible_web/live/change_domain_v2_test.exs
- test/plausible_web/live/installationv2_test.exs
Fix console warnings on `ce_test`. Run InstallationSupport related test suites only on Enterprise Edition.
> fix CE warning in tests

- lib/plausible_web/live/installationv2.ex
Shows a warning linking to (not yet written) GTM template upgrade guide.
> ScriptV2: Show warning when using Legacy GTM template, update links

- lib/plausible/installation_support/checks/detection.ex
- lib/plausible/installation_support/checks/installation.ex
- lib/plausible/installation_support/detection/diagnostics.ex
- lib/plausible_web/live/change_domain_v2.ex
- lib/plausible_web/plugins/api/schemas/tracker_script_configuration.ex
- lib/plausible_web/plugins/api/schemas/tracker_script_configuration/update_request.ex
- lib/plausible_web/tracker.ex
- test/plausible_web/live/change_domain_v2_test.exs
- test/plausible_web/live/installationv2_test.exs
- tracker/installation_support/check-npm.js
- tracker/installation_support/detector.js
- tracker/test/installation_support/detector.spec.js
This PR refines the scriptv2 domain change flow by:
1. Improving the "Back to settings button"
2. Tweaking dark mode support
3. Purging CDN cache on domain change
The major change is also detecting whether npm library was used and showing the "warning" to update their configuration in 72 hours.
Along the way we also support storing/detecting npm module within the onboarding module.
Basecamp ref: https://3.basecamp.com/5308029/buckets/42034199/card_tables/cards/8949869924
> ScriptV2: Domain change refinement

- lib/plausible_web/live/installationv2/instructions.ex
- lib/plausible_web/views/site_view.ex
- test/plausible_web/live/installationv2_test.exs
- tracker/package.json
- tracker/src/web-snippet.js
- tracker/test/installation_support/verifier-v2.spec.ts
- tracker/test/support/initialize-page-dynamically.ts
Basecamp ref: https://3.basecamp.com/5308029/buckets/42034199/card_tables/cards/8935985563
`defer` -> `async` will be handled in a separate PR.
> ScriptV2: snippet structure change

- lib/plausible_web/live/sites.ex
- lib/plausible_web/live/verification.ex
Fix pageview polling in the verification tool. Basecamp ref: https://3.basecamp.com/5308029/buckets/42034199/card_tables/cards/8967893006
Also add a dev-env-only convenience for quickly deleting sites (something I found annoying when playing around with onboarding UI locally, decided to include in this small PR to get it in):
> Fix bug with pageview queries stacking after verification retries

- extra/lib/plausible_web/live/customer_support/user/components/overview.ex
- test/plausible_web/live/customer_support/users_test.exs
> CRM: Expose 2FA user status & allow CS to force disable it

- lib/plausible/installation_support/checks/installation_v2.ex
- lib/plausible/installation_support/verification/diagnostics.ex
- test/plausible/installation_support/verification/diagnostics_test.exs
- tracker/compiler/index.js
- tracker/installation_support/autoconsent-rules/autoconsent/cookiebot.json
- tracker/installation_support/autoconsent-to-cookies.js
- tracker/installation_support/verifier-v2.js
- tracker/npm_package/CHANGELOG.md
- tracker/package-lock.json
- tracker/package.json
- tracker/test/fixtures/cookies-cookiebot.html
- tracker/test/fixtures/cookies-iubenda.html
- tracker/test/fixtures/cookies-onetrust.html
- tracker/test/fixtures/cookies-quantcast.html
- tracker/test/installation_support/verifier-v2.spec.ts
- tracker/test/support/types.ts
Makes use of https://www.npmjs.com/package/@duckduckgo/autoconsent to accept cookies during installation verification process. 
I picked this approach in favor of hand-rolling a cookie consenter because I don't think we'll be able to maintain a hand-rolled solution at a good-enough level as consent management platforms (CMPs) wax and wane in popularity and our user base becomes more international.
The autoconsent library and rules to detect CMPs are bundled into the verifier script. This increases its size: the compiled verifier-v2.js file is now ~840kb (up from ~3kb on master) , of which 800kb are rulesets for 100s of different cookie banner setups. Since the extra size takes longer to deliver to Browserless.io, I think we should trim it down. 
Edit: It's now trimmed down to be ~100kb. …
> Script v2: Verifier accepts cookies

- config/.env.dev
Otherwise it generates a ton of noise in the console unless persistor is setup locally too.
> Use embedded persistor implementation in local dev env

- CHANGELOG.md
- lib/plausible_web/live/plain_combo.ex
- lib/plausible_web/templates/site/settings_integrations.html.heex
This PR embeds a tiny live view capable of only rendering the `ComboBox` live component, in order to make it possible to search through GSC properties. Existing tests pass and `ComboBox` itself is tested extensively, so there's not much to add here.
> Enable filtering Seratch Console properties via ComboBox live component

- lib/plausible/ingestion/persistor/remote.ex
This PR attempts to address an issue where connections in large HTTP2 pool are marked as inactive and closed down just when another request is made using them. Roughly the same scenario like in https://github.com/sneako/finch/issues/144
> Retry persistor requests on HTTP2 disconnected errors

- lib/plausible/installation_support/verification/diagnostics.ex
- test/plausible/installation_support/verification/diagnostics_test.exs
- tracker/test/support/types.ts
The problems this PR attempts to solve are
1) weird message and recommendation in the case of unknown error 
2) too many unknown errors logged in sentry
> Script v2: Show "Plausible not detected" errors with installation type specific recommendations

- lib/plausible/stats/query_optimizer.ex
- test/plausible/stats/query_optimizer_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_comparisons_test.exs
`year` and `month` periods worked differently from what I expected: they always compare with the last N months/years compared to the running year/month. This resulted in empty graphs.
<details>
<summary><strong>Screenshots before/after: Month to date comparison graph</strong></summary>
Before:
After:
</details>
<details>
<summary><strong>Screenshots before/after: Year to date comparison graph</strong></summary>
Before:
After:
</details>
Ref: https://3.basecamp.com/5308029/buckets/26383192/card_tables/cards/8450025970#__recording_9035003250
> Fix: Trim comparisons for year/month

- CHANGELOG.md
- lib/plausible/stats/query.ex
- lib/plausible/stats/query_optimizer.ex
- lib/plausible/stats/sql/expression.ex
- lib/plausible/stats/sql/query_builder.ex
- lib/plausible/stats/table_decider.ex
- test/plausible/stats/query_optimizer_test.exs
- test/plausible/stats/table_decider_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_test.exs
When graphing timeseries, **Session smearing** refers to counting sessions in _each_ of the time buckets a session was active in instead of only when it ended. This works well for visitors/visit graphs, but for visit duration metric it was causing severe over-counting under each value.
This PR:
1. Refactors session smearing to only work for visits/visitors metrics and no longer with visit_duration
2. Fixes a bug with visits metric when smearing
To facilitate this, internals of the query building are revamped to allow joining more than 1 event query with 1 session query. Some business logic was also moved to QueryOptimizer.
Basecamp ref: https://3.basecamp.com/5308029/buckets/36789884/card_tables/cards/8546432041#__recording_9025673227
> Stats: Rebuild session smearing for timeseries

- lib/plausible/installation_support/detection/checks.ex
- lib/plausible_web/live/change_domain_v2.ex
- lib/plausible_web/live/installationv2.ex
- lib/plausible_web/live/verification.ex
- test/plausible_web/live/change_domain_v2_test.exs
- test/plausible_web/live/installationv2_test.exs
Prevents excessive browserless calls to detect technology.
> Script v2: Rate limit tech detection

- assets/js/dashboard/util/url.ts
- lib/plausible/site.ex
- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/legacy/legacy_query_builder.ex
- lib/plausible/stats/query.ex
- lib/plausible/stats/sql/where_builder.ex
- lib/plausible_web/controllers/stats_controller.ex
- lib/plausible_web/plugs/authorize_public_api.ex
- lib/plausible_web/plugs/authorize_site_access.ex
- test/plausible/stats/query_parser_test.exs
This PR is a proof of concept that aims to uncover possible issues/limitations querying clickhouse for rollup sites. It does not touch any database fields yet, but allows viewing the dashboard of multiple sites at once. To be reverted as soon as we get the necessary insights.
> POC: Rollup view

- lib/plausible/installation_support/detection/diagnostics.ex
- lib/plausible/installation_support/verification/checks.ex
- lib/plausible/installation_support/verification/diagnostics.ex
- lib/plausible_web/live/installation.ex
- lib/plausible_web/live/installationv2.ex
- lib/plausible_web/live/verification.ex
- lib/plausible_web/tracker.ex
- test/plausible/installation_support/verification/checks_test.exs
- test/plausible_web/controllers/settings_controller_test.exs
- test/plausible_web/controllers/site_controller_test.exs
- test/plausible_web/live/change_domain_v2_test.exs
- test/plausible_web/live/components/verification_test.exs
- test/plausible_web/live/verification_test.exs
- test/plausible_web/live/verification_v2_test.exs
- test/support/test_utils.ex
- Fixes the issue when StatsController redirects to :verification without installation_type not known at that point.
- Fixes typo in error case
- Fixes custom_url screen being allowed for non v2 verification
- Adds v2 verification tests
- Adds utility to assert on html that contains single quotes without manually re-encoding chars
> Script v2: Maybe load installation type from DB

- tracker/.prettierignore
- tracker/test/outbound-links.spec.ts
- tracker/test/tagged-events.spec.ts
- tracker/test/transform-request.spec.ts
There's a problem tracking tagged a elements if they're within svg tags. `url` property isn't added automatically. It's hard to fix using ES5-only logic without increasing script size or script complexity (if polyfilling only for .compat variants)
Including the URL automatically with tagged links is convenience functionality that I propose we document with this edge case like this: https://github.com/plausible/docs/pull/635.
This PR 
1) updates the test case about this
2) adds tests for transformRequest examples from docs
> Script v2: Update tests relating to tagged a elements as well as examples from docs

- assets/css/app.css
- assets/js/dashboard/index.tsx
- assets/js/dashboard/stats/behaviours/index.js
- assets/js/dashboard/stats/graph/graph-util.js
- assets/js/dashboard/stats/graph/visitor-graph.js
- assets/js/dashboard/stats/reports/list.tsx
- assets/tailwind.config.js
- lib/plausible_web/live/sites.ex
- lib/plausible_web/templates/layout/_header.html.heex
- Reduce shadow and increased border radius on cards, to be consistent with the rest of the app
- Reduce logo size
- Align horizontal and vertical spacing between cards
- Replaced custom CSS for `.stats-item` with Tailwind utility classes 
- Reduce line width of the main graph
**Before:** 
**After:**
- Fix horizontal alignment on tables
**Before:**
**After:**
- Reduce border radius on sites overview for consistency with dashboard
- Add transition to hover effect on sites overview cards
**Before:**
https://github.com/user-attachments/assets/e86255d8-9266-4261-b41a-e6c3e2f47c06
**After:**
https://github.com/user-attachments/assets/fc4a0fde-d654-4139-8b8c-6cc1f0ad9919
> Make visual tweaks to the dashboard

- lib/plausible_web/components/billing/plan_box.ex
- lib/plausible_web/components/generic.ex
- test/plausible_web/live/choose_plan_test.exs
- Add "Learn more" tooltip to the info icon that is used repeatedly in settings to link to docs, for extra affordance.
- Add centered? attribute to tooltip component.
- Replace the tooltip-content class with testid attribute, as it was only used for testing purposes.
> Add tooltip to info icon in settings

- lib/plausible_web/controllers/api/stats_controller.ex
- test/plausible_web/controllers/api/stats_controller/suggestions_test.exs
https://sentry.plausible.io/organizations/plausible/issues/47/?environment=prod&project=2&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D+downcase&referrer=issue-stream&statsPeriod=14d&stream_index=0
https://sentry.plausible.io/organizations/plausible/issues/46/?environment=prod&project=2&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D+downcase&referrer=issue-stream&statsPeriod=14d&stream_index=1
https://sentry.plausible.io/organizations/plausible/issues/1081/?environment=prod&project=2&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D+downcase&referrer=issue-stream&statsPeriod=14d&stream_index=2
Not sure why we're getting requests to this endpoint with missing `q` parameter. Solving this by validating the existence of it and return 400 in case it's …
> Fix Sentry error in filter suggestions

- extra/lib/plausible/consolidated_view.ex
- extra/lib/plausible/consolidated_view/cache.ex
- lib/plausible/application.ex
- lib/plausible/cache.ex
- test/plausible/consolidated_view/cache_test.exs
- test/support/data_case.ex
This lets us have an interface to lookup regular site ids per consolidated view id efficiently. I don't think it needs more tests coverage at this point - since all the caches and their common characteristics are thoroughly tested elsewhere.
> `ConsolidatedView.Cache` - first pass

- extra/lib/plausible/consolidated_view.ex
- lib/plausible/application.ex
- lib/plausible/site.ex
- lib/plausible/sites.ex
- lib/plausible/stats/clickhouse.ex
- lib/plausible/stats/filters/query_parser.ex
- lib/plausible/stats/legacy/legacy_query_builder.ex
- lib/plausible/stats/query.ex
- lib/plausible/stats/sql/where_builder.ex
- lib/plausible_web/controllers/stats_controller.ex
- lib/plausible_web/live/verification.ex
- lib/plausible_web/plugs/authorize_public_api.ex
- lib/plausible_web/plugs/authorize_site_access.ex
- test/plausible/consolidated_view_test.exs
- test/plausible/stats/query_parser_test.exs
- test/plausible/stats/query_test.exs
- test/plausible_web/controllers/api/external_stats_controller/query_consolidated_view_test.exs
- test/plausible_web/controllers/api/stats_controller/pages_test.exs
- test/plausible_web/controllers/stats_controller_test.exs
- test/support/teams/test.ex
Get rid of the current virtual rollups and replace them with consolidated views. Note that there's no functionality for creating any consolidated views yet, other than calling `Plausible.ConsolidatedView.enable(team)` manually from `iex -S mix`. The next PR will make it possible to create consolidated views from the CRM.
> Remove virtual rollups in favour of persisted consolidated sites

- extra/lib/plausible_web/live/customer_support/team.ex
- extra/lib/plausible_web/live/customer_support/team/components/consolidated_views.ex
- test/plausible_web/live/customer_support/teams_test.exs
Adds a new tab in the CS to manage consolidated views.
> Add Consolidated Views tab to /cs

- lib/plausible/telemetry/plausible_metrics.ex
Expose newly introduced metrics for relayed persistor setup.
> Configure promex metrics sent by `Persistor.EmbeddedWithRelay`

- lib/plausible/ingestion/persistor/remote.ex
- test/plausible/ingestion/persistor_test.exs
"no_session_for_engagement" is an error that is expected to happen under normal circumstances. This PR stops explicitly logging it. The respective test got also updated to reflect that persistor returns this error with 422 HTTP code and not 500.
> Don't log `no_session_for_engagement` errors coming from persistor

- extra/lib/plausible/installation_support/checks/detection.ex
- extra/lib/plausible/installation_support/checks/installation_v2.ex
Whenever there's an unexpected browserless response (without the key `completed` in the payload), we'll also log the request body.
> Improve logging on failed browserless requests

- extra/lib/plausible/installation_support/checks/detection.ex
Increases detection call timeout. The idea is to prefer to get a timeout from the inner function that's run on the site, rather than destroy the whole function context.
> Increase detection call timeout

- lib/plausible_web/plugs/secure_embed_headers.ex
- lib/plausible_web/plugs/secure_headers.ex
- lib/plausible_web/router.ex
Recent Phoenix update introduced `content-security-policy` header which breaks embedding. This PR replaces default secure headers with a custom version with CSP removed, just for shared links. We might revise it further in the future following something like https://help.docebo.com/hc/en-us/articles/15539609538194-Configuring-your-site-content-security-policy-for-embedded-learning
> Adjust secure headers for shared links to avoid breaking embeds
